In [2]:
import pandas as pd
%matplotlib inline
import tangos
import tangos.examples.mergers as mergers
import pynbody

import numpy as np
import h5py
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
h = 0.6776942783267969

from tangos_halo_module.halo_properties import track_halo_property, get_timesteps, ID_to_sim_halo_snap, infall_final_n_particles, infall_final_coordinates, apocentric_distance, disruption_time, accretion_time, orbit_interpolation, infall_velocity, quenching_time, max_sSFR_time, max_mass_time 
from tangos_halo_module.path import get_file_path, get_halo_snap_num, read_file
from tangos_halo_module.halos import ID_to_tangos_halo, get_survivors, get_main_progenitor_branch, get_zombies, get_host, get_survivor_IDs, get_zombie_IDs, blockPrint, enablePrint, tangos_to_pynbody_halo

In [3]:
ids = np.loadtxt('ids100.txt')
ids=[int(i) for i in ids]
ids

[14840961025,
 14832642,
 14840964127,
 32913443,
 14840961061,
 14812709,
 329022513,
 1484096567,
 3294096956,
 32940964414,
 329022530,
 329409616,
 329038417,
 329409620,
 329038430,
 329127010,
 329038438,
 32904809,
 329409643,
 148409620589,
 329022579,
 14840962,
 14840963,
 14840961156,
 14840964,
 14840965,
 14840966,
 14840967,
 14812804,
 1484096138,
 329409673,
 329409675,
 32906374,
 32940965015,
 14840961179,
 14840961693,
 329409696,
 3294096555,
 1484096179,
 1484096194,
 14829762,
 3294096585,
 329067210,
 1484096204,
 1484096210,
 32933603,
 3290192110,
 3290192111,
 148409613555,
 148409619718,
 148153610,
 148409610,
 148409611,
 148409612,
 148128013,
 1484096271,
 14840965903,
 148409617,
 148110610,
 148115218,
 148409621,
 1484096278,
 148409622,
 148409632,
 148409633,
 148409634,
 148409635,
 1484096803,
 32924962,
 148409639,
 148409641,
 148409651,
 148409653,
 148409655,
 14840964409,
 148409663,
 148409668,
 1484096266,
 1484096331,
 148409676,
 148409677,
 329096015,
 14840964944,
 32914768,
 1484096857,
 329019225,
 14840961883,
 32940961630,
 14840967007,
 329019230,
 14840961379,
 32908648,
 14840961900,
 14840962413,
 14840962927,
 32940961648,
 14840968565,
 1484096374,
 3290188153,
 3294096768,
 1484096387,
 14840961413,
 14814089,
 1484096412,
 32930722,
 1484096422,
 32940969,
 148409612211,
 32909747,
 14840964022,
 14811066,
 14840961467,
 1484096459,
 329048011,
 3294096335,
 329048022,
 1484096478,
 3294096350,
 329048034,
 32940963299,
 32906729,
 14840962026,
 329034745,
 32907774]

In [3]:
idx=[str(int(i)) for i in ids]
idx.sort()
h148_ids = idx[:77]
h329_ids = idx[77:]
print(h148_ids)
print(h329_ids)

['148110610', '14811066', '148115218', '14812709', '148128013', '14812804', '14814089', '148153610', '14829762', '14832642', '148409610', '14840961025', '14840961061', '148409611', '14840961156', '14840961179', '148409612', '148409612211', '148409613555', '14840961379', '1484096138', '14840961413', '14840961467', '14840961693', '148409617', '1484096179', '14840961883', '14840961900', '1484096194', '148409619718', '14840962', '14840962026', '1484096204', '148409620589', '148409621', '1484096210', '148409622', '14840962413', '1484096266', '1484096271', '1484096278', '14840962927', '14840963', '148409632', '148409633', '1484096331', '148409634', '148409635', '1484096374', '1484096387', '148409639', '14840964', '14840964022', '148409641', '1484096412', '14840964127', '1484096422', '14840964409', '1484096459', '1484096478', '14840964944', '14840965', '148409651', '148409653', '148409655', '1484096567', '14840965903', '14840966', '148409663', '148409668', '14840967', '14840967007', '148409676', '148409677', '1484096803', '14840968565', '1484096857']
['3290188153', '3290192110', '3290192111', '329019225', '329019230', '329022513', '329022530', '329022579', '329034745', '329038417', '329038430', '329038438', '329048011', '329048022', '329048034', '32904809', '32906374', '329067210', '32906729', '32907774', '32908648', '329096015', '32909747', '329127010', '32913443', '32914768', '32924962', '32930722', '32933603', '329409616', '32940961630', '32940961648', '329409620', '32940963299', '3294096335', '3294096350', '329409643', '32940964414', '32940965015', '3294096555', '3294096585', '329409673', '329409675', '3294096768', '32940969', '3294096956', '329409696']

### Get MPB ids & Store them

In [5]:
# for sim in ['h329', 'h148']:
#     if sim=='h329':
#         idx = h329_ids
#     else:
#         idx = h148_ids
#     column_names = ['snapshot']+idx
#     df = pd.DataFrame(columns = column_names)
#     df.to_csv(str(sim)+'MPB_ids.csv', index=False)
#     ts = get_timesteps(simulation=sim, resolution=100)[3]
#     df['snapshot'] = ts
#     df.to_csv(str(sim)+'MPB_ids.csv', index=False)
#     print('initialized ', sim)

resolution=100
def store_MPB_ids(ID=0):
    if ID != 0:
        print('Started ', ID)
        simulation, status, halo_id, snap_num = ID_to_sim_halo_snap(ID=ID)
        print(simulation, status, halo_id, snap_num)
        tangos_halo = ID_to_tangos_halo(ID=ID, resolution=resolution)
    
    # Satellite MPB ids
    MPB, MPB_ids = get_main_progenitor_branch(tangos_halo=tangos_halo, simulation=simulation, resolution=resolution)
    print(MPB_ids)
    print(MPB)
    # Store and recall
    # Host MPB and ids
    host = get_host(simulation=simulation, resolution=resolution)
    host_MPB, host_ids = get_main_progenitor_branch(tangos_halo=host, simulation=simulation, 
                                                    resolution=resolution)
    print(host_ids)
    # Only consider halo while separate from host
    for i, idx in enumerate(MPB_ids):
        if idx in host_ids:
            MPB_ids[i]=0
            
    MPB_ids[MPB_ids==host_ids] = 0
    print('Separate from host', MPB_ids)

    for i in range(len(MPB_ids)):
        if MPB_ids[i]!=0:
            if len(str(MPB[i]))>6:
                MPB_ids[i]=get_halo_snap_num(tangos_halo=MPB[i])[2]
            else: 
                MPB_ids[i]=0
#     dat = {str(ID): MPB_ids,}
#     df = pd.DataFrame(data=dat)
    df = pd.read_csv(str(simulation)+'MPB_ids.csv')
    df[str(ID)] = MPB_ids
    df.to_csv(str(simulation)+'MPB_ids.csv', index=False)
    print(df)
    print('Finished ', ID)
    
completed_ids = np.zeros(0)

In [11]:
# count=0
# done=0
# while done<124:
#     try:
#         print('Watch me go for the ', count, 'th time...')
#         for idx in ids:
#             if idx in completed_ids:
#                 print('Already Exists ', idx)
#                 done=len(completed_ids)
#                 print('Completed Count --> ', done)
#                 pass
#             else:
#                 print('Started ', idx)
#                 store_MPB_ids(ID=idx)
#                 completed_ids = np.concatenate((completed_ids, [idx]), axis=None)
#                 print('Finished ', idx)
#                 done=len(completed_ids)
#                 print('Completed Count --> ', done)
#     except: 
#         count+=1
#         continue

Watch me go for the  0 th time...
Already Exists  14840961025
Completed Count -->  77
Already Exists  14832642
Completed Count -->  77
Already Exists  14840964127
Completed Count -->  77
Already Exists  32913443
Completed Count -->  77
Already Exists  14840961061
Completed Count -->  77
Already Exists  14812709
Completed Count -->  77
Already Exists  329022513
Completed Count -->  77
Already Exists  1484096567
Completed Count -->  77
Already Exists  3294096956
Completed Count -->  77
Already Exists  32940964414
Completed Count -->  77
Already Exists  329022530
Completed Count -->  77
Already Exists  329409616
Completed Count -->  77
Already Exists  329038417
Completed Count -->  77
Already Exists  329409620
Completed Count -->  77
Already Exists  329038430
Completed Count -->  77
Already Exists  329127010
Completed Count -->  77
Already Exists  329038438
Completed Count -->  77
Already Exists  32904809
Completed Count -->  77
Already Exists  329409643
Completed Count -->  77
Already Exists  148409620589
Completed Count -->  77
Already Exists  329022579
Completed Count -->  77
Already Exists  14840962
Completed Count -->  77
Already Exists  14840963
Completed Count -->  77
Already Exists  14840961156
Completed Count -->  77
Already Exists  14840964
Completed Count -->  77
Already Exists  14840965
Completed Count -->  77
Already Exists  14840966
Completed Count -->  77
Already Exists  14840967
Completed Count -->  77
Already Exists  14812804
Completed Count -->  77
Already Exists  1484096138
Completed Count -->  77
Already Exists  329409673
Completed Count -->  77
Already Exists  329409675
Completed Count -->  77
Already Exists  32906374
Completed Count -->  77
Already Exists  32940965015
Completed Count -->  77
Already Exists  14840961179
Completed Count -->  77
Already Exists  14840961693
Completed Count -->  77
Already Exists  329409696
Completed Count -->  77
Already Exists  3294096555
Completed Count -->  77
Already Exists  1484096179
Completed Count -->  77
Already Exists  1484096194
Completed Count -->  77
Already Exists  14829762
Completed Count -->  77
Already Exists  3294096585
Completed Count -->  77
Already Exists  329067210
Completed Count -->  77
Already Exists  1484096204
Completed Count -->  77
Already Exists  1484096210
Completed Count -->  77
Already Exists  32933603
Completed Count -->  77
Already Exists  3290192110
Completed Count -->  77
Already Exists  3290192111
Completed Count -->  77
Already Exists  148409613555
Completed Count -->  77
Already Exists  148409619718
Completed Count -->  77
Already Exists  148153610
Completed Count -->  77
Already Exists  148409610
Completed Count -->  77
Already Exists  148409611
Completed Count -->  77
Already Exists  148409612
Completed Count -->  77
Already Exists  148128013
Completed Count -->  77
Already Exists  1484096271
Completed Count -->  77
Already Exists  14840965903
Completed Count -->  77
Already Exists  148409617
Completed Count -->  77
Already Exists  148110610
Completed Count -->  77
Already Exists  148115218
Completed Count -->  77
Already Exists  148409621
Completed Count -->  77
Already Exists  1484096278
Completed Count -->  77
Already Exists  148409622
Completed Count -->  77
Already Exists  148409632
Completed Count -->  77
Already Exists  148409633
Completed Count -->  77
Already Exists  148409634
Completed Count -->  77
Already Exists  148409635
Completed Count -->  77
Already Exists  1484096803
Completed Count -->  77
Already Exists  32924962
Completed Count -->  77
Already Exists  148409639
Completed Count -->  77
Already Exists  148409641
Completed Count -->  77
Already Exists  148409651
Completed Count -->  77
Already Exists  148409653
Completed Count -->  77
Already Exists  148409655
Completed Count -->  77
Already Exists  14840964409
Completed Count -->  77
Already Exists  148409663
Completed Count -->  77
Already Exists  148409668
Completed Count -->  77
Started  1484096266
Started  1484096266
h148 Survivor 266 4096
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481536271', '1481664296', '1481740313', '1481920312', '1482048314', '1482088310', '1482112305', '1482208294', '1482304279', '1482400282', '1482496276', '1482555268', '1482592264', '1482688262', '1482784255', '1482880270', '1482976288', '1483072286', '1483168287', '1483195288', '1483264291', '1483360289', '1483456287', '1483552283', '1483606279', '1483648277', '1483671275', '1483744279', '1483760276', '1483810277', '1483840275', '1483936273', '1484032266', '1484096266']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_271' | NDM=13890 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_296' | NDM=12155 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_313' | NDM=11258 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_312' | NDM=10707 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_314' | NDM=10701 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_310' | NDM=10711 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_305' | NDM=10723 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_294' | NDM=10758 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_279' | NDM=10784 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_282' | NDM=10793 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_276' | NDM=10771 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_268' | NDM=10763 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_264' | NDM=10753 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_262' | NDM=10705 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_255' | NDM=10624 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_270' | NDM=9922 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_288' | NDM=8976 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_286' | NDM=8810 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_287' | NDM=8697 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_288' | NDM=8661 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_291' | NDM=8536 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_289' | NDM=8408 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_287' | NDM=8347 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_283' | NDM=8295 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_279' | NDM=8280 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_277' | NDM=8275 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_275' | NDM=8272 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_279' | NDM=8220 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_276' | NDM=8257 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_277' | NDM=8246 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_275' | NDM=8245 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_273' | NDM=8212 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_266' | NDM=8149 Nstar=460 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_266' | NDM=8044 Nstar=460 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481536271', '1481664296', '1481740313', '1481920312', '1482048314', '1482088310', '1482112305', '1482208294', '1482304279', '1482400282', '1482496276', '1482555268', '1482592264', '1482688262', '1482784255', '1482880270', '1482976288', '1483072286', '1483168287', '1483195288', '1483264291', '1483360289', '1483456287', '1483552283', '1483606279', '1483648277', '1483671275', '1483744279', '1483760276', '1483810277', '1483840275', '1483936273', '1484032266', '1484096266']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0          NaN           0          0           0
1           0          0          NaN           0          0           0
2           0          0          NaN           0          0           0
3           0          0          NaN           0          0           0
4           0          0          NaN           0          0           0
5           0          0          NaN           0          0           0
6           0          0          NaN           0          0           0
7           0          0          NaN           0          0           0
8           0          0          NaN           0          0           0
9           0          0          NaN           0          0           0
10          0          0          NaN           0          0           0
11          0          0          NaN           0          0           0
12          0          0          NaN           0          0           0
13          0          0          NaN           0          0           0
14          0          0          NaN           0          0           0
15          0          0          NaN           0          0           0
16          0          0          NaN           0          0           0
17  148102429  148102420          NaN   148102478  148102443  1481024434
18  148110628  148110618          NaN   148110676  148110642  1481106226
19  148115225  148115217          NaN   148115274  148115236  1481152220
20  148127024  148127016          NaN   148127070  148127036  1481270209
21  148128023  148128015          NaN   148128069  148128035  1481280206
22  148140822  148140811          NaN  1481408101  148140832  1481408167
23  148147623  148147610          NaN   148147690  148147632  1481476159
24  148153624  148153611          NaN   148153683  148153633  1481536151
25  148166421   14816649          NaN   148166489  148166432  1481664184
26  148174023   14817409          NaN   148174092  148174032  1481740258
27  148192029   14819209          NaN   148192093  148192032  1481920159
28  148204838   14820489          NaN   148204891  148204830  1482048169
29  148208838   14820889          NaN   148208892  148208830  1482088290
30  148211238   14821129          NaN   148211292  148211229  1482112155
31  148220839   14822089          NaN   148220894  148220829  1482208426
32  148230441   14823049          NaN   148230496  148230430  1482304416
33  148240044   14824009          NaN   148240096  148240028  1482400414
34  148249647   14824969          NaN   148249696  148249632  1482496615
35  148255545   14825559          NaN   148255597  148255535  1482555631
36  148259245   14825929          NaN   148259296  148259235  1482592640
37  148268847   14826889          NaN   148268897  148268838  1482688647
38  148278446   14827849          NaN   148278496  148278450  1482784651
39  148288045   14828809          NaN   148288095  148288056  1482880658
40  148297659   14829769          NaN   148297694  148297656  1482976676

Watch me go for the  1 th time...
Already Exists  14840961025
Completed Count -->  78
Already Exists  14832642
Completed Count -->  78
Already Exists  14840964127
Completed Count -->  78
Already Exists  32913443
Completed Count -->  78
Already Exists  14840961061
Completed Count -->  78
Already Exists  14812709
Completed Count -->  78
Already Exists  329022513
Completed Count -->  78
Already Exists  1484096567
Completed Count -->  78
Already Exists  3294096956
Completed Count -->  78
Already Exists  32940964414
Completed Count -->  78
Already Exists  329022530
Completed Count -->  78
Already Exists  329409616
Completed Count -->  78
Already Exists  329038417
Completed Count -->  78
Already Exists  329409620
Completed Count -->  78
Already Exists  329038430
Completed Count -->  78
Already Exists  329127010
Completed Count -->  78
Already Exists  329038438
Completed Count -->  78
Already Exists  32904809
Completed Count -->  78
Already Exists  329409643
Completed Count -->  78
Already Exists  148409620589
Completed Count -->  78
Already Exists  329022579
Completed Count -->  78
Already Exists  14840962
Completed Count -->  78
Already Exists  14840963
Completed Count -->  78
Already Exists  14840961156
Completed Count -->  78
Already Exists  14840964
Completed Count -->  78
Already Exists  14840965
Completed Count -->  78
Already Exists  14840966
Completed Count -->  78
Already Exists  14840967
Completed Count -->  78
Already Exists  14812804
Completed Count -->  78
Already Exists  1484096138
Completed Count -->  78
Already Exists  329409673
Completed Count -->  78
Already Exists  329409675
Completed Count -->  78
Already Exists  32906374
Completed Count -->  78
Already Exists  32940965015
Completed Count -->  78
Already Exists  14840961179
Completed Count -->  78
Already Exists  14840961693
Completed Count -->  78
Already Exists  329409696
Completed Count -->  78
Already Exists  3294096555
Completed Count -->  78
Already Exists  1484096179
Completed Count -->  78
Already Exists  1484096194
Completed Count -->  78
Already Exists  14829762
Completed Count -->  78
Already Exists  3294096585
Completed Count -->  78
Already Exists  329067210
Completed Count -->  78
Already Exists  1484096204
Completed Count -->  78
Already Exists  1484096210
Completed Count -->  78
Already Exists  32933603
Completed Count -->  78
Already Exists  3290192110
Completed Count -->  78
Already Exists  3290192111
Completed Count -->  78
Already Exists  148409613555
Completed Count -->  78
Already Exists  148409619718
Completed Count -->  78
Already Exists  148153610
Completed Count -->  78
Already Exists  148409610
Completed Count -->  78
Already Exists  148409611
Completed Count -->  78
Already Exists  148409612
Completed Count -->  78
Already Exists  148128013
Completed Count -->  78
Already Exists  1484096271
Completed Count -->  78
Already Exists  14840965903
Completed Count -->  78
Already Exists  148409617
Completed Count -->  78
Already Exists  148110610
Completed Count -->  78
Already Exists  148115218
Completed Count -->  78
Already Exists  148409621
Completed Count -->  78
Already Exists  1484096278
Completed Count -->  78
Already Exists  148409622
Completed Count -->  78
Already Exists  148409632
Completed Count -->  78
Already Exists  148409633
Completed Count -->  78
Already Exists  148409634
Completed Count -->  78
Already Exists  148409635
Completed Count -->  78
Already Exists  1484096803
Completed Count -->  78
Already Exists  32924962
Completed Count -->  78
Already Exists  148409639
Completed Count -->  78
Already Exists  148409641
Completed Count -->  78
Already Exists  148409651
Completed Count -->  78
Already Exists  148409653
Completed Count -->  78
Already Exists  148409655
Completed Count -->  78
Already Exists  14840964409
Completed Count -->  78
Already Exists  148409663
Completed Count -->  78
Already Exists  148409668
Completed Count -->  78
Already Exists  1484096266
Completed Count -->  78
Started  1484096331
Started  1484096331
h148 Survivor 331 4096
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481024107', '1481106108', '1481152105', '1481270108', '1481280108', '148140894', '148147696', '148153693', '148166492', '148174096', '1481920117', '1482048113', '1482088120', '1482112120', '1482208126', '1482304130', '1482400130', '1482496131', '1482555130', '1482592130', '1482688128', '1482784124', '1482880125', '1482976122', '1483072118', '1483168119', '1483195119', '1483264118', '1483360293', '1483456276', '1483552282', '1483606289', '1483648293', '1483671292', '1483744299', '1483760304', '1483810309', '1483840315', '1483936328', '1484032331', '1484096331']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_107' | NDM=48734 Nstar=157 Ngas=218>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_108' | NDM=49551 Nstar=157 Ngas=80>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_105' | NDM=50314 Nstar=157 Ngas=48>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_108' | NDM=52391 Nstar=157 Ngas=20>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_108' | NDM=52615 Nstar=157 Ngas=19>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_94' | NDM=54379 Nstar=157 Ngas=6>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_96' | NDM=54965 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_93' | NDM=55307 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_92' | NDM=55416 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_96' | NDM=53344 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_117' | NDM=35637 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_113' | NDM=34948 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_120' | NDM=34168 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_120' | NDM=33607 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_126' | NDM=31417 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_130' | NDM=29600 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_130' | NDM=28810 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_131' | NDM=28482 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_130' | NDM=28398 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_130' | NDM=28366 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_128' | NDM=28238 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_124' | NDM=28204 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_125' | NDM=28158 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_122' | NDM=28127 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_118' | NDM=28042 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_119' | NDM=27811 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_119' | NDM=27668 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_118' | NDM=26752 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_293' | NDM=8592 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_276' | NDM=9007 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_282' | NDM=8600 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_289' | NDM=8272 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_293' | NDM=8051 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_292' | NDM=7949 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_299' | NDM=7601 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_304' | NDM=7513 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_309' | NDM=7262 Nstar=155 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_315' | NDM=7153 Nstar=155 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_328' | NDM=6881 Nstar=154 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_331' | NDM=6713 Nstar=154 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_331' | NDM=6629 Nstar=154 Ngas=0>]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481024107', '1481106108', '1481152105', '1481270108', '1481280108', '148140894', '148147696', '148153693', '148166492', '148174096', '1481920117', '1482048113', '1482088120', '1482112120', '1482208126', '1482304130', '1482400130', '1482496131', '1482555130', '1482592130', '1482688128', '1482784124', '1482880125', '1482976122', '1483072118', '1483168119', '1483195119', '1483264118', '1483360293', '1483456276', '1483552282', '1483606289', '1483648293', '1483671292', '1483744299', '1483760304', '1483810309', '1483840315', '1483936328', '1484032331', '1484096331']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0          NaN           0          0           0
1           0          0          NaN           0          0           0
2           0          0          NaN           0          0           0
3           0          0          NaN           0          0           0
4           0          0          NaN           0          0           0
5           0          0          NaN           0          0           0
6           0          0          NaN           0          0           0
7           0          0          NaN           0          0           0
8           0          0          NaN           0          0           0
9           0          0          NaN           0          0           0
10          0          0          NaN           0          0           0
11          0          0          NaN           0          0           0
12          0          0          NaN           0          0           0
13          0          0          NaN           0          0           0
14          0          0          NaN           0          0           0
15          0          0          NaN           0          0           0
16          0          0          NaN           0          0           0
17  148102429  148102420          NaN   148102478  148102443  1481024434
18  148110628  148110618          NaN   148110676  148110642  1481106226
19  148115225  148115217          NaN   148115274  148115236  1481152220
20  148127024  148127016          NaN   148127070  148127036  1481270209
21  148128023  148128015          NaN   148128069  148128035  1481280206
22  148140822  148140811          NaN  1481408101  148140832  1481408167
23  148147623  148147610          NaN   148147690  148147632  1481476159
24  148153624  148153611          NaN   148153683  148153633  1481536151
25  148166421   14816649          NaN   148166489  148166432  1481664184
26  148174023   14817409          NaN   148174092  148174032  1481740258
27  148192029   14819209          NaN   148192093  148192032  1481920159
28  148204838   14820489          NaN   148204891  148204830  1482048169
29  148208838   14820889          NaN   148208892  148208830  1482088290
30  148211238   14821129          NaN   148211292  148211229  1482112155
31  148220839   14822089          NaN   148220894  148220829  1482208426
32  148230441   14823049          NaN   148230496  148230430  1482304416
33  148240044   14824009          NaN   148240096  148240028  1482400414
34  148249647   14824969          NaN   148249696  148249632  1482496615
35  148255545   14825559          NaN   148255597  148255535  1482555631
36  148259245   14825929          NaN   148259296  148259235  1482592640
37  148268847   14826889          NaN   148268897  148268838  1482688647
38  148278446   14827849          NaN   148278496  148278450  1482784651
39  148288045   14828809          NaN   148288095  148288056  1482880658
40  148297659   14829769          NaN   148297694  148297656  1482976676
41  148307261   14830728          NaN   148307291  148307260  1483072660
42  148316861   14831689          NaN   148316888  148316860  1483168670
43  148319561   14831959          NaN   148319588  148319562  1483195670
44  148326460   14832649          NaN   148326484  148326463  1483264670
45  148336059   14833608          NaN   148336080  148336063  1483360684
46  148345660   14834568          NaN   148345680  148345663  1483456722
47  148355259   14835527          NaN   148355277  148355262  1483552797
48  148360662   14836067          NaN   148360680  148360665  1483606800
49  148364861   14836487          NaN   148364880  148364865  1483648798
50  148367160   14836717          NaN   148367180  148367165  1483671802
51  148374460   14837447          NaN   148374477  148374464  1483744794
52  148376059   14837607          NaN   148376077  148376065  1483760800
53  148381059   14838107          NaN   148381077  148381066  1483810802
54  148384058   14838407          NaN   148384077  148384066  1483840796
55  148393659   14839367          NaN   148393676  148393670  1483936801
56  148403266   14840327          NaN   148403276  148403275  1484032798
57  148409668   14840967          NaN   148409676  148409677  1484096803

    14840968565  1484096857
0           NaN         NaN
1           NaN         NaN
2           NaN         NaN
3           NaN         NaN
4           NaN         NaN
5           NaN         NaN
6           NaN         NaN
7           NaN         NaN
8           NaN         NaN
9           NaN         NaN
10          NaN         NaN
11          NaN         NaN
12          NaN         NaN
13          NaN         NaN
14          NaN         NaN
15          NaN         NaN
16          NaN         NaN
17          NaN         NaN
18          NaN         NaN
19          NaN         NaN
20          NaN         NaN
21          NaN         NaN
22          NaN         NaN
23          NaN         NaN
24          NaN         NaN
25          NaN         NaN
26          NaN         NaN
27          NaN         NaN
28          NaN         NaN
29          NaN         NaN
30          NaN         NaN
31          NaN         NaN
32          NaN         NaN
33          NaN         NaN
34          NaN         NaN
35          NaN         NaN
36          NaN         NaN
37          NaN         NaN
38          NaN         NaN
39          NaN         NaN
40          NaN         NaN
41          NaN         NaN
42          NaN         NaN
43          NaN         NaN
44          NaN         NaN
45          NaN         NaN
46          NaN         NaN
47          NaN         NaN
48          NaN         NaN
49          NaN         NaN
50          NaN         NaN
51          NaN         NaN
52          NaN         NaN
53          NaN         NaN
54          NaN         NaN
55          NaN         NaN
56          NaN         NaN
57          NaN         NaN

[58 rows x 78 columns]
Finished  1484096331
Finished  1484096331
Completed Count -->  79
Started  148409676
Started  148409676
h148 Survivor 76 4096

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148102478', '148110676', '148115274', '148127070', '148128069', '1481408101', '148147690', '148153683', '148166489', '148174092', '148192093', '148204891', '148208892', '148211292', '148220894', '148230496', '148240096', '148249696', '148255597', '148259296', '148268897', '148278496', '148288095', '148297694', '148307291', '148316888', '148319588', '148326484', '148336080', '148345680', '148355277', '148360680', '148364880', '148367180', '148374477', '148376077', '148381077', '148384077', '148393676', '148403276', '148409676']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_78' | NDM=76880 Nstar=510 Ngas=2266>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_76' | NDM=77604 Nstar=510 Ngas=1139>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_74' | NDM=76982 Nstar=510 Ngas=1194>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_70' | NDM=79487 Nstar=510 Ngas=1144>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_69' | NDM=78883 Nstar=510 Ngas=1090>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_101' | NDM=48502 Nstar=510 Ngas=118>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_90' | NDM=60460 Nstar=510 Ngas=22>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_83' | NDM=63440 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_89' | NDM=57204 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_92' | NDM=55397 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_93' | NDM=51609 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_91' | NDM=47743 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_92' | NDM=46569 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_92' | NDM=45870 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_94' | NDM=43887 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_96' | NDM=42793 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_96' | NDM=42485 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_96' | NDM=41987 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_97' | NDM=41602 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_96' | NDM=41352 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_97' | NDM=40944 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_96' | NDM=40681 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_95' | NDM=40515 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_94' | NDM=40429 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_91' | NDM=40352 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_88' | NDM=40318 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_88' | NDM=40312 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_84' | NDM=40275 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_80' | NDM=40265 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_80' | NDM=40246 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_77' | NDM=40232 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_80' | NDM=40229 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_80' | NDM=40244 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_80' | NDM=40265 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_77' | NDM=40287 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_77' | NDM=40279 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_77' | NDM=40306 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_77' | NDM=40311 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_76' | NDM=40333 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_76' | NDM=40314 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_76' | NDM=40261 Nstar=510 Ngas=0>]
Watch me go for the  2 th time...
Already Exists  14840961025
Completed Count -->  79
Already Exists  14832642
Completed Count -->  79
Already Exists  14840964127
Completed Count -->  79
Already Exists  32913443
Completed Count -->  79
Already Exists  14840961061
Completed Count -->  79
Already Exists  14812709
Completed Count -->  79
Already Exists  329022513
Completed Count -->  79
Already Exists  1484096567
Completed Count -->  79
Already Exists  3294096956
Completed Count -->  79
Already Exists  32940964414
Completed Count -->  79
Already Exists  329022530
Completed Count -->  79
Already Exists  329409616
Completed Count -->  79
Already Exists  329038417
Completed Count -->  79
Already Exists  329409620
Completed Count -->  79
Already Exists  329038430
Completed Count -->  79
Already Exists  329127010
Completed Count -->  79
Already Exists  329038438
Completed Count -->  79
Already Exists  32904809
Completed Count -->  79
Already Exists  329409643
Completed Count -->  79
Already Exists  148409620589
Completed Count -->  79
Already Exists  329022579
Completed Count -->  79
Already Exists  14840962
Completed Count -->  79
Already Exists  14840963
Completed Count -->  79
Already Exists  14840961156
Completed Count -->  79
Already Exists  14840964
Completed Count -->  79
Already Exists  14840965
Completed Count -->  79
Already Exists  14840966
Completed Count -->  79
Already Exists  14840967
Completed Count -->  79
Already Exists  14812804
Completed Count -->  79
Already Exists  1484096138
Completed Count -->  79
Already Exists  329409673
Completed Count -->  79
Already Exists  329409675
Completed Count -->  79
Already Exists  32906374
Completed Count -->  79
Already Exists  32940965015
Completed Count -->  79
Already Exists  14840961179
Completed Count -->  79
Already Exists  14840961693
Completed Count -->  79
Already Exists  329409696
Completed Count -->  79
Already Exists  3294096555
Completed Count -->  79
Already Exists  1484096179
Completed Count -->  79
Already Exists  1484096194
Completed Count -->  79
Already Exists  14829762
Completed Count -->  79
Already Exists  3294096585
Completed Count -->  79
Already Exists  329067210
Completed Count -->  79
Already Exists  1484096204
Completed Count -->  79
Already Exists  1484096210
Completed Count -->  79
Already Exists  32933603
Completed Count -->  79
Already Exists  3290192110
Completed Count -->  79
Already Exists  3290192111
Completed Count -->  79
Already Exists  148409613555
Completed Count -->  79
Already Exists  148409619718
Completed Count -->  79
Already Exists  148153610
Completed Count -->  79
Already Exists  148409610
Completed Count -->  79
Already Exists  148409611
Completed Count -->  79
Already Exists  148409612
Completed Count -->  79
Already Exists  148128013
Completed Count -->  79
Already Exists  1484096271
Completed Count -->  79
Already Exists  14840965903
Completed Count -->  79
Already Exists  148409617
Completed Count -->  79
Already Exists  148110610
Completed Count -->  79
Already Exists  148115218
Completed Count -->  79
Already Exists  148409621
Completed Count -->  79
Already Exists  1484096278
Completed Count -->  79
Already Exists  148409622
Completed Count -->  79
Already Exists  148409632
Completed Count -->  79
Already Exists  148409633
Completed Count -->  79
Already Exists  148409634
Completed Count -->  79
Already Exists  148409635
Completed Count -->  79
Already Exists  1484096803
Completed Count -->  79
Already Exists  32924962
Completed Count -->  79
Already Exists  148409639
Completed Count -->  79
Already Exists  148409641
Completed Count -->  79
Already Exists  148409651
Completed Count -->  79
Already Exists  148409653
Completed Count -->  79
Already Exists  148409655
Completed Count -->  79
Already Exists  14840964409
Completed Count -->  79
Already Exists  148409663
Completed Count -->  79
Already Exists  148409668
Completed Count -->  79
Already Exists  1484096266
Completed Count -->  79
Already Exists  1484096331
Completed Count -->  79
Started  148409676
Started  148409676
h148 Survivor 76 4096

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148102478', '148110676', '148115274', '148127070', '148128069', '1481408101', '148147690', '148153683', '148166489', '148174092', '148192093', '148204891', '148208892', '148211292', '148220894', '148230496', '148240096', '148249696', '148255597', '148259296', '148268897', '148278496', '148288095', '148297694', '148307291', '148316888', '148319588', '148326484', '148336080', '148345680', '148355277', '148360680', '148364880', '148367180', '148374477', '148376077', '148381077', '148384077', '148393676', '148403276', '148409676']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_78' | NDM=76880 Nstar=510 Ngas=2266>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_76' | NDM=77604 Nstar=510 Ngas=1139>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_74' | NDM=76982 Nstar=510 Ngas=1194>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_70' | NDM=79487 Nstar=510 Ngas=1144>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_69' | NDM=78883 Nstar=510 Ngas=1090>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_101' | NDM=48502 Nstar=510 Ngas=118>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_90' | NDM=60460 Nstar=510 Ngas=22>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_83' | NDM=63440 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_89' | NDM=57204 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_92' | NDM=55397 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_93' | NDM=51609 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_91' | NDM=47743 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_92' | NDM=46569 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_92' | NDM=45870 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_94' | NDM=43887 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_96' | NDM=42793 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_96' | NDM=42485 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_96' | NDM=41987 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_97' | NDM=41602 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_96' | NDM=41352 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_97' | NDM=40944 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_96' | NDM=40681 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_95' | NDM=40515 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_94' | NDM=40429 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_91' | NDM=40352 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_88' | NDM=40318 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_88' | NDM=40312 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_84' | NDM=40275 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_80' | NDM=40265 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_80' | NDM=40246 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_77' | NDM=40232 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_80' | NDM=40229 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_80' | NDM=40244 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_80' | NDM=40265 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_77' | NDM=40287 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_77' | NDM=40279 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_77' | NDM=40306 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_77' | NDM=40311 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_76' | NDM=40333 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_76' | NDM=40314 Nstar=510 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_76' | NDM=40261 Nstar=510 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148102478', '148110676', '148115274', '148127070', '148128069', '1481408101', '148147690', '148153683', '148166489', '148174092', '148192093', '148204891', '148208892', '148211292', '148220894', '148230496', '148240096', '148249696', '148255597', '148259296', '148268897', '148278496', '148288095', '148297694', '148307291', '148316888', '148319588', '148326484', '148336080', '148345680', '148355277', '148360680', '148364880', '148367180', '148374477', '148376077', '148381077', '148384077', '148393676', '148403276', '148409676']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0          NaN           0          0           0
1           0          0          NaN           0          0           0
2           0          0          NaN           0          0           0
3           0          0          NaN           0          0           0
4           0          0          NaN           0          0           0
5           0          0          NaN           0          0           0
6           0          0          NaN           0          0           0
7           0          0          NaN           0          0           0
8           0          0          NaN           0          0           0
9           0          0          NaN           0          0           0
10          0          0          NaN           0          0           0
11          0          0          NaN           0          0           0
12          0          0          NaN           0          0           0
13          0          0          NaN           0          0           0
14          0          0          NaN           0          0           0
15          0          0          NaN           0          0           0
16          0          0          NaN           0          0           0
17  148102429  148102420          NaN   148102478  148102443  1481024434
18  148110628  148110618          NaN   148110676  148110642  1481106226
19  148115225  148115217          NaN   148115274  148115236  1481152220
20  148127024  148127016          NaN   148127070  148127036  1481270209
21  148128023  148128015          NaN   148128069  148128035  1481280206
22  148140822  148140811          NaN  1481408101  148140832  1481408167
23  148147623  148147610          NaN   148147690  148147632  1481476159
24  148153624  148153611          NaN   148153683  148153633  1481536151
25  148166421   14816649          NaN   148166489  148166432  1481664184
26  148174023   14817409          NaN   148174092  148174032  1481740258
27  148192029   14819209          NaN   148192093  148192032  1481920159
28  148204838   14820489          NaN   148204891  148204830  1482048169
29  148208838   14820889          NaN   148208892  148208830  1482088290
30  148211238   14821129          NaN   148211292  148211229  1482112155
31  148220839   14822089          NaN   148220894  148220829  1482208426
32  148230441   14823049          NaN   148230496  148230430  1482304416
33  148240044   14824009          NaN   148240096  148240028  1482400414
34  148249647   14824969          NaN   148249696  148249632  1482496615
35  148255545   14825559          NaN   148255597  148255535  1482555631
36  148259245   14825929          NaN   148259296  148259235  1482592640
37  148268847   14826889          NaN   148268897  148268838  1482688647
38  148278446   14827849          NaN   148278496  148278450  1482784651
39  148288045   14828809          NaN   148288095  148288056  1482880658
40  148297659   14829769          NaN   148297694  148297656  1482976676
41  148307261   14830728          NaN   148307291  148307260  1483072660
42  148316861   14831689          NaN   148316888  148316860  1483168670
43  148319561   14831959          NaN   148319588  148319562  1483195670
44  148326460   14832649          NaN   148326484  148326463  1483264670
45  148336059   14833608          NaN   148336080  148336063  1483360684
46  148345660   14834568          NaN   148345680  148345663  1483456722
47  148355259   14835527          NaN   148355277  148355262  1483552797
48  148360662   14836067          NaN   148360680  148360665  1483606800
49  148364861   14836487          NaN   148364880  148364865  1483648798
50  148367160   14836717          NaN   148367180  148367165  1483671802
51  148374460   14837447          NaN   148374477  148374464  1483744794
52  148376059   14837607          NaN   148376077  148376065  1483760800
53  148381059   14838107          NaN   148381077  148381066  1483810802
54  148384058   14838407          NaN   148384077  148384066  1483840796
55  148393659   14839367          NaN   148393676  148393670  1483936801
56  148403266   14840327          NaN   148403276  148403275  1484032798
57  148409668   14840967          NaN   148409676  148409677  1484096803

    14840968565  1484096857
0           NaN         NaN
1           NaN         NaN
2           NaN         NaN
3           NaN         NaN
4           NaN         NaN
5           NaN         NaN
6           NaN         NaN
7           NaN         NaN
8           NaN         NaN
9           NaN         NaN
10          NaN         NaN
11          NaN         NaN
12          NaN         NaN
13          NaN         NaN
14          NaN         NaN
15          NaN         NaN
16          NaN         NaN
17          NaN         NaN
18          NaN         NaN
19          NaN         NaN
20          NaN         NaN
21          NaN         NaN
22          NaN         NaN
23          NaN         NaN
24          NaN         NaN
25          NaN         NaN
26          NaN         NaN
27          NaN         NaN
28          NaN         NaN
29          NaN         NaN
30          NaN         NaN
31          NaN         NaN
32          NaN         NaN
33          NaN         NaN
34          NaN         NaN
35          NaN         NaN
36          NaN         NaN
37          NaN         NaN
38          NaN         NaN
39          NaN         NaN
40          NaN         NaN
41          NaN         NaN
42          NaN         NaN
43          NaN         NaN
44          NaN         NaN
45          NaN         NaN
46          NaN         NaN
47          NaN         NaN
48          NaN         NaN
49          NaN         NaN
50          NaN         NaN
51          NaN         NaN
52          NaN         NaN
53          NaN         NaN
54          NaN         NaN
55          NaN         NaN
56          NaN         NaN
57          NaN         NaN

[58 rows x 78 columns]
Finished  148409676
Finished  148409676
Completed Count -->  80
Started  148409677
Started  148409677
h148 Survivor 77 4096

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148102443', '148110642', '148115236', '148127036', '148128035', '148140832', '148147632', '148153633', '148166432', '148174032', '148192032', '148204830', '148208830', '148211229', '148220829', '148230430', '148240028', '148249632', '148255535', '148259235', '148268838', '148278450', '148288056', '148297656', '148307260', '148316860', '148319562', '148326463', '148336063', '148345663', '148355262', '148360665', '148364865', '148367165', '148374464', '148376065', '148381066', '148384066', '148393670', '148403275', '148409677']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_43' | NDM=130618 Nstar=886 Ngas=30950>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_42' | NDM=143225 Nstar=994 Ngas=30058>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_36' | NDM=149932 Nstar=1021 Ngas=27700>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_36' | NDM=154642 Nstar=1207 Ngas=36396>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_35' | NDM=154637 Nstar=1207 Ngas=37783>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_32' | NDM=158509 Nstar=1234 Ngas=44005>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_32' | NDM=161551 Nstar=1267 Ngas=43318>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_33' | NDM=164273 Nstar=1320 Ngas=43672>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_32' | NDM=172070 Nstar=1424 Ngas=42709>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_32' | NDM=175474 Nstar=1509 Ngas=43546>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_32' | NDM=174311 Nstar=1665 Ngas=42604>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_30' | NDM=177624 Nstar=1830 Ngas=38228>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_30' | NDM=178591 Nstar=1942 Ngas=37621>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_29' | NDM=179163 Nstar=2059 Ngas=36283>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_29' | NDM=181915 Nstar=2182 Ngas=35500>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_30' | NDM=180162 Nstar=2396 Ngas=35052>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_28' | NDM=175764 Nstar=2666 Ngas=32752>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_32' | NDM=127383 Nstar=2822 Ngas=28092>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_35' | NDM=139419 Nstar=2891 Ngas=27011>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_35' | NDM=127592 Nstar=3275 Ngas=23249>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_38' | NDM=123608 Nstar=3444 Ngas=15676>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_50' | NDM=89708 Nstar=3527 Ngas=11113>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_56' | NDM=76305 Nstar=3538 Ngas=7628>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_56' | NDM=74149 Nstar=3538 Ngas=7004>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_60' | NDM=70630 Nstar=3538 Ngas=6144>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_60' | NDM=65636 Nstar=3538 Ngas=5159>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_62' | NDM=64526 Nstar=3538 Ngas=4948>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_63' | NDM=61994 Nstar=3538 Ngas=4423>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_63' | NDM=56050 Nstar=3538 Ngas=4065>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_63' | NDM=57044 Nstar=3538 Ngas=3723>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_62' | NDM=55101 Nstar=3538 Ngas=3251>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_65' | NDM=54181 Nstar=3538 Ngas=2955>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_65' | NDM=53298 Nstar=3538 Ngas=2902>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_65' | NDM=52821 Nstar=3538 Ngas=2831>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_64' | NDM=50847 Nstar=3538 Ngas=2388>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_65' | NDM=50332 Nstar=3538 Ngas=2292>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_66' | NDM=48483 Nstar=3538 Ngas=2081>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_66' | NDM=47083 Nstar=3538 Ngas=1834>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_70' | NDM=41128 Nstar=3538 Ngas=925>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_75' | NDM=37935 Nstar=3538 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_77' | NDM=37111 Nstar=3538 Ngas=0>]
Watch me go for the  3 th time...
Already Exists  14840961025
Completed Count -->  80
Already Exists  14832642
Completed Count -->  80
Already Exists  14840964127
Completed Count -->  80
Already Exists  32913443
Completed Count -->  80
Already Exists  14840961061
Completed Count -->  80
Already Exists  14812709
Completed Count -->  80
Already Exists  329022513
Completed Count -->  80
Already Exists  1484096567
Completed Count -->  80
Already Exists  3294096956
Completed Count -->  80
Already Exists  32940964414
Completed Count -->  80
Already Exists  329022530
Completed Count -->  80
Already Exists  329409616
Completed Count -->  80
Already Exists  329038417
Completed Count -->  80
Already Exists  329409620
Completed Count -->  80
Already Exists  329038430
Completed Count -->  80
Already Exists  329127010
Completed Count -->  80
Already Exists  329038438
Completed Count -->  80
Already Exists  32904809
Completed Count -->  80
Already Exists  329409643
Completed Count -->  80
Already Exists  148409620589
Completed Count -->  80
Already Exists  329022579
Completed Count -->  80
Already Exists  14840962
Completed Count -->  80
Already Exists  14840963
Completed Count -->  80
Already Exists  14840961156
Completed Count -->  80
Already Exists  14840964
Completed Count -->  80
Already Exists  14840965
Completed Count -->  80
Already Exists  14840966
Completed Count -->  80
Already Exists  14840967
Completed Count -->  80
Already Exists  14812804
Completed Count -->  80
Already Exists  1484096138
Completed Count -->  80
Already Exists  329409673
Completed Count -->  80
Already Exists  329409675
Completed Count -->  80
Already Exists  32906374
Completed Count -->  80
Already Exists  32940965015
Completed Count -->  80
Already Exists  14840961179
Completed Count -->  80
Already Exists  14840961693
Completed Count -->  80
Already Exists  329409696
Completed Count -->  80
Already Exists  3294096555
Completed Count -->  80
Already Exists  1484096179
Completed Count -->  80
Already Exists  1484096194
Completed Count -->  80
Already Exists  14829762
Completed Count -->  80
Already Exists  3294096585
Completed Count -->  80
Already Exists  329067210
Completed Count -->  80
Already Exists  1484096204
Completed Count -->  80
Already Exists  1484096210
Completed Count -->  80
Already Exists  32933603
Completed Count -->  80
Already Exists  3290192110
Completed Count -->  80
Already Exists  3290192111
Completed Count -->  80
Already Exists  148409613555
Completed Count -->  80
Already Exists  148409619718
Completed Count -->  80
Already Exists  148153610
Completed Count -->  80
Already Exists  148409610
Completed Count -->  80
Already Exists  148409611
Completed Count -->  80
Already Exists  148409612
Completed Count -->  80
Already Exists  148128013
Completed Count -->  80
Already Exists  1484096271
Completed Count -->  80
Already Exists  14840965903
Completed Count -->  80
Already Exists  148409617
Completed Count -->  80
Already Exists  148110610
Completed Count -->  80
Already Exists  148115218
Completed Count -->  80
Already Exists  148409621
Completed Count -->  80
Already Exists  1484096278
Completed Count -->  80
Already Exists  148409622
Completed Count -->  80
Already Exists  148409632
Completed Count -->  80
Already Exists  148409633
Completed Count -->  80
Already Exists  148409634
Completed Count -->  80
Already Exists  148409635
Completed Count -->  80
Already Exists  1484096803
Completed Count -->  80
Already Exists  32924962
Completed Count -->  80
Already Exists  148409639
Completed Count -->  80
Already Exists  148409641
Completed Count -->  80
Already Exists  148409651
Completed Count -->  80
Already Exists  148409653
Completed Count -->  80
Already Exists  148409655
Completed Count -->  80
Already Exists  14840964409
Completed Count -->  80
Already Exists  148409663
Completed Count -->  80
Already Exists  148409668
Completed Count -->  80
Already Exists  1484096266
Completed Count -->  80
Already Exists  1484096331
Completed Count -->  80
Already Exists  148409676
Completed Count -->  80
Started  148409677
Started  148409677
h148 Survivor 77 4096

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148102443', '148110642', '148115236', '148127036', '148128035', '148140832', '148147632', '148153633', '148166432', '148174032', '148192032', '148204830', '148208830', '148211229', '148220829', '148230430', '148240028', '148249632', '148255535', '148259235', '148268838', '148278450', '148288056', '148297656', '148307260', '148316860', '148319562', '148326463', '148336063', '148345663', '148355262', '148360665', '148364865', '148367165', '148374464', '148376065', '148381066', '148384066', '148393670', '148403275', '148409677']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_43' | NDM=130618 Nstar=886 Ngas=30950>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_42' | NDM=143225 Nstar=994 Ngas=30058>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_36' | NDM=149932 Nstar=1021 Ngas=27700>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_36' | NDM=154642 Nstar=1207 Ngas=36396>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_35' | NDM=154637 Nstar=1207 Ngas=37783>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_32' | NDM=158509 Nstar=1234 Ngas=44005>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_32' | NDM=161551 Nstar=1267 Ngas=43318>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_33' | NDM=164273 Nstar=1320 Ngas=43672>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_32' | NDM=172070 Nstar=1424 Ngas=42709>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_32' | NDM=175474 Nstar=1509 Ngas=43546>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_32' | NDM=174311 Nstar=1665 Ngas=42604>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_30' | NDM=177624 Nstar=1830 Ngas=38228>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_30' | NDM=178591 Nstar=1942 Ngas=37621>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_29' | NDM=179163 Nstar=2059 Ngas=36283>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_29' | NDM=181915 Nstar=2182 Ngas=35500>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_30' | NDM=180162 Nstar=2396 Ngas=35052>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_28' | NDM=175764 Nstar=2666 Ngas=32752>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_32' | NDM=127383 Nstar=2822 Ngas=28092>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_35' | NDM=139419 Nstar=2891 Ngas=27011>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_35' | NDM=127592 Nstar=3275 Ngas=23249>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_38' | NDM=123608 Nstar=3444 Ngas=15676>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_50' | NDM=89708 Nstar=3527 Ngas=11113>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_56' | NDM=76305 Nstar=3538 Ngas=7628>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_56' | NDM=74149 Nstar=3538 Ngas=7004>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_60' | NDM=70630 Nstar=3538 Ngas=6144>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_60' | NDM=65636 Nstar=3538 Ngas=5159>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_62' | NDM=64526 Nstar=3538 Ngas=4948>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_63' | NDM=61994 Nstar=3538 Ngas=4423>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_63' | NDM=56050 Nstar=3538 Ngas=4065>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_63' | NDM=57044 Nstar=3538 Ngas=3723>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_62' | NDM=55101 Nstar=3538 Ngas=3251>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_65' | NDM=54181 Nstar=3538 Ngas=2955>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_65' | NDM=53298 Nstar=3538 Ngas=2902>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_65' | NDM=52821 Nstar=3538 Ngas=2831>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_64' | NDM=50847 Nstar=3538 Ngas=2388>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_65' | NDM=50332 Nstar=3538 Ngas=2292>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_66' | NDM=48483 Nstar=3538 Ngas=2081>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_66' | NDM=47083 Nstar=3538 Ngas=1834>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_70' | NDM=41128 Nstar=3538 Ngas=925>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_75' | NDM=37935 Nstar=3538 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_77' | NDM=37111 Nstar=3538 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148102443', '148110642', '148115236', '148127036', '148128035', '148140832', '148147632', '148153633', '148166432', '148174032', '148192032', '148204830', '148208830', '148211229', '148220829', '148230430', '148240028', '148249632', '148255535', '148259235', '148268838', '148278450', '148288056', '148297656', '148307260', '148316860', '148319562', '148326463', '148336063', '148345663', '148355262', '148360665', '148364865', '148367165', '148374464', '148376065', '148381066', '148384066', '148393670', '148403275', '148409677']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0          NaN           0          0           0
1           0          0          NaN           0          0           0
2           0          0          NaN           0          0           0
3           0          0          NaN           0          0           0
4           0          0          NaN           0          0           0
5           0          0          NaN           0          0           0
6           0          0          NaN           0          0           0
7           0          0          NaN           0          0           0
8           0          0          NaN           0          0           0
9           0          0          NaN           0          0           0
10          0          0          NaN           0          0           0
11          0          0          NaN           0          0           0
12          0          0          NaN           0          0           0
13          0          0          NaN           0          0           0
14          0          0          NaN           0          0           0
15          0          0          NaN           0          0           0
16          0          0          NaN           0          0           0
17  148102429  148102420          NaN   148102478  148102443  1481024434
18  148110628  148110618          NaN   148110676  148110642  1481106226
19  148115225  148115217          NaN   148115274  148115236  1481152220
20  148127024  148127016          NaN   148127070  148127036  1481270209
21  148128023  148128015          NaN   148128069  148128035  1481280206
22  148140822  148140811          NaN  1481408101  148140832  1481408167
23  148147623  148147610          NaN   148147690  148147632  1481476159
24  148153624  148153611          NaN   148153683  148153633  1481536151
25  148166421   14816649          NaN   148166489  148166432  1481664184
26  148174023   14817409          NaN   148174092  148174032  1481740258
27  148192029   14819209          NaN   148192093  148192032  1481920159
28  148204838   14820489          NaN   148204891  148204830  1482048169
29  148208838   14820889          NaN   148208892  148208830  1482088290
30  148211238   14821129          NaN   148211292  148211229  1482112155
31  148220839   14822089          NaN   148220894  148220829  1482208426
32  148230441   14823049          NaN   148230496  148230430  1482304416
33  148240044   14824009          NaN   148240096  148240028  1482400414
34  148249647   14824969          NaN   148249696  148249632  1482496615
35  148255545   14825559          NaN   148255597  148255535  1482555631
36  148259245   14825929          NaN   148259296  148259235  1482592640
37  148268847   14826889          NaN   148268897  148268838  1482688647
38  148278446   14827849          NaN   148278496  148278450  1482784651
39  148288045   14828809          NaN   148288095  148288056  1482880658
40  148297659   14829769          NaN   148297694  148297656  1482976676
41  148307261   14830728          NaN   148307291  148307260  1483072660
42  148316861   14831689          NaN   148316888  148316860  1483168670
43  148319561   14831959          NaN   148319588  148319562  1483195670
44  148326460   14832649          NaN   148326484  148326463  1483264670
45  148336059   14833608          NaN   148336080  148336063  1483360684
46  148345660   14834568          NaN   148345680  148345663  1483456722
47  148355259   14835527          NaN   148355277  148355262  1483552797
48  148360662   14836067          NaN   148360680  148360665  1483606800
49  148364861   14836487          NaN   148364880  148364865  1483648798
50  148367160   14836717          NaN   148367180  148367165  1483671802
51  148374460   14837447          NaN   148374477  148374464  1483744794
52  148376059   14837607          NaN   148376077  148376065  1483760800
53  148381059   14838107          NaN   148381077  148381066  1483810802
54  148384058   14838407          NaN   148384077  148384066  1483840796
55  148393659   14839367          NaN   148393676  148393670  1483936801
56  148403266   14840327          NaN   148403276  148403275  1484032798
57  148409668   14840967          NaN   148409676  148409677  1484096803

    14840968565  1484096857
0           NaN         NaN
1           NaN         NaN
2           NaN         NaN
3           NaN         NaN
4           NaN         NaN
5           NaN         NaN
6           NaN         NaN
7           NaN         NaN
8           NaN         NaN
9           NaN         NaN
10          NaN         NaN
11          NaN         NaN
12          NaN         NaN
13          NaN         NaN
14          NaN         NaN
15          NaN         NaN
16          NaN         NaN
17          NaN         NaN
18          NaN         NaN
19          NaN         NaN
20          NaN         NaN
21          NaN         NaN
22          NaN         NaN
23          NaN         NaN
24          NaN         NaN
25          NaN         NaN
26          NaN         NaN
27          NaN         NaN
28          NaN         NaN
29          NaN         NaN
30          NaN         NaN
31          NaN         NaN
32          NaN         NaN
33          NaN         NaN
34          NaN         NaN
35          NaN         NaN
36          NaN         NaN
37          NaN         NaN
38          NaN         NaN
39          NaN         NaN
40          NaN         NaN
41          NaN         NaN
42          NaN         NaN
43          NaN         NaN
44          NaN         NaN
45          NaN         NaN
46          NaN         NaN
47          NaN         NaN
48          NaN         NaN
49          NaN         NaN
50          NaN         NaN
51          NaN         NaN
52          NaN         NaN
53          NaN         NaN
54          NaN         NaN
55          NaN         NaN
56          NaN         NaN
57          NaN         NaN

[58 rows x 78 columns]
Finished  148409677
Finished  148409677
Completed Count -->  81
Started  329096015
Started  329096015
h329 Zombie 15 0960

[0, 0, 0, '329013931', '329018825', '329019224', '329022527', '329027511', '329028812', '329034714', '329038416', '329045718', '329048016', '329057614', '329063713', '329067211', '32907689', '32907779', '32908648', '329096015', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[-1.0 -1.0 -1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_31' | NDM=8885 Nstar=19 Ngas=7526>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_25' | NDM=23021 Nstar=224 Ngas=17950>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_24' | NDM=23626 Nstar=246 Ngas=18525>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_27' | NDM=27487 Nstar=497 Ngas=22605>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_11' | NDM=84783 Nstar=2096 Ngas=69785>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_12' | NDM=101322 Nstar=3884 Ngas=76716>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_14' | NDM=152492 Nstar=11497 Ngas=77447>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_16' | NDM=158674 Nstar=13649 Ngas=78276>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_18' | NDM=146304 Nstar=15952 Ngas=78295>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_16' | NDM=155208 Nstar=16285 Ngas=88942>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_14' | NDM=174657 Nstar=21597 Ngas=98906>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_13' | NDM=177981 Nstar=23888 Ngas=98003>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_11' | NDM=191748 Nstar=25282 Ngas=108325>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_9' | NDM=177166 Nstar=31767 Ngas=86812>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_9' | NDM=182239 Nstar=31790 Ngas=88089>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_8' | NDM=219319 Nstar=34309 Ngas=93312>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_15' | NDM=92150 Nstar=34748 Ngas=29328>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_1' | NDM=15196786 Nstar=7990531 Ngas=11217754>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1' | NDM=15578696 Nstar=10217161 Ngas=11755160>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1' | NDM=15747259 Nstar=11784296 Ngas=11968198>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1' | NDM=15761360 Nstar=13147640 Ngas=12285340>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1' | NDM=15832293 Nstar=16238307 Ngas=12845015>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1' | NDM=15990494 Nstar=17157603 Ngas=12930029>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1' | NDM=17922263 Nstar=20611248 Ngas=14418911>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1' | NDM=20220937 Nstar=24755716 Ngas=15683385>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1' | NDM=20568424 Nstar=26701663 Ngas=15670524>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1' | NDM=21292522 Nstar=29070320 Ngas=16200299>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1' | NDM=22138471 Nstar=34143108 Ngas=16098369>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1' | NDM=22233114 Nstar=37948971 Ngas=16217261>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1' | NDM=22265580 Nstar=38395660 Ngas=16249600>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1' | NDM=22541017 Nstar=41934879 Ngas=16143723>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1' | NDM=23087646 Nstar=46137673 Ngas=15803476>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1' | NDM=23617232 Nstar=50351876 Ngas=15643527>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1' | NDM=24221915 Nstar=53530614 Ngas=15566115>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1' | NDM=24513553 Nstar=54733955 Ngas=15453339>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1' | NDM=26676353 Nstar=59100003 Ngas=16082599>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1' | NDM=29354421 Nstar=64311453 Ngas=16874211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1' | NDM=31464533 Nstar=68631869 Ngas=16998639>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1' | NDM=32730524 Nstar=72629063 Ngas=17093857>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1' | NDM=33576743 Nstar=76168219 Ngas=16582991>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1' | NDM=34007948 Nstar=77829519 Ngas=16271248>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1' | NDM=34817467 Nstar=82227069 Ngas=16133249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1' | NDM=35279749 Nstar=86891324 Ngas=15727574>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1' | NDM=34968677 Nstar=91010100 Ngas=14700620>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1' | NDM=34685343 Nstar=94725659 Ngas=13794122>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1' | NDM=34411771 Nstar=98430465 Ngas=12965040>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
Watch me go for the  4 th time...
Already Exists  14840961025
Completed Count -->  81
Already Exists  14832642
Completed Count -->  81
Already Exists  14840964127
Completed Count -->  81
Already Exists  32913443
Completed Count -->  81
Already Exists  14840961061
Completed Count -->  81
Already Exists  14812709
Completed Count -->  81
Already Exists  329022513
Completed Count -->  81
Already Exists  1484096567
Completed Count -->  81
Already Exists  3294096956
Completed Count -->  81
Already Exists  32940964414
Completed Count -->  81
Already Exists  329022530
Completed Count -->  81
Already Exists  329409616
Completed Count -->  81
Already Exists  329038417
Completed Count -->  81
Already Exists  329409620
Completed Count -->  81
Already Exists  329038430
Completed Count -->  81
Already Exists  329127010
Completed Count -->  81
Already Exists  329038438
Completed Count -->  81
Already Exists  32904809
Completed Count -->  81
Already Exists  329409643
Completed Count -->  81
Already Exists  148409620589
Completed Count -->  81
Already Exists  329022579
Completed Count -->  81
Already Exists  14840962
Completed Count -->  81
Already Exists  14840963
Completed Count -->  81
Already Exists  14840961156
Completed Count -->  81
Already Exists  14840964
Completed Count -->  81
Already Exists  14840965
Completed Count -->  81
Already Exists  14840966
Completed Count -->  81
Already Exists  14840967
Completed Count -->  81
Already Exists  14812804
Completed Count -->  81
Already Exists  1484096138
Completed Count -->  81
Already Exists  329409673
Completed Count -->  81
Already Exists  329409675
Completed Count -->  81
Already Exists  32906374
Completed Count -->  81
Already Exists  32940965015
Completed Count -->  81
Already Exists  14840961179
Completed Count -->  81
Already Exists  14840961693
Completed Count -->  81
Already Exists  329409696
Completed Count -->  81
Already Exists  3294096555
Completed Count -->  81
Already Exists  1484096179
Completed Count -->  81
Already Exists  1484096194
Completed Count -->  81
Already Exists  14829762
Completed Count -->  81
Already Exists  3294096585
Completed Count -->  81
Already Exists  329067210
Completed Count -->  81
Already Exists  1484096204
Completed Count -->  81
Already Exists  1484096210
Completed Count -->  81
Already Exists  32933603
Completed Count -->  81
Already Exists  3290192110
Completed Count -->  81
Already Exists  3290192111
Completed Count -->  81
Already Exists  148409613555
Completed Count -->  81
Already Exists  148409619718
Completed Count -->  81
Already Exists  148153610
Completed Count -->  81
Already Exists  148409610
Completed Count -->  81
Already Exists  148409611
Completed Count -->  81
Already Exists  148409612
Completed Count -->  81
Already Exists  148128013
Completed Count -->  81
Already Exists  1484096271
Completed Count -->  81
Already Exists  14840965903
Completed Count -->  81
Already Exists  148409617
Completed Count -->  81
Already Exists  148110610
Completed Count -->  81
Already Exists  148115218
Completed Count -->  81
Already Exists  148409621
Completed Count -->  81
Already Exists  1484096278
Completed Count -->  81
Already Exists  148409622
Completed Count -->  81
Already Exists  148409632
Completed Count -->  81
Already Exists  148409633
Completed Count -->  81
Already Exists  148409634
Completed Count -->  81
Already Exists  148409635
Completed Count -->  81
Already Exists  1484096803
Completed Count -->  81
Already Exists  32924962
Completed Count -->  81
Already Exists  148409639
Completed Count -->  81
Already Exists  148409641
Completed Count -->  81
Already Exists  148409651
Completed Count -->  81
Already Exists  148409653
Completed Count -->  81
Already Exists  148409655
Completed Count -->  81
Already Exists  14840964409
Completed Count -->  81
Already Exists  148409663
Completed Count -->  81
Already Exists  148409668
Completed Count -->  81
Already Exists  1484096266
Completed Count -->  81
Already Exists  1484096331
Completed Count -->  81
Already Exists  148409676
Completed Count -->  81
Already Exists  148409677
Completed Count -->  81
Started  329096015
Started  329096015
h329 Zombie 15 0960

[0, 0, 0, '329013931', '329018825', '329019224', '329022527', '329027511', '329028812', '329034714', '329038416', '329045718', '329048016', '329057614', '329063713', '329067211', '32907689', '32907779', '32908648', '329096015', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[-1.0 -1.0 -1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_31' | NDM=8885 Nstar=19 Ngas=7526>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_25' | NDM=23021 Nstar=224 Ngas=17950>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_24' | NDM=23626 Nstar=246 Ngas=18525>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_27' | NDM=27487 Nstar=497 Ngas=22605>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_11' | NDM=84783 Nstar=2096 Ngas=69785>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_12' | NDM=101322 Nstar=3884 Ngas=76716>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_14' | NDM=152492 Nstar=11497 Ngas=77447>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_16' | NDM=158674 Nstar=13649 Ngas=78276>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_18' | NDM=146304 Nstar=15952 Ngas=78295>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_16' | NDM=155208 Nstar=16285 Ngas=88942>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_14' | NDM=174657 Nstar=21597 Ngas=98906>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_13' | NDM=177981 Nstar=23888 Ngas=98003>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_11' | NDM=191748 Nstar=25282 Ngas=108325>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_9' | NDM=177166 Nstar=31767 Ngas=86812>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_9' | NDM=182239 Nstar=31790 Ngas=88089>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_8' | NDM=219319 Nstar=34309 Ngas=93312>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_15' | NDM=92150 Nstar=34748 Ngas=29328>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_1' | NDM=15196786 Nstar=7990531 Ngas=11217754>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1' | NDM=15578696 Nstar=10217161 Ngas=11755160>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1' | NDM=15747259 Nstar=11784296 Ngas=11968198>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1' | NDM=15761360 Nstar=13147640 Ngas=12285340>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1' | NDM=15832293 Nstar=16238307 Ngas=12845015>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1' | NDM=15990494 Nstar=17157603 Ngas=12930029>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1' | NDM=17922263 Nstar=20611248 Ngas=14418911>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1' | NDM=20220937 Nstar=24755716 Ngas=15683385>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1' | NDM=20568424 Nstar=26701663 Ngas=15670524>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1' | NDM=21292522 Nstar=29070320 Ngas=16200299>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1' | NDM=22138471 Nstar=34143108 Ngas=16098369>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1' | NDM=22233114 Nstar=37948971 Ngas=16217261>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1' | NDM=22265580 Nstar=38395660 Ngas=16249600>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1' | NDM=22541017 Nstar=41934879 Ngas=16143723>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1' | NDM=23087646 Nstar=46137673 Ngas=15803476>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1' | NDM=23617232 Nstar=50351876 Ngas=15643527>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1' | NDM=24221915 Nstar=53530614 Ngas=15566115>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1' | NDM=24513553 Nstar=54733955 Ngas=15453339>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1' | NDM=26676353 Nstar=59100003 Ngas=16082599>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1' | NDM=29354421 Nstar=64311453 Ngas=16874211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1' | NDM=31464533 Nstar=68631869 Ngas=16998639>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1' | NDM=32730524 Nstar=72629063 Ngas=17093857>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1' | NDM=33576743 Nstar=76168219 Ngas=16582991>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1' | NDM=34007948 Nstar=77829519 Ngas=16271248>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1' | NDM=34817467 Nstar=82227069 Ngas=16133249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1' | NDM=35279749 Nstar=86891324 Ngas=15727574>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1' | NDM=34968677 Nstar=91010100 Ngas=14700620>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1' | NDM=34685343 Nstar=94725659 Ngas=13794122>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1' | NDM=34411771 Nstar=98430465 Ngas=12965040>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
[0, 0, 0, '329013931', '329018825', '329019224', '329022527', '329027511', '329028812', '329034714', '329038416', '329045718', '329048016', '329057614', '329063713', '329067211', '32907689', '32907779', '32908648', '329096015', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71         NaN           0           0        NaN        NaN
1         96         NaN   329009662    32900969        NaN        NaN
2        108         NaN   329010856   329010810        NaN        NaN
3        139         NaN  3290139151   329013963        NaN        NaN
4        188         NaN  3290188114  3290188111        NaN        NaN
5        192         NaN  3290192110  3290192111        NaN        NaN
6        225         NaN    32902251    32902251        NaN        NaN
7        275         NaN    32902751    32902751        NaN        NaN
8        288         NaN    32902881    32902881        NaN        NaN
9        347         NaN    32903471    32903471        NaN        NaN
10       384         NaN    32903841    32903841        NaN        NaN
11       457         NaN    32904571    32904571        NaN        NaN
12       480         NaN    32904801    32904801        NaN        NaN
13       576         NaN    32905761    32905761        NaN        NaN
14       637         NaN    32906371    32906371        NaN        NaN
15       672         NaN    32906721    32906721        NaN        NaN
16       768         NaN    32907681    32907681        NaN        NaN
17       777         NaN    32907771    32907771        NaN        NaN
18       864         NaN    32908641    32908641        NaN        NaN
19       960         NaN    32909601    32909601        NaN        NaN
20       974         NaN    32909741    32909741        NaN        NaN
21      1056         NaN    32910561    32910561        NaN        NaN
22      1106         NaN    32911061    32911061        NaN        NaN
23      1152         NaN    32911521    32911521        NaN        NaN
24      1248         NaN    32912481    32912481        NaN        NaN
25      1270         NaN    32912701    32912701        NaN        NaN
26      1344         NaN    32913441    32913441        NaN        NaN
27      1440         NaN    32914401    32914401        NaN        NaN
28      1476         NaN    32914761    32914761        NaN        NaN
29      1536         NaN    32915361    32915361        NaN        NaN
..       ...         ...         ...         ...        ...        ...
32      1740         NaN    32917401    32917401        NaN        NaN
33      1824         NaN    32918241    32918241        NaN        NaN
34      1920         NaN    32919201    32919201        NaN        NaN
35      2016         NaN    32920161    32920161        NaN        NaN
36      2088         NaN    32920881    32920881        NaN        NaN
37      2112         NaN    32921121    32921121        NaN        NaN
38      2208         NaN    32922081    32922081        NaN        NaN
39      2304         NaN    32923041    32923041        NaN        NaN
40      2400         NaN    32924001    32924001        NaN        NaN
41      2496         NaN    32924961    32924961        NaN        NaN
42      2555         NaN    32925551    32925551        NaN        NaN
43      2592         NaN    32925921    32925921        NaN        NaN
44      2688         NaN    32926881    32926881        NaN        NaN
45      2784         NaN    32927841    32927841        NaN        NaN
46      2880         NaN    32928801    32928801        NaN        NaN
47      2976         NaN    32929761    32929761        NaN        NaN
48      3072         NaN    32930721    32930721        NaN        NaN
49      3168         NaN    32931681    32931681        NaN        NaN
50      3195         NaN    32931951    32931951        NaN        NaN
51      3264         NaN    32932641    32932641        NaN        NaN
52      3360         NaN    32933601    32933601        NaN        NaN
53      3456         NaN    32934561    32934561        NaN        NaN
54      3552         NaN    32935521    32935521        NaN        NaN
55      3606         NaN    32936061    32936061        NaN        NaN
56      3648         NaN    32936481    32936481        NaN        NaN
57      3744         NaN    32937441    32937441        NaN        NaN
58      3840         NaN    32938401    32938401        NaN        NaN
59      3936         NaN    32939361    32939361        NaN        NaN
60      4032         NaN    32940321    32940321        NaN        NaN
61      4096         NaN    32940961    32940961        NaN        NaN

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0         NaN
1    3290096221           0  32900961020   329009640           0         NaN
2    3290108234           0  32901081471   329010844           0         NaN
3    3290139545           0   3290139119  3290139138           0         NaN
4    3290188538           0    329018879  3290188197           0         NaN
5    3290192554           0    329019278  3290192195           0         NaN
6    3290225544           0    329022582  3290225210  3290225189         NaN
7    3290275579           0    329027574  3290275196  3290275121         NaN
8    3290288619           0    329028872  3290288186  3290288109         NaN
9    3290347581           0    329034758  3290347164   329034764         NaN
10   3290384579           0    329038460  3290384127   329038446         NaN
11   3290457588           0    329045751  3290457104   329045736         NaN
12   3290480583           0    329048049  3290480102   329048032         NaN
13   3290576536           0    329057638   329057696   329057626         NaN
14   3290637554           0    329063738  3290637104   329063727         NaN
15   3290672559           0    329067235  3290672100   329067221         NaN
16   3290768567           0    329076836   329076886   329076824         NaN
17   3290777570           0    329077736   329077786   329077723         NaN
18   3290864555           0    329086434   329086477   329086420         NaN
19   3290960543           0    329096033   329096073   329096021         NaN
20   3290974534           0    329097431   329097473   329097420         NaN
21   3291056562           0    329105639   329105668   329105622         NaN
22   3291106741           0    329110652   329110666   329110622         NaN
23   3291152887           0    329115265   329115271   329115223         NaN
24  32912481314           0    329124869   329124868   329124825         NaN
25   3291270963           0    329127068   329127066   329127026         NaN
26   3291344954           0    329134471   329134461   329134424         NaN
27   3291440948           0    329144073   329144058   329144021         NaN
28   3291476953           0    329147674   329147661   329147621         NaN
29   3291536954           0    329153675   329153662   329153634         NaN
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043         NaN
33  32918241363           0    329182478   329182462   329182445         NaN
34  32919201657           0    329192075   329192057   329192047         NaN
35  32920161763           0    329201673   329201653   329201648         NaN
36  32920881809           0   3292088210   329208852   329208849         NaN
37  32921121823           0   3292112188   329211251   329211250         NaN
38  32922081833           0   3292208214   329220850   329220848         NaN
39  32923041843           0   3292304234   329230450   329230449         NaN
40  32924001879           0   3292400261   329240048   329240050         NaN
41  32924962122           0   3292496271   329249648   329249650         NaN

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14817401283', '14819201352', '14820481355', '14820881352', '14821121339', '14822081323', '14823041325', '14824001415', '14824962156', '14825552227', '14825922252', '14826882262', '14827842302', '14828802820', '14829763088', '14830723176', '14831683211', '14831953202', '14832643229', '14833603398', '14834564151', '14835524165', '14836064214', '14836484218', '14836714207', '14837444198', '14837604240', '14838104265', '14838404328', '14839364927', '14840324951', '14840964944']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_1283' | NDM=2690 Nstar=10 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_1352' | NDM=2440 Nstar=10 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_1355' | NDM=2340 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_1352' | NDM=2329 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_1339' | NDM=2325 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_1323' | NDM=2305 Nstar=20 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_1325' | NDM=2270 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_1415' | NDM=2054 Nstar=10 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_2156' | NDM=1287 Nstar=13 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_2227' | NDM=1221 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_2252' | NDM=1193 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_2262' | NDM=1149 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_2302' | NDM=1099 Nstar=9 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_2820' | NDM=853 Nstar=8 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_3088' | NDM=752 Nstar=7 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_3176' | NDM=712 Nstar=7 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_3211' | NDM=695 Nstar=7 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_3202' | NDM=690 Nstar=7 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_3229' | NDM=678 Nstar=7 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_3398' | NDM=629 Nstar=7 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_4151' | NDM=501 Nstar=3 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_4165' | NDM=489 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_4214' | NDM=480 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_4218' | NDM=474 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_4207' | NDM=473 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_4198' | NDM=470 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_4240' | NDM=463 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_4265' | NDM=455 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_4328' | NDM=445 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_4927' | NDM=380 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_4951' | NDM=370 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_4944' | NDM=369 Nstar=1 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14817401283', '14819201352', '14820481355', '14820881352', '14821121339', '14822081323', '14823041325', '14824001415', '14824962156', '14825552227', '14825922252', '14826882262', '14827842302', '14828802820', '14829763088', '14830723176', '14831683211', '14831953202', '14832643229', '14833603398', '14834564151', '14835524165', '14836064214', '14836484218', '14836714207', '14837444198', '14837604240', '14838104265', '14838404328', '14839364927', '14840324951', '14840964944']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0          NaN           0          0           0
1           0          0          NaN           0          0           0
2           0          0          NaN           0          0           0
3           0          0          NaN           0          0           0
4           0          0          NaN           0          0           0
5           0          0          NaN           0          0           0
6           0          0          NaN           0          0           0
7           0          0          NaN           0          0           0
8           0          0          NaN           0          0           0
9           0          0          NaN           0          0           0
10          0          0          NaN           0          0           0
11          0          0          NaN           0          0           0
12          0          0          NaN           0          0           0
13          0          0          NaN           0          0           0
14          0          0          NaN           0          0           0
15          0          0          NaN           0          0           0
16          0          0          NaN           0          0           0
17  148102429  148102420          NaN   148102478  148102443  1481024434
18  148110628  148110618          NaN   148110676  148110642  1481106226
19  148115225  148115217          NaN   148115274  148115236  1481152220
20  148127024  148127016          NaN   148127070  148127036  1481270209
21  148128023  148128015          NaN   148128069  148128035  1481280206
22  148140822  148140811          NaN  1481408101  148140832  1481408167
23  148147623  148147610          NaN   148147690  148147632  1481476159
24  148153624  148153611          NaN   148153683  148153633  1481536151
25  148166421   14816649          NaN   148166489  148166432  1481664184
26  148174023   14817409          NaN   148174092  148174032  1481740258
27  148192029   14819209          NaN   148192093  148192032  1481920159
28  148204838   14820489          NaN   148204891  148204830  1482048169
29  148208838   14820889          NaN   148208892  148208830  1482088290
30  148211238   14821129          NaN   148211292  148211229  1482112155
31  148220839   14822089          NaN   148220894  148220829  1482208426
32  148230441   14823049          NaN   148230496  148230430  1482304416
33  148240044   14824009          NaN   148240096  148240028  1482400414
34  148249647   14824969          NaN   148249696  148249632  1482496615
35  148255545   14825559          NaN   148255597  148255535  1482555631
36  148259245   14825929          NaN   148259296  148259235  1482592640
37  148268847   14826889          NaN   148268897  148268838  1482688647
38  148278446   14827849          NaN   148278496  148278450  1482784651
39  148288045   14828809          NaN   148288095  148288056  1482880658
40  148297659   14829769          NaN   148297694  148297656  1482976676
41  148307261   14830728          NaN   148307291  148307260  1483072660
42  148316861   14831689          NaN   148316888  148316860  1483168670
43  148319561   14831959          NaN   148319588  148319562  1483195670
44  148326460   14832649          NaN   148326484  148326463  1483264670
45  148336059   14833608          NaN   148336080  148336063  1483360684
46  148345660   14834568          NaN   148345680  148345663  1483456722
47  148355259   14835527          NaN   148355277  148355262  1483552797
48  148360662   14836067          NaN   148360680  148360665  1483606800
49  148364861   14836487          NaN   148364880  148364865  1483648798
50  148367160   14836717          NaN   148367180  148367165  1483671802
51  148374460   14837447          NaN   148374477  148374464  1483744794
52  148376059   14837607          NaN   148376077  148376065  1483760800
53  148381059   14838107          NaN   148381077  148381066  1483810802
54  148384058   14838407          NaN   148384077  148384066  1483840796
55  148393659   14839367          NaN   148393676  148393670  1483936801
56  148403266   14840327          NaN   148403276  148403275  1484032798
57  148409668   14840967          NaN   148409676  148409677  1484096803

    14840968565  1484096857
0           NaN         NaN
1           NaN         NaN
2           NaN         NaN
3           NaN         NaN
4           NaN         NaN
5           NaN         NaN
6           NaN         NaN
7           NaN         NaN
8           NaN         NaN
9           NaN         NaN
10          NaN         NaN
11          NaN         NaN
12          NaN         NaN
13          NaN         NaN
14          NaN         NaN
15          NaN         NaN
16          NaN         NaN
17          NaN         NaN
18          NaN         NaN
19          NaN         NaN
20          NaN         NaN
21          NaN         NaN
22          NaN         NaN
23          NaN         NaN
24          NaN         NaN
25          NaN         NaN
26          NaN         NaN
27          NaN         NaN
28          NaN         NaN
29          NaN         NaN
30          NaN         NaN
31          NaN         NaN
32          NaN         NaN
33          NaN         NaN
34          NaN         NaN
35          NaN         NaN
36          NaN         NaN
37          NaN         NaN
38          NaN         NaN
39          NaN         NaN
40          NaN         NaN
41          NaN         NaN
42          NaN         NaN
43          NaN         NaN
44          NaN         NaN
45          NaN         NaN
46          NaN         NaN
47          NaN         NaN
48          NaN         NaN
49          NaN         NaN
50          NaN         NaN
51          NaN         NaN
52          NaN         NaN
53          NaN         NaN
54          NaN         NaN
55          NaN         NaN
56          NaN         NaN
57          NaN         NaN

[58 rows x 78 columns]
Finished  14840964944
Finished  14840964944
Completed Count -->  83
Started  32914768
Started  32914768
h329 Zombie 8 1476

[0, 0, 0, '3290139195', '329018878', '329019276', '329022572', '329027571', '329028873', '329034757', '329038431', '329045719', '329048019', '329057613', '329063711', '32906728', '32907688', '32907778', '32908647', '32909608', '32909748', '32910569', '32911069', '329115210', '32912489', '32912709', '32913447', '32914406', '32914768', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[-1.0 -1.0 -1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_195' | NDM=1820 Nstar=0 Ngas=242>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_78' | NDM=6867 Nstar=0 Ngas=4153>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_76' | NDM=7223 Nstar=0 Ngas=4431>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_72' | NDM=8610 Nstar=0 Ngas=6784>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_71' | NDM=10966 Nstar=5 Ngas=8137>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_73' | NDM=11552 Nstar=8 Ngas=8293>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_57' | NDM=16091 Nstar=21 Ngas=13447>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_31' | NDM=36192 Nstar=981 Ngas=45305>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_19' | NDM=80038 Nstar=2304 Ngas=107824>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_19' | NDM=103985 Nstar=10244 Ngas=98194>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_13' | NDM=161302 Nstar=14183 Ngas=141395>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_11' | NDM=173448 Nstar=18520 Ngas=176236>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_8' | NDM=227294 Nstar=28897 Ngas=206628>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_8' | NDM=297738 Nstar=39118 Ngas=243523>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_8' | NDM=299374 Nstar=39319 Ngas=238759>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_7' | NDM=301384 Nstar=43311 Ngas=239083>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_8' | NDM=275327 Nstar=56401 Ngas=202492>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_8' | NDM=267248 Nstar=56942 Ngas=185213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_9' | NDM=131736 Nstar=62237 Ngas=97540>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_9' | NDM=121565 Nstar=66288 Ngas=82409>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_10' | NDM=126945 Nstar=66654 Ngas=74488>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_9' | NDM=117770 Nstar=67392 Ngas=61200>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_9' | NDM=114701 Nstar=67378 Ngas=58958>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_7' | NDM=109594 Nstar=67638 Ngas=47473>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_6' | NDM=92523 Nstar=67620 Ngas=40792>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_8' | NDM=69394 Nstar=66718 Ngas=33407>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1' | NDM=21292522 Nstar=29070320 Ngas=16200299>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1' | NDM=22138471 Nstar=34143108 Ngas=16098369>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1' | NDM=22233114 Nstar=37948971 Ngas=16217261>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1' | NDM=22265580 Nstar=38395660 Ngas=16249600>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1' | NDM=22541017 Nstar=41934879 Ngas=16143723>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1' | NDM=23087646 Nstar=46137673 Ngas=15803476>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1' | NDM=23617232 Nstar=50351876 Ngas=15643527>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1' | NDM=24221915 Nstar=53530614 Ngas=15566115>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1' | NDM=24513553 Nstar=54733955 Ngas=15453339>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1' | NDM=26676353 Nstar=59100003 Ngas=16082599>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1' | NDM=29354421 Nstar=64311453 Ngas=16874211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1' | NDM=31464533 Nstar=68631869 Ngas=16998639>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1' | NDM=32730524 Nstar=72629063 Ngas=17093857>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1' | NDM=33576743 Nstar=76168219 Ngas=16582991>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1' | NDM=34007948 Nstar=77829519 Ngas=16271248>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1' | NDM=34817467 Nstar=82227069 Ngas=16133249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1' | NDM=35279749 Nstar=86891324 Ngas=15727574>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1' | NDM=34968677 Nstar=91010100 Ngas=14700620>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1' | NDM=34685343 Nstar=94725659 Ngas=13794122>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1' | NDM=34411771 Nstar=98430465 Ngas=12965040>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
[0, 0, 0, '3290139195', '329018878', '329019276', '329022572', '329027571', '329028873', '329034757', '329038431', '329045719', '329048019', '329057613', '329063711', '32906728', '32907688', '32907778', '32908647', '32909608', '32909748', '32910569', '32911069', '329115210', '32912489', '32912709', '32913447', '32914406', '32914768', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71         NaN           0           0        NaN        NaN
1         96         NaN   329009662    32900969        NaN        NaN
2        108         NaN   329010856   329010810        NaN        NaN
3        139         NaN  3290139151   329013963        NaN        NaN
4        188         NaN  3290188114  3290188111        NaN        NaN
5        192         NaN  3290192110  3290192111        NaN        NaN
6        225         NaN    32902251    32902251        NaN        NaN
7        275         NaN    32902751    32902751        NaN        NaN
8        288         NaN    32902881    32902881        NaN        NaN
9        347         NaN    32903471    32903471        NaN        NaN
10       384         NaN    32903841    32903841        NaN        NaN
11       457         NaN    32904571    32904571        NaN        NaN
12       480         NaN    32904801    32904801        NaN        NaN
13       576         NaN    32905761    32905761        NaN        NaN
14       637         NaN    32906371    32906371        NaN        NaN
15       672         NaN    32906721    32906721        NaN        NaN
16       768         NaN    32907681    32907681        NaN        NaN
17       777         NaN    32907771    32907771        NaN        NaN
18       864         NaN    32908641    32908641        NaN        NaN
19       960         NaN    32909601    32909601        NaN        NaN
20       974         NaN    32909741    32909741        NaN        NaN
21      1056         NaN    32910561    32910561        NaN        NaN
22      1106         NaN    32911061    32911061        NaN        NaN
23      1152         NaN    32911521    32911521        NaN        NaN
24      1248         NaN    32912481    32912481        NaN        NaN
25      1270         NaN    32912701    32912701        NaN        NaN
26      1344         NaN    32913441    32913441        NaN        NaN
27      1440         NaN    32914401    32914401        NaN        NaN
28      1476         NaN    32914761    32914761        NaN        NaN
29      1536         NaN    32915361    32915361        NaN        NaN
..       ...         ...         ...         ...        ...        ...
32      1740         NaN    32917401    32917401        NaN        NaN
33      1824         NaN    32918241    32918241        NaN        NaN
34      1920         NaN    32919201    32919201        NaN        NaN
35      2016         NaN    32920161    32920161        NaN        NaN
36      2088         NaN    32920881    32920881        NaN        NaN
37      2112         NaN    32921121    32921121        NaN        NaN
38      2208         NaN    32922081    32922081        NaN        NaN
39      2304         NaN    32923041    32923041        NaN        NaN
40      2400         NaN    32924001    32924001        NaN        NaN
41      2496         NaN    32924961    32924961        NaN        NaN
42      2555         NaN    32925551    32925551        NaN        NaN
43      2592         NaN    32925921    32925921        NaN        NaN
44      2688         NaN    32926881    32926881        NaN        NaN
45      2784         NaN    32927841    32927841        NaN        NaN
46      2880         NaN    32928801    32928801        NaN        NaN
47      2976         NaN    32929761    32929761        NaN        NaN
48      3072         NaN    32930721    32930721        NaN        NaN
49      3168         NaN    32931681    32931681        NaN        NaN
50      3195         NaN    32931951    32931951        NaN        NaN
51      3264         NaN    32932641    32932641        NaN        NaN
52      3360         NaN    32933601    32933601        NaN        NaN
53      3456         NaN    32934561    32934561        NaN        NaN
54      3552         NaN    32935521    32935521        NaN        NaN
55      3606         NaN    32936061    32936061        NaN        NaN
56      3648         NaN    32936481    32936481        NaN        NaN
57      3744         NaN    32937441    32937441        NaN        NaN
58      3840         NaN    32938401    32938401        NaN        NaN
59      3936         NaN    32939361    32939361        NaN        NaN
60      4032         NaN    32940321    32940321        NaN        NaN
61      4096         NaN    32940961    32940961        NaN        NaN

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0         NaN
1    3290096221           0  32900961020   329009640           0         NaN
2    3290108234           0  32901081471   329010844           0         NaN
3    3290139545           0   3290139119  3290139138           0         NaN
4    3290188538           0    329018879  3290188197           0         NaN
5    3290192554           0    329019278  3290192195           0         NaN
6    3290225544           0    329022582  3290225210  3290225189         NaN
7    3290275579           0    329027574  3290275196  3290275121         NaN
8    3290288619           0    329028872  3290288186  3290288109         NaN
9    3290347581           0    329034758  3290347164   329034764         NaN
10   3290384579           0    329038460  3290384127   329038446         NaN
11   3290457588           0    329045751  3290457104   329045736         NaN
12   3290480583           0    329048049  3290480102   329048032         NaN
13   3290576536           0    329057638   329057696   329057626         NaN
14   3290637554           0    329063738  3290637104   329063727         NaN
15   3290672559           0    329067235  3290672100   329067221         NaN
16   3290768567           0    329076836   329076886   329076824         NaN
17   3290777570           0    329077736   329077786   329077723         NaN
18   3290864555           0    329086434   329086477   329086420         NaN
19   3290960543           0    329096033   329096073   329096021         NaN
20   3290974534           0    329097431   329097473   329097420         NaN
21   3291056562           0    329105639   329105668   329105622         NaN
22   3291106741           0    329110652   329110666   329110622         NaN
23   3291152887           0    329115265   329115271   329115223         NaN
24  32912481314           0    329124869   329124868   329124825         NaN
25   3291270963           0    329127068   329127066   329127026         NaN
26   3291344954           0    329134471   329134461   329134424         NaN
27   3291440948           0    329144073   329144058   329144021         NaN
28   3291476953           0    329147674   329147661   329147621         NaN
29   3291536954           0    329153675   329153662   329153634         NaN
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043         NaN
33  32918241363           0    329182478   329182462   329182445         NaN
34  32919201657           0    329192075   329192057   329192047         NaN
35  32920161763           0    329201673   329201653   329201648         NaN
36  32920881809           0   3292088210   329208852   329208849         NaN
37  32921121823           0   3292112188   329211251   329211250         NaN
38  32922081833           0   3292208214   329220850   329220848         NaN
39  32923041843           0   3292304234   329230450   329230449         NaN
40  32924001879           0   3292400261   329240048   329240050         NaN
41  32924962122           0   3292496271   329249648   329249650         NaN
42  32925552182           0   3292555278   329255548   329255551         NaN

Watch me go for the  5 th time...
Already Exists  14840961025
Completed Count -->  84
Already Exists  14832642
Completed Count -->  84
Already Exists  14840964127
Completed Count -->  84
Already Exists  32913443
Completed Count -->  84
Already Exists  14840961061
Completed Count -->  84
Already Exists  14812709
Completed Count -->  84
Already Exists  329022513
Completed Count -->  84
Already Exists  1484096567
Completed Count -->  84
Already Exists  3294096956
Completed Count -->  84
Already Exists  32940964414
Completed Count -->  84
Already Exists  329022530
Completed Count -->  84
Already Exists  329409616
Completed Count -->  84
Already Exists  329038417
Completed Count -->  84
Already Exists  329409620
Completed Count -->  84
Already Exists  329038430
Completed Count -->  84
Already Exists  329127010
Completed Count -->  84
Already Exists  329038438
Completed Count -->  84
Already Exists  32904809
Completed Count -->  84
Already Exists  329409643
Completed Count -->  84
Already Exists  148409620589
Completed Count -->  84
Already Exists  329022579
Completed Count -->  84
Already Exists  14840962
Completed Count -->  84
Already Exists  14840963
Completed Count -->  84
Already Exists  14840961156
Completed Count -->  84
Already Exists  14840964
Completed Count -->  84
Already Exists  14840965
Completed Count -->  84
Already Exists  14840966
Completed Count -->  84
Already Exists  14840967
Completed Count -->  84
Already Exists  14812804
Completed Count -->  84
Already Exists  1484096138
Completed Count -->  84
Already Exists  329409673
Completed Count -->  84
Already Exists  329409675
Completed Count -->  84
Already Exists  32906374
Completed Count -->  84
Already Exists  32940965015
Completed Count -->  84
Already Exists  14840961179
Completed Count -->  84
Already Exists  14840961693
Completed Count -->  84
Already Exists  329409696
Completed Count -->  84
Already Exists  3294096555
Completed Count -->  84
Already Exists  1484096179
Completed Count -->  84
Already Exists  1484096194
Completed Count -->  84
Already Exists  14829762
Completed Count -->  84
Already Exists  3294096585
Completed Count -->  84
Already Exists  329067210
Completed Count -->  84
Already Exists  1484096204
Completed Count -->  84
Already Exists  1484096210
Completed Count -->  84
Already Exists  32933603
Completed Count -->  84
Already Exists  3290192110
Completed Count -->  84
Already Exists  3290192111
Completed Count -->  84
Already Exists  148409613555
Completed Count -->  84
Already Exists  148409619718
Completed Count -->  84
Already Exists  148153610
Completed Count -->  84
Already Exists  148409610
Completed Count -->  84
Already Exists  148409611
Completed Count -->  84
Already Exists  148409612
Completed Count -->  84
Already Exists  148128013
Completed Count -->  84
Already Exists  1484096271
Completed Count -->  84
Already Exists  14840965903
Completed Count -->  84
Already Exists  148409617
Completed Count -->  84
Already Exists  148110610
Completed Count -->  84
Already Exists  148115218
Completed Count -->  84
Already Exists  148409621
Completed Count -->  84
Already Exists  1484096278
Completed Count -->  84
Already Exists  148409622
Completed Count -->  84
Already Exists  148409632
Completed Count -->  84
Already Exists  148409633
Completed Count -->  84
Already Exists  148409634
Completed Count -->  84
Already Exists  148409635
Completed Count -->  84
Already Exists  1484096803
Completed Count -->  84
Already Exists  32924962
Completed Count -->  84
Already Exists  148409639
Completed Count -->  84
Already Exists  148409641
Completed Count -->  84
Already Exists  148409651
Completed Count -->  84
Already Exists  148409653
Completed Count -->  84
Already Exists  148409655
Completed Count -->  84
Already Exists  14840964409
Completed Count -->  84
Already Exists  148409663
Completed Count -->  84
Already Exists  148409668
Completed Count -->  84
Already Exists  1484096266
Completed Count -->  84
Already Exists  1484096331
Completed Count -->  84
Already Exists  148409676
Completed Count -->  84
Already Exists  148409677
Completed Count -->  84
Already Exists  329096015
Completed Count -->  84
Already Exists  14840964944
Completed Count -->  84
Already Exists  32914768
Completed Count -->  84
Started  1484096857
Started  1484096857
h148 Survivor 857 4096
Watch me go for the  6 th time...
Already Exists  14840961025
Completed Count -->  84
Already Exists  14832642
Completed Count -->  84
Already Exists  14840964127
Completed Count -->  84
Already Exists  32913443
Completed Count -->  84
Already Exists  14840961061
Completed Count -->  84
Already Exists  14812709
Completed Count -->  84
Already Exists  329022513
Completed Count -->  84
Already Exists  1484096567
Completed Count -->  84
Already Exists  3294096956
Completed Count -->  84
Already Exists  32940964414
Completed Count -->  84
Already Exists  329022530
Completed Count -->  84
Already Exists  329409616
Completed Count -->  84
Already Exists  329038417
Completed Count -->  84
Already Exists  329409620
Completed Count -->  84
Already Exists  329038430
Completed Count -->  84
Already Exists  329127010
Completed Count -->  84
Already Exists  329038438
Completed Count -->  84
Already Exists  32904809
Completed Count -->  84
Already Exists  329409643
Completed Count -->  84
Already Exists  148409620589
Completed Count -->  84
Already Exists  329022579
Completed Count -->  84
Already Exists  14840962
Completed Count -->  84
Already Exists  14840963
Completed Count -->  84
Already Exists  14840961156
Completed Count -->  84
Already Exists  14840964
Completed Count -->  84
Already Exists  14840965
Completed Count -->  84
Already Exists  14840966
Completed Count -->  84
Already Exists  14840967
Completed Count -->  84
Already Exists  14812804
Completed Count -->  84
Already Exists  1484096138
Completed Count -->  84
Already Exists  329409673
Completed Count -->  84
Already Exists  329409675
Completed Count -->  84
Already Exists  32906374
Completed Count -->  84
Already Exists  32940965015
Completed Count -->  84
Already Exists  14840961179
Completed Count -->  84
Already Exists  14840961693
Completed Count -->  84
Already Exists  329409696
Completed Count -->  84
Already Exists  3294096555
Completed Count -->  84
Already Exists  1484096179
Completed Count -->  84
Already Exists  1484096194
Completed Count -->  84
Already Exists  14829762
Completed Count -->  84
Already Exists  3294096585
Completed Count -->  84
Already Exists  329067210
Completed Count -->  84
Already Exists  1484096204
Completed Count -->  84
Already Exists  1484096210
Completed Count -->  84
Already Exists  32933603
Completed Count -->  84
Already Exists  3290192110
Completed Count -->  84
Already Exists  3290192111
Completed Count -->  84
Already Exists  148409613555
Completed Count -->  84
Already Exists  148409619718
Completed Count -->  84
Already Exists  148153610
Completed Count -->  84
Already Exists  148409610
Completed Count -->  84
Already Exists  148409611
Completed Count -->  84
Already Exists  148409612
Completed Count -->  84
Already Exists  148128013
Completed Count -->  84
Already Exists  1484096271
Completed Count -->  84
Already Exists  14840965903
Completed Count -->  84
Already Exists  148409617
Completed Count -->  84
Already Exists  148110610
Completed Count -->  84
Already Exists  148115218
Completed Count -->  84
Already Exists  148409621
Completed Count -->  84
Already Exists  1484096278
Completed Count -->  84
Already Exists  148409622
Completed Count -->  84
Already Exists  148409632
Completed Count -->  84
Already Exists  148409633
Completed Count -->  84
Already Exists  148409634
Completed Count -->  84
Already Exists  148409635
Completed Count -->  84
Already Exists  1484096803
Completed Count -->  84
Already Exists  32924962
Completed Count -->  84
Already Exists  148409639
Completed Count -->  84
Already Exists  148409641
Completed Count -->  84
Already Exists  148409651
Completed Count -->  84
Already Exists  148409653
Completed Count -->  84
Already Exists  148409655
Completed Count -->  84
Already Exists  14840964409
Completed Count -->  84
Already Exists  148409663
Completed Count -->  84
Already Exists  148409668
Completed Count -->  84
Already Exists  1484096266
Completed Count -->  84
Already Exists  1484096331
Completed Count -->  84
Already Exists  148409676
Completed Count -->  84
Already Exists  148409677
Completed Count -->  84
Already Exists  329096015
Completed Count -->  84
Already Exists  14840964944
Completed Count -->  84
Already Exists  32914768
Completed Count -->  84
Started  1484096857
Started  1484096857
h148 Survivor 857 4096

Watch me go for the  7 th time...
Already Exists  14840961025
Completed Count -->  84
Already Exists  14832642
Completed Count -->  84
Already Exists  14840964127
Completed Count -->  84
Already Exists  32913443
Completed Count -->  84
Already Exists  14840961061
Completed Count -->  84
Already Exists  14812709
Completed Count -->  84
Already Exists  329022513
Completed Count -->  84
Already Exists  1484096567
Completed Count -->  84
Already Exists  3294096956
Completed Count -->  84
Already Exists  32940964414
Completed Count -->  84
Already Exists  329022530
Completed Count -->  84
Already Exists  329409616
Completed Count -->  84
Already Exists  329038417
Completed Count -->  84
Already Exists  329409620
Completed Count -->  84
Already Exists  329038430
Completed Count -->  84
Already Exists  329127010
Completed Count -->  84
Already Exists  329038438
Completed Count -->  84
Already Exists  32904809
Completed Count -->  84
Already Exists  329409643
Completed Count -->  84
Already Exists  148409620589
Completed Count -->  84
Already Exists  329022579
Completed Count -->  84
Already Exists  14840962
Completed Count -->  84
Already Exists  14840963
Completed Count -->  84
Already Exists  14840961156
Completed Count -->  84
Already Exists  14840964
Completed Count -->  84
Already Exists  14840965
Completed Count -->  84
Already Exists  14840966
Completed Count -->  84
Already Exists  14840967
Completed Count -->  84
Already Exists  14812804
Completed Count -->  84
Already Exists  1484096138
Completed Count -->  84
Already Exists  329409673
Completed Count -->  84
Already Exists  329409675
Completed Count -->  84
Already Exists  32906374
Completed Count -->  84
Already Exists  32940965015
Completed Count -->  84
Already Exists  14840961179
Completed Count -->  84
Already Exists  14840961693
Completed Count -->  84
Already Exists  329409696
Completed Count -->  84
Already Exists  3294096555
Completed Count -->  84
Already Exists  1484096179
Completed Count -->  84
Already Exists  1484096194
Completed Count -->  84
Already Exists  14829762
Completed Count -->  84
Already Exists  3294096585
Completed Count -->  84
Already Exists  329067210
Completed Count -->  84
Already Exists  1484096204
Completed Count -->  84
Already Exists  1484096210
Completed Count -->  84
Already Exists  32933603
Completed Count -->  84
Already Exists  3290192110
Completed Count -->  84
Already Exists  3290192111
Completed Count -->  84
Already Exists  148409613555
Completed Count -->  84
Already Exists  148409619718
Completed Count -->  84
Already Exists  148153610
Completed Count -->  84
Already Exists  148409610
Completed Count -->  84
Already Exists  148409611
Completed Count -->  84
Already Exists  148409612
Completed Count -->  84
Already Exists  148128013
Completed Count -->  84
Already Exists  1484096271
Completed Count -->  84
Already Exists  14840965903
Completed Count -->  84
Already Exists  148409617
Completed Count -->  84
Already Exists  148110610
Completed Count -->  84
Already Exists  148115218
Completed Count -->  84
Already Exists  148409621
Completed Count -->  84
Already Exists  1484096278
Completed Count -->  84
Already Exists  148409622
Completed Count -->  84
Already Exists  148409632
Completed Count -->  84
Already Exists  148409633
Completed Count -->  84
Already Exists  148409634
Completed Count -->  84
Already Exists  148409635
Completed Count -->  84
Already Exists  1484096803
Completed Count -->  84
Already Exists  32924962
Completed Count -->  84
Already Exists  148409639
Completed Count -->  84
Already Exists  148409641
Completed Count -->  84
Already Exists  148409651
Completed Count -->  84
Already Exists  148409653
Completed Count -->  84
Already Exists  148409655
Completed Count -->  84
Already Exists  14840964409
Completed Count -->  84
Already Exists  148409663
Completed Count -->  84
Already Exists  148409668
Completed Count -->  84
Already Exists  1484096266
Completed Count -->  84
Already Exists  1484096331
Completed Count -->  84
Already Exists  148409676
Completed Count -->  84
Already Exists  148409677
Completed Count -->  84
Already Exists  329096015
Completed Count -->  84
Already Exists  14840964944
Completed Count -->  84
Already Exists  32914768
Completed Count -->  84
Started  1484096857
Started  1484096857
h148 Survivor 857 4096
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481664583', '1481740675', '1481920723', '1482048709', '1482088716', '1482112721', '1482208764', '1482304820', '1482400761', '1482496764', '1482555761', '1482592774', '1482688844', '1482784888', '1482880871', '1482976861', '1483072837', '1483168827', '1483195823', '1483264814', '1483360815', '1483456812', '1483552798', '1483606789', '1483648782', '1483671780', '1483744767', '1483760767', '1483810759', '1483840752', '1483936756', '1484032786', '1484096857']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_583' | NDM=6345 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_675' | NDM=5405 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_723' | NDM=4699 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_709' | NDM=4562 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_716' | NDM=4514 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_721' | NDM=4483 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_764' | NDM=4088 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_820' | NDM=3746 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_761' | NDM=3976 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_764' | NDM=3853 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_761' | NDM=3758 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_774' | NDM=3680 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_844' | NDM=3377 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_888' | NDM=3166 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_871' | NDM=3126 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_861' | NDM=3107 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_837' | NDM=3078 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_827' | NDM=3043 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_823' | NDM=3039 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_814' | NDM=3022 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_815' | NDM=2998 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_812' | NDM=2982 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_798' | NDM=2971 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_789' | NDM=2962 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_782' | NDM=2955 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_780' | NDM=2948 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_767' | NDM=2945 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_767' | NDM=2943 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_759' | NDM=2941 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_752' | NDM=2939 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_756' | NDM=2907 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_786' | NDM=2781 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_857' | NDM=2486 Nstar=12 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481664583', '1481740675', '1481920723', '1482048709', '1482088716', '1482112721', '1482208764', '1482304820', '1482400761', '1482496764', '1482555761', '1482592774', '1482688844', '1482784888', '1482880871', '1482976861', '1483072837', '1483168827', '1483195823', '1483264814', '1483360815', '1483456812', '1483552798', '1483606789', '1483648782', '1483671780', '1483744767', '1483760767', '1483810759', '1483840752', '1483936756', '1484032786', '1484096857']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0          NaN           0          0           0
1           0          0          NaN           0          0           0
2           0          0          NaN           0          0           0
3           0          0          NaN           0          0           0
4           0          0          NaN           0          0           0
5           0          0          NaN           0          0           0
6           0          0          NaN           0          0           0
7           0          0          NaN           0          0           0
8           0          0          NaN           0          0           0
9           0          0          NaN           0          0           0
10          0          0          NaN           0          0           0
11          0          0          NaN           0          0           0
12          0          0          NaN           0          0           0
13          0          0          NaN           0          0           0
14          0          0          NaN           0          0           0
15          0          0          NaN           0          0           0
16          0          0          NaN           0          0           0
17  148102429  148102420          NaN   148102478  148102443  1481024434
18  148110628  148110618          NaN   148110676  148110642  1481106226
19  148115225  148115217          NaN   148115274  148115236  1481152220
20  148127024  148127016          NaN   148127070  148127036  1481270209
21  148128023  148128015          NaN   148128069  148128035  1481280206
22  148140822  148140811          NaN  1481408101  148140832  1481408167
23  148147623  148147610          NaN   148147690  148147632  1481476159
24  148153624  148153611          NaN   148153683  148153633  1481536151
25  148166421   14816649          NaN   148166489  148166432  1481664184
26  148174023   14817409          NaN   148174092  148174032  1481740258
27  148192029   14819209          NaN   148192093  148192032  1481920159
28  148204838   14820489          NaN   148204891  148204830  1482048169
29  148208838   14820889          NaN   148208892  148208830  1482088290
30  148211238   14821129          NaN   148211292  148211229  1482112155
31  148220839   14822089          NaN   148220894  148220829  1482208426
32  148230441   14823049          NaN   148230496  148230430  1482304416
33  148240044   14824009          NaN   148240096  148240028  1482400414
34  148249647   14824969          NaN   148249696  148249632  1482496615
35  148255545   14825559          NaN   148255597  148255535  1482555631
36  148259245   14825929          NaN   148259296  148259235  1482592640
37  148268847   14826889          NaN   148268897  148268838  1482688647

[0, 0, 0, '329013935', '329018827', '329019225', '32902251', '32902751', '32902881', '32903471', '32903841', '32904571', '32904801', '32905761', '32906371', '32906721', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[-1.0 -1.0 -1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_35' | NDM=8678 Nstar=39 Ngas=6470>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_27' | NDM=24329 Nstar=350 Ngas=14652>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_25' | NDM=25806 Nstar=351 Ngas=15709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_1' | NDM=555633 Nstar=56382 Ngas=429309>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_1' | NDM=1164620 Nstar=210832 Ngas=696579>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_1' | NDM=1288072 Nstar=282661 Ngas=714042>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_1' | NDM=1699021 Nstar=453046 Ngas=843163>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_1' | NDM=1884862 Nstar=573154 Ngas=945541>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_1' | NDM=2788363 Nstar=842283 Ngas=1392793>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_1' | NDM=3225374 Nstar=976143 Ngas=1595943>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_1' | NDM=5065263 Nstar=1530172 Ngas=2738713>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_1' | NDM=7451554 Nstar=2236951 Ngas=4644431>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_1' | NDM=8496675 Nstar=2702944 Ngas=5442931>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_1' | NDM=10617049 Nstar=3856093 Ngas=7275738>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_1' | NDM=10872015 Nstar=3980353 Ngas=7482669>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_1' | NDM=12715287 Nstar=5722615 Ngas=9000800>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_1' | NDM=15028263 Nstar=7698307 Ngas=11059109>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_1' | NDM=15196786 Nstar=7990531 Ngas=11217754>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1' | NDM=15578696 Nstar=10217161 Ngas=11755160>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1' | NDM=15747259 Nstar=11784296 Ngas=11968198>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1' | NDM=15761360 Nstar=13147640 Ngas=12285340>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1' | NDM=15832293 Nstar=16238307 Ngas=12845015>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1' | NDM=15990494 Nstar=17157603 Ngas=12930029>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1' | NDM=17922263 Nstar=20611248 Ngas=14418911>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1' | NDM=20220937 Nstar=24755716 Ngas=15683385>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1' | NDM=20568424 Nstar=26701663 Ngas=15670524>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1' | NDM=21292522 Nstar=29070320 Ngas=16200299>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1' | NDM=22138471 Nstar=34143108 Ngas=16098369>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1' | NDM=22233114 Nstar=37948971 Ngas=16217261>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1' | NDM=22265580 Nstar=38395660 Ngas=16249600>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1' | NDM=22541017 Nstar=41934879 Ngas=16143723>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1' | NDM=23087646 Nstar=46137673 Ngas=15803476>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1' | NDM=23617232 Nstar=50351876 Ngas=15643527>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1' | NDM=24221915 Nstar=53530614 Ngas=15566115>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1' | NDM=24513553 Nstar=54733955 Ngas=15453339>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1' | NDM=26676353 Nstar=59100003 Ngas=16082599>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1' | NDM=29354421 Nstar=64311453 Ngas=16874211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1' | NDM=31464533 Nstar=68631869 Ngas=16998639>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1' | NDM=32730524 Nstar=72629063 Ngas=17093857>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1' | NDM=33576743 Nstar=76168219 Ngas=16582991>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1' | NDM=34007948 Nstar=77829519 Ngas=16271248>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1' | NDM=34817467 Nstar=82227069 Ngas=16133249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1' | NDM=35279749 Nstar=86891324 Ngas=15727574>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1' | NDM=34968677 Nstar=91010100 Ngas=14700620>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1' | NDM=34685343 Nstar=94725659 Ngas=13794122>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1' | NDM=34411771 Nstar=98430465 Ngas=12965040>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
[0, 0, 0, '329013935', '329018827', '329019225', '32902251', '32902751', '32902881', '32903471', '32903841', '32904571', '32904801', '32905761', '32906371', '32906721', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71         NaN           0           0          0        NaN
1         96         NaN   329009662    32900969          0        NaN
2        108         NaN   329010856   329010810          0        NaN
3        139         NaN  3290139151   329013963  329013935        NaN
4        188         NaN  3290188114  3290188111  329018827        NaN
5        192         NaN  3290192110  3290192111  329019225        NaN
6        225         NaN    32902251    32902251   32902251        NaN
7        275         NaN    32902751    32902751   32902751        NaN
8        288         NaN    32902881    32902881   32902881        NaN
9        347         NaN    32903471    32903471   32903471        NaN
10       384         NaN    32903841    32903841   32903841        NaN
11       457         NaN    32904571    32904571   32904571        NaN
12       480         NaN    32904801    32904801   32904801        NaN
13       576         NaN    32905761    32905761   32905761        NaN
14       637         NaN    32906371    32906371   32906371        NaN
15       672         NaN    32906721    32906721   32906721        NaN
16       768         NaN    32907681    32907681   32907681        NaN
17       777         NaN    32907771    32907771   32907771        NaN
18       864         NaN    32908641    32908641   32908641        NaN
19       960         NaN    32909601    32909601   32909601        NaN
20       974         NaN    32909741    32909741   32909741        NaN
21      1056         NaN    32910561    32910561   32910561        NaN
22      1106         NaN    32911061    32911061   32911061        NaN
23      1152         NaN    32911521    32911521   32911521        NaN
24      1248         NaN    32912481    32912481   32912481        NaN
25      1270         NaN    32912701    32912701   32912701        NaN
26      1344         NaN    32913441    32913441   32913441        NaN
27      1440         NaN    32914401    32914401   32914401        NaN
28      1476         NaN    32914761    32914761   32914761        NaN
29      1536         NaN    32915361    32915361   32915361        NaN
..       ...         ...         ...         ...        ...        ...
32      1740         NaN    32917401    32917401   32917401        NaN
33      1824         NaN    32918241    32918241   32918241        NaN
34      1920         NaN    32919201    32919201   32919201        NaN
35      2016         NaN    32920161    32920161   32920161        NaN
36      2088         NaN    32920881    32920881   32920881        NaN
37      2112         NaN    32921121    32921121   32921121        NaN
38      2208         NaN    32922081    32922081   32922081        NaN
39      2304         NaN    32923041    32923041   32923041        NaN
40      2400         NaN    32924001    32924001   32924001        NaN
41      2496         NaN    32924961    32924961   32924961        NaN
42      2555         NaN    32925551    32925551   32925551        NaN
43      2592         NaN    32925921    32925921   32925921        NaN
44      2688         NaN    32926881    32926881   32926881        NaN
45      2784         NaN    32927841    32927841   32927841        NaN
46      2880         NaN    32928801    32928801   32928801        NaN
47      2976         NaN    32929761    32929761   32929761        NaN
48      3072         NaN    32930721    32930721   32930721        NaN
49      3168         NaN    32931681    32931681   32931681        NaN
50      3195         NaN    32931951    32931951   32931951        NaN
51      3264         NaN    32932641    32932641   32932641        NaN
52      3360         NaN    32933601    32933601   32933601        NaN
53      3456         NaN    32934561    32934561   32934561        NaN
54      3552         NaN    32935521    32935521   32935521        NaN
55      3606         NaN    32936061    32936061   32936061        NaN
56      3648         NaN    32936481    32936481   32936481        NaN
57      3744         NaN    32937441    32937441   32937441        NaN
58      3840         NaN    32938401    32938401   32938401        NaN
59      3936         NaN    32939361    32939361   32939361        NaN
60      4032         NaN    32940321    32940321   32940321        NaN
61      4096         NaN    32940961    32940961   32940961        NaN

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0         NaN
1    3290096221           0  32900961020   329009640           0         NaN
2    3290108234           0  32901081471   329010844           0         NaN
3    3290139545           0   3290139119  3290139138           0         NaN
4    3290188538           0    329018879  3290188197           0         NaN
5    3290192554           0    329019278  3290192195           0         NaN
6    3290225544           0    329022582  3290225210  3290225189         NaN
7    3290275579           0    329027574  3290275196  3290275121         NaN
8    3290288619           0    329028872  3290288186  3290288109         NaN
9    3290347581           0    329034758  3290347164   329034764         NaN
10   3290384579           0    329038460  3290384127   329038446         NaN
11   3290457588           0    329045751  3290457104   329045736         NaN
12   3290480583           0    329048049  3290480102   329048032         NaN
13   3290576536           0    329057638   329057696   329057626         NaN
14   3290637554           0    329063738  3290637104   329063727         NaN
15   3290672559           0    329067235  3290672100   329067221         NaN
16   3290768567           0    329076836   329076886   329076824         NaN
17   3290777570           0    329077736   329077786   329077723         NaN
18   3290864555           0    329086434   329086477   329086420         NaN
19   3290960543           0    329096033   329096073   329096021         NaN
20   3290974534           0    329097431   329097473   329097420         NaN
21   3291056562           0    329105639   329105668   329105622         NaN
22   3291106741           0    329110652   329110666   329110622         NaN
23   3291152887           0    329115265   329115271   329115223         NaN
24  32912481314           0    329124869   329124868   329124825         NaN
25   3291270963           0    329127068   329127066   329127026         NaN
26   3291344954           0    329134471   329134461   329134424         NaN
27   3291440948           0    329144073   329144058   329144021         NaN
28   3291476953           0    329147674   329147661   329147621         NaN
29   3291536954           0    329153675   329153662   329153634         NaN
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043         NaN
33  32918241363           0    329182478   329182462   329182445         NaN
34  32919201657           0    329192075   329192057   329192047         NaN
35  32920161763           0    329201673   329201653   329201648         NaN
36  32920881809           0   3292088210   329208852   329208849         NaN
37  32921121823           0   3292112188   329211251   329211250         NaN
38  32922081833           0   3292208214   329220850   329220848         NaN
39  32923041843           0   3292304234   329230450   329230449         NaN
40  32924001879           0   3292400261   329240048   329240050         NaN
41  32924962122           0   3292496271   329249648   329249650         NaN

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14840961883']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_1883' | NDM=0 Nstar=1058 Ngas=0>]
Watch me go for the  8 th time...
Already Exists  14840961025
Completed Count -->  86
Already Exists  14832642
Completed Count -->  86
Already Exists  14840964127
Completed Count -->  86
Already Exists  32913443
Completed Count -->  86
Already Exists  14840961061
Completed Count -->  86
Already Exists  14812709
Completed Count -->  86
Already Exists  329022513
Completed Count -->  86
Already Exists  1484096567
Completed Count -->  86
Already Exists  3294096956
Completed Count -->  86
Already Exists  32940964414
Completed Count -->  86
Already Exists  329022530
Completed Count -->  86
Already Exists  329409616
Completed Count -->  86
Already Exists  329038417
Completed Count -->  86
Already Exists  329409620
Completed Count -->  86
Already Exists  329038430
Completed Count -->  86
Already Exists  329127010
Completed Count -->  86
Already Exists  329038438
Completed Count -->  86
Already Exists  32904809
Completed Count -->  86
Already Exists  329409643
Completed Count -->  86
Already Exists  148409620589
Completed Count -->  86
Already Exists  329022579
Completed Count -->  86
Already Exists  14840962
Completed Count -->  86
Already Exists  14840963
Completed Count -->  86
Already Exists  14840961156
Completed Count -->  86
Already Exists  14840964
Completed Count -->  86
Already Exists  14840965
Completed Count -->  86
Already Exists  14840966
Completed Count -->  86
Already Exists  14840967
Completed Count -->  86
Already Exists  14812804
Completed Count -->  86
Already Exists  1484096138
Completed Count -->  86
Already Exists  329409673
Completed Count -->  86
Already Exists  329409675
Completed Count -->  86
Already Exists  32906374
Completed Count -->  86
Already Exists  32940965015
Completed Count -->  86
Already Exists  14840961179
Completed Count -->  86
Already Exists  14840961693
Completed Count -->  86
Already Exists  329409696
Completed Count -->  86
Already Exists  3294096555
Completed Count -->  86
Already Exists  1484096179
Completed Count -->  86
Already Exists  1484096194
Completed Count -->  86
Already Exists  14829762
Completed Count -->  86
Already Exists  3294096585
Completed Count -->  86
Already Exists  329067210
Completed Count -->  86
Already Exists  1484096204
Completed Count -->  86
Already Exists  1484096210
Completed Count -->  86
Already Exists  32933603
Completed Count -->  86
Already Exists  3290192110
Completed Count -->  86
Already Exists  3290192111
Completed Count -->  86
Already Exists  148409613555
Completed Count -->  86
Already Exists  148409619718
Completed Count -->  86
Already Exists  148153610
Completed Count -->  86
Already Exists  148409610
Completed Count -->  86
Already Exists  148409611
Completed Count -->  86
Already Exists  148409612
Completed Count -->  86
Already Exists  148128013
Completed Count -->  86
Already Exists  1484096271
Completed Count -->  86
Already Exists  14840965903
Completed Count -->  86
Already Exists  148409617
Completed Count -->  86
Already Exists  148110610
Completed Count -->  86
Already Exists  148115218
Completed Count -->  86
Already Exists  148409621
Completed Count -->  86
Already Exists  1484096278
Completed Count -->  86
Already Exists  148409622
Completed Count -->  86
Already Exists  148409632
Completed Count -->  86
Already Exists  148409633
Completed Count -->  86
Already Exists  148409634
Completed Count -->  86
Already Exists  148409635
Completed Count -->  86
Already Exists  1484096803
Completed Count -->  86
Already Exists  32924962
Completed Count -->  86
Already Exists  148409639
Completed Count -->  86
Already Exists  148409641
Completed Count -->  86
Already Exists  148409651
Completed Count -->  86
Already Exists  148409653
Completed Count -->  86
Already Exists  148409655
Completed Count -->  86
Already Exists  14840964409
Completed Count -->  86
Already Exists  148409663
Completed Count -->  86
Already Exists  148409668
Completed Count -->  86
Already Exists  1484096266
Completed Count -->  86
Already Exists  1484096331
Completed Count -->  86
Already Exists  148409676
Completed Count -->  86
Already Exists  148409677
Completed Count -->  86
Already Exists  329096015
Completed Count -->  86
Already Exists  14840964944
Completed Count -->  86
Already Exists  32914768
Completed Count -->  86
Already Exists  1484096857
Completed Count -->  86
Already Exists  329019225
Completed Count -->  86
Started  14840961883
Started  14840961883
h148 Survivor 1883 4096
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14840961883']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_1883' | NDM=0 Nstar=1058 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14840961883']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0          NaN           0          0           0
1           0          0          NaN           0          0           0
2           0          0          NaN           0          0           0
3           0          0          NaN           0          0           0
4           0          0          NaN           0          0           0
5           0          0          NaN           0          0           0
6           0          0          NaN           0          0           0
7           0          0          NaN           0          0           0
8           0          0          NaN           0          0           0
9           0          0          NaN           0          0           0
10          0          0          NaN           0          0           0
11          0          0          NaN           0          0           0
12          0          0          NaN           0          0           0
13          0          0          NaN           0          0           0
14          0          0          NaN           0          0           0
15          0          0          NaN           0          0           0
16          0          0          NaN           0          0           0
17  148102429  148102420          NaN   148102478  148102443  1481024434
18  148110628  148110618          NaN   148110676  148110642  1481106226
19  148115225  148115217          NaN   148115274  148115236  1481152220
20  148127024  148127016          NaN   148127070  148127036  1481270209
21  148128023  148128015          NaN   148128069  148128035  1481280206
22  148140822  148140811          NaN  1481408101  148140832  1481408167
23  148147623  148147610          NaN   148147690  148147632  1481476159
24  148153624  148153611          NaN   148153683  148153633  1481536151
25  148166421   14816649          NaN   148166489  148166432  1481664184
26  148174023   14817409          NaN   148174092  148174032  1481740258
27  148192029   14819209          NaN   148192093  148192032  1481920159
28  148204838   14820489          NaN   148204891  148204830  1482048169
29  148208838   14820889          NaN   148208892  148208830  1482088290
30  148211238   14821129          NaN   148211292  148211229  1482112155
31  148220839   14822089          NaN   148220894  148220829  1482208426
32  148230441   14823049          NaN   148230496  148230430  1482304416
33  148240044   14824009          NaN   148240096  148240028  1482400414
34  148249647   14824969          NaN   148249696  148249632  1482496615
35  148255545   14825559          NaN   148255597  148255535  1482555631
36  148259245   14825929          NaN   148259296  148259235  1482592640
37  148268847   14826889          NaN   148268897  148268838  1482688647
38  148278446   14827849          NaN   148278496  148278450  1482784651
39  148288045   14828809          NaN   148288095  148288056  1482880658
40  148297659   14829769          NaN   148297694  148297656  1482976676
41  148307261   14830728          NaN   148307291  148307260  1483072660
42  148316861   14831689          NaN   148316888  148316860  1483168670
43  148319561   14831959          NaN   148319588  148319562  1483195670
44  148326460   14832649          NaN   148326484  148326463  1483264670
45  148336059   14833608          NaN   148336080  148336063  1483360684
46  148345660   14834568          NaN   148345680  148345663  1483456722
47  148355259   14835527          NaN   148355277  148355262  1483552797
48  148360662   14836067          NaN   148360680  148360665  1483606800
49  148364861   14836487          NaN   148364880  148364865  1483648798
50  148367160   14836717          NaN   148367180  148367165  1483671802
51  148374460   14837447          NaN   148374477  148374464  1483744794
52  148376059   14837607          NaN   148376077  148376065  1483760800
53  148381059   14838107          NaN   148381077  148381066  1483810802
54  148384058   14838407          NaN   148384077  148384066  1483840796
55  148393659   14839367          NaN   148393676  148393670  1483936801
56  148403266   14840327          NaN   148403276  148403275  1484032798
57  148409668   14840967          NaN   148409676  148409677  1484096803

    14840968565  1484096857
0           NaN           0
1           NaN           0
2           NaN           0
3           NaN           0
4           NaN           0
5           NaN           0
6           NaN           0
7           NaN           0
8           NaN           0
9           NaN           0
10          NaN           0
11          NaN           0
12          NaN           0
13          NaN           0
14          NaN           0
15          NaN           0
16          NaN           0
17          NaN           0
18          NaN           0
19          NaN           0
20          NaN           0
21          NaN           0
22          NaN           0
23          NaN           0
24          NaN           0
25          NaN  1481664583
26          NaN  1481740675
27          NaN  1481920723
28          NaN  1482048709
29          NaN  1482088716
30          NaN  1482112721
31          NaN  1482208764
32          NaN  1482304820
33          NaN  1482400761
34          NaN  1482496764
35          NaN  1482555761
36          NaN  1482592774
37          NaN  1482688844
38          NaN  1482784888
39          NaN  1482880871
40          NaN  1482976861
41          NaN  1483072837
42          NaN  1483168827
43          NaN  1483195823
44          NaN  1483264814
45          NaN  1483360815
46          NaN  1483456812
47          NaN  1483552798
48          NaN  1483606789

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '32940321478', '32940961630']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1478' | NDM=0 Nstar=542 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1630' | NDM=0 Nstar=479 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '32940321478', '32940961630']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71         NaN           0           0          0        NaN
1         96         NaN   329009662    32900969          0        NaN
2        108         NaN   329010856   329010810          0        NaN
3        139         NaN  3290139151   329013963  329013935        NaN
4        188         NaN  3290188114  3290188111  329018827        NaN
5        192         NaN  3290192110  3290192111  329019225        NaN
6        225         NaN    32902251    32902251   32902251        NaN
7        275         NaN    32902751    32902751   32902751        NaN
8        288         NaN    32902881    32902881   32902881        NaN
9        347         NaN    32903471    32903471   32903471        NaN
10       384         NaN    32903841    32903841   32903841        NaN
11       457         NaN    32904571    32904571   32904571        NaN
12       480         NaN    32904801    32904801   32904801        NaN
13       576         NaN    32905761    32905761   32905761        NaN
14       637         NaN    32906371    32906371   32906371        NaN
15       672         NaN    32906721    32906721   32906721        NaN
16       768         NaN    32907681    32907681   32907681        NaN
17       777         NaN    32907771    32907771   32907771        NaN
18       864         NaN    32908641    32908641   32908641        NaN
19       960         NaN    32909601    32909601   32909601        NaN
20       974         NaN    32909741    32909741   32909741        NaN
21      1056         NaN    32910561    32910561   32910561        NaN
22      1106         NaN    32911061    32911061   32911061        NaN
23      1152         NaN    32911521    32911521   32911521        NaN
24      1248         NaN    32912481    32912481   32912481        NaN
25      1270         NaN    32912701    32912701   32912701        NaN
26      1344         NaN    32913441    32913441   32913441        NaN
27      1440         NaN    32914401    32914401   32914401        NaN
28      1476         NaN    32914761    32914761   32914761        NaN
29      1536         NaN    32915361    32915361   32915361        NaN
..       ...         ...         ...         ...        ...        ...
32      1740         NaN    32917401    32917401   32917401        NaN
33      1824         NaN    32918241    32918241   32918241        NaN
34      1920         NaN    32919201    32919201   32919201        NaN
35      2016         NaN    32920161    32920161   32920161        NaN
36      2088         NaN    32920881    32920881   32920881        NaN
37      2112         NaN    32921121    32921121   32921121        NaN
38      2208         NaN    32922081    32922081   32922081        NaN
39      2304         NaN    32923041    32923041   32923041        NaN
40      2400         NaN    32924001    32924001   32924001        NaN
41      2496         NaN    32924961    32924961   32924961        NaN
42      2555         NaN    32925551    32925551   32925551        NaN
43      2592         NaN    32925921    32925921   32925921        NaN
44      2688         NaN    32926881    32926881   32926881        NaN
45      2784         NaN    32927841    32927841   32927841        NaN
46      2880         NaN    32928801    32928801   32928801        NaN
47      2976         NaN    32929761    32929761   32929761        NaN
48      3072         NaN    32930721    32930721   32930721        NaN
49      3168         NaN    32931681    32931681   32931681        NaN
50      3195         NaN    32931951    32931951   32931951        NaN
51      3264         NaN    32932641    32932641   32932641        NaN
52      3360         NaN    32933601    32933601   32933601        NaN
53      3456         NaN    32934561    32934561   32934561        NaN
54      3552         NaN    32935521    32935521   32935521        NaN
55      3606         NaN    32936061    32936061   32936061        NaN
56      3648         NaN    32936481    32936481   32936481        NaN
57      3744         NaN    32937441    32937441   32937441        NaN
58      3840         NaN    32938401    32938401   32938401        NaN
59      3936         NaN    32939361    32939361   32939361        NaN
60      4032         NaN    32940321    32940321   32940321        NaN
61      4096         NaN    32940961    32940961   32940961        NaN

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0         NaN
1    3290096221           0  32900961020   329009640           0         NaN
2    3290108234           0  32901081471   329010844           0         NaN
3    3290139545           0   3290139119  3290139138           0         NaN
4    3290188538           0    329018879  3290188197           0         NaN
5    3290192554           0    329019278  3290192195           0         NaN
6    3290225544           0    329022582  3290225210  3290225189         NaN
7    3290275579           0    329027574  3290275196  3290275121         NaN
8    3290288619           0    329028872  3290288186  3290288109         NaN
9    3290347581           0    329034758  3290347164   329034764         NaN
10   3290384579           0    329038460  3290384127   329038446         NaN
11   3290457588           0    329045751  3290457104   329045736         NaN
12   3290480583           0    329048049  3290480102   329048032         NaN
13   3290576536           0    329057638   329057696   329057626         NaN
14   3290637554           0    329063738  3290637104   329063727         NaN
15   3290672559           0    329067235  3290672100   329067221         NaN
16   3290768567           0    329076836   329076886   329076824         NaN
17   3290777570           0    329077736   329077786   329077723         NaN
18   3290864555           0    329086434   329086477   329086420         NaN
19   3290960543           0    329096033   329096073   329096021         NaN
20   3290974534           0    329097431   329097473   329097420         NaN
21   3291056562           0    329105639   329105668   329105622         NaN
22   3291106741           0    329110652   329110666   329110622         NaN
23   3291152887           0    329115265   329115271   329115223         NaN
24  32912481314           0    329124869   329124868   329124825         NaN
25   3291270963           0    329127068   329127066   329127026         NaN
26   3291344954           0    329134471   329134461   329134424         NaN
27   3291440948           0    329144073   329144058   329144021         NaN
28   3291476953           0    329147674   329147661   329147621         NaN
29   3291536954           0    329153675   329153662   329153634         NaN
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043         NaN
33  32918241363           0    329182478   329182462   329182445         NaN
34  32919201657           0    329192075   329192057   329192047         NaN
35  32920161763           0    329201673   329201653   329201648         NaN
36  32920881809           0   3292088210   329208852   329208849         NaN
37  32921121823           0   3292112188   329211251   329211250         NaN
38  32922081833           0   3292208214   329220850   329220848         NaN
39  32923041843           0   3292304234   329230450   329230449         NaN
40  32924001879           0   3292400261   329240048   329240050         NaN
41  32924962122           0   3292496271   329249648   329249650         NaN
42  32925552182           0   3292555278   329255548   329255551         NaN
43  32925922176           0   3292592282   329259249   329259252         NaN
44  32926882164           0   3292688286   329268849   329268853         NaN
45  32927842152           0   3292784291   329278449   329278454         NaN
46  32928802121           0   3292880313   329288050   329288057         NaN
47  32929762119           0   3292976362   329297650   329297662         NaN
48  32930722348           0   3293072379   329307248   329307266         NaN
49  32931683019           0   3293168381   329316846   329316863         NaN
50  32931953176           0   3293195382   329319546   329319564         NaN
51  32932643395           0   3293264386   329326447   329326463         NaN
52  32933603421           0   3293360393   329336046   329336069         NaN
53  32934563452  3293456528   3293456390   329345644   329345669         NaN
54  32935523520  3293552526   3293552387   329355245   329355271         NaN
55  32936063546  3293606534   3293606388   329360645   329360673         NaN
56  32936483588  3293648534   3293648390   329364845   329364872         NaN
57  32937444656  3293744559   3293744407   329374445   329374474         NaN
58  32938405004  3293840554   3293840515   329384059   329384075         NaN
59  32939365000  3293936554   3293936552   329393673   329393675         NaN
60  32940325024  3294032554   3294032579   329403272   329403275         NaN
61  32940965015  3294096555   3294096585   329409673   329409675         NaN

    32940969  3294096956  329409696
0        NaN           0          0
1        NaN           0  329009612
2        NaN           0  329010814
3        NaN   329013940  329013960
4        NaN   329018862  329018880
5        NaN   329019261  329019281
6        NaN   329022554  329022577
7        NaN   329027554  329027566
8        NaN   329028857  329028868
9        NaN   329034755  329034763
10       NaN   329038455  329038462
11       NaN   329045759  329045758
12       NaN   329048064  329048058
13       NaN   329057673  329057653
14       NaN   329063775  329063751
15       NaN   329067270  329067248
16       NaN   329076858  329076844
17       NaN   329077759  329077744
18       NaN  3290864141  329086440
19       NaN   329096065  329096039
20       NaN   329097466  329097438
21       NaN   329105678  329105637
22       NaN   329110681  329110637
23       NaN   329115287  329115237
24       NaN   329124883  329124841
25       NaN   329127083  329127043
26       NaN   329134478  329134442
27       NaN   329144075  329144043
28       NaN   329147681  329147643
29       NaN  3291536100  329153645
..       ...         ...        ...
32       NaN  3291740129  329174054
33       NaN  3291824136  329182455
34       NaN  3291920141  329192056
35       NaN  3292016148  329201651
36       NaN  3292088147  329208854
37       NaN  3292112148  329211254
38       NaN  3292208151  329220857
39       NaN  3292304155  329230460
40       NaN  3292400169  329240062
41       NaN  3292496248  329249667
42       NaN  3292555258  329255568
43       NaN  3292592266  329259269
44       NaN  3292688291  329268874
45       NaN  3292784302  329278482
46       NaN  3292880323  329288085
47       NaN  3292976371  329297685
48       NaN  3293072442  329307288
49       NaN  3293168486  329316890
50       NaN  3293195497  329319589
51       NaN  3293264508  329326490
52       NaN  3293360534  329336091
53       NaN  3293456580  329345688
54       NaN  3293552666  329355290
55       NaN  3293606703  329360692
56       NaN  3293648728  329364890
57       NaN  3293744763  329374492
58       NaN  3293840774  329384094
59       NaN  3293936825  329393692
60       NaN  3294032906  329403293
61       NaN  3294096956  329409696

[62 rows x 48 columns]
Finished  32940961630
Finished  32940961630
Completed Count -->  88
Started  14840967007
Started  14840967007
h148 Survivor 7007 4096

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14822083497', '14823043442', '14824003365', '14824963293', '14825553257', '14825923218', '14826883158', '14827843254', '14828803215', '14829763183', '14830723119', '14831683080', '14831953057', '14832643021', '14833604234', '14834564423', '14835524415', '14836064442', '14836484417', '14836714436', '14837444450', '14837604580', '14838106247', '14838406616', '14839366912', '14840326946', '14840967007']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_3497' | NDM=1 Nstar=807 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_3442' | NDM=0 Nstar=807 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_3365' | NDM=0 Nstar=806 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_3293' | NDM=0 Nstar=804 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_3257' | NDM=0 Nstar=802 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_3218' | NDM=0 Nstar=803 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_3158' | NDM=0 Nstar=799 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_3254' | NDM=0 Nstar=748 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_3215' | NDM=0 Nstar=741 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_3183' | NDM=0 Nstar=735 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_3119' | NDM=0 Nstar=732 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_3080' | NDM=0 Nstar=730 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_3057' | NDM=0 Nstar=729 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_3021' | NDM=0 Nstar=730 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_4234' | NDM=0 Nstar=500 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_4423' | NDM=0 Nstar=470 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_4415' | NDM=0 Nstar=461 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_4442' | NDM=0 Nstar=455 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_4417' | NDM=0 Nstar=453 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_4436' | NDM=0 Nstar=449 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_4450' | NDM=0 Nstar=443 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_4580' | NDM=0 Nstar=429 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_6247' | NDM=0 Nstar=297 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_6616' | NDM=0 Nstar=277 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_6912' | NDM=0 Nstar=259 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_6946' | NDM=0 Nstar=253 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_7007' | NDM=0 Nstar=249 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14822083497', '14823043442', '14824003365', '14824963293', '14825553257', '14825923218', '14826883158', '14827843254', '14828803215', '14829763183', '14830723119', '14831683080', '14831953057', '14832643021', '14833604234', '14834564423', '14835524415', '14836064442', '14836484417', '14836714436', '14837444450', '14837604580', '14838106247', '14838406616', '14839366912', '14840326946', '14840967007']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0           NaN           0
1           NaN           0
2           NaN           0
3           NaN           0
4           NaN           0
5           NaN           0
6           NaN           0
7           NaN           0
8           NaN           0
9           NaN           0
10          NaN           0
11          NaN           0
12          NaN           0
13          NaN           0
14          NaN           0
15          NaN           0
16          NaN           0
17          NaN           0
18          NaN           0
19          NaN           0
20          NaN           0
21          NaN           0
22          NaN           0
23          NaN           0
24          NaN           0
25          NaN  1481664583
26          NaN  1481740675
27          NaN  1481920723
28          NaN  1482048709
29          NaN  1482088716
30          NaN  1482112721
31          NaN  1482208764
32          NaN  1482304820
33          NaN  1482400761
34          NaN  1482496764
35          NaN  1482555761
36          NaN  1482592774
37          NaN  1482688844
38          NaN  1482784888
39          NaN  1482880871
40          NaN  1482976861
41          NaN  1483072837
42          NaN  1483168827
43          NaN  1483195823
44          NaN  1483264814
45          NaN  1483360815
46          NaN  1483456812
47          NaN  1483552798
48          NaN  1483606789
49          NaN  1483648782
50          NaN  1483671780
51          NaN  1483744767
52          NaN  1483760767
53          NaN  1483810759
54          NaN  1483840752
55          NaN  1483936756
56          NaN  1484032786
57          NaN  1484096857

[58 rows x 78 columns]
Finished  14840967007
Finished  14840967007
Completed Count -->  89
Started  329019230
Started  329019230
h329 Zombie 30 0192

[0, 0, '329010836', '329013959', '329018833', '329019230', '32902251', '32902751', '32902881', '32903471', '32903841', '32904571', '32904801', '32905761', '32906371', '32906721', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[-1.0 -1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108/halo_36' | NDM=1567 Nstar=0 Ngas=1095>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_59' | NDM=5142 Nstar=0 Ngas=4078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_33' | NDM=17336 Nstar=93 Ngas=14425>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_30' | NDM=19765 Nstar=94 Ngas=16616>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_1' | NDM=555633 Nstar=56382 Ngas=429309>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_1' | NDM=1164620 Nstar=210832 Ngas=696579>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_1' | NDM=1288072 Nstar=282661 Ngas=714042>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_1' | NDM=1699021 Nstar=453046 Ngas=843163>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_1' | NDM=1884862 Nstar=573154 Ngas=945541>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_1' | NDM=2788363 Nstar=842283 Ngas=1392793>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_1' | NDM=3225374 Nstar=976143 Ngas=1595943>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_1' | NDM=5065263 Nstar=1530172 Ngas=2738713>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_1' | NDM=7451554 Nstar=2236951 Ngas=4644431>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_1' | NDM=8496675 Nstar=2702944 Ngas=5442931>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_1' | NDM=10617049 Nstar=3856093 Ngas=7275738>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_1' | NDM=10872015 Nstar=3980353 Ngas=7482669>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_1' | NDM=12715287 Nstar=5722615 Ngas=9000800>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_1' | NDM=15028263 Nstar=7698307 Ngas=11059109>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_1' | NDM=15196786 Nstar=7990531 Ngas=11217754>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1' | NDM=15578696 Nstar=10217161 Ngas=11755160>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1' | NDM=15747259 Nstar=11784296 Ngas=11968198>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1' | NDM=15761360 Nstar=13147640 Ngas=12285340>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1' | NDM=15832293 Nstar=16238307 Ngas=12845015>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1' | NDM=15990494 Nstar=17157603 Ngas=12930029>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1' | NDM=17922263 Nstar=20611248 Ngas=14418911>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1' | NDM=20220937 Nstar=24755716 Ngas=15683385>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1' | NDM=20568424 Nstar=26701663 Ngas=15670524>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1' | NDM=21292522 Nstar=29070320 Ngas=16200299>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1' | NDM=22138471 Nstar=34143108 Ngas=16098369>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1' | NDM=22233114 Nstar=37948971 Ngas=16217261>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1' | NDM=22265580 Nstar=38395660 Ngas=16249600>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1' | NDM=22541017 Nstar=41934879 Ngas=16143723>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1' | NDM=23087646 Nstar=46137673 Ngas=15803476>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1' | NDM=23617232 Nstar=50351876 Ngas=15643527>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1' | NDM=24221915 Nstar=53530614 Ngas=15566115>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1' | NDM=24513553 Nstar=54733955 Ngas=15453339>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1' | NDM=26676353 Nstar=59100003 Ngas=16082599>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1' | NDM=29354421 Nstar=64311453 Ngas=16874211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1' | NDM=31464533 Nstar=68631869 Ngas=16998639>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1' | NDM=32730524 Nstar=72629063 Ngas=17093857>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1' | NDM=33576743 Nstar=76168219 Ngas=16582991>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1' | NDM=34007948 Nstar=77829519 Ngas=16271248>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1' | NDM=34817467 Nstar=82227069 Ngas=16133249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1' | NDM=35279749 Nstar=86891324 Ngas=15727574>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1' | NDM=34968677 Nstar=91010100 Ngas=14700620>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1' | NDM=34685343 Nstar=94725659 Ngas=13794122>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1' | NDM=34411771 Nstar=98430465 Ngas=12965040>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
[0, 0, '329010836', '329013959', '329018833', '329019230', '32902251', '32902751', '32902881', '32903471', '32903841', '32904571', '32904801', '32905761', '32906371', '32906721', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71         NaN           0           0          0          0
1         96         NaN   329009662    32900969          0          0
2        108         NaN   329010856   329010810          0  329010836
3        139         NaN  3290139151   329013963  329013935  329013959
4        188         NaN  3290188114  3290188111  329018827  329018833
5        192         NaN  3290192110  3290192111  329019225  329019230
6        225         NaN    32902251    32902251   32902251   32902251
7        275         NaN    32902751    32902751   32902751   32902751
8        288         NaN    32902881    32902881   32902881   32902881
9        347         NaN    32903471    32903471   32903471   32903471
10       384         NaN    32903841    32903841   32903841   32903841
11       457         NaN    32904571    32904571   32904571   32904571
12       480         NaN    32904801    32904801   32904801   32904801
13       576         NaN    32905761    32905761   32905761   32905761
14       637         NaN    32906371    32906371   32906371   32906371
15       672         NaN    32906721    32906721   32906721   32906721
16       768         NaN    32907681    32907681   32907681   32907681
17       777         NaN    32907771    32907771   32907771   32907771
18       864         NaN    32908641    32908641   32908641   32908641
19       960         NaN    32909601    32909601   32909601   32909601
20       974         NaN    32909741    32909741   32909741   32909741
21      1056         NaN    32910561    32910561   32910561   32910561
22      1106         NaN    32911061    32911061   32911061   32911061
23      1152         NaN    32911521    32911521   32911521   32911521
24      1248         NaN    32912481    32912481   32912481   32912481
25      1270         NaN    32912701    32912701   32912701   32912701
26      1344         NaN    32913441    32913441   32913441   32913441
27      1440         NaN    32914401    32914401   32914401   32914401
28      1476         NaN    32914761    32914761   32914761   32914761
29      1536         NaN    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740         NaN    32917401    32917401   32917401   32917401
33      1824         NaN    32918241    32918241   32918241   32918241
34      1920         NaN    32919201    32919201   32919201   32919201
35      2016         NaN    32920161    32920161   32920161   32920161
36      2088         NaN    32920881    32920881   32920881   32920881
37      2112         NaN    32921121    32921121   32921121   32921121
38      2208         NaN    32922081    32922081   32922081   32922081
39      2304         NaN    32923041    32923041   32923041   32923041
40      2400         NaN    32924001    32924001   32924001   32924001
41      2496         NaN    32924961    32924961   32924961   32924961
42      2555         NaN    32925551    32925551   32925551   32925551
43      2592         NaN    32925921    32925921   32925921   32925921
44      2688         NaN    32926881    32926881   32926881   32926881
45      2784         NaN    32927841    32927841   32927841   32927841
46      2880         NaN    32928801    32928801   32928801   32928801
47      2976         NaN    32929761    32929761   32929761   32929761
48      3072         NaN    32930721    32930721   32930721   32930721
49      3168         NaN    32931681    32931681   32931681   32931681
50      3195         NaN    32931951    32931951   32931951   32931951
51      3264         NaN    32932641    32932641   32932641   32932641
52      3360         NaN    32933601    32933601   32933601   32933601
53      3456         NaN    32934561    32934561   32934561   32934561
54      3552         NaN    32935521    32935521   32935521   32935521
55      3606         NaN    32936061    32936061   32936061   32936061
56      3648         NaN    32936481    32936481   32936481   32936481
57      3744         NaN    32937441    32937441   32937441   32937441
58      3840         NaN    32938401    32938401   32938401   32938401
59      3936         NaN    32939361    32939361   32939361   32939361
60      4032         NaN    32940321    32940321   32940321   32940321
61      4096         NaN    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0         NaN
1    3290096221           0  32900961020   329009640           0         NaN
2    3290108234           0  32901081471   329010844           0         NaN
3    3290139545           0   3290139119  3290139138           0         NaN
4    3290188538           0    329018879  3290188197           0         NaN
5    3290192554           0    329019278  3290192195           0         NaN
6    3290225544           0    329022582  3290225210  3290225189         NaN
7    3290275579           0    329027574  3290275196  3290275121         NaN
8    3290288619           0    329028872  3290288186  3290288109         NaN
9    3290347581           0    329034758  3290347164   329034764         NaN
10   3290384579           0    329038460  3290384127   329038446         NaN
11   3290457588           0    329045751  3290457104   329045736         NaN
12   3290480583           0    329048049  3290480102   329048032         NaN
13   3290576536           0    329057638   329057696   329057626         NaN
14   3290637554           0    329063738  3290637104   329063727         NaN
15   3290672559           0    329067235  3290672100   329067221         NaN
16   3290768567           0    329076836   329076886   329076824         NaN
17   3290777570           0    329077736   329077786   329077723         NaN
18   3290864555           0    329086434   329086477   329086420         NaN
19   3290960543           0    329096033   329096073   329096021         NaN
20   3290974534           0    329097431   329097473   329097420         NaN
21   3291056562           0    329105639   329105668   329105622         NaN
22   3291106741           0    329110652   329110666   329110622         NaN
23   3291152887           0    329115265   329115271   329115223         NaN
24  32912481314           0    329124869   329124868   329124825         NaN
25   3291270963           0    329127068   329127066   329127026         NaN
26   3291344954           0    329134471   329134461   329134424         NaN
27   3291440948           0    329144073   329144058   329144021         NaN
28   3291476953           0    329147674   329147661   329147621         NaN
29   3291536954           0    329153675   329153662   329153634         NaN
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043         NaN
33  32918241363           0    329182478   329182462   329182445         NaN
34  32919201657           0    329192075   329192057   329192047         NaN
35  32920161763           0    329201673   329201653   329201648         NaN
36  32920881809           0   3292088210   329208852   329208849         NaN
37  32921121823           0   3292112188   329211251   329211250         NaN
38  32922081833           0   3292208214   329220850   329220848         NaN
39  32923041843           0   3292304234   329230450   329230449         NaN

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481024284', '1481106275', '1481152279', '1481270275', '1481280278', '1481408248', '1481476233', '1481536224', '1481664212', '1481740209', '1481920206', '1482048195', '1482088193', '1482112193', '1482208345', '1482304344', '1482400327', '1482496356', '1482555402', '1482592483', '1482688743', '1482784743', '1482880744', '1482976754', '1483072752', '1483168763', '1483195765', '1483264761', '1483360764', '1483456760', '1483552755', '1483606758', '1483648758', '1483671755', '1483744757', '1483760765', '1483810797', '1483840833', '14839361326', '14840321358', '14840961379']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_284' | NDM=17410 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_275' | NDM=17887 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_279' | NDM=17571 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_275' | NDM=16607 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_278' | NDM=16552 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_248' | NDM=16332 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_233' | NDM=16406 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_224' | NDM=16558 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_212' | NDM=16923 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_209' | NDM=17211 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_206' | NDM=17846 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_195' | NDM=18161 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_193' | NDM=18073 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_193' | NDM=17890 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_345' | NDM=9824 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_344' | NDM=9514 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_327' | NDM=9816 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_356' | NDM=8611 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_402' | NDM=7319 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_483' | NDM=6116 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_743' | NDM=3814 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_743' | NDM=3757 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_744' | NDM=3652 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_754' | NDM=3568 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_752' | NDM=3437 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_763' | NDM=3320 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_765' | NDM=3294 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_761' | NDM=3261 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_764' | NDM=3215 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_760' | NDM=3165 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_755' | NDM=3122 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_758' | NDM=3086 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_758' | NDM=3064 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_755' | NDM=3058 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_757' | NDM=2991 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_765' | NDM=2966 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_797' | NDM=2844 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_833' | NDM=2692 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_1326' | NDM=1568 Nstar=3 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_1358' | NDM=1513 Nstar=3 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_1379' | NDM=1469 Nstar=3 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481024284', '1481106275', '1481152279', '1481270275', '1481280278', '1481408248', '1481476233', '1481536224', '1481664212', '1481740209', '1481920206', '1482048195', '1482088193', '1482112193', '1482208345', '1482304344', '1482400327', '1482496356', '1482555402', '1482592483', '1482688743', '1482784743', '1482880744', '1482976754', '1483072752', '1483168763', '1483195765', '1483264761', '1483360764', '1483456760', '1483552755', '1483606758', '1483648758', '1483671755', '1483744757', '1483760765', '1483810797', '1483840833', '14839361326', '14840321358', '14840961379']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0           NaN           0
1           NaN           0
2           NaN           0
3           NaN           0
4           NaN           0
5           NaN           0
6           NaN           0
7           NaN           0
8           NaN           0
9           NaN           0
10          NaN           0
11          NaN           0
12          NaN           0
13          NaN           0
14          NaN           0
15          NaN           0
16          NaN           0
17          NaN           0
18          NaN           0
19          NaN           0
20          NaN           0
21          NaN           0
22          NaN           0
23          NaN           0
24          NaN           0
25          NaN  1481664583
26          NaN  1481740675
27          NaN  1481920723
28          NaN  1482048709
29          NaN  1482088716
30          NaN  1482112721
31          NaN  1482208764
32          NaN  1482304820
33          NaN  1482400761
34          NaN  1482496764
35          NaN  1482555761
36          NaN  1482592774
37          NaN  1482688844
38          NaN  1482784888
39          NaN  1482880871
40          NaN  1482976861
41          NaN  1483072837
42          NaN  1483168827
43          NaN  1483195823
44          NaN  1483264814
45          NaN  1483360815
46          NaN  1483456812
47          NaN  1483552798
48          NaN  1483606789
49          NaN  1483648782
50          NaN  1483671780
51          NaN  1483744767
52          NaN  1483760767
53          NaN  1483810759
54          NaN  1483840752
55          NaN  1483936756
56          NaN  1484032786
57          NaN  1484096857

[58 rows x 78 columns]
Finished  14840961379
Finished  14840961379
Completed Count -->  91
Started  32908648
Started  32908648
h329 Zombie 8 0864

[0, 0, 0, '329013931', '329018825', '329019224', '329022527', '329027511', '329028812', '329034714', '329038416', '329045718', '329048016', '329057614', '329063713', '329067211', '32907689', '32907779', '32908648', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[-1.0 -1.0 -1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_31' | NDM=8885 Nstar=19 Ngas=7526>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_25' | NDM=23021 Nstar=224 Ngas=17950>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_24' | NDM=23626 Nstar=246 Ngas=18525>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_27' | NDM=27487 Nstar=497 Ngas=22605>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_11' | NDM=84783 Nstar=2096 Ngas=69785>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_12' | NDM=101322 Nstar=3884 Ngas=76716>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_14' | NDM=152492 Nstar=11497 Ngas=77447>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_16' | NDM=158674 Nstar=13649 Ngas=78276>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_18' | NDM=146304 Nstar=15952 Ngas=78295>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_16' | NDM=155208 Nstar=16285 Ngas=88942>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_14' | NDM=174657 Nstar=21597 Ngas=98906>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_13' | NDM=177981 Nstar=23888 Ngas=98003>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_11' | NDM=191748 Nstar=25282 Ngas=108325>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_9' | NDM=177166 Nstar=31767 Ngas=86812>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_9' | NDM=182239 Nstar=31790 Ngas=88089>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_8' | NDM=219319 Nstar=34309 Ngas=93312>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_1' | NDM=15028263 Nstar=7698307 Ngas=11059109>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_1' | NDM=15196786 Nstar=7990531 Ngas=11217754>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1' | NDM=15578696 Nstar=10217161 Ngas=11755160>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1' | NDM=15747259 Nstar=11784296 Ngas=11968198>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1' | NDM=15761360 Nstar=13147640 Ngas=12285340>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1' | NDM=15832293 Nstar=16238307 Ngas=12845015>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1' | NDM=15990494 Nstar=17157603 Ngas=12930029>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1' | NDM=17922263 Nstar=20611248 Ngas=14418911>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1' | NDM=20220937 Nstar=24755716 Ngas=15683385>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1' | NDM=20568424 Nstar=26701663 Ngas=15670524>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1' | NDM=21292522 Nstar=29070320 Ngas=16200299>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1' | NDM=22138471 Nstar=34143108 Ngas=16098369>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1' | NDM=22233114 Nstar=37948971 Ngas=16217261>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1' | NDM=22265580 Nstar=38395660 Ngas=16249600>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1' | NDM=22541017 Nstar=41934879 Ngas=16143723>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1' | NDM=23087646 Nstar=46137673 Ngas=15803476>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1' | NDM=23617232 Nstar=50351876 Ngas=15643527>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1' | NDM=24221915 Nstar=53530614 Ngas=15566115>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1' | NDM=24513553 Nstar=54733955 Ngas=15453339>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1' | NDM=26676353 Nstar=59100003 Ngas=16082599>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1' | NDM=29354421 Nstar=64311453 Ngas=16874211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1' | NDM=31464533 Nstar=68631869 Ngas=16998639>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1' | NDM=32730524 Nstar=72629063 Ngas=17093857>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1' | NDM=33576743 Nstar=76168219 Ngas=16582991>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1' | NDM=34007948 Nstar=77829519 Ngas=16271248>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1' | NDM=34817467 Nstar=82227069 Ngas=16133249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1' | NDM=35279749 Nstar=86891324 Ngas=15727574>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1' | NDM=34968677 Nstar=91010100 Ngas=14700620>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1' | NDM=34685343 Nstar=94725659 Ngas=13794122>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1' | NDM=34411771 Nstar=98430465 Ngas=12965040>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
[0, 0, 0, '329013931', '329018825', '329019224', '329022527', '329027511', '329028812', '329034714', '329038416', '329045718', '329048016', '329057614', '329063713', '329067211', '32907689', '32907779', '32908648', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71         NaN           0           0          0          0
1         96         NaN   329009662    32900969          0          0
2        108         NaN   329010856   329010810          0  329010836
3        139         NaN  3290139151   329013963  329013935  329013959
4        188         NaN  3290188114  3290188111  329018827  329018833
5        192         NaN  3290192110  3290192111  329019225  329019230
6        225         NaN    32902251    32902251   32902251   32902251
7        275         NaN    32902751    32902751   32902751   32902751
8        288         NaN    32902881    32902881   32902881   32902881
9        347         NaN    32903471    32903471   32903471   32903471
10       384         NaN    32903841    32903841   32903841   32903841
11       457         NaN    32904571    32904571   32904571   32904571
12       480         NaN    32904801    32904801   32904801   32904801
13       576         NaN    32905761    32905761   32905761   32905761
14       637         NaN    32906371    32906371   32906371   32906371
15       672         NaN    32906721    32906721   32906721   32906721
16       768         NaN    32907681    32907681   32907681   32907681
17       777         NaN    32907771    32907771   32907771   32907771
18       864         NaN    32908641    32908641   32908641   32908641
19       960         NaN    32909601    32909601   32909601   32909601
20       974         NaN    32909741    32909741   32909741   32909741
21      1056         NaN    32910561    32910561   32910561   32910561
22      1106         NaN    32911061    32911061   32911061   32911061
23      1152         NaN    32911521    32911521   32911521   32911521
24      1248         NaN    32912481    32912481   32912481   32912481
25      1270         NaN    32912701    32912701   32912701   32912701
26      1344         NaN    32913441    32913441   32913441   32913441
27      1440         NaN    32914401    32914401   32914401   32914401
28      1476         NaN    32914761    32914761   32914761   32914761
29      1536         NaN    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740         NaN    32917401    32917401   32917401   32917401
33      1824         NaN    32918241    32918241   32918241   32918241
34      1920         NaN    32919201    32919201   32919201   32919201
35      2016         NaN    32920161    32920161   32920161   32920161
36      2088         NaN    32920881    32920881   32920881   32920881
37      2112         NaN    32921121    32921121   32921121   32921121
38      2208         NaN    32922081    32922081   32922081   32922081
39      2304         NaN    32923041    32923041   32923041   32923041
40      2400         NaN    32924001    32924001   32924001   32924001
41      2496         NaN    32924961    32924961   32924961   32924961
42      2555         NaN    32925551    32925551   32925551   32925551
43      2592         NaN    32925921    32925921   32925921   32925921
44      2688         NaN    32926881    32926881   32926881   32926881
45      2784         NaN    32927841    32927841   32927841   32927841
46      2880         NaN    32928801    32928801   32928801   32928801
47      2976         NaN    32929761    32929761   32929761   32929761
48      3072         NaN    32930721    32930721   32930721   32930721
49      3168         NaN    32931681    32931681   32931681   32931681
50      3195         NaN    32931951    32931951   32931951   32931951
51      3264         NaN    32932641    32932641   32932641   32932641
52      3360         NaN    32933601    32933601   32933601   32933601
53      3456         NaN    32934561    32934561   32934561   32934561
54      3552         NaN    32935521    32935521   32935521   32935521
55      3606         NaN    32936061    32936061   32936061   32936061
56      3648         NaN    32936481    32936481   32936481   32936481
57      3744         NaN    32937441    32937441   32937441   32937441
58      3840         NaN    32938401    32938401   32938401   32938401
59      3936         NaN    32939361    32939361   32939361   32939361
60      4032         NaN    32940321    32940321   32940321   32940321
61      4096         NaN    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0         NaN
1    3290096221           0  32900961020   329009640           0         NaN
2    3290108234           0  32901081471   329010844           0         NaN
3    3290139545           0   3290139119  3290139138           0         NaN
4    3290188538           0    329018879  3290188197           0         NaN
5    3290192554           0    329019278  3290192195           0         NaN
6    3290225544           0    329022582  3290225210  3290225189         NaN
7    3290275579           0    329027574  3290275196  3290275121         NaN
8    3290288619           0    329028872  3290288186  3290288109         NaN
9    3290347581           0    329034758  3290347164   329034764         NaN
10   3290384579           0    329038460  3290384127   329038446         NaN
11   3290457588           0    329045751  3290457104   329045736         NaN
12   3290480583           0    329048049  3290480102   329048032         NaN
13   3290576536           0    329057638   329057696   329057626         NaN
14   3290637554           0    329063738  3290637104   329063727         NaN
15   3290672559           0    329067235  3290672100   329067221         NaN
16   3290768567           0    329076836   329076886   329076824         NaN
17   3290777570           0    329077736   329077786   329077723         NaN
18   3290864555           0    329086434   329086477   329086420         NaN
19   3290960543           0    329096033   329096073   329096021         NaN
20   3290974534           0    329097431   329097473   329097420         NaN
21   3291056562           0    329105639   329105668   329105622         NaN
22   3291106741           0    329110652   329110666   329110622         NaN
23   3291152887           0    329115265   329115271   329115223         NaN
24  32912481314           0    329124869   329124868   329124825         NaN
25   3291270963           0    329127068   329127066   329127026         NaN
26   3291344954           0    329134471   329134461   329134424         NaN
27   3291440948           0    329144073   329144058   329144021         NaN
28   3291476953           0    329147674   329147661   329147621         NaN
29   3291536954           0    329153675   329153662   329153634         NaN
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043         NaN
33  32918241363           0    329182478   329182462   329182445         NaN
34  32919201657           0    329192075   329192057   329192047         NaN
35  32920161763           0    329201673   329201653   329201648         NaN
36  32920881809           0   3292088210   329208852   329208849         NaN
37  32921121823           0   3292112188   329211251   329211250         NaN
38  32922081833           0   3292208214   329220850   329220848         NaN
39  32923041843           0   3292304234   329230450   329230449         NaN
40  32924001879           0   3292400261   329240048   329240050         NaN
41  32924962122           0   3292496271   329249648   329249650         NaN

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481536677', '1481664684', '1481740763', '1481920773', '1482048789', '1482088787', '1482112784', '1482208774', '1482304768', '1482400752', '1482496743', '1482555731', '1482592722', '1482688716', '1482784695', '1482880683', '1482976679', '1483072673', '14831681901', '14831951724', '14832642155', '14833601824', '14834561878', '14835521919', '14836061957', '14836481964', '14836711960', '14837441996', '14837601951', '14838101933', '14838401929', '14839361918', '14840321902', '14840961900']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_677' | NDM=5474 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_684' | NDM=5292 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_763' | NDM=4646 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_773' | NDM=4365 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_789' | NDM=4124 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_787' | NDM=4090 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_784' | NDM=4067 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_774' | NDM=4036 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_768' | NDM=4025 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_752' | NDM=4038 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_743' | NDM=4000 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_731' | NDM=4001 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_722' | NDM=3998 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_716' | NDM=3989 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_695' | NDM=3994 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_683' | NDM=3988 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_679' | NDM=3962 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_673' | NDM=3846 Nstar=14 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_1901' | NDM=1239 Nstar=13 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_1724' | NDM=1370 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_2155' | NDM=1055 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_1824' | NDM=1244 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_1878' | NDM=1176 Nstar=12 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_1919' | NDM=1129 Nstar=10 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_1957' | NDM=1100 Nstar=10 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_1964' | NDM=1087 Nstar=10 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_1960' | NDM=1083 Nstar=10 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_1996' | NDM=1051 Nstar=10 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_1951' | NDM=1076 Nstar=10 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_1933' | NDM=1072 Nstar=10 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_1929' | NDM=1068 Nstar=10 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_1918' | NDM=1058 Nstar=10 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_1902' | NDM=1044 Nstar=10 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_1900' | NDM=1037 Nstar=10 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481536677', '1481664684', '1481740763', '1481920773', '1482048789', '1482088787', '1482112784', '1482208774', '1482304768', '1482400752', '1482496743', '1482555731', '1482592722', '1482688716', '1482784695', '1482880683', '1482976679', '1483072673', '14831681901', '14831951724', '14832642155', '14833601824', '14834561878', '14835521919', '14836061957', '14836481964', '14836711960', '14837441996', '14837601951', '14838101933', '14838401929', '14839361918', '14840321902', '14840961900']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0           NaN           0
1           NaN           0
2           NaN           0
3           NaN           0
4           NaN           0
5           NaN           0
6           NaN           0
7           NaN           0
8           NaN           0
9           NaN           0
10          NaN           0
11          NaN           0
12          NaN           0
13          NaN           0
14          NaN           0
15          NaN           0
16          NaN           0
17          NaN           0
18          NaN           0
19          NaN           0
20          NaN           0
21          NaN           0
22          NaN           0
23          NaN           0
24          NaN           0
25          NaN  1481664583
26          NaN  1481740675
27          NaN  1481920723
28          NaN  1482048709
29          NaN  1482088716
30          NaN  1482112721
31          NaN  1482208764
32          NaN  1482304820
33          NaN  1482400761
34          NaN  1482496764
35          NaN  1482555761
36          NaN  1482592774
37          NaN  1482688844
38          NaN  1482784888
39          NaN  1482880871
40          NaN  1482976861
41          NaN  1483072837
42          NaN  1483168827
43          NaN  1483195823
44          NaN  1483264814
45          NaN  1483360815
46          NaN  1483456812
47          NaN  1483552798
48          NaN  1483606789
49          NaN  1483648782
50          NaN  1483671780
51          NaN  1483744767
52          NaN  1483760767
53          NaN  1483810759
54          NaN  1483840752
55          NaN  1483936756
56          NaN  1484032786
57          NaN  1484096857

[58 rows x 78 columns]
Finished  14840961900
Finished  14840961900
Completed Count -->  93
Started  14840962413
Started  14840962413
h148 Survivor 2413 4096

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148127067', '148128067', '148140886', '1481476104', '148153697', '1481664104', '1481740114', '1481920339', '14820481782', '14820881798', '14821121845', '14822082023', '14823042638', '14824002623', '14824962571', '14825552546', '14825922586', '14826882675', '14827842660', '14828802623', '14829762581', '14830722578', '14831682634', '14831952624', '14832642608', '14833602565', '14834562539', '14835522509', '14836062525', '14836482515', '14836712503', '14837442470', '14837602460', '14838102445', '14838402436', '14839362402', '14840322376', '14840962413']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_67' | NDM=55243 Nstar=14798 Ngas=17670>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_67' | NDM=54604 Nstar=14798 Ngas=14490>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_86' | NDM=44641 Nstar=14797 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_104' | NDM=36871 Nstar=14789 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_97' | NDM=37355 Nstar=14788 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_104' | NDM=32965 Nstar=14783 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_114' | NDM=28139 Nstar=14768 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_339' | NDM=2560 Nstar=7849 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_1782' | NDM=21 Nstar=1732 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_1798' | NDM=21 Nstar=1702 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_1845' | NDM=12 Nstar=1645 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_2023' | NDM=7 Nstar=1477 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_2638' | NDM=0 Nstar=1082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_2623' | NDM=0 Nstar=1067 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_2571' | NDM=0 Nstar=1065 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_2546' | NDM=0 Nstar=1049 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_2586' | NDM=0 Nstar=1021 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_2675' | NDM=0 Nstar=960 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_2660' | NDM=0 Nstar=935 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_2623' | NDM=0 Nstar=926 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_2581' | NDM=0 Nstar=919 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_2578' | NDM=0 Nstar=904 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_2634' | NDM=0 Nstar=870 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_2624' | NDM=0 Nstar=867 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_2608' | NDM=0 Nstar=865 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_2565' | NDM=0 Nstar=865 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_2539' | NDM=0 Nstar=861 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_2509' | NDM=0 Nstar=853 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_2525' | NDM=0 Nstar=837 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_2515' | NDM=0 Nstar=834 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_2503' | NDM=0 Nstar=834 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_2470' | NDM=0 Nstar=836 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_2460' | NDM=0 Nstar=836 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_2445' | NDM=0 Nstar=836 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_2436' | NDM=0 Nstar=836 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_2402' | NDM=0 Nstar=833 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_2376' | NDM=0 Nstar=831 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_2413' | NDM=0 Nstar=813 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148127067', '148128067', '148140886', '1481476104', '148153697', '1481664104', '1481740114', '1481920339', '14820481782', '14820881798', '14821121845', '14822082023', '14823042638', '14824002623', '14824962571', '14825552546', '14825922586', '14826882675', '14827842660', '14828802623', '14829762581', '14830722578', '14831682634', '14831952624', '14832642608', '14833602565', '14834562539', '14835522509', '14836062525', '14836482515', '14836712503', '14837442470', '14837602460', '14838102445', '14838402436', '14839362402', '14840322376', '14840962413']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0           NaN           0
1           NaN           0
2           NaN           0
3           NaN           0
4           NaN           0
5           NaN           0
6           NaN           0
7           NaN           0
8           NaN           0
9           NaN           0
10          NaN           0
11          NaN           0
12          NaN           0
13          NaN           0
14          NaN           0
15          NaN           0
16          NaN           0
17          NaN           0
18          NaN           0
19          NaN           0
20          NaN           0
21          NaN           0
22          NaN           0
23          NaN           0
24          NaN           0
25          NaN  1481664583
26          NaN  1481740675
27          NaN  1481920723
28          NaN  1482048709
29          NaN  1482088716
30          NaN  1482112721
31          NaN  1482208764
32          NaN  1482304820
33          NaN  1482400761
34          NaN  1482496764
35          NaN  1482555761
36          NaN  1482592774
37          NaN  1482688844
38          NaN  1482784888
39          NaN  1482880871
40          NaN  1482976861
41          NaN  1483072837
42          NaN  1483168827
43          NaN  1483195823
44          NaN  1483264814
45          NaN  1483360815
46          NaN  1483456812
47          NaN  1483552798
48          NaN  1483606789
49          NaN  1483648782
50          NaN  1483671780
51          NaN  1483744767
52          NaN  1483760767
53          NaN  1483810759
54          NaN  1483840752
55          NaN  1483936756
56          NaN  1484032786
57          NaN  1484096857

[58 rows x 78 columns]
Finished  14840962413
Finished  14840962413
Completed Count -->  94
Started  14840962927
Started  14840962927
h148 Survivor 2927 4096

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14817403459', '14819203385', '14820483333', '14820883314', '14821123286', '14822083244', '14823043379', '14824003401', '14824963375', '14825553340', '14825923363', '14826883226', '14827843174', '14828803272', '14829763249', '14830723181', '14831683154', '14831953113', '14832643068', '14833603049', '14834563052', '14835523090', '14836063098', '14836483043', '14836713023', '14837443012', '14837603033', '14838102995', '14838402988', '14839362955', '14840322915', '14840962927']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_3459' | NDM=905 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_3385' | NDM=886 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_3333' | NDM=869 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_3314' | NDM=868 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_3286' | NDM=868 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_3244' | NDM=864 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_3379' | NDM=806 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_3401' | NDM=778 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_3375' | NDM=767 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_3340' | NDM=761 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_3363' | NDM=742 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_3226' | NDM=759 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_3174' | NDM=750 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_3272' | NDM=710 Nstar=19 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_3249' | NDM=702 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_3181' | NDM=700 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_3154' | NDM=695 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_3113' | NDM=698 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_3068' | NDM=701 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_3049' | NDM=693 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_3052' | NDM=678 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_3090' | NDM=657 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_3098' | NDM=652 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_3043' | NDM=654 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_3023' | NDM=655 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_3012' | NDM=651 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_3033' | NDM=646 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_2995' | NDM=648 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_2988' | NDM=647 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_2955' | NDM=644 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_2915' | NDM=642 Nstar=18 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_2927' | NDM=632 Nstar=18 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14817403459', '14819203385', '14820483333', '14820883314', '14821123286', '14822083244', '14823043379', '14824003401', '14824963375', '14825553340', '14825923363', '14826883226', '14827843174', '14828803272', '14829763249', '14830723181', '14831683154', '14831953113', '14832643068', '14833603049', '14834563052', '14835523090', '14836063098', '14836483043', '14836713023', '14837443012', '14837603033', '14838102995', '14838402988', '14839362955', '14840322915', '14840962927']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0           NaN           0
1           NaN           0
2           NaN           0
3           NaN           0
4           NaN           0
5           NaN           0
6           NaN           0
7           NaN           0
8           NaN           0
9           NaN           0
10          NaN           0
11          NaN           0
12          NaN           0
13          NaN           0
14          NaN           0
15          NaN           0
16          NaN           0
17          NaN           0
18          NaN           0
19          NaN           0
20          NaN           0
21          NaN           0
22          NaN           0
23          NaN           0
24          NaN           0
25          NaN  1481664583
26          NaN  1481740675
27          NaN  1481920723
28          NaN  1482048709
29          NaN  1482088716
30          NaN  1482112721
31          NaN  1482208764
32          NaN  1482304820
33          NaN  1482400761
34          NaN  1482496764
35          NaN  1482555761
36          NaN  1482592774
37          NaN  1482688844
38          NaN  1482784888
39          NaN  1482880871
40          NaN  1482976861
41          NaN  1483072837
42          NaN  1483168827
43          NaN  1483195823
44          NaN  1483264814
45          NaN  1483360815
46          NaN  1483456812
47          NaN  1483552798
48          NaN  1483606789
49          NaN  1483648782
50          NaN  1483671780
51          NaN  1483744767
52          NaN  1483760767
53          NaN  1483810759
54          NaN  1483840752
55          NaN  1483936756
56          NaN  1484032786
57          NaN  1484096857

[58 rows x 78 columns]
Finished  14840962927
Finished  14840962927
Completed Count -->  95
Started  32940961648
Started  32940961648
h329 Survivor 1648 4096

['3290071292', '3290096321', '3290108319', '3290139540', '3290188655', '3290192670', '3290225644', '3290275731', '3290288741', '3290347733', '3290384723', '3290457738', '3290480735', '3290576648', '3290637660', '3290672682', '3290768844', '3290777849', '3290864965', '32909601070', '32909741074', '32910561076', '32911061093', '32911521101', '32912481274', '32912701209', '32913441270', '32914401290', '32914761312', '32915361320', '32916321402', '32917281495', '32917401509', '32918241519', '32919201537', '32920161520', '32920881543', '32921121565', '32922081665', '32923041696', '32924001677', '32924961697', '32925551746', '32925921755', '32926881748', '32927841732', '32928801702', '32929761688', '32930721713', '32931681699', '32931951705', '32932641700', '32933601694', '32934561680', '32935521695', '32936061689', '32936481703', '32937441684', '32938401669', '32939361657', '32940321643', '32940961648']
[ <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000071/halo_292' | NDM=401 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096/halo_321' | NDM=421 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108/halo_319' | NDM=480 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_540' | NDM=701 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_655' | NDM=892 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_670' | NDM=888 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_644' | NDM=1079 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_731' | NDM=1215 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_741' | NDM=1243 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_733' | NDM=1401 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_723' | NDM=1495 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_738' | NDM=1598 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_735' | NDM=1635 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_648' | NDM=1826 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_660' | NDM=1876 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_682' | NDM=1812 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_844' | NDM=1549 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_849' | NDM=1526 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_965' | NDM=1342 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_1070' | NDM=1226 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_1074' | NDM=1224 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1076' | NDM=1191 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1093' | NDM=1169 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1101' | NDM=1151 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1274' | NDM=992 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1209' | NDM=1037 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1270' | NDM=986 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1290' | NDM=940 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1312' | NDM=913 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1320' | NDM=884 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1402' | NDM=823 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1495' | NDM=755 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1509' | NDM=746 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1519' | NDM=726 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1537' | NDM=705 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1520' | NDM=699 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1543' | NDM=678 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1565' | NDM=663 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1665' | NDM=611 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1696' | NDM=593 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1677' | NDM=587 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1697' | NDM=571 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1746' | NDM=547 Nstar=16 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1755' | NDM=541 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1748' | NDM=532 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1732' | NDM=531 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1702' | NDM=529 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1688' | NDM=523 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1713' | NDM=508 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1699' | NDM=503 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1705' | NDM=502 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1700' | NDM=497 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1694' | NDM=493 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1680' | NDM=492 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1695' | NDM=483 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1689' | NDM=480 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1703' | NDM=474 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1684' | NDM=472 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1669' | NDM=470 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1657' | NDM=469 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1643' | NDM=467 Nstar=14 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1648' | NDM=459 Nstar=13 Ngas=0>]
[0, '3290096321', '3290108319', '3290139540', '3290188655', '3290192670', '3290225644', '3290275731', '3290288741', '3290347733', '3290384723', '3290457738', '3290480735', '3290576648', '3290637660', '3290672682', '3290768844', '3290777849', '3290864965', '32909601070', '32909741074', '32910561076', '32911061093', '32911521101', '32912481274', '32912701209', '32913441270', '32914401290', '32914761312', '32915361320', '32916321402', '32917281495', '32917401509', '32918241519', '32919201537', '32920161520', '32920881543', '32921121565', '32922081665', '32923041696', '32924001677', '32924961697', '32925551746', '32925921755', '32926881748', '32927841732', '32928801702', '32929761688', '32930721713', '32931681699', '32931951705', '32932641700', '32933601694', '32934561680', '32935521695', '32936061689', '32936481703', '32937441684', '32938401669', '32939361657', '32940321643', '32940961648']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71         NaN           0           0          0          0
1         96         NaN   329009662    32900969          0          0
2        108         NaN   329010856   329010810          0  329010836
3        139         NaN  3290139151   329013963  329013935  329013959
4        188         NaN  3290188114  3290188111  329018827  329018833
5        192         NaN  3290192110  3290192111  329019225  329019230
6        225         NaN    32902251    32902251   32902251   32902251
7        275         NaN    32902751    32902751   32902751   32902751
8        288         NaN    32902881    32902881   32902881   32902881
9        347         NaN    32903471    32903471   32903471   32903471
10       384         NaN    32903841    32903841   32903841   32903841
11       457         NaN    32904571    32904571   32904571   32904571
12       480         NaN    32904801    32904801   32904801   32904801
13       576         NaN    32905761    32905761   32905761   32905761
14       637         NaN    32906371    32906371   32906371   32906371
15       672         NaN    32906721    32906721   32906721   32906721
16       768         NaN    32907681    32907681   32907681   32907681
17       777         NaN    32907771    32907771   32907771   32907771
18       864         NaN    32908641    32908641   32908641   32908641
19       960         NaN    32909601    32909601   32909601   32909601
20       974         NaN    32909741    32909741   32909741   32909741
21      1056         NaN    32910561    32910561   32910561   32910561
22      1106         NaN    32911061    32911061   32911061   32911061
23      1152         NaN    32911521    32911521   32911521   32911521
24      1248         NaN    32912481    32912481   32912481   32912481
25      1270         NaN    32912701    32912701   32912701   32912701
26      1344         NaN    32913441    32913441   32913441   32913441
27      1440         NaN    32914401    32914401   32914401   32914401
28      1476         NaN    32914761    32914761   32914761   32914761
29      1536         NaN    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740         NaN    32917401    32917401   32917401   32917401
33      1824         NaN    32918241    32918241   32918241   32918241
34      1920         NaN    32919201    32919201   32919201   32919201
35      2016         NaN    32920161    32920161   32920161   32920161
36      2088         NaN    32920881    32920881   32920881   32920881
37      2112         NaN    32921121    32921121   32921121   32921121
38      2208         NaN    32922081    32922081   32922081   32922081
39      2304         NaN    32923041    32923041   32923041   32923041
40      2400         NaN    32924001    32924001   32924001   32924001
41      2496         NaN    32924961    32924961   32924961   32924961
42      2555         NaN    32925551    32925551   32925551   32925551
43      2592         NaN    32925921    32925921   32925921   32925921
44      2688         NaN    32926881    32926881   32926881   32926881
45      2784         NaN    32927841    32927841   32927841   32927841
46      2880         NaN    32928801    32928801   32928801   32928801
47      2976         NaN    32929761    32929761   32929761   32929761
48      3072         NaN    32930721    32930721   32930721   32930721
49      3168         NaN    32931681    32931681   32931681   32931681
50      3195         NaN    32931951    32931951   32931951   32931951
51      3264         NaN    32932641    32932641   32932641   32932641
52      3360         NaN    32933601    32933601   32933601   32933601
53      3456         NaN    32934561    32934561   32934561   32934561
54      3552         NaN    32935521    32935521   32935521   32935521
55      3606         NaN    32936061    32936061   32936061   32936061
56      3648         NaN    32936481    32936481   32936481   32936481
57      3744         NaN    32937441    32937441   32937441   32937441
58      3840         NaN    32938401    32938401   32938401   32938401
59      3936         NaN    32939361    32939361   32939361   32939361
60      4032         NaN    32940321    32940321   32940321   32940321
61      4096         NaN    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0         NaN
1    3290096221           0  32900961020   329009640           0         NaN
2    3290108234           0  32901081471   329010844           0         NaN
3    3290139545           0   3290139119  3290139138           0         NaN
4    3290188538           0    329018879  3290188197           0         NaN
5    3290192554           0    329019278  3290192195           0         NaN
6    3290225544           0    329022582  3290225210  3290225189         NaN
7    3290275579           0    329027574  3290275196  3290275121         NaN
8    3290288619           0    329028872  3290288186  3290288109         NaN
9    3290347581           0    329034758  3290347164   329034764         NaN
10   3290384579           0    329038460  3290384127   329038446         NaN
11   3290457588           0    329045751  3290457104   329045736         NaN
12   3290480583           0    329048049  3290480102   329048032         NaN
13   3290576536           0    329057638   329057696   329057626         NaN
14   3290637554           0    329063738  3290637104   329063727         NaN
15   3290672559           0    329067235  3290672100   329067221         NaN
16   3290768567           0    329076836   329076886   329076824         NaN
17   3290777570           0    329077736   329077786   329077723         NaN
18   3290864555           0    329086434   329086477   329086420         NaN
19   3290960543           0    329096033   329096073   329096021         NaN
20   3290974534           0    329097431   329097473   329097420         NaN
21   3291056562           0    329105639   329105668   329105622         NaN
22   3291106741           0    329110652   329110666   329110622         NaN
23   3291152887           0    329115265   329115271   329115223         NaN
24  32912481314           0    329124869   329124868   329124825         NaN
25   3291270963           0    329127068   329127066   329127026         NaN
26   3291344954           0    329134471   329134461   329134424         NaN
27   3291440948           0    329144073   329144058   329144021         NaN
28   3291476953           0    329147674   329147661   329147621         NaN
29   3291536954           0    329153675   329153662   329153634         NaN
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043         NaN
33  32918241363           0    329182478   329182462   329182445         NaN
34  32919201657           0    329192075   329192057   329192047         NaN
35  32920161763           0    329201673   329201653   329201648         NaN
36  32920881809           0   3292088210   329208852   329208849         NaN
37  32921121823           0   3292112188   329211251   329211250         NaN
38  32922081833           0   3292208214   329220850   329220848         NaN
39  32923041843           0   3292304234   329230450   329230449         NaN
40  32924001879           0   3292400261   329240048   329240050         NaN
41  32924962122           0   3292496271   329249648   329249650         NaN
42  32925552182           0   3292555278   329255548   329255551         NaN
43  32925922176           0   3292592282   329259249   329259252         NaN

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14820883070', '14821123108', '14822083288', '14823043356', '14824003391', '14824964889', '14825555134', '14825925307', '14826885446', '14827845472', '14828805569', '14829766423', '14830726494', '14831686490', '14831956438', '14832646491', '14833606420', '14834566949', '14835527642', '14836067699', '14836487660', '14836717573', '14837447690', '14837607621', '14838107661', '14838407640', '14839367781', '14840328859', '14840968565']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_3070' | NDM=962 Nstar=5 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_3108' | NDM=938 Nstar=5 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_3288' | NDM=867 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_3356' | NDM=827 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_3391' | NDM=795 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_4889' | NDM=520 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_5134' | NDM=484 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_5307' | NDM=462 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_5446' | NDM=439 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_5472' | NDM=425 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_5569' | NDM=408 Nstar=4 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_6423' | NDM=341 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_6494' | NDM=330 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_6490' | NDM=323 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_6438' | NDM=322 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_6491' | NDM=315 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_6420' | NDM=313 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_6949' | NDM=280 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_7642' | NDM=246 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_7699' | NDM=241 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_7660' | NDM=241 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_7573' | NDM=242 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_7690' | NDM=235 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_7621' | NDM=236 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_7661' | NDM=233 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_7640' | NDM=233 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_7781' | NDM=225 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_8859' | NDM=192 Nstar=1 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_8565' | NDM=197 Nstar=1 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14820883070', '14821123108', '14822083288', '14823043356', '14824003391', '14824964889', '14825555134', '14825925307', '14826885446', '14827845472', '14828805569', '14829766423', '14830726494', '14831686490', '14831956438', '14832646491', '14833606420', '14834566949', '14835527642', '14836067699', '14836487660', '14836717573', '14837447690', '14837607621', '14838107661', '14838407640', '14839367781', '14840328859', '14840968565']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0
5             0           0
6             0           0
7             0           0
8             0           0
9             0           0
10            0           0
11            0           0
12            0           0
13            0           0
14            0           0
15            0           0
16            0           0
17            0           0
18            0           0
19            0           0
20            0           0
21            0           0
22            0           0
23            0           0
24            0           0
25            0  1481664583
26            0  1481740675
27            0  1481920723
28            0  1482048709
29  14820883070  1482088716
30  14821123108  1482112721
31  14822083288  1482208764
32  14823043356  1482304820
33  14824003391  1482400761
34  14824964889  1482496764
35  14825555134  1482555761
36  14825925307  1482592774
37  14826885446  1482688844
38  14827845472  1482784888
39  14828805569  1482880871
40  14829766423  1482976861
41  14830726494  1483072837
42  14831686490  1483168827
43  14831956438  1483195823
44  14832646491  1483264814
45  14833606420  1483360815
46  14834566949  1483456812
47  14835527642  1483552798
48  14836067699  1483606789
49  14836487660  1483648782
50  14836717573  1483671780
51  14837447690  1483744767
52  14837607621  1483760767
53  14838107661  1483810759
54  14838407640  1483840752
55  14839367781  1483936756
56  14840328859  1484032786
57  14840968565  1484096857

[58 rows x 78 columns]
Finished  14840968565
Finished  14840968565
Completed Count -->  97
Started  1484096374
Started  1484096374
h148 Survivor 374 4096

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481024292', '1481106283', '1481152277', '1481270260', '1481280283', '1481408222', '1481476222', '1481536229', '1481664249', '1481740254', '1481920261', '1482048256', '1482088259', '1482112258', '1482208245', '1482304241', '1482400236', '1482496235', '1482555229', '1482592230', '1482688226', '1482784227', '1482880296', '1482976362', '1483072365', '1483168428', '1483195498', '1483264390', '1483360393', '1483456390', '1483552392', '1483606387', '1483648385', '1483671381', '1483744386', '1483760384', '1483810377', '1483840378', '1483936370', '1484032370', '1484096374']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_292' | NDM=16894 Nstar=11 Ngas=20>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_283' | NDM=17402 Nstar=11 Ngas=19>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_277' | NDM=17693 Nstar=11 Ngas=19>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_260' | NDM=18166 Nstar=11 Ngas=19>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_283' | NDM=16298 Nstar=11 Ngas=19>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_222' | NDM=18479 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_222' | NDM=17747 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_229' | NDM=16278 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_249' | NDM=14562 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_254' | NDM=14053 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_261' | NDM=13220 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_256' | NDM=13047 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_259' | NDM=12997 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_258' | NDM=12992 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_245' | NDM=12971 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_241' | NDM=12959 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_236' | NDM=12963 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_235' | NDM=12959 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_229' | NDM=12943 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_230' | NDM=12939 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_226' | NDM=12835 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_227' | NDM=12516 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_296' | NDM=9558 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_362' | NDM=7612 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_365' | NDM=7281 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_428' | NDM=6146 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_498' | NDM=5057 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_390' | NDM=6784 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_393' | NDM=6592 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_390' | NDM=6486 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_392' | NDM=6393 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_387' | NDM=6372 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_385' | NDM=6351 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_381' | NDM=6342 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_386' | NDM=6307 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_384' | NDM=6300 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_377' | NDM=6299 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_378' | NDM=6293 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_370' | NDM=6259 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_370' | NDM=6168 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_374' | NDM=6003 Nstar=11 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481024292', '1481106283', '1481152277', '1481270260', '1481280283', '1481408222', '1481476222', '1481536229', '1481664249', '1481740254', '1481920261', '1482048256', '1482088259', '1482112258', '1482208245', '1482304241', '1482400236', '1482496235', '1482555229', '1482592230', '1482688226', '1482784227', '1482880296', '1482976362', '1483072365', '1483168428', '1483195498', '1483264390', '1483360393', '1483456390', '1483552392', '1483606387', '1483648385', '1483671381', '1483744386', '1483760384', '1483810377', '1483840378', '1483936370', '1484032370', '1484096374']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0
5             0           0
6             0           0
7             0           0
8             0           0
9             0           0
10            0           0
11            0           0
12            0           0
13            0           0
14            0           0
15            0           0
16            0           0
17            0           0
18            0           0
19            0           0
20            0           0
21            0           0
22            0           0
23            0           0
24            0           0
25            0  1481664583
26            0  1481740675
27            0  1481920723
28            0  1482048709
29  14820883070  1482088716
30  14821123108  1482112721
31  14822083288  1482208764
32  14823043356  1482304820
33  14824003391  1482400761
34  14824964889  1482496764
35  14825555134  1482555761
36  14825925307  1482592774
37  14826885446  1482688844
38  14827845472  1482784888
39  14828805569  1482880871
40  14829766423  1482976861
41  14830726494  1483072837
42  14831686490  1483168827
43  14831956438  1483195823
44  14832646491  1483264814
45  14833606420  1483360815
46  14834566949  1483456812
47  14835527642  1483552798
48  14836067699  1483606789
49  14836487660  1483648782
50  14836717573  1483671780
51  14837447690  1483744767
52  14837607621  1483760767
53  14838107661  1483810759
54  14838407640  1483840752
55  14839367781  1483936756
56  14840328859  1484032786
57  14840968565  1484096857

[58 rows x 78 columns]
Finished  1484096374
Finished  1484096374
Completed Count -->  98
Started  3290188153
Started  3290188153
h329 Zombie 153 0188

['329007145', '329009638', '329010830', '329013986', '3290188153', '32901921', '32902251', '32902751', '32902881', '32903471', '32903841', '32904571', '32904801', '32905761', '32906371', '32906721', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[ <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000071/halo_45' | NDM=594 Nstar=0 Ngas=429>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096/halo_38' | NDM=1308 Nstar=0 Ngas=833>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108/halo_30' | NDM=1813 Nstar=0 Ngas=1188>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_86' | NDM=3734 Nstar=8 Ngas=2249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_153' | NDM=3795 Nstar=17 Ngas=733>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_1' | NDM=209793 Nstar=12581 Ngas=180544>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_1' | NDM=555633 Nstar=56382 Ngas=429309>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_1' | NDM=1164620 Nstar=210832 Ngas=696579>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_1' | NDM=1288072 Nstar=282661 Ngas=714042>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_1' | NDM=1699021 Nstar=453046 Ngas=843163>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_1' | NDM=1884862 Nstar=573154 Ngas=945541>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_1' | NDM=2788363 Nstar=842283 Ngas=1392793>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_1' | NDM=3225374 Nstar=976143 Ngas=1595943>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_1' | NDM=5065263 Nstar=1530172 Ngas=2738713>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_1' | NDM=7451554 Nstar=2236951 Ngas=4644431>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_1' | NDM=8496675 Nstar=2702944 Ngas=5442931>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_1' | NDM=10617049 Nstar=3856093 Ngas=7275738>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_1' | NDM=10872015 Nstar=3980353 Ngas=7482669>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_1' | NDM=12715287 Nstar=5722615 Ngas=9000800>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_1' | NDM=15028263 Nstar=7698307 Ngas=11059109>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_1' | NDM=15196786 Nstar=7990531 Ngas=11217754>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1' | NDM=15578696 Nstar=10217161 Ngas=11755160>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1' | NDM=15747259 Nstar=11784296 Ngas=11968198>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1' | NDM=15761360 Nstar=13147640 Ngas=12285340>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1' | NDM=15832293 Nstar=16238307 Ngas=12845015>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1' | NDM=15990494 Nstar=17157603 Ngas=12930029>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1' | NDM=17922263 Nstar=20611248 Ngas=14418911>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1' | NDM=20220937 Nstar=24755716 Ngas=15683385>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1' | NDM=20568424 Nstar=26701663 Ngas=15670524>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1' | NDM=21292522 Nstar=29070320 Ngas=16200299>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1' | NDM=22138471 Nstar=34143108 Ngas=16098369>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1' | NDM=22233114 Nstar=37948971 Ngas=16217261>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1' | NDM=22265580 Nstar=38395660 Ngas=16249600>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1' | NDM=22541017 Nstar=41934879 Ngas=16143723>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1' | NDM=23087646 Nstar=46137673 Ngas=15803476>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1' | NDM=23617232 Nstar=50351876 Ngas=15643527>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1' | NDM=24221915 Nstar=53530614 Ngas=15566115>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1' | NDM=24513553 Nstar=54733955 Ngas=15453339>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1' | NDM=26676353 Nstar=59100003 Ngas=16082599>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1' | NDM=29354421 Nstar=64311453 Ngas=16874211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1' | NDM=31464533 Nstar=68631869 Ngas=16998639>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1' | NDM=32730524 Nstar=72629063 Ngas=17093857>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1' | NDM=33576743 Nstar=76168219 Ngas=16582991>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1' | NDM=34007948 Nstar=77829519 Ngas=16271248>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1' | NDM=34817467 Nstar=82227069 Ngas=16133249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1' | NDM=35279749 Nstar=86891324 Ngas=15727574>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1' | NDM=34968677 Nstar=91010100 Ngas=14700620>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1' | NDM=34685343 Nstar=94725659 Ngas=13794122>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1' | NDM=34411771 Nstar=98430465 Ngas=12965040>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
[0, '329009638', '329010830', '329013986', '3290188153', '32901921', '32902251', '32902751', '32902881', '32903471', '32903841', '32904571', '32904801', '32905761', '32906371', '32906721', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71           0           0           0          0          0
1         96   329009638   329009662    32900969          0          0
2        108   329010830   329010856   329010810          0  329010836
3        139   329013986  3290139151   329013963  329013935  329013959
4        188  3290188153  3290188114  3290188111  329018827  329018833
5        192    32901921  3290192110  3290192111  329019225  329019230
6        225    32902251    32902251    32902251   32902251   32902251
7        275    32902751    32902751    32902751   32902751   32902751
8        288    32902881    32902881    32902881   32902881   32902881
9        347    32903471    32903471    32903471   32903471   32903471
10       384    32903841    32903841    32903841   32903841   32903841
11       457    32904571    32904571    32904571   32904571   32904571
12       480    32904801    32904801    32904801   32904801   32904801
13       576    32905761    32905761    32905761   32905761   32905761
14       637    32906371    32906371    32906371   32906371   32906371
15       672    32906721    32906721    32906721   32906721   32906721
16       768    32907681    32907681    32907681   32907681   32907681
17       777    32907771    32907771    32907771   32907771   32907771
18       864    32908641    32908641    32908641   32908641   32908641
19       960    32909601    32909601    32909601   32909601   32909601
20       974    32909741    32909741    32909741   32909741   32909741
21      1056    32910561    32910561    32910561   32910561   32910561
22      1106    32911061    32911061    32911061   32911061   32911061
23      1152    32911521    32911521    32911521   32911521   32911521
24      1248    32912481    32912481    32912481   32912481   32912481
25      1270    32912701    32912701    32912701   32912701   32912701
26      1344    32913441    32913441    32913441   32913441   32913441
27      1440    32914401    32914401    32914401   32914401   32914401
28      1476    32914761    32914761    32914761   32914761   32914761
29      1536    32915361    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740    32917401    32917401    32917401   32917401   32917401
33      1824    32918241    32918241    32918241   32918241   32918241
34      1920    32919201    32919201    32919201   32919201   32919201
35      2016    32920161    32920161    32920161   32920161   32920161
36      2088    32920881    32920881    32920881   32920881   32920881
37      2112    32921121    32921121    32921121   32921121   32921121
38      2208    32922081    32922081    32922081   32922081   32922081
39      2304    32923041    32923041    32923041   32923041   32923041
40      2400    32924001    32924001    32924001   32924001   32924001
41      2496    32924961    32924961    32924961   32924961   32924961
42      2555    32925551    32925551    32925551   32925551   32925551
43      2592    32925921    32925921    32925921   32925921   32925921
44      2688    32926881    32926881    32926881   32926881   32926881
45      2784    32927841    32927841    32927841   32927841   32927841
46      2880    32928801    32928801    32928801   32928801   32928801
47      2976    32929761    32929761    32929761   32929761   32929761
48      3072    32930721    32930721    32930721   32930721   32930721
49      3168    32931681    32931681    32931681   32931681   32931681
50      3195    32931951    32931951    32931951   32931951   32931951
51      3264    32932641    32932641    32932641   32932641   32932641
52      3360    32933601    32933601    32933601   32933601   32933601
53      3456    32934561    32934561    32934561   32934561   32934561
54      3552    32935521    32935521    32935521   32935521   32935521
55      3606    32936061    32936061    32936061   32936061   32936061
56      3648    32936481    32936481    32936481   32936481   32936481
57      3744    32937441    32937441    32937441   32937441   32937441
58      3840    32938401    32938401    32938401   32938401   32938401
59      3936    32939361    32939361    32939361   32939361   32939361
60      4032    32940321    32940321    32940321   32940321   32940321
61      4096    32940961    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0         NaN
1    3290096221           0  32900961020   329009640           0         NaN
2    3290108234           0  32901081471   329010844           0         NaN
3    3290139545           0   3290139119  3290139138           0         NaN
4    3290188538           0    329018879  3290188197           0         NaN
5    3290192554           0    329019278  3290192195           0         NaN
6    3290225544           0    329022582  3290225210  3290225189         NaN
7    3290275579           0    329027574  3290275196  3290275121         NaN
8    3290288619           0    329028872  3290288186  3290288109         NaN
9    3290347581           0    329034758  3290347164   329034764         NaN
10   3290384579           0    329038460  3290384127   329038446         NaN
11   3290457588           0    329045751  3290457104   329045736         NaN
12   3290480583           0    329048049  3290480102   329048032         NaN
13   3290576536           0    329057638   329057696   329057626         NaN
14   3290637554           0    329063738  3290637104   329063727         NaN
15   3290672559           0    329067235  3290672100   329067221         NaN
16   3290768567           0    329076836   329076886   329076824         NaN
17   3290777570           0    329077736   329077786   329077723         NaN
18   3290864555           0    329086434   329086477   329086420         NaN
19   3290960543           0    329096033   329096073   329096021         NaN
20   3290974534           0    329097431   329097473   329097420         NaN
21   3291056562           0    329105639   329105668   329105622         NaN
22   3291106741           0    329110652   329110666   329110622         NaN
23   3291152887           0    329115265   329115271   329115223         NaN
24  32912481314           0    329124869   329124868   329124825         NaN
25   3291270963           0    329127068   329127066   329127026         NaN
26   3291344954           0    329134471   329134461   329134424         NaN
27   3291440948           0    329144073   329144058   329144021         NaN
28   3291476953           0    329147674   329147661   329147621         NaN
29   3291536954           0    329153675   329153662   329153634         NaN
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043         NaN
33  32918241363           0    329182478   329182462   329182445         NaN
34  32919201657           0    329192075   329192057   329192047         NaN
35  32920161763           0    329201673   329201653   329201648         NaN
36  32920881809           0   3292088210   329208852   329208849         NaN
37  32921121823           0   3292112188   329211251   329211250         NaN

['3290071182', '3290096124', '3290108114', '3290139261', '3290188285', '3290192291', '3290225307', '3290275307', '3290288300', '3290347281', '3290384281', '3290457298', '3290480324', '3290576383', '3290637432', '3290672445', '3290768468', '3290777467', '3290864451', '3290960483', '3290974478', '3291056516', '3291106605', '3291152630', '3291248663', '3291270664', '3291344669', '3291440664', '3291476662', '3291536656', '3291632680', '3291728707', '3291740718', '3291824721', '3291920729', '3292016729', '3292088728', '3292112723', '3292208722', '3292304732', '3292400787', '3292496824', '3292555828', '3292592829', '3292688812', '3292784818', '3292880812', '3292976814', '3293072822', '3293168808', '3293195815', '3293264809', '3293360798', '3293456793', '3293552779', '3293606772', '3293648771', '3293744765', '3293840765', '3293936767', '3294032765', '3294096768']
[ <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000071/halo_182' | NDM=499 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096/halo_124' | NDM=777 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108/halo_114' | NDM=976 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_261' | NDM=1301 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_285' | NDM=1889 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_291' | NDM=1907 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_307' | NDM=2186 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_307' | NDM=2618 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_300' | NDM=2680 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_281' | NDM=3220 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_281' | NDM=3404 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_298' | NDM=3322 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_324' | NDM=3183 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_383' | NDM=3025 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_432' | NDM=2643 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_445' | NDM=2561 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_468' | NDM=2548 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_467' | NDM=2562 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_451' | NDM=2593 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_483' | NDM=2551 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_478' | NDM=2540 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_516' | NDM=2303 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_605' | NDM=2037 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_630' | NDM=1957 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_663' | NDM=1838 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_664' | NDM=1810 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_669' | NDM=1786 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_664' | NDM=1759 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_662' | NDM=1756 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_656' | NDM=1744 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_680' | NDM=1702 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_707' | NDM=1617 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_718' | NDM=1600 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_721' | NDM=1540 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_729' | NDM=1497 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_729' | NDM=1470 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_728' | NDM=1453 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_723' | NDM=1448 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_722' | NDM=1432 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_732' | NDM=1406 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_787' | NDM=1296 Nstar=51 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_824' | NDM=1200 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_828' | NDM=1184 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_829' | NDM=1177 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_812' | NDM=1166 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_818' | NDM=1155 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_812' | NDM=1144 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_814' | NDM=1129 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_822' | NDM=1102 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_808' | NDM=1095 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_815' | NDM=1092 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_809' | NDM=1085 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_798' | NDM=1081 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_793' | NDM=1079 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_779' | NDM=1076 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_772' | NDM=1075 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_771' | NDM=1074 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_765' | NDM=1070 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_765' | NDM=1062 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_767' | NDM=1056 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_765' | NDM=1036 Nstar=50 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_768' | NDM=1023 Nstar=49 Ngas=0>]
[0, '3290096124', '3290108114', '3290139261', '3290188285', '3290192291', '3290225307', '3290275307', '3290288300', '3290347281', '3290384281', '3290457298', '3290480324', '3290576383', '3290637432', '3290672445', '3290768468', '3290777467', '3290864451', '3290960483', '3290974478', '3291056516', '3291106605', '3291152630', '3291248663', '3291270664', '3291344669', '3291440664', '3291476662', '3291536656', '3291632680', '3291728707', '3291740718', '3291824721', '3291920729', '3292016729', '3292088728', '3292112723', '3292208722', '3292304732', '3292400787', '3292496824', '3292555828', '3292592829', '3292688812', '3292784818', '3292880812', '3292976814', '3293072822', '3293168808', '3293195815', '3293264809', '3293360798', '3293456793', '3293552779', '3293606772', '3293648771', '3293744765', '3293840765', '3293936767', '3294032765', '3294096768']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71           0           0           0          0          0
1         96   329009638   329009662    32900969          0          0
2        108   329010830   329010856   329010810          0  329010836
3        139   329013986  3290139151   329013963  329013935  329013959
4        188  3290188153  3290188114  3290188111  329018827  329018833
5        192    32901921  3290192110  3290192111  329019225  329019230
6        225    32902251    32902251    32902251   32902251   32902251
7        275    32902751    32902751    32902751   32902751   32902751
8        288    32902881    32902881    32902881   32902881   32902881
9        347    32903471    32903471    32903471   32903471   32903471
10       384    32903841    32903841    32903841   32903841   32903841
11       457    32904571    32904571    32904571   32904571   32904571
12       480    32904801    32904801    32904801   32904801   32904801
13       576    32905761    32905761    32905761   32905761   32905761
14       637    32906371    32906371    32906371   32906371   32906371
15       672    32906721    32906721    32906721   32906721   32906721
16       768    32907681    32907681    32907681   32907681   32907681
17       777    32907771    32907771    32907771   32907771   32907771
18       864    32908641    32908641    32908641   32908641   32908641
19       960    32909601    32909601    32909601   32909601   32909601
20       974    32909741    32909741    32909741   32909741   32909741
21      1056    32910561    32910561    32910561   32910561   32910561
22      1106    32911061    32911061    32911061   32911061   32911061
23      1152    32911521    32911521    32911521   32911521   32911521
24      1248    32912481    32912481    32912481   32912481   32912481
25      1270    32912701    32912701    32912701   32912701   32912701
26      1344    32913441    32913441    32913441   32913441   32913441
27      1440    32914401    32914401    32914401   32914401   32914401
28      1476    32914761    32914761    32914761   32914761   32914761
29      1536    32915361    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740    32917401    32917401    32917401   32917401   32917401
33      1824    32918241    32918241    32918241   32918241   32918241
34      1920    32919201    32919201    32919201   32919201   32919201
35      2016    32920161    32920161    32920161   32920161   32920161
36      2088    32920881    32920881    32920881   32920881   32920881
37      2112    32921121    32921121    32921121   32921121   32921121
38      2208    32922081    32922081    32922081   32922081   32922081
39      2304    32923041    32923041    32923041   32923041   32923041
40      2400    32924001    32924001    32924001   32924001   32924001
41      2496    32924961    32924961    32924961   32924961   32924961
42      2555    32925551    32925551    32925551   32925551   32925551
43      2592    32925921    32925921    32925921   32925921   32925921
44      2688    32926881    32926881    32926881   32926881   32926881
45      2784    32927841    32927841    32927841   32927841   32927841
46      2880    32928801    32928801    32928801   32928801   32928801
47      2976    32929761    32929761    32929761   32929761   32929761
48      3072    32930721    32930721    32930721   32930721   32930721
49      3168    32931681    32931681    32931681   32931681   32931681
50      3195    32931951    32931951    32931951   32931951   32931951
51      3264    32932641    32932641    32932641   32932641   32932641
52      3360    32933601    32933601    32933601   32933601   32933601
53      3456    32934561    32934561    32934561   32934561   32934561
54      3552    32935521    32935521    32935521   32935521   32935521
55      3606    32936061    32936061    32936061   32936061   32936061
56      3648    32936481    32936481    32936481   32936481   32936481
57      3744    32937441    32937441    32937441   32937441   32937441
58      3840    32938401    32938401    32938401   32938401   32938401
59      3936    32939361    32939361    32939361   32939361   32939361
60      4032    32940321    32940321    32940321   32940321   32940321
61      4096    32940961    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0           0
1    3290096221           0  32900961020   329009640           0  3290096124
2    3290108234           0  32901081471   329010844           0  3290108114
3    3290139545           0   3290139119  3290139138           0  3290139261
4    3290188538           0    329018879  3290188197           0  3290188285
5    3290192554           0    329019278  3290192195           0  3290192291
6    3290225544           0    329022582  3290225210  3290225189  3290225307
7    3290275579           0    329027574  3290275196  3290275121  3290275307
8    3290288619           0    329028872  3290288186  3290288109  3290288300
9    3290347581           0    329034758  3290347164   329034764  3290347281
10   3290384579           0    329038460  3290384127   329038446  3290384281
11   3290457588           0    329045751  3290457104   329045736  3290457298
12   3290480583           0    329048049  3290480102   329048032  3290480324
13   3290576536           0    329057638   329057696   329057626  3290576383
14   3290637554           0    329063738  3290637104   329063727  3290637432
15   3290672559           0    329067235  3290672100   329067221  3290672445
16   3290768567           0    329076836   329076886   329076824  3290768468
17   3290777570           0    329077736   329077786   329077723  3290777467
18   3290864555           0    329086434   329086477   329086420  3290864451
19   3290960543           0    329096033   329096073   329096021  3290960483
20   3290974534           0    329097431   329097473   329097420  3290974478
21   3291056562           0    329105639   329105668   329105622  3291056516
22   3291106741           0    329110652   329110666   329110622  3291106605
23   3291152887           0    329115265   329115271   329115223  3291152630
24  32912481314           0    329124869   329124868   329124825  3291248663
25   3291270963           0    329127068   329127066   329127026  3291270664
26   3291344954           0    329134471   329134461   329134424  3291344669
27   3291440948           0    329144073   329144058   329144021  3291440664
28   3291476953           0    329147674   329147661   329147621  3291476662
29   3291536954           0    329153675   329153662   329153634  3291536656
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043  3291740718
33  32918241363           0    329182478   329182462   329182445  3291824721
34  32919201657           0    329192075   329192057   329192047  3291920729
35  32920161763           0    329201673   329201653   329201648  3292016729
36  32920881809           0   3292088210   329208852   329208849  3292088728
37  32921121823           0   3292112188   329211251   329211250  3292112723
38  32922081833           0   3292208214   329220850   329220848  3292208722
39  32923041843           0   3292304234   329230450   329230449  3292304732
40  32924001879           0   3292400261   329240048   329240050  3292400787
41  32924962122           0   3292496271   329249648   329249650  3292496824
42  32925552182           0   3292555278   329255548   329255551  3292555828
43  32925922176           0   3292592282   329259249   329259252  3292592829
44  32926882164           0   3292688286   329268849   329268853  3292688812

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481024232', '1481106241', '1481152237', '1481270247', '1481280250', '1481408245', '1481476246', '1481536252', '1481664215', '1481740214', '1481920216', '1482048210', '1482088208', '1482112205', '1482208204', '1482304202', '1482400196', '1482496253', '1482555225', '1482592368', '1482688375', '1482784380', '1482880391', '1482976405', '1483072411', '1483168418', '1483195411', '1483264414', '1483360411', '1483456401', '1483552402', '1483606396', '1483648393', '1483671389', '1483744391', '1483760389', '1483810384', '1483840382', '1483936376', '1484032374', '1484096387']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_232' | NDM=21992 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_241' | NDM=20788 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_237' | NDM=20292 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_247' | NDM=19192 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_250' | NDM=18833 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_245' | NDM=16639 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_246' | NDM=15753 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_252' | NDM=15207 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_215' | NDM=16857 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_214' | NDM=16799 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_216' | NDM=16613 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_210' | NDM=16491 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_208' | NDM=16386 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_205' | NDM=16328 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_204' | NDM=16102 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_202' | NDM=15905 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_196' | NDM=15926 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_253' | NDM=12342 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_225' | NDM=13234 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_368' | NDM=8011 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_375' | NDM=7786 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_380' | NDM=7456 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_391' | NDM=7112 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_405' | NDM=6751 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_411' | NDM=6516 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_418' | NDM=6378 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_411' | NDM=6358 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_414' | NDM=6323 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_411' | NDM=6294 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_401' | NDM=6280 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_402' | NDM=6259 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_396' | NDM=6254 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_393' | NDM=6249 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_389' | NDM=6243 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_391' | NDM=6222 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_389' | NDM=6217 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_384' | NDM=6198 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_382' | NDM=6186 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_376' | NDM=6167 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_374' | NDM=6105 Nstar=2 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_387' | NDM=5691 Nstar=2 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481024232', '1481106241', '1481152237', '1481270247', '1481280250', '1481408245', '1481476246', '1481536252', '1481664215', '1481740214', '1481920216', '1482048210', '1482088208', '1482112205', '1482208204', '1482304202', '1482400196', '1482496253', '1482555225', '1482592368', '1482688375', '1482784380', '1482880391', '1482976405', '1483072411', '1483168418', '1483195411', '1483264414', '1483360411', '1483456401', '1483552402', '1483606396', '1483648393', '1483671389', '1483744391', '1483760389', '1483810384', '1483840382', '1483936376', '1484032374', '1484096387']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0
5             0           0
6             0           0
7             0           0
8             0           0
9             0           0
10            0           0
11            0           0
12            0           0
13            0           0
14            0           0
15            0           0
16            0           0
17            0           0
18            0           0
19            0           0
20            0           0
21            0           0
22            0           0
23            0           0
24            0           0
25            0  1481664583
26            0  1481740675
27            0  1481920723
28            0  1482048709
29  14820883070  1482088716
30  14821123108  1482112721
31  14822083288  1482208764
32  14823043356  1482304820
33  14824003391  1482400761
34  14824964889  1482496764
35  14825555134  1482555761
36  14825925307  1482592774
37  14826885446  1482688844
38  14827845472  1482784888
39  14828805569  1482880871
40  14829766423  1482976861
41  14830726494  1483072837
42  14831686490  1483168827
43  14831956438  1483195823
44  14832646491  1483264814
45  14833606420  1483360815
46  14834566949  1483456812
47  14835527642  1483552798
48  14836067699  1483606789
49  14836487660  1483648782
50  14836717573  1483671780
51  14837447690  1483744767
52  14837607621  1483760767
53  14838107661  1483810759
54  14838407640  1483840752
55  14839367781  1483936756
56  14840328859  1484032786
57  14840968565  1484096857

[58 rows x 78 columns]
Finished  1484096387
Finished  1484096387
Completed Count -->  101
Started  14840961413
Started  14840961413
h148 Survivor 1413 4096

Watch me go for the  9 th time...
Already Exists  14840961025
Completed Count -->  101
Already Exists  14832642
Completed Count -->  101
Already Exists  14840964127
Completed Count -->  101
Already Exists  32913443
Completed Count -->  101
Already Exists  14840961061
Completed Count -->  101
Already Exists  14812709
Completed Count -->  101
Already Exists  329022513
Completed Count -->  101
Already Exists  1484096567
Completed Count -->  101
Already Exists  3294096956
Completed Count -->  101
Already Exists  32940964414
Completed Count -->  101
Already Exists  329022530
Completed Count -->  101
Already Exists  329409616
Completed Count -->  101
Already Exists  329038417
Completed Count -->  101
Already Exists  329409620
Completed Count -->  101
Already Exists  329038430
Completed Count -->  101
Already Exists  329127010
Completed Count -->  101
Already Exists  329038438
Completed Count -->  101
Already Exists  32904809
Completed Count -->  101
Already Exists  329409643
Completed Count -->  101
Already Exists  148409620589
Completed Count -->  101
Already Exists  329022579
Completed Count -->  101
Already Exists  14840962
Completed Count -->  101
Already Exists  14840963
Completed Count -->  101
Already Exists  14840961156
Completed Count -->  101
Already Exists  14840964
Completed Count -->  101
Already Exists  14840965
Completed Count -->  101
Already Exists  14840966
Completed Count -->  101
Already Exists  14840967
Completed Count -->  101
Already Exists  14812804
Completed Count -->  101
Already Exists  1484096138
Completed Count -->  101
Already Exists  329409673
Completed Count -->  101
Already Exists  329409675
Completed Count -->  101
Already Exists  32906374
Completed Count -->  101
Already Exists  32940965015
Completed Count -->  101
Already Exists  14840961179
Completed Count -->  101
Already Exists  14840961693
Completed Count -->  101
Already Exists  329409696
Completed Count -->  101
Already Exists  3294096555
Completed Count -->  101
Already Exists  1484096179
Completed Count -->  101
Already Exists  1484096194
Completed Count -->  101
Already Exists  14829762
Completed Count -->  101
Already Exists  3294096585
Completed Count -->  101
Already Exists  329067210
Completed Count -->  101
Already Exists  1484096204
Completed Count -->  101
Already Exists  1484096210
Completed Count -->  101
Already Exists  32933603
Completed Count -->  101
Already Exists  3290192110
Completed Count -->  101
Already Exists  3290192111
Completed Count -->  101
Already Exists  148409613555
Completed Count -->  101
Already Exists  148409619718
Completed Count -->  101
Already Exists  148153610
Completed Count -->  101
Already Exists  148409610
Completed Count -->  101
Already Exists  148409611
Completed Count -->  101
Already Exists  148409612
Completed Count -->  101
Already Exists  148128013
Completed Count -->  101
Already Exists  1484096271
Completed Count -->  101
Already Exists  14840965903
Completed Count -->  101
Already Exists  148409617
Completed Count -->  101
Already Exists  148110610
Completed Count -->  101
Already Exists  148115218
Completed Count -->  101
Already Exists  148409621
Completed Count -->  101
Already Exists  1484096278
Completed Count -->  101
Already Exists  148409622
Completed Count -->  101
Already Exists  148409632
Completed Count -->  101
Already Exists  148409633
Completed Count -->  101
Already Exists  148409634
Completed Count -->  101
Already Exists  148409635
Completed Count -->  101
Already Exists  1484096803
Completed Count -->  101
Already Exists  32924962
Completed Count -->  101
Already Exists  148409639
Completed Count -->  101
Already Exists  148409641
Completed Count -->  101
Already Exists  148409651
Completed Count -->  101
Already Exists  148409653
Completed Count -->  101
Already Exists  148409655
Completed Count -->  101
Already Exists  14840964409
Completed Count -->  101
Already Exists  148409663
Completed Count -->  101
Already Exists  148409668
Completed Count -->  101
Already Exists  1484096266
Completed Count -->  101
Already Exists  1484096331
Completed Count -->  101
Already Exists  148409676
Completed Count -->  101
Already Exists  148409677
Completed Count -->  101
Already Exists  329096015
Completed Count -->  101
Already Exists  14840964944
Completed Count -->  101
Already Exists  32914768
Completed Count -->  101
Already Exists  1484096857
Completed Count -->  101
Already Exists  329019225
Completed Count -->  101
Already Exists  14840961883
Completed Count -->  101
Already Exists  32940961630
Completed Count -->  101
Already Exists  14840967007
Completed Count -->  101
Already Exists  329019230
Completed Count -->  101
Already Exists  14840961379
Completed Count -->  101
Already Exists  32908648
Completed Count -->  101
Already Exists  14840961900
Completed Count -->  101
Already Exists  14840962413
Completed Count -->  101
Already Exists  14840962927
Completed Count -->  101
Already Exists  32940961648
Completed Count -->  101
Already Exists  14840968565
Completed Count -->  101
Already Exists  1484096374
Completed Count -->  101
Already Exists  3290188153
Completed Count -->  101
Already Exists  3294096768
Completed Count -->  101
Already Exists  1484096387
Completed Count -->  101
Started  14840961413
Started  14840961413
h148 Survivor 1413 4096
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14810241127', '14811061194', '14811521200', '14812701291', '14812801298', '14814081405', '14814761479', '14815361480', '14816641509', '14817401539', '14819201652', '14820481687', '14820881685', '14821121686', '14822081680', '14823041682', '14824001677', '14824961740', '14825551728', '14825921733', '14826881727', '14827841696', '14828801689', '14829761707', '14830721670', '14831681643', '14831951644', '14832641619', '14833601588', '14834561575', '14835521550', '14836061527', '14836481511', '14836711506', '14837441495', '14837601491', '14838101482', '14838401465', '14839361443', '14840321423', '14840961413']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_1127' | NDM=3719 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_1194' | NDM=3445 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_1200' | NDM=3288 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_1291' | NDM=3004 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_1298' | NDM=2994 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_1405' | NDM=2589 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_1479' | NDM=2444 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_1480' | NDM=2376 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_1509' | NDM=2273 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_1539' | NDM=2228 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_1652' | NDM=1969 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_1687' | NDM=1862 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_1685' | NDM=1846 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_1686' | NDM=1833 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_1680' | NDM=1795 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_1682' | NDM=1760 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_1677' | NDM=1704 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_1740' | NDM=1615 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_1728' | NDM=1591 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_1733' | NDM=1571 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_1727' | NDM=1541 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_1696' | NDM=1524 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_1689' | NDM=1500 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_1707' | NDM=1463 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_1670' | NDM=1453 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_1643' | NDM=1445 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_1644' | NDM=1444 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_1619' | NDM=1439 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_1588' | NDM=1432 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_1575' | NDM=1433 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_1550' | NDM=1430 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_1527' | NDM=1429 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_1511' | NDM=1429 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_1506' | NDM=1430 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_1495' | NDM=1428 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_1491' | NDM=1427 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_1482' | NDM=1425 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_1465' | NDM=1425 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_1443' | NDM=1424 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_1423' | NDM=1421 Nstar=11 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_1413' | NDM=1417 Nstar=11 Ngas=0>]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14810241127', '14811061194', '14811521200', '14812701291', '14812801298', '14814081405', '14814761479', '14815361480', '14816641509', '14817401539', '14819201652', '14820481687', '14820881685', '14821121686', '14822081680', '14823041682', '14824001677', '14824961740', '14825551728', '14825921733', '14826881727', '14827841696', '14828801689', '14829761707', '14830721670', '14831681643', '14831951644', '14832641619', '14833601588', '14834561575', '14835521550', '14836061527', '14836481511', '14836711506', '14837441495', '14837601491', '14838101482', '14838401465', '14839361443', '14840321423', '14840961413']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

    14814089  148153610  14829762     ...       14840966  148409663  \
0        NaN          0         0     ...              0          0
1        NaN          0         0     ...              0          0
2        NaN          0         0     ...              0          0
3        NaN          0         0     ...              0          0
4        NaN          0         0     ...              0          0
5        NaN          0         0     ...              0          0
6        NaN          0         0     ...              0          0
7        NaN          0         0     ...              0          0
8        NaN          0         0     ...              0          0
9        NaN          0         0     ...              0          0
10       NaN          0         0     ...              0          0
11       NaN          0         0     ...              0          0
12       NaN          0         0     ...              0          0
13       NaN          0         0     ...              0          0
14       NaN          0         0     ...              0          0
15       NaN          0         0     ...              0          0
16       NaN          0         0     ...              0          0
17       NaN  148102415  14810242     ...      148102412  148102483
18       NaN  148110613  14811062     ...       14811069  148110677
19       NaN  148115211  14811522     ...       14811529  148115273
20       NaN  148127012  14812702     ...      148127010  148127071
21       NaN  148128011  14812802     ...       14812809  148128070
22       NaN  148140810  14814082     ...       14814088  148140862
23       NaN  148147616  14814762     ...       14814768  148147669
24       NaN  148153610  14815362     ...       14815368  148153669
25       NaN   14816641  14816642     ...       14816648  148166469
26       NaN   14817401  14817402     ...       14817408  148174064
27       NaN   14819201  14819202     ...       14819208  148192064
28       NaN   14820481  14820482     ...       14820488  148204862
29       NaN   14820881  14820882     ...       14820888  148208862
30       NaN   14821121  14821122     ...       14821128  148211261
31       NaN   14822081  14822082     ...       14822088  148220860
32       NaN   14823041  14823042     ...       14823048  148230461
33       NaN   14824001  14824002     ...       14824008  148240060
34       NaN   14824961  14824962     ...       14824968  148249665
35       NaN   14825551  14825552     ...       14825558  148255565
36       NaN   14825921  14825922     ...       14825928  148259265
37       NaN   14826881  14826882     ...       14826888  148268866
38       NaN   14827841  14827842     ...       14827848  148278465
39       NaN   14828801  14828802     ...       14828808  148288064
40       NaN   14829761  14829762     ...       14829768  148297666
41       NaN   14830721  14830721     ...       14830726  148307267
42       NaN   14831681  14831681     ...       14831688  148316866
43       NaN   14831951  14831951     ...       14831958  148319567
44       NaN   14832641  14832641     ...       14832648  148326468
45       NaN   14833601  14833601     ...       14833607  148336067
46       NaN   14834561  14834561     ...       14834567  148345667
47       NaN   14835521  14835521     ...       14835526  148355266
48       NaN   14836061  14836061     ...       14836066  148360668
49       NaN   14836481  14836481     ...       14836486  148364866
50       NaN   14836711  14836711     ...       14836716  148367167
51       NaN   14837441  14837441     ...       14837446  148374466
52       NaN   14837601  14837601     ...       14837606  148376066
53       NaN   14838101  14838101     ...       14838106  148381065
54       NaN   14838401  14838401     ...       14838406  148384064
55       NaN   14839361  14839361     ...       14839366  148393663
56       NaN   14840321  14840321     ...       14840326  148403262
57       NaN   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0
5             0           0
6             0           0
7             0           0
8             0           0
9             0           0
10            0           0
11            0           0
12            0           0
13            0           0
14            0           0
15            0           0
16            0           0
17            0           0
18            0           0
19            0           0
20            0           0
21            0           0
22            0           0
23            0           0
24            0           0
25            0  1481664583
26            0  1481740675
27            0  1481920723
28            0  1482048709
29  14820883070  1482088716
30  14821123108  1482112721
31  14822083288  1482208764
32  14823043356  1482304820
33  14824003391  1482400761
34  14824964889  1482496764
35  14825555134  1482555761
36  14825925307  1482592774
37  14826885446  1482688844
38  14827845472  1482784888
39  14828805569  1482880871
40  14829766423  1482976861
41  14830726494  1483072837
42  14831686490  1483168827
43  14831956438  1483195823
44  14832646491  1483264814
45  14833606420  1483360815
46  14834566949  1483456812
47  14835527642  1483552798
48  14836067699  1483606789
49  14836487660  1483648782
50  14836717573  1483671780
51  14837447690  1483744767
52  14837607621  1483760767
53  14838107661  1483810759
54  14838407640  1483840752
55  14839367781  1483936756
56  14840328859  1484032786
57  14840968565  1484096857

[58 rows x 78 columns]
Finished  14840961413
Finished  14840961413
Completed Count -->  102
Started  14814089
Started  14814089
h148 Zombie 9 1408

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148102414', '148110612', '148115210', '148127011', '148128010', '14814089', '14814761', '14815361', '14816641', '14817401', '14819201', '14820481', '14820881', '14821121', '14822081', '14823041', '14824001', '14824961', '14825551', '14825921', '14826881', '14827841', '14828801', '14829761', '14830721', '14831681', '14831951', '14832641', '14833601', '14834561', '14835521', '14836061', '14836481', '14836711', '14837441', '14837601', '14838101', '14838401', '14839361', '14840321', '14840961']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_14' | NDM=690579 Nstar=63871 Ngas=486036>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_12' | NDM=731606 Nstar=83170 Ngas=520332>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_10' | NDM=727767 Nstar=88165 Ngas=542584>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_11' | NDM=780022 Nstar=108622 Ngas=561355>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_10' | NDM=780550 Nstar=109169 Ngas=562941>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_9' | NDM=723299 Nstar=126120 Ngas=520834>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_1' | NDM=52004649 Nstar=48517944 Ngas=37598752>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_1' | NDM=53923378 Nstar=53871908 Ngas=39624071>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_1' | NDM=53028504 Nstar=67650363 Ngas=41160525>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_1' | NDM=52538651 Nstar=75777722 Ngas=41946434>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_1' | NDM=56084252 Nstar=98380133 Ngas=43998788>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_1' | NDM=57713295 Nstar=115914448 Ngas=43757050>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_1' | NDM=58088133 Nstar=125274832 Ngas=42721848>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_1' | NDM=58284883 Nstar=128396317 Ngas=41268341>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_1' | NDM=60407892 Nstar=136063352 Ngas=42526327>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_1' | NDM=69719556 Nstar=151745066 Ngas=48679549>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_1' | NDM=74682561 Nstar=161288463 Ngas=49838203>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_1' | NDM=79209282 Nstar=171242211 Ngas=50776202>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_1' | NDM=81034353 Nstar=178405453 Ngas=51274583>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_1' | NDM=83533480 Nstar=182930962 Ngas=52156952>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_1' | NDM=88184399 Nstar=191859919 Ngas=53169813>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_1' | NDM=92128287 Nstar=200448545 Ngas=53996941>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_1' | NDM=92940876 Nstar=208293336 Ngas=54631732>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_1' | NDM=93137267 Nstar=216139033 Ngas=54182355>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_1' | NDM=93736187 Nstar=224685115 Ngas=53002659>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_1' | NDM=94968147 Nstar=232409562 Ngas=52937142>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_1' | NDM=95347084 Nstar=234720893 Ngas=52805098>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_1' | NDM=96926797 Nstar=240553350 Ngas=52804416>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_1' | NDM=100393030 Nstar=248831799 Ngas=53306203>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_1' | NDM=102755225 Nstar=256536772 Ngas=53324840>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_1' | NDM=108077897 Nstar=265884484 Ngas=55729574>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_1' | NDM=109410522 Nstar=269836568 Ngas=56173111>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_1' | NDM=110247779 Nstar=272811832 Ngas=56212487>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_1' | NDM=110732781 Nstar=274415388 Ngas=56246035>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_1' | NDM=111919159 Nstar=279705605 Ngas=56130783>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_1' | NDM=112282813 Nstar=280846217 Ngas=56086346>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_1' | NDM=112822614 Nstar=284201687 Ngas=55870207>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_1' | NDM=113010704 Nstar=285992241 Ngas=55775510>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_1' | NDM=113660248 Nstar=291859545 Ngas=55252145>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_1' | NDM=114035352 Nstar=297707243 Ngas=54610224>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_1' | NDM=114345489 Nstar=301507217 Ngas=54135923>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148102414', '148110612', '148115210', '148127011', '148128010', '14814089', '14814761', '14815361', '14816641', '14817401', '14819201', '14820481', '14820881', '14821121', '14822081', '14823041', '14824001', '14824961', '14825551', '14825921', '14826881', '14827841', '14828801', '14829761', '14830721', '14831681', '14831951', '14832641', '14833601', '14834561', '14835521', '14836061', '14836481', '14836711', '14837441', '14837601', '14838101', '14838401', '14839361', '14840321', '14840961']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

     14814089  148153610  14829762     ...       14840966  148409663  \
0           0          0         0     ...              0          0
1           0          0         0     ...              0          0
2           0          0         0     ...              0          0
3           0          0         0     ...              0          0
4           0          0         0     ...              0          0
5           0          0         0     ...              0          0
6           0          0         0     ...              0          0
7           0          0         0     ...              0          0
8           0          0         0     ...              0          0
9           0          0         0     ...              0          0
10          0          0         0     ...              0          0
11          0          0         0     ...              0          0
12          0          0         0     ...              0          0
13          0          0         0     ...              0          0
14          0          0         0     ...              0          0
15          0          0         0     ...              0          0
16          0          0         0     ...              0          0
17  148102414  148102415  14810242     ...      148102412  148102483
18  148110612  148110613  14811062     ...       14811069  148110677
19  148115210  148115211  14811522     ...       14811529  148115273
20  148127011  148127012  14812702     ...      148127010  148127071
21  148128010  148128011  14812802     ...       14812809  148128070
22   14814089  148140810  14814082     ...       14814088  148140862
23   14814761  148147616  14814762     ...       14814768  148147669
24   14815361  148153610  14815362     ...       14815368  148153669
25   14816641   14816641  14816642     ...       14816648  148166469
26   14817401   14817401  14817402     ...       14817408  148174064
27   14819201   14819201  14819202     ...       14819208  148192064
28   14820481   14820481  14820482     ...       14820488  148204862
29   14820881   14820881  14820882     ...       14820888  148208862
30   14821121   14821121  14821122     ...       14821128  148211261
31   14822081   14822081  14822082     ...       14822088  148220860
32   14823041   14823041  14823042     ...       14823048  148230461
33   14824001   14824001  14824002     ...       14824008  148240060
34   14824961   14824961  14824962     ...       14824968  148249665
35   14825551   14825551  14825552     ...       14825558  148255565
36   14825921   14825921  14825922     ...       14825928  148259265
37   14826881   14826881  14826882     ...       14826888  148268866
38   14827841   14827841  14827842     ...       14827848  148278465
39   14828801   14828801  14828802     ...       14828808  148288064
40   14829761   14829761  14829762     ...       14829768  148297666
41   14830721   14830721  14830721     ...       14830726  148307267
42   14831681   14831681  14831681     ...       14831688  148316866
43   14831951   14831951  14831951     ...       14831958  148319567
44   14832641   14832641  14832641     ...       14832648  148326468
45   14833601   14833601  14833601     ...       14833607  148336067
46   14834561   14834561  14834561     ...       14834567  148345667
47   14835521   14835521  14835521     ...       14835526  148355266
48   14836061   14836061  14836061     ...       14836066  148360668
49   14836481   14836481  14836481     ...       14836486  148364866
50   14836711   14836711  14836711     ...       14836716  148367167
51   14837441   14837441  14837441     ...       14837446  148374466
52   14837601   14837601  14837601     ...       14837606  148376066
53   14838101   14838101  14838101     ...       14838106  148381065
54   14838401   14838401  14838401     ...       14838406  148384064
55   14839361   14839361  14839361     ...       14839366  148393663
56   14840321   14840321  14840321     ...       14840326  148403262
57   14840961   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0
5             0           0
6             0           0
7             0           0
8             0           0
9             0           0
10            0           0
11            0           0
12            0           0
13            0           0
14            0           0
15            0           0
16            0           0
17            0           0
18            0           0
19            0           0
20            0           0
21            0           0
22            0           0
23            0           0
24            0           0
25            0  1481664583
26            0  1481740675
27            0  1481920723
28            0  1482048709
29  14820883070  1482088716
30  14821123108  1482112721
31  14822083288  1482208764
32  14823043356  1482304820
33  14824003391  1482400761
34  14824964889  1482496764
35  14825555134  1482555761
36  14825925307  1482592774
37  14826885446  1482688844
38  14827845472  1482784888
39  14828805569  1482880871
40  14829766423  1482976861
41  14830726494  1483072837
42  14831686490  1483168827
43  14831956438  1483195823
44  14832646491  1483264814
45  14833606420  1483360815
46  14834566949  1483456812
47  14835527642  1483552798
48  14836067699  1483606789
49  14836487660  1483648782
50  14836717573  1483671780
51  14837447690  1483744767

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148102491', '148110689', '148115283', '148127083', '148128086', '148140881', '148147695', '1481536101', '1481664120', '1481740179', '1481920183', '1482048182', '1482088185', '1482112188', '1482208190', '1482304189', '1482400188', '1482496191', '1482555190', '1482592190', '1482688202', '1482784238', '1482880247', '1482976249', '1483072251', '1483168256', '1483195259', '1483264257', '1483360259', '1483456255', '1483552256', '1483606264', '1483648287', '1483671318', '1483744392', '1483760392', '1483810394', '1483840394', '1483936404', '1484032403', '1484096412']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_91' | NDM=57089 Nstar=29 Ngas=579>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_89' | NDM=57954 Nstar=29 Ngas=186>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_83' | NDM=58860 Nstar=29 Ngas=240>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_83' | NDM=60973 Nstar=29 Ngas=371>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_86' | NDM=61102 Nstar=29 Ngas=354>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_81' | NDM=62924 Nstar=29 Ngas=346>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_95' | NDM=55628 Nstar=29 Ngas=324>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_101' | NDM=49383 Nstar=29 Ngas=228>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_120' | NDM=40031 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_179' | NDM=21003 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_183' | NDM=19831 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_182' | NDM=19507 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_185' | NDM=18898 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_188' | NDM=18603 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_190' | NDM=18009 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_189' | NDM=17696 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_188' | NDM=17157 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_191' | NDM=16740 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_190' | NDM=16371 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_190' | NDM=16040 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_202' | NDM=14553 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_238' | NDM=11762 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_247' | NDM=11331 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_249' | NDM=11118 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_251' | NDM=10772 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_256' | NDM=10455 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_259' | NDM=10363 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_257' | NDM=10204 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_259' | NDM=10042 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_255' | NDM=9959 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_256' | NDM=9712 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_264' | NDM=9365 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_287' | NDM=8597 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_318' | NDM=7390 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_392' | NDM=6189 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_392' | NDM=6129 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_394' | NDM=5967 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_394' | NDM=5870 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_404' | NDM=5627 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_403' | NDM=5466 Nstar=29 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_412' | NDM=5364 Nstar=29 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148102491', '148110689', '148115283', '148127083', '148128086', '148140881', '148147695', '1481536101', '1481664120', '1481740179', '1481920183', '1482048182', '1482088185', '1482112188', '1482208190', '1482304189', '1482400188', '1482496191', '1482555190', '1482592190', '1482688202', '1482784238', '1482880247', '1482976249', '1483072251', '1483168256', '1483195259', '1483264257', '1483360259', '1483456255', '1483552256', '1483606264', '1483648287', '1483671318', '1483744392', '1483760392', '1483810394', '1483840394', '1483936404', '1484032403', '1484096412']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

     14814089  148153610  14829762     ...       14840966  148409663  \
0           0          0         0     ...              0          0
1           0          0         0     ...              0          0
2           0          0         0     ...              0          0
3           0          0         0     ...              0          0
4           0          0         0     ...              0          0
5           0          0         0     ...              0          0
6           0          0         0     ...              0          0
7           0          0         0     ...              0          0
8           0          0         0     ...              0          0
9           0          0         0     ...              0          0
10          0          0         0     ...              0          0
11          0          0         0     ...              0          0
12          0          0         0     ...              0          0
13          0          0         0     ...              0          0
14          0          0         0     ...              0          0
15          0          0         0     ...              0          0
16          0          0         0     ...              0          0
17  148102414  148102415  14810242     ...      148102412  148102483
18  148110612  148110613  14811062     ...       14811069  148110677
19  148115210  148115211  14811522     ...       14811529  148115273
20  148127011  148127012  14812702     ...      148127010  148127071
21  148128010  148128011  14812802     ...       14812809  148128070
22   14814089  148140810  14814082     ...       14814088  148140862
23   14814761  148147616  14814762     ...       14814768  148147669
24   14815361  148153610  14815362     ...       14815368  148153669
25   14816641   14816641  14816642     ...       14816648  148166469
26   14817401   14817401  14817402     ...       14817408  148174064
27   14819201   14819201  14819202     ...       14819208  148192064
28   14820481   14820481  14820482     ...       14820488  148204862
29   14820881   14820881  14820882     ...       14820888  148208862
30   14821121   14821121  14821122     ...       14821128  148211261
31   14822081   14822081  14822082     ...       14822088  148220860
32   14823041   14823041  14823042     ...       14823048  148230461
33   14824001   14824001  14824002     ...       14824008  148240060
34   14824961   14824961  14824962     ...       14824968  148249665
35   14825551   14825551  14825552     ...       14825558  148255565
36   14825921   14825921  14825922     ...       14825928  148259265
37   14826881   14826881  14826882     ...       14826888  148268866
38   14827841   14827841  14827842     ...       14827848  148278465
39   14828801   14828801  14828802     ...       14828808  148288064
40   14829761   14829761  14829762     ...       14829768  148297666
41   14830721   14830721  14830721     ...       14830726  148307267
42   14831681   14831681  14831681     ...       14831688  148316866
43   14831951   14831951  14831951     ...       14831958  148319567
44   14832641   14832641  14832641     ...       14832648  148326468
45   14833601   14833601  14833601     ...       14833607  148336067
46   14834561   14834561  14834561     ...       14834567  148345667
47   14835521   14835521  14835521     ...       14835526  148355266
48   14836061   14836061  14836061     ...       14836066  148360668
49   14836481   14836481  14836481     ...       14836486  148364866
50   14836711   14836711  14836711     ...       14836716  148367167
51   14837441   14837441  14837441     ...       14837446  148374466
52   14837601   14837601  14837601     ...       14837606  148376066
53   14838101   14838101  14838101     ...       14838106  148381065
54   14838401   14838401  14838401     ...       14838406  148384064
55   14839361   14839361  14839361     ...       14839366  148393663
56   14840321   14840321  14840321     ...       14840326  148403262
57   14840961   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0
5             0           0
6             0           0
7             0           0
8             0           0
9             0           0
10            0           0
11            0           0
12            0           0
13            0           0
14            0           0
15            0           0
16            0           0
17            0           0
18            0           0
19            0           0
20            0           0
21            0           0
22            0           0
23            0           0
24            0           0
25            0  1481664583
26            0  1481740675
27            0  1481920723
28            0  1482048709
29  14820883070  1482088716
30  14821123108  1482112721
31  14822083288  1482208764
32  14823043356  1482304820
33  14824003391  1482400761
34  14824964889  1482496764
35  14825555134  1482555761
36  14825925307  1482592774
37  14826885446  1482688844
38  14827845472  1482784888
39  14828805569  1482880871
40  14829766423  1482976861
41  14830726494  1483072837
42  14831686490  1483168827
43  14831956438  1483195823
44  14832646491  1483264814
45  14833606420  1483360815
46  14834566949  1483456812
47  14835527642  1483552798
48  14836067699  1483606789
49  14836487660  1483648782
50  14836717573  1483671780
51  14837447690  1483744767
52  14837607621  1483760767
53  14838107661  1483810759
54  14838407640  1483840752
55  14839367781  1483936756
56  14840328859  1484032786
57  14840968565  1484096857

[58 rows x 78 columns]
Finished  1484096412
Finished  1484096412
Completed Count -->  104
Started  32930722
Started  32930722
h329 Zombie 2 3072

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '32925922', '32926882', '32927842', '32928802', '32929762', '32930722', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_2' | NDM=1021799 Nstar=1522033 Ngas=608608>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_2' | NDM=1207804 Nstar=1550346 Ngas=566190>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_2' | NDM=1195417 Nstar=1578924 Ngas=567037>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_2' | NDM=1093412 Nstar=1606258 Ngas=547756>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_2' | NDM=946889 Nstar=1626312 Ngas=515504>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_2' | NDM=762397 Nstar=1654100 Ngas=447779>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '32925922', '32926882', '32927842', '32928802', '32929762', '32930722', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71           0           0           0          0          0
1         96   329009638   329009662    32900969          0          0
2        108   329010830   329010856   329010810          0  329010836
3        139   329013986  3290139151   329013963  329013935  329013959
4        188  3290188153  3290188114  3290188111  329018827  329018833
5        192    32901921  3290192110  3290192111  329019225  329019230
6        225    32902251    32902251    32902251   32902251   32902251
7        275    32902751    32902751    32902751   32902751   32902751
8        288    32902881    32902881    32902881   32902881   32902881
9        347    32903471    32903471    32903471   32903471   32903471
10       384    32903841    32903841    32903841   32903841   32903841
11       457    32904571    32904571    32904571   32904571   32904571
12       480    32904801    32904801    32904801   32904801   32904801
13       576    32905761    32905761    32905761   32905761   32905761
14       637    32906371    32906371    32906371   32906371   32906371
15       672    32906721    32906721    32906721   32906721   32906721
16       768    32907681    32907681    32907681   32907681   32907681
17       777    32907771    32907771    32907771   32907771   32907771
18       864    32908641    32908641    32908641   32908641   32908641
19       960    32909601    32909601    32909601   32909601   32909601
20       974    32909741    32909741    32909741   32909741   32909741
21      1056    32910561    32910561    32910561   32910561   32910561
22      1106    32911061    32911061    32911061   32911061   32911061
23      1152    32911521    32911521    32911521   32911521   32911521
24      1248    32912481    32912481    32912481   32912481   32912481
25      1270    32912701    32912701    32912701   32912701   32912701
26      1344    32913441    32913441    32913441   32913441   32913441
27      1440    32914401    32914401    32914401   32914401   32914401
28      1476    32914761    32914761    32914761   32914761   32914761
29      1536    32915361    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740    32917401    32917401    32917401   32917401   32917401
33      1824    32918241    32918241    32918241   32918241   32918241
34      1920    32919201    32919201    32919201   32919201   32919201
35      2016    32920161    32920161    32920161   32920161   32920161
36      2088    32920881    32920881    32920881   32920881   32920881
37      2112    32921121    32921121    32921121   32921121   32921121
38      2208    32922081    32922081    32922081   32922081   32922081
39      2304    32923041    32923041    32923041   32923041   32923041
40      2400    32924001    32924001    32924001   32924001   32924001
41      2496    32924961    32924961    32924961   32924961   32924961
42      2555    32925551    32925551    32925551   32925551   32925551
43      2592    32925921    32925921    32925921   32925921   32925921
44      2688    32926881    32926881    32926881   32926881   32926881
45      2784    32927841    32927841    32927841   32927841   32927841
46      2880    32928801    32928801    32928801   32928801   32928801
47      2976    32929761    32929761    32929761   32929761   32929761
48      3072    32930721    32930721    32930721   32930721   32930721
49      3168    32931681    32931681    32931681   32931681   32931681
50      3195    32931951    32931951    32931951   32931951   32931951
51      3264    32932641    32932641    32932641   32932641   32932641
52      3360    32933601    32933601    32933601   32933601   32933601
53      3456    32934561    32934561    32934561   32934561   32934561
54      3552    32935521    32935521    32935521   32935521   32935521
55      3606    32936061    32936061    32936061   32936061   32936061
56      3648    32936481    32936481    32936481   32936481   32936481
57      3744    32937441    32937441    32937441   32937441   32937441
58      3840    32938401    32938401    32938401   32938401   32938401
59      3936    32939361    32939361    32939361   32939361   32939361
60      4032    32940321    32940321    32940321   32940321   32940321
61      4096    32940961    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0           0
1    3290096221           0  32900961020   329009640           0  3290096124
2    3290108234           0  32901081471   329010844           0  3290108114
3    3290139545           0   3290139119  3290139138           0  3290139261
4    3290188538           0    329018879  3290188197           0  3290188285
5    3290192554           0    329019278  3290192195           0  3290192291
6    3290225544           0    329022582  3290225210  3290225189  3290225307
7    3290275579           0    329027574  3290275196  3290275121  3290275307
8    3290288619           0    329028872  3290288186  3290288109  3290288300
9    3290347581           0    329034758  3290347164   329034764  3290347281
10   3290384579           0    329038460  3290384127   329038446  3290384281
11   3290457588           0    329045751  3290457104   329045736  3290457298
12   3290480583           0    329048049  3290480102   329048032  3290480324
13   3290576536           0    329057638   329057696   329057626  3290576383
14   3290637554           0    329063738  3290637104   329063727  3290637432
15   3290672559           0    329067235  3290672100   329067221  3290672445
16   3290768567           0    329076836   329076886   329076824  3290768468
17   3290777570           0    329077736   329077786   329077723  3290777467
18   3290864555           0    329086434   329086477   329086420  3290864451
19   3290960543           0    329096033   329096073   329096021  3290960483
20   3290974534           0    329097431   329097473   329097420  3290974478
21   3291056562           0    329105639   329105668   329105622  3291056516
22   3291106741           0    329110652   329110666   329110622  3291106605
23   3291152887           0    329115265   329115271   329115223  3291152630
24  32912481314           0    329124869   329124868   329124825  3291248663
25   3291270963           0    329127068   329127066   329127026  3291270664
26   3291344954           0    329134471   329134461   329134424  3291344669
27   3291440948           0    329144073   329144058   329144021  3291440664
28   3291476953           0    329147674   329147661   329147621  3291476662
29   3291536954           0    329153675   329153662   329153634  3291536656
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043  3291740718
33  32918241363           0    329182478   329182462   329182445  3291824721
34  32919201657           0    329192075   329192057   329192047  3291920729
35  32920161763           0    329201673   329201653   329201648  3292016729
36  32920881809           0   3292088210   329208852   329208849  3292088728
37  32921121823           0   3292112188   329211251   329211250  3292112723
38  32922081833           0   3292208214   329220850   329220848  3292208722
39  32923041843           0   3292304234   329230450   329230449  3292304732
40  32924001879           0   3292400261   329240048   329240050  3292400787
41  32924962122           0   3292496271   329249648   329249650  3292496824
42  32925552182           0   3292555278   329255548   329255551  3292555828
43  32925922176           0   3292592282   329259249   329259252  3292592829
44  32926882164           0   3292688286   329268849   329268853  3292688812
45  32927842152           0   3292784291   329278449   329278454  3292784818
46  32928802121           0   3292880313   329288050   329288057  3292880812
47  32929762119           0   3292976362   329297650   329297662  3292976814
48  32930722348           0   3293072379   329307248   329307266  3293072822
49  32931683019           0   3293168381   329316846   329316863  3293168808
50  32931953176           0   3293195382   329319546   329319564  3293195815
51  32932643395           0   3293264386   329326447   329326463  3293264809
52  32933603421           0   3293360393   329336046   329336069  3293360798
53  32934563452  3293456528   3293456390   329345644   329345669  3293456793
54  32935523520  3293552526   3293552387   329355245   329355271  3293552779
55  32936063546  3293606534   3293606388   329360645   329360673  3293606772
56  32936483588  3293648534   3293648390   329364845   329364872  3293648771
57  32937444656  3293744559   3293744407   329374445   329374474  3293744765
58  32938405004  3293840554   3293840515   329384059   329384075  3293840765
59  32939365000  3293936554   3293936552   329393673   329393675  3293936767
60  32940325024  3294032554   3294032579   329403272   329403275  3294032765
61  32940965015  3294096555   3294096585   329409673   329409675  3294096768

    32940969  3294096956  329409696
0        NaN           0          0
1        NaN           0  329009612
2        NaN           0  329010814
3        NaN   329013940  329013960
4        NaN   329018862  329018880
5        NaN   329019261  329019281
6        NaN   329022554  329022577
7        NaN   329027554  329027566
8        NaN   329028857  329028868
9        NaN   329034755  329034763
10       NaN   329038455  329038462
11       NaN   329045759  329045758
12       NaN   329048064  329048058
13       NaN   329057673  329057653
14       NaN   329063775  329063751
15       NaN   329067270  329067248
16       NaN   329076858  329076844
17       NaN   329077759  329077744
18       NaN  3290864141  329086440
19       NaN   329096065  329096039
20       NaN   329097466  329097438
21       NaN   329105678  329105637
22       NaN   329110681  329110637
23       NaN   329115287  329115237
24       NaN   329124883  329124841
25       NaN   329127083  329127043
26       NaN   329134478  329134442
27       NaN   329144075  329144043
28       NaN   329147681  329147643
29       NaN  3291536100  329153645
..       ...         ...        ...
32       NaN  3291740129  329174054
33       NaN  3291824136  329182455
34       NaN  3291920141  329192056
35       NaN  3292016148  329201651
36       NaN  3292088147  329208854
37       NaN  3292112148  329211254
38       NaN  3292208151  329220857
39       NaN  3292304155  329230460
40       NaN  3292400169  329240062
41       NaN  3292496248  329249667
42       NaN  3292555258  329255568
43       NaN  3292592266  329259269
44       NaN  3292688291  329268874
45       NaN  3292784302  329278482
46       NaN  3292880323  329288085
47       NaN  3292976371  329297685
48       NaN  3293072442  329307288
49       NaN  3293168486  329316890
50       NaN  3293195497  329319589
51       NaN  3293264508  329326490
52       NaN  3293360534  329336091
53       NaN  3293456580  329345688
54       NaN  3293552666  329355290
55       NaN  3293606703  329360692
56       NaN  3293648728  329364890
57       NaN  3293744763  329374492
58       NaN  3293840774  329384094
59       NaN  3293936825  329393692
60       NaN  3294032906  329403293
61       NaN  3294096956  329409696

[62 rows x 48 columns]
Finished  32930722
Finished  32930722
Completed Count -->  105
Started  1484096422
Started  1484096422
h148 Survivor 422 4096

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481024237', '1481106228', '1481152219', '1481270213', '1481280213', '1481408189', '1481476183', '1481536175', '1481664163', '1481740164', '1481920158', '1482048151', '1482088150', '1482112148', '1482208146', '1482304144', '1482400141', '1482496142', '1482555142', '1482592141', '1482688146', '1482784186', '1482880188', '1482976187', '1483072185', '1483168189', '1483195191', '1483264192', '1483360197', '1483456201', '1483552199', '1483606198', '1483648199', '1483671197', '1483744200', '1483760200', '1483810202', '1483840202', '1483936270', '1484032387', '1484096422']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_237' | NDM=21667 Nstar=47 Ngas=19>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_228' | NDM=22295 Nstar=47 Ngas=19>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_219' | NDM=22628 Nstar=47 Ngas=19>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_213' | NDM=23228 Nstar=47 Ngas=19>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_213' | NDM=23264 Nstar=47 Ngas=19>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_189' | NDM=23696 Nstar=47 Ngas=19>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_183' | NDM=23871 Nstar=47 Ngas=19>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_175' | NDM=24072 Nstar=47 Ngas=19>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_163' | NDM=24447 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_164' | NDM=24637 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_158' | NDM=25133 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_151' | NDM=25365 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_150' | NDM=25432 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_148' | NDM=25458 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_146' | NDM=25576 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_144' | NDM=25571 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_141' | NDM=25553 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_142' | NDM=25413 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_142' | NDM=25241 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_141' | NDM=25034 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_146' | NDM=23199 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_186' | NDM=16471 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_188' | NDM=15075 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_187' | NDM=15506 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_185' | NDM=14928 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_189' | NDM=14217 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_191' | NDM=14011 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_192' | NDM=13544 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_197' | NDM=13066 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_201' | NDM=12759 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_199' | NDM=12518 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_198' | NDM=12406 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_199' | NDM=12317 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_197' | NDM=12260 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_200' | NDM=12117 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_200' | NDM=12077 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_202' | NDM=11856 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_202' | NDM=11608 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_270' | NDM=8763 Nstar=47 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_387' | NDM=5674 Nstar=46 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_422' | NDM=5246 Nstar=45 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481024237', '1481106228', '1481152219', '1481270213', '1481280213', '1481408189', '1481476183', '1481536175', '1481664163', '1481740164', '1481920158', '1482048151', '1482088150', '1482112148', '1482208146', '1482304144', '1482400141', '1482496142', '1482555142', '1482592141', '1482688146', '1482784186', '1482880188', '1482976187', '1483072185', '1483168189', '1483195191', '1483264192', '1483360197', '1483456201', '1483552199', '1483606198', '1483648199', '1483671197', '1483744200', '1483760200', '1483810202', '1483840202', '1483936270', '1484032387', '1484096422']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

     14814089  148153610  14829762     ...       14840966  148409663  \
0           0          0         0     ...              0          0
1           0          0         0     ...              0          0
2           0          0         0     ...              0          0
3           0          0         0     ...              0          0
4           0          0         0     ...              0          0
5           0          0         0     ...              0          0
6           0          0         0     ...              0          0
7           0          0         0     ...              0          0
8           0          0         0     ...              0          0
9           0          0         0     ...              0          0
10          0          0         0     ...              0          0
11          0          0         0     ...              0          0
12          0          0         0     ...              0          0
13          0          0         0     ...              0          0
14          0          0         0     ...              0          0
15          0          0         0     ...              0          0
16          0          0         0     ...              0          0
17  148102414  148102415  14810242     ...      148102412  148102483
18  148110612  148110613  14811062     ...       14811069  148110677
19  148115210  148115211  14811522     ...       14811529  148115273
20  148127011  148127012  14812702     ...      148127010  148127071
21  148128010  148128011  14812802     ...       14812809  148128070
22   14814089  148140810  14814082     ...       14814088  148140862
23   14814761  148147616  14814762     ...       14814768  148147669
24   14815361  148153610  14815362     ...       14815368  148153669
25   14816641   14816641  14816642     ...       14816648  148166469
26   14817401   14817401  14817402     ...       14817408  148174064
27   14819201   14819201  14819202     ...       14819208  148192064
28   14820481   14820481  14820482     ...       14820488  148204862
29   14820881   14820881  14820882     ...       14820888  148208862
30   14821121   14821121  14821122     ...       14821128  148211261
31   14822081   14822081  14822082     ...       14822088  148220860
32   14823041   14823041  14823042     ...       14823048  148230461
33   14824001   14824001  14824002     ...       14824008  148240060
34   14824961   14824961  14824962     ...       14824968  148249665
35   14825551   14825551  14825552     ...       14825558  148255565
36   14825921   14825921  14825922     ...       14825928  148259265
37   14826881   14826881  14826882     ...       14826888  148268866
38   14827841   14827841  14827842     ...       14827848  148278465
39   14828801   14828801  14828802     ...       14828808  148288064
40   14829761   14829761  14829762     ...       14829768  148297666
41   14830721   14830721  14830721     ...       14830726  148307267
42   14831681   14831681  14831681     ...       14831688  148316866
43   14831951   14831951  14831951     ...       14831958  148319567
44   14832641   14832641  14832641     ...       14832648  148326468
45   14833601   14833601  14833601     ...       14833607  148336067
46   14834561   14834561  14834561     ...       14834567  148345667
47   14835521   14835521  14835521     ...       14835526  148355266
48   14836061   14836061  14836061     ...       14836066  148360668
49   14836481   14836481  14836481     ...       14836486  148364866
50   14836711   14836711  14836711     ...       14836716  148367167
51   14837441   14837441  14837441     ...       14837446  148374466
52   14837601   14837601  14837601     ...       14837606  148376066
53   14838101   14838101  14838101     ...       14838106  148381065
54   14838401   14838401  14838401     ...       14838406  148384064
55   14839361   14839361  14839361     ...       14839366  148393663
56   14840321   14840321  14840321     ...       14840326  148403262
57   14840961   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0
5             0           0
6             0           0
7             0           0
8             0           0
9             0           0
10            0           0
11            0           0
12            0           0
13            0           0
14            0           0
15            0           0
16            0           0
17            0           0
18            0           0
19            0           0
20            0           0
21            0           0
22            0           0
23            0           0
24            0           0
25            0  1481664583
26            0  1481740675
27            0  1481920723
28            0  1482048709
29  14820883070  1482088716
30  14821123108  1482112721
31  14822083288  1482208764
32  14823043356  1482304820
33  14824003391  1482400761
34  14824964889  1482496764
35  14825555134  1482555761
36  14825925307  1482592774
37  14826885446  1482688844
38  14827845472  1482784888
39  14828805569  1482880871
40  14829766423  1482976861
41  14830726494  1483072837
42  14831686490  1483168827
43  14831956438  1483195823
44  14832646491  1483264814
45  14833606420  1483360815
46  14834566949  1483456812
47  14835527642  1483552798
48  14836067699  1483606789
49  14836487660  1483648782
50  14836717573  1483671780
51  14837447690  1483744767
52  14837607621  1483760767
53  14838107661  1483810759
54  14838407640  1483840752
55  14839367781  1483936756
56  14840328859  1484032786
57  14840968565  1484096857

[58 rows x 78 columns]
Finished  1484096422
Finished  1484096422
Completed Count -->  106
Started  32940969
Started  32940969
h329 Survivor 9 4096

[0, 0, 0, '329013924', '329018822', '329019220', '329022523', '329027522', '329028820', '329034720', '329038419', '329045717', '329048017', '329057615', '329063714', '329067212', '329076810', '329077710', '32908649', '329096010', '329097410', '329105610', '329110610', '32911529', '32912488', '32912708', '32913446', '32914405', '32914765', '32915365', '32916325', '32917284', '32917404', '32918244', '32919204', '32920164', '32920884', '32921124', '32922084', '32923044', '32924004', '32924964', '32925553', '32925924', '32926884', '32927844', '32928804', '32929764', '32930724', '32931683', '32931954', '32932644', '32933604', '32934563', '32935523', '32936063', '32936483', '32937442', '32938402', '32939362', '32940329', '32940969']
[-1.0 -1.0 -1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_24' | NDM=10657 Nstar=2 Ngas=10030>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_22' | NDM=27119 Nstar=368 Ngas=17688>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_20' | NDM=28123 Nstar=376 Ngas=18249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_23' | NDM=35615 Nstar=547 Ngas=24613>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_22' | NDM=48628 Nstar=976 Ngas=37992>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_20' | NDM=56675 Nstar=1178 Ngas=44749>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_20' | NDM=73534 Nstar=2270 Ngas=65507>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_19' | NDM=93673 Nstar=3550 Ngas=85949>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_17' | NDM=127860 Nstar=8115 Ngas=114459>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_17' | NDM=132585 Nstar=8552 Ngas=113793>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_15' | NDM=141233 Nstar=10995 Ngas=107866>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_14' | NDM=135460 Nstar=12405 Ngas=98206>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_12' | NDM=134027 Nstar=12985 Ngas=93036>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_10' | NDM=142737 Nstar=13915 Ngas=78730>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_10' | NDM=144061 Nstar=13915 Ngas=78980>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_9' | NDM=153624 Nstar=14331 Ngas=80730>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_10' | NDM=172431 Nstar=14630 Ngas=85242>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_10' | NDM=174269 Nstar=14630 Ngas=84861>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_10' | NDM=183707 Nstar=16482 Ngas=72984>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_10' | NDM=189281 Nstar=16496 Ngas=58839>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_9' | NDM=192813 Nstar=16496 Ngas=62027>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_8' | NDM=195989 Nstar=16775 Ngas=57491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_8' | NDM=196467 Nstar=16775 Ngas=56978>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_6' | NDM=197323 Nstar=16776 Ngas=57613>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_5' | NDM=198647 Nstar=17115 Ngas=54910>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_5' | NDM=201116 Nstar=17152 Ngas=51817>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_5' | NDM=207069 Nstar=17416 Ngas=45265>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_5' | NDM=217766 Nstar=17602 Ngas=47675>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_4' | NDM=277481 Nstar=23934 Ngas=77519>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_4' | NDM=298955 Nstar=26202 Ngas=92716>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_4' | NDM=343740 Nstar=27236 Ngas=137659>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_4' | NDM=369613 Nstar=28578 Ngas=155042>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_4' | NDM=375688 Nstar=29737 Ngas=153214>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_4' | NDM=392941 Nstar=30297 Ngas=151395>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_4' | NDM=397574 Nstar=30345 Ngas=149534>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_4' | NDM=396974 Nstar=30802 Ngas=142633>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_4' | NDM=385703 Nstar=31158 Ngas=146680>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_4' | NDM=377592 Nstar=31748 Ngas=146390>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_4' | NDM=374379 Nstar=32483 Ngas=147089>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_3' | NDM=373725 Nstar=34015 Ngas=142849>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_4' | NDM=372968 Nstar=34151 Ngas=123874>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_4' | NDM=374525 Nstar=34794 Ngas=109919>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_4' | NDM=378053 Nstar=35135 Ngas=115982>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_4' | NDM=381750 Nstar=35733 Ngas=121007>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_4' | NDM=384976 Nstar=36400 Ngas=121479>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_4' | NDM=387726 Nstar=37044 Ngas=119763>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_3' | NDM=390854 Nstar=37700 Ngas=117103>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_4' | NDM=391850 Nstar=37839 Ngas=115694>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_4' | NDM=393648 Nstar=38447 Ngas=106260>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_4' | NDM=396329 Nstar=38920 Ngas=95876>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_3' | NDM=398499 Nstar=39504 Ngas=95147>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_3' | NDM=398462 Nstar=40080 Ngas=92026>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_3' | NDM=397848 Nstar=40387 Ngas=86406>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_3' | NDM=396947 Nstar=40571 Ngas=82025>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_2' | NDM=392301 Nstar=41117 Ngas=72101>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_2' | NDM=384925 Nstar=41599 Ngas=63932>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_2' | NDM=339158 Nstar=42206 Ngas=63196>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_9' | NDM=60729 Nstar=41370 Ngas=46104>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_9' | NDM=75287 Nstar=41648 Ngas=38464>]
[0, 0, 0, '329013924', '329018822', '329019220', '329022523', '329027522', '329028820', '329034720', '329038419', '329045717', '329048017', '329057615', '329063714', '329067212', '329076810', '329077710', '32908649', '329096010', '329097410', '329105610', '329110610', '32911529', '32912488', '32912708', '32913446', '32914405', '32914765', '32915365', '32916325', '32917284', '32917404', '32918244', '32919204', '32920164', '32920884', '32921124', '32922084', '32923044', '32924004', '32924964', '32925553', '32925924', '32926884', '32927844', '32928804', '32929764', '32930724', '32931683', '32931954', '32932644', '32933604', '32934563', '32935523', '32936063', '32936483', '32937442', '32938402', '32939362', '32940329', '32940969']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71           0           0           0          0          0
1         96   329009638   329009662    32900969          0          0
2        108   329010830   329010856   329010810          0  329010836
3        139   329013986  3290139151   329013963  329013935  329013959
4        188  3290188153  3290188114  3290188111  329018827  329018833
5        192    32901921  3290192110  3290192111  329019225  329019230
6        225    32902251    32902251    32902251   32902251   32902251
7        275    32902751    32902751    32902751   32902751   32902751
8        288    32902881    32902881    32902881   32902881   32902881
9        347    32903471    32903471    32903471   32903471   32903471
10       384    32903841    32903841    32903841   32903841   32903841
11       457    32904571    32904571    32904571   32904571   32904571
12       480    32904801    32904801    32904801   32904801   32904801
13       576    32905761    32905761    32905761   32905761   32905761
14       637    32906371    32906371    32906371   32906371   32906371
15       672    32906721    32906721    32906721   32906721   32906721
16       768    32907681    32907681    32907681   32907681   32907681
17       777    32907771    32907771    32907771   32907771   32907771
18       864    32908641    32908641    32908641   32908641   32908641
19       960    32909601    32909601    32909601   32909601   32909601
20       974    32909741    32909741    32909741   32909741   32909741
21      1056    32910561    32910561    32910561   32910561   32910561
22      1106    32911061    32911061    32911061   32911061   32911061
23      1152    32911521    32911521    32911521   32911521   32911521
24      1248    32912481    32912481    32912481   32912481   32912481
25      1270    32912701    32912701    32912701   32912701   32912701
26      1344    32913441    32913441    32913441   32913441   32913441
27      1440    32914401    32914401    32914401   32914401   32914401
28      1476    32914761    32914761    32914761   32914761   32914761
29      1536    32915361    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740    32917401    32917401    32917401   32917401   32917401
33      1824    32918241    32918241    32918241   32918241   32918241
34      1920    32919201    32919201    32919201   32919201   32919201
35      2016    32920161    32920161    32920161   32920161   32920161
36      2088    32920881    32920881    32920881   32920881   32920881
37      2112    32921121    32921121    32921121   32921121   32921121
38      2208    32922081    32922081    32922081   32922081   32922081
39      2304    32923041    32923041    32923041   32923041   32923041
40      2400    32924001    32924001    32924001   32924001   32924001
41      2496    32924961    32924961    32924961   32924961   32924961
42      2555    32925551    32925551    32925551   32925551   32925551
43      2592    32925921    32925921    32925921   32925921   32925921
44      2688    32926881    32926881    32926881   32926881   32926881
45      2784    32927841    32927841    32927841   32927841   32927841
46      2880    32928801    32928801    32928801   32928801   32928801
47      2976    32929761    32929761    32929761   32929761   32929761
48      3072    32930721    32930721    32930721   32930721   32930721
49      3168    32931681    32931681    32931681   32931681   32931681
50      3195    32931951    32931951    32931951   32931951   32931951
51      3264    32932641    32932641    32932641   32932641   32932641
52      3360    32933601    32933601    32933601   32933601   32933601
53      3456    32934561    32934561    32934561   32934561   32934561
54      3552    32935521    32935521    32935521   32935521   32935521
55      3606    32936061    32936061    32936061   32936061   32936061
56      3648    32936481    32936481    32936481   32936481   32936481
57      3744    32937441    32937441    32937441   32937441   32937441
58      3840    32938401    32938401    32938401   32938401   32938401
59      3936    32939361    32939361    32939361   32939361   32939361
60      4032    32940321    32940321    32940321   32940321   32940321
61      4096    32940961    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0           0
1    3290096221           0  32900961020   329009640           0  3290096124
2    3290108234           0  32901081471   329010844           0  3290108114
3    3290139545           0   3290139119  3290139138           0  3290139261
4    3290188538           0    329018879  3290188197           0  3290188285
5    3290192554           0    329019278  3290192195           0  3290192291
6    3290225544           0    329022582  3290225210  3290225189  3290225307
7    3290275579           0    329027574  3290275196  3290275121  3290275307
8    3290288619           0    329028872  3290288186  3290288109  3290288300
9    3290347581           0    329034758  3290347164   329034764  3290347281
10   3290384579           0    329038460  3290384127   329038446  3290384281
11   3290457588           0    329045751  3290457104   329045736  3290457298
12   3290480583           0    329048049  3290480102   329048032  3290480324
13   3290576536           0    329057638   329057696   329057626  3290576383
14   3290637554           0    329063738  3290637104   329063727  3290637432
15   3290672559           0    329067235  3290672100   329067221  3290672445
16   3290768567           0    329076836   329076886   329076824  3290768468
17   3290777570           0    329077736   329077786   329077723  3290777467
18   3290864555           0    329086434   329086477   329086420  3290864451
19   3290960543           0    329096033   329096073   329096021  3290960483
20   3290974534           0    329097431   329097473   329097420  3290974478
21   3291056562           0    329105639   329105668   329105622  3291056516
22   3291106741           0    329110652   329110666   329110622  3291106605
23   3291152887           0    329115265   329115271   329115223  3291152630
24  32912481314           0    329124869   329124868   329124825  3291248663
25   3291270963           0    329127068   329127066   329127026  3291270664
26   3291344954           0    329134471   329134461   329134424  3291344669
27   3291440948           0    329144073   329144058   329144021  3291440664
28   3291476953           0    329147674   329147661   329147621  3291476662
29   3291536954           0    329153675   329153662   329153634  3291536656
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043  3291740718
33  32918241363           0    329182478   329182462   329182445  3291824721
34  32919201657           0    329192075   329192057   329192047  3291920729
35  32920161763           0    329201673   329201653   329201648  3292016729
36  32920881809           0   3292088210   329208852   329208849  3292088728
37  32921121823           0   3292112188   329211251   329211250  3292112723
38  32922081833           0   3292208214   329220850   329220848  3292208722
39  32923041843           0   3292304234   329230450   329230449  3292304732
40  32924001879           0   3292400261   329240048   329240050  3292400787
41  32924962122           0   3292496271   329249648   329249650  3292496824
42  32925552182           0   3292555278   329255548   329255551  3292555828
43  32925922176           0   3292592282   329259249   329259252  3292592829
44  32926882164           0   3292688286   329268849   329268853  3292688812
45  32927842152           0   3292784291   329278449   329278454  3292784818

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148268811976', '148278412202', '148288012871', '148297612628', '148307212472', '148316812164', '148319512142', '148326412152', '148336012336', '148345612640', '148355212791', '148360612740', '148364812583', '148367112710', '148374412596', '148376012612', '148381012417', '148384012481', '148393612335', '148403212183', '148409612211']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_11976' | NDM=0 Nstar=179 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_12202' | NDM=0 Nstar=171 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_12871' | NDM=0 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_12628' | NDM=0 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_12472' | NDM=0 Nstar=156 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_12164' | NDM=0 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_12142' | NDM=0 Nstar=157 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_12152' | NDM=0 Nstar=154 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_12336' | NDM=0 Nstar=148 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_12640' | NDM=0 Nstar=141 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_12791' | NDM=0 Nstar=137 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_12740' | NDM=0 Nstar=136 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_12583' | NDM=1 Nstar=136 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_12710' | NDM=0 Nstar=135 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_12596' | NDM=0 Nstar=134 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_12612' | NDM=0 Nstar=134 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_12417' | NDM=0 Nstar=135 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_12481' | NDM=0 Nstar=134 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_12335' | NDM=0 Nstar=133 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_12183' | NDM=0 Nstar=134 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_12211' | NDM=0 Nstar=132 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148268811976', '148278412202', '148288012871', '148297612628', '148307212472', '148316812164', '148319512142', '148326412152', '148336012336', '148345612640', '148355212791', '148360612740', '148364812583', '148367112710', '148374412596', '148376012612', '148381012417', '148384012481', '148393612335', '148403212183', '148409612211']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

     14814089  148153610  14829762     ...       14840966  148409663  \
0           0          0         0     ...              0          0
1           0          0         0     ...              0          0
2           0          0         0     ...              0          0
3           0          0         0     ...              0          0
4           0          0         0     ...              0          0
5           0          0         0     ...              0          0
6           0          0         0     ...              0          0
7           0          0         0     ...              0          0
8           0          0         0     ...              0          0
9           0          0         0     ...              0          0
10          0          0         0     ...              0          0
11          0          0         0     ...              0          0
12          0          0         0     ...              0          0
13          0          0         0     ...              0          0
14          0          0         0     ...              0          0
15          0          0         0     ...              0          0
16          0          0         0     ...              0          0
17  148102414  148102415  14810242     ...      148102412  148102483
18  148110612  148110613  14811062     ...       14811069  148110677
19  148115210  148115211  14811522     ...       14811529  148115273
20  148127011  148127012  14812702     ...      148127010  148127071
21  148128010  148128011  14812802     ...       14812809  148128070
22   14814089  148140810  14814082     ...       14814088  148140862
23   14814761  148147616  14814762     ...       14814768  148147669
24   14815361  148153610  14815362     ...       14815368  148153669
25   14816641   14816641  14816642     ...       14816648  148166469
26   14817401   14817401  14817402     ...       14817408  148174064
27   14819201   14819201  14819202     ...       14819208  148192064
28   14820481   14820481  14820482     ...       14820488  148204862
29   14820881   14820881  14820882     ...       14820888  148208862
30   14821121   14821121  14821122     ...       14821128  148211261
31   14822081   14822081  14822082     ...       14822088  148220860
32   14823041   14823041  14823042     ...       14823048  148230461
33   14824001   14824001  14824002     ...       14824008  148240060
34   14824961   14824961  14824962     ...       14824968  148249665
35   14825551   14825551  14825552     ...       14825558  148255565
36   14825921   14825921  14825922     ...       14825928  148259265
37   14826881   14826881  14826882     ...       14826888  148268866
38   14827841   14827841  14827842     ...       14827848  148278465
39   14828801   14828801  14828802     ...       14828808  148288064
40   14829761   14829761  14829762     ...       14829768  148297666
41   14830721   14830721  14830721     ...       14830726  148307267
42   14831681   14831681  14831681     ...       14831688  148316866
43   14831951   14831951  14831951     ...       14831958  148319567
44   14832641   14832641  14832641     ...       14832648  148326468
45   14833601   14833601  14833601     ...       14833607  148336067
46   14834561   14834561  14834561     ...       14834567  148345667
47   14835521   14835521  14835521     ...       14835526  148355266
48   14836061   14836061  14836061     ...       14836066  148360668
49   14836481   14836481  14836481     ...       14836486  148364866
50   14836711   14836711  14836711     ...       14836716  148367167
51   14837441   14837441  14837441     ...       14837446  148374466
52   14837601   14837601  14837601     ...       14837606  148376066
53   14838101   14838101  14838101     ...       14838106  148381065
54   14838401   14838401  14838401     ...       14838406  148384064
55   14839361   14839361  14839361     ...       14839366  148393663
56   14840321   14840321  14840321     ...       14840326  148403262
57   14840961   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0
5             0           0
6             0           0
7             0           0
8             0           0
9             0           0
10            0           0
11            0           0
12            0           0
13            0           0
14            0           0
15            0           0
16            0           0
17            0           0
18            0           0
19            0           0
20            0           0
21            0           0
22            0           0
23            0           0
24            0           0
25            0  1481664583
26            0  1481740675
27            0  1481920723
28            0  1482048709
29  14820883070  1482088716
30  14821123108  1482112721
31  14822083288  1482208764
32  14823043356  1482304820
33  14824003391  1482400761
34  14824964889  1482496764
35  14825555134  1482555761
36  14825925307  1482592774
37  14826885446  1482688844
38  14827845472  1482784888
39  14828805569  1482880871
40  14829766423  1482976861
41  14830726494  1483072837
42  14831686490  1483168827
43  14831956438  1483195823
44  14832646491  1483264814
45  14833606420  1483360815
46  14834566949  1483456812
47  14835527642  1483552798
48  14836067699  1483606789
49  14836487660  1483648782
50  14836717573  1483671780
51  14837447690  1483744767
52  14837607621  1483760767
53  14838107661  1483810759
54  14838407640  1483840752
55  14839367781  1483936756
56  14840328859  1484032786
57  14840968565  1484096857

[58 rows x 78 columns]
Finished  148409612211
Finished  148409612211
Completed Count -->  108
Started  32909747
Started  32909747
h329 Zombie 7 0974

['329007180', '329009659', '329010835', '329013981', '329018857', '329019256', '329022538', '329027532', '329028828', '329034716', '329038413', '32904574', '32904804', '32905768', '32906378', '32906727', '32907687', '32907777', '32908645', '32909607', '32909747', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[ <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000071/halo_80' | NDM=449 Nstar=0 Ngas=335>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096/halo_59' | NDM=1085 Nstar=0 Ngas=524>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108/halo_35' | NDM=1707 Nstar=0 Ngas=969>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_81' | NDM=4063 Nstar=0 Ngas=2515>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_57' | NDM=10378 Nstar=27 Ngas=6615>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_56' | NDM=11118 Nstar=30 Ngas=7102>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_38' | NDM=22398 Nstar=53 Ngas=14505>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_32' | NDM=34954 Nstar=487 Ngas=27466>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_28' | NDM=45715 Nstar=529 Ngas=37393>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_16' | NDM=110669 Nstar=1501 Ngas=95724>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_13' | NDM=148202 Nstar=3266 Ngas=133291>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_4' | NDM=505458 Nstar=43117 Ngas=363821>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_4' | NDM=519872 Nstar=44273 Ngas=364945>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_8' | NDM=410660 Nstar=62064 Ngas=307535>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_8' | NDM=408708 Nstar=65320 Ngas=306451>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_7' | NDM=430393 Nstar=68056 Ngas=317450>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_7' | NDM=514654 Nstar=71215 Ngas=390617>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_7' | NDM=523337 Nstar=71568 Ngas=404386>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_5' | NDM=617616 Nstar=80677 Ngas=522607>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_7' | NDM=422445 Nstar=95896 Ngas=418810>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_7' | NDM=347391 Nstar=99010 Ngas=386889>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1' | NDM=15578696 Nstar=10217161 Ngas=11755160>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1' | NDM=15747259 Nstar=11784296 Ngas=11968198>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1' | NDM=15761360 Nstar=13147640 Ngas=12285340>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1' | NDM=15832293 Nstar=16238307 Ngas=12845015>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1' | NDM=15990494 Nstar=17157603 Ngas=12930029>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1' | NDM=17922263 Nstar=20611248 Ngas=14418911>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1' | NDM=20220937 Nstar=24755716 Ngas=15683385>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1' | NDM=20568424 Nstar=26701663 Ngas=15670524>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1' | NDM=21292522 Nstar=29070320 Ngas=16200299>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1' | NDM=22138471 Nstar=34143108 Ngas=16098369>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1' | NDM=22233114 Nstar=37948971 Ngas=16217261>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1' | NDM=22265580 Nstar=38395660 Ngas=16249600>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1' | NDM=22541017 Nstar=41934879 Ngas=16143723>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1' | NDM=23087646 Nstar=46137673 Ngas=15803476>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1' | NDM=23617232 Nstar=50351876 Ngas=15643527>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1' | NDM=24221915 Nstar=53530614 Ngas=15566115>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1' | NDM=24513553 Nstar=54733955 Ngas=15453339>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1' | NDM=26676353 Nstar=59100003 Ngas=16082599>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1' | NDM=29354421 Nstar=64311453 Ngas=16874211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1' | NDM=31464533 Nstar=68631869 Ngas=16998639>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1' | NDM=32730524 Nstar=72629063 Ngas=17093857>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1' | NDM=33576743 Nstar=76168219 Ngas=16582991>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1' | NDM=34007948 Nstar=77829519 Ngas=16271248>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1' | NDM=34817467 Nstar=82227069 Ngas=16133249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1' | NDM=35279749 Nstar=86891324 Ngas=15727574>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1' | NDM=34968677 Nstar=91010100 Ngas=14700620>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1' | NDM=34685343 Nstar=94725659 Ngas=13794122>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1' | NDM=34411771 Nstar=98430465 Ngas=12965040>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
[0, '329009659', '329010835', '329013981', '329018857', '329019256', '329022538', '329027532', '329028828', '329034716', '329038413', '32904574', '32904804', '32905768', '32906378', '32906727', '32907687', '32907777', '32908645', '32909607', '32909747', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71           0           0           0          0          0
1         96   329009638   329009662    32900969          0          0
2        108   329010830   329010856   329010810          0  329010836
3        139   329013986  3290139151   329013963  329013935  329013959
4        188  3290188153  3290188114  3290188111  329018827  329018833
5        192    32901921  3290192110  3290192111  329019225  329019230
6        225    32902251    32902251    32902251   32902251   32902251
7        275    32902751    32902751    32902751   32902751   32902751
8        288    32902881    32902881    32902881   32902881   32902881
9        347    32903471    32903471    32903471   32903471   32903471
10       384    32903841    32903841    32903841   32903841   32903841
11       457    32904571    32904571    32904571   32904571   32904571
12       480    32904801    32904801    32904801   32904801   32904801
13       576    32905761    32905761    32905761   32905761   32905761
14       637    32906371    32906371    32906371   32906371   32906371
15       672    32906721    32906721    32906721   32906721   32906721
16       768    32907681    32907681    32907681   32907681   32907681
17       777    32907771    32907771    32907771   32907771   32907771
18       864    32908641    32908641    32908641   32908641   32908641
19       960    32909601    32909601    32909601   32909601   32909601
20       974    32909741    32909741    32909741   32909741   32909741
21      1056    32910561    32910561    32910561   32910561   32910561
22      1106    32911061    32911061    32911061   32911061   32911061
23      1152    32911521    32911521    32911521   32911521   32911521
24      1248    32912481    32912481    32912481   32912481   32912481
25      1270    32912701    32912701    32912701   32912701   32912701
26      1344    32913441    32913441    32913441   32913441   32913441
27      1440    32914401    32914401    32914401   32914401   32914401
28      1476    32914761    32914761    32914761   32914761   32914761
29      1536    32915361    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740    32917401    32917401    32917401   32917401   32917401
33      1824    32918241    32918241    32918241   32918241   32918241
34      1920    32919201    32919201    32919201   32919201   32919201
35      2016    32920161    32920161    32920161   32920161   32920161
36      2088    32920881    32920881    32920881   32920881   32920881
37      2112    32921121    32921121    32921121   32921121   32921121
38      2208    32922081    32922081    32922081   32922081   32922081
39      2304    32923041    32923041    32923041   32923041   32923041
40      2400    32924001    32924001    32924001   32924001   32924001
41      2496    32924961    32924961    32924961   32924961   32924961
42      2555    32925551    32925551    32925551   32925551   32925551
43      2592    32925921    32925921    32925921   32925921   32925921
44      2688    32926881    32926881    32926881   32926881   32926881
45      2784    32927841    32927841    32927841   32927841   32927841
46      2880    32928801    32928801    32928801   32928801   32928801
47      2976    32929761    32929761    32929761   32929761   32929761
48      3072    32930721    32930721    32930721   32930721   32930721
49      3168    32931681    32931681    32931681   32931681   32931681
50      3195    32931951    32931951    32931951   32931951   32931951
51      3264    32932641    32932641    32932641   32932641   32932641
52      3360    32933601    32933601    32933601   32933601   32933601
53      3456    32934561    32934561    32934561   32934561   32934561
54      3552    32935521    32935521    32935521   32935521   32935521
55      3606    32936061    32936061    32936061   32936061   32936061
56      3648    32936481    32936481    32936481   32936481   32936481
57      3744    32937441    32937441    32937441   32937441   32937441
58      3840    32938401    32938401    32938401   32938401   32938401
59      3936    32939361    32939361    32939361   32939361   32939361
60      4032    32940321    32940321    32940321   32940321   32940321
61      4096    32940961    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0           0
1    3290096221           0  32900961020   329009640           0  3290096124
2    3290108234           0  32901081471   329010844           0  3290108114
3    3290139545           0   3290139119  3290139138           0  3290139261
4    3290188538           0    329018879  3290188197           0  3290188285
5    3290192554           0    329019278  3290192195           0  3290192291
6    3290225544           0    329022582  3290225210  3290225189  3290225307
7    3290275579           0    329027574  3290275196  3290275121  3290275307
8    3290288619           0    329028872  3290288186  3290288109  3290288300
9    3290347581           0    329034758  3290347164   329034764  3290347281
10   3290384579           0    329038460  3290384127   329038446  3290384281
11   3290457588           0    329045751  3290457104   329045736  3290457298
12   3290480583           0    329048049  3290480102   329048032  3290480324
13   3290576536           0    329057638   329057696   329057626  3290576383
14   3290637554           0    329063738  3290637104   329063727  3290637432
15   3290672559           0    329067235  3290672100   329067221  3290672445
16   3290768567           0    329076836   329076886   329076824  3290768468
17   3290777570           0    329077736   329077786   329077723  3290777467
18   3290864555           0    329086434   329086477   329086420  3290864451
19   3290960543           0    329096033   329096073   329096021  3290960483
20   3290974534           0    329097431   329097473   329097420  3290974478
21   3291056562           0    329105639   329105668   329105622  3291056516
22   3291106741           0    329110652   329110666   329110622  3291106605
23   3291152887           0    329115265   329115271   329115223  3291152630
24  32912481314           0    329124869   329124868   329124825  3291248663
25   3291270963           0    329127068   329127066   329127026  3291270664
26   3291344954           0    329134471   329134461   329134424  3291344669
27   3291440948           0    329144073   329144058   329144021  3291440664
28   3291476953           0    329147674   329147661   329147621  3291476662
29   3291536954           0    329153675   329153662   329153634  3291536656
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043  3291740718
33  32918241363           0    329182478   329182462   329182445  3291824721
34  32919201657           0    329192075   329192057   329192047  3291920729
35  32920161763           0    329201673   329201653   329201648  3292016729
36  32920881809           0   3292088210   329208852   329208849  3292088728
37  32921121823           0   3292112188   329211251   329211250  3292112723

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14814085871', '14814765742', '14815365725', '14816645601', '14817405586', '14819205381', '14820485260', '14820885245', '14821125232', '14822085214', '14823045122', '14824005038', '14824964957', '14825554891', '14825924827', '14826884736', '14827844612', '14828804530', '14829764453', '14830724415', '14831684425', '14831954389', '14832644358', '14833604295', '14834564247', '14835524179', '14836064156', '14836484143', '14836714142', '14837444170', '14837604170', '14838104170', '14838404165', '14839364091', '14840324058', '14840964022']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_5871' | NDM=531 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_5742' | NDM=531 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_5725' | NDM=523 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_5601' | NDM=519 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_5586' | NDM=517 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_5381' | NDM=515 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_5260' | NDM=513 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_5245' | NDM=510 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_5232' | NDM=509 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_5214' | NDM=501 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_5122' | NDM=499 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_5038' | NDM=496 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_4957' | NDM=494 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_4891' | NDM=492 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_4827' | NDM=493 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_4736' | NDM=492 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_4612' | NDM=492 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_4530' | NDM=492 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_4453' | NDM=491 Nstar=24 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_4415' | NDM=484 Nstar=23 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_4425' | NDM=475 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_4389' | NDM=476 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_4358' | NDM=473 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_4295' | NDM=471 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_4247' | NDM=470 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_4179' | NDM=468 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_4156' | NDM=468 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_4143' | NDM=465 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_4142' | NDM=462 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_4170' | NDM=453 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_4170' | NDM=451 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_4170' | NDM=447 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_4165' | NDM=447 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_4091' | NDM=447 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_4058' | NDM=445 Nstar=22 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_4022' | NDM=445 Nstar=22 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14814085871', '14814765742', '14815365725', '14816645601', '14817405586', '14819205381', '14820485260', '14820885245', '14821125232', '14822085214', '14823045122', '14824005038', '14824964957', '14825554891', '14825924827', '14826884736', '14827844612', '14828804530', '14829764453', '14830724415', '14831684425', '14831954389', '14832644358', '14833604295', '14834564247', '14835524179', '14836064156', '14836484143', '14836714142', '14837444170', '14837604170', '14838104170', '14838404165', '14839364091', '14840324058', '14840964022']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0       NaN          0         0          0         0
1        108          0       NaN          0         0          0         0
2        128          0       NaN          0         0          0         0
3        139          0       NaN          0         0          0         0
4        188          0       NaN          0         0          0         0
5        225          0       NaN          0         0          0         0
6        256          0       NaN          0         0          0         0
7        275          0       NaN          0         0          0         0
8        347          0       NaN          0         0          0         0
9        384          0       NaN          0         0          0         0
10       457          0       NaN          0         0          0         0
11       512          0       NaN          0         0          0         0
12       637          0       NaN          0         0          0         0
13       640          0       NaN          0         0          0         0
14       777          0       NaN          0         0          0         0
15       896          0       NaN          0         0          0         0
16       974          0       NaN          0         0          0         0
17      1024  148102411       NaN  148102422  14810243  148102416  14810243
18      1106  148110610       NaN  148110620  14811063  148110614  14811063
19      1152   14811521       NaN  148115218  14811523  148115212  14811523
20      1270   14812701       NaN   14812701  14812709  148127014  14812703
21      1280   14812801       NaN   14812801  14812801  148128013  14812804
22      1408   14814081       NaN   14814081  14814081   14814081  14814081
23      1476   14814761       NaN   14814761  14814761   14814761  14814761
24      1536   14815361       NaN   14815361  14815361   14815361  14815361
25      1664   14816641       NaN   14816641  14816641   14816641  14816641
26      1740   14817401       NaN   14817401  14817401   14817401  14817401
27      1920   14819201       NaN   14819201  14819201   14819201  14819201
28      2048   14820481       NaN   14820481  14820481   14820481  14820481
29      2088   14820881       NaN   14820881  14820881   14820881  14820881
30      2112   14821121       NaN   14821121  14821121   14821121  14821121
31      2208   14822081       NaN   14822081  14822081   14822081  14822081
32      2304   14823041       NaN   14823041  14823041   14823041  14823041
33      2400   14824001       NaN   14824001  14824001   14824001  14824001
34      2496   14824961       NaN   14824961  14824961   14824961  14824961
35      2555   14825551       NaN   14825551  14825551   14825551  14825551
36      2592   14825921       NaN   14825921  14825921   14825921  14825921
37      2688   14826881       NaN   14826881  14826881   14826881  14826881
38      2784   14827841       NaN   14827841  14827841   14827841  14827841
39      2880   14828801       NaN   14828801  14828801   14828801  14828801
40      2976   14829761       NaN   14829761  14829761   14829761  14829761
41      3072   14830721       NaN   14830721  14830721   14830721  14830721
42      3168   14831681       NaN   14831681  14831681   14831681  14831681
43      3195   14831951       NaN   14831951  14831951   14831951  14831951
44      3264   14832641       NaN   14832641  14832641   14832641  14832641
45      3360   14833601       NaN   14833601  14833601   14833601  14833601
46      3456   14834561       NaN   14834561  14834561   14834561  14834561
47      3552   14835521       NaN   14835521  14835521   14835521  14835521
48      3606   14836061       NaN   14836061  14836061   14836061  14836061
49      3648   14836481       NaN   14836481  14836481   14836481  14836481
50      3671   14836711       NaN   14836711  14836711   14836711  14836711
51      3744   14837441       NaN   14837441  14837441   14837441  14837441
52      3760   14837601       NaN   14837601  14837601   14837601  14837601
53      3810   14838101       NaN   14838101  14838101   14838101  14838101
54      3840   14838401       NaN   14838401  14838401   14838401  14838401
55      3936   14839361       NaN   14839361  14839361   14839361  14839361
56      4032   14840321       NaN   14840321  14840321   14840321  14840321
57      4096   14840961       NaN   14840961  14840961   14840961  14840961

     14814089  148153610  14829762     ...       14840966  148409663  \
0           0          0         0     ...              0          0
1           0          0         0     ...              0          0
2           0          0         0     ...              0          0
3           0          0         0     ...              0          0
4           0          0         0     ...              0          0
5           0          0         0     ...              0          0
6           0          0         0     ...              0          0
7           0          0         0     ...              0          0
8           0          0         0     ...              0          0
9           0          0         0     ...              0          0
10          0          0         0     ...              0          0
11          0          0         0     ...              0          0
12          0          0         0     ...              0          0
13          0          0         0     ...              0          0
14          0          0         0     ...              0          0
15          0          0         0     ...              0          0
16          0          0         0     ...              0          0
17  148102414  148102415  14810242     ...      148102412  148102483
18  148110612  148110613  14811062     ...       14811069  148110677
19  148115210  148115211  14811522     ...       14811529  148115273
20  148127011  148127012  14812702     ...      148127010  148127071
21  148128010  148128011  14812802     ...       14812809  148128070
22   14814089  148140810  14814082     ...       14814088  148140862
23   14814761  148147616  14814762     ...       14814768  148147669
24   14815361  148153610  14815362     ...       14815368  148153669
25   14816641   14816641  14816642     ...       14816648  148166469
26   14817401   14817401  14817402     ...       14817408  148174064
27   14819201   14819201  14819202     ...       14819208  148192064
28   14820481   14820481  14820482     ...       14820488  148204862
29   14820881   14820881  14820882     ...       14820888  148208862
30   14821121   14821121  14821122     ...       14821128  148211261
31   14822081   14822081  14822082     ...       14822088  148220860
32   14823041   14823041  14823042     ...       14823048  148230461
33   14824001   14824001  14824002     ...       14824008  148240060
34   14824961   14824961  14824962     ...       14824968  148249665
35   14825551   14825551  14825552     ...       14825558  148255565
36   14825921   14825921  14825922     ...       14825928  148259265
37   14826881   14826881  14826882     ...       14826888  148268866
38   14827841   14827841  14827842     ...       14827848  148278465
39   14828801   14828801  14828802     ...       14828808  148288064
40   14829761   14829761  14829762     ...       14829768  148297666
41   14830721   14830721  14830721     ...       14830726  148307267
42   14831681   14831681  14831681     ...       14831688  148316866
43   14831951   14831951  14831951     ...       14831958  148319567
44   14832641   14832641  14832641     ...       14832648  148326468
45   14833601   14833601  14833601     ...       14833607  148336067
46   14834561   14834561  14834561     ...       14834567  148345667
47   14835521   14835521  14835521     ...       14835526  148355266
48   14836061   14836061  14836061     ...       14836066  148360668
49   14836481   14836481  14836481     ...       14836486  148364866
50   14836711   14836711  14836711     ...       14836716  148367167
51   14837441   14837441  14837441     ...       14837446  148374466
52   14837601   14837601  14837601     ...       14837606  148376066
53   14838101   14838101  14838101     ...       14838106  148381065
54   14838401   14838401  14838401     ...       14838406  148384064
55   14839361   14839361  14839361     ...       14839366  148393663
56   14840321   14840321  14840321     ...       14840326  148403262
57   14840961   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0
5             0           0
6             0           0
7             0           0
8             0           0
9             0           0
10            0           0
11            0           0
12            0           0
13            0           0
14            0           0
15            0           0
16            0           0
17            0           0
18            0           0
19            0           0
20            0           0
21            0           0
22            0           0
23            0           0
24            0           0
25            0  1481664583
26            0  1481740675
27            0  1481920723
28            0  1482048709
29  14820883070  1482088716
30  14821123108  1482112721
31  14822083288  1482208764
32  14823043356  1482304820
33  14824003391  1482400761
34  14824964889  1482496764
35  14825555134  1482555761
36  14825925307  1482592774
37  14826885446  1482688844
38  14827845472  1482784888
39  14828805569  1482880871
40  14829766423  1482976861
41  14830726494  1483072837
42  14831686490  1483168827
43  14831956438  1483195823
44  14832646491  1483264814
45  14833606420  1483360815
46  14834566949  1483456812
47  14835527642  1483552798
48  14836067699  1483606789
49  14836487660  1483648782
50  14836717573  1483671780
51  14837447690  1483744767
52  14837607621  1483760767
53  14838107661  1483810759
54  14838407640  1483840752
55  14839367781  1483936756
56  14840328859  1484032786
57  14840968565  1484096857

[58 rows x 78 columns]
Finished  14840964022
Finished  14840964022
Completed Count -->  110
Started  14811066
Started  14811066
h148 Zombie 6 1106

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14810245', '14811066', '14811521', '14812701', '14812801', '14814081', '14814761', '14815361', '14816641', '14817401', '14819201', '14820481', '14820881', '14821121', '14822081', '14823041', '14824001', '14824961', '14825551', '14825921', '14826881', '14827841', '14828801', '14829761', '14830721', '14831681', '14831951', '14832641', '14833601', '14834561', '14835521', '14836061', '14836481', '14836711', '14837441', '14837601', '14838101', '14838401', '14839361', '14840321', '14840961']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_5' | NDM=2139581 Nstar=650286 Ngas=1492591>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_6' | NDM=1674750 Nstar=706702 Ngas=1463847>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_1' | NDM=30847962 Nstar=22776872 Ngas=20787115>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_1' | NDM=42087941 Nstar=32310162 Ngas=28613683>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_1' | NDM=42786993 Nstar=33180551 Ngas=29052887>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_1' | NDM=50278977 Nstar=42982851 Ngas=35578096>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_1' | NDM=52004649 Nstar=48517944 Ngas=37598752>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_1' | NDM=53923378 Nstar=53871908 Ngas=39624071>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_1' | NDM=53028504 Nstar=67650363 Ngas=41160525>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_1' | NDM=52538651 Nstar=75777722 Ngas=41946434>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_1' | NDM=56084252 Nstar=98380133 Ngas=43998788>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_1' | NDM=57713295 Nstar=115914448 Ngas=43757050>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_1' | NDM=58088133 Nstar=125274832 Ngas=42721848>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_1' | NDM=58284883 Nstar=128396317 Ngas=41268341>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_1' | NDM=60407892 Nstar=136063352 Ngas=42526327>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_1' | NDM=69719556 Nstar=151745066 Ngas=48679549>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_1' | NDM=74682561 Nstar=161288463 Ngas=49838203>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_1' | NDM=79209282 Nstar=171242211 Ngas=50776202>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_1' | NDM=81034353 Nstar=178405453 Ngas=51274583>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_1' | NDM=83533480 Nstar=182930962 Ngas=52156952>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_1' | NDM=88184399 Nstar=191859919 Ngas=53169813>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_1' | NDM=92128287 Nstar=200448545 Ngas=53996941>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_1' | NDM=92940876 Nstar=208293336 Ngas=54631732>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_1' | NDM=93137267 Nstar=216139033 Ngas=54182355>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_1' | NDM=93736187 Nstar=224685115 Ngas=53002659>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_1' | NDM=94968147 Nstar=232409562 Ngas=52937142>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_1' | NDM=95347084 Nstar=234720893 Ngas=52805098>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_1' | NDM=96926797 Nstar=240553350 Ngas=52804416>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_1' | NDM=100393030 Nstar=248831799 Ngas=53306203>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_1' | NDM=102755225 Nstar=256536772 Ngas=53324840>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_1' | NDM=108077897 Nstar=265884484 Ngas=55729574>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_1' | NDM=109410522 Nstar=269836568 Ngas=56173111>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_1' | NDM=110247779 Nstar=272811832 Ngas=56212487>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_1' | NDM=110732781 Nstar=274415388 Ngas=56246035>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_1' | NDM=111919159 Nstar=279705605 Ngas=56130783>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_1' | NDM=112282813 Nstar=280846217 Ngas=56086346>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_1' | NDM=112822614 Nstar=284201687 Ngas=55870207>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_1' | NDM=113010704 Nstar=285992241 Ngas=55775510>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_1' | NDM=113660248 Nstar=291859545 Ngas=55252145>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_1' | NDM=114035352 Nstar=297707243 Ngas=54610224>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_1' | NDM=114345489 Nstar=301507217 Ngas=54135923>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '14810245', '14811066', '14811521', '14812701', '14812801', '14814081', '14814761', '14815361', '14816641', '14817401', '14819201', '14820481', '14820881', '14821121', '14822081', '14823041', '14824001', '14824961', '14825551', '14825921', '14826881', '14827841', '14828801', '14829761', '14830721', '14831681', '14831951', '14832641', '14833601', '14834561', '14835521', '14836061', '14836481', '14836711', '14837441', '14837601', '14838101', '14838401', '14839361', '14840321', '14840961']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0         0          0         0          0         0
1        108          0         0          0         0          0         0
2        128          0         0          0         0          0         0
3        139          0         0          0         0          0         0
4        188          0         0          0         0          0         0
5        225          0         0          0         0          0         0
6        256          0         0          0         0          0         0
7        275          0         0          0         0          0         0
8        347          0         0          0         0          0         0
9        384          0         0          0         0          0         0
10       457          0         0          0         0          0         0
11       512          0         0          0         0          0         0
12       637          0         0          0         0          0         0
13       640          0         0          0         0          0         0
14       777          0         0          0         0          0         0
15       896          0         0          0         0          0         0
16       974          0         0          0         0          0         0
17      1024  148102411  14810245  148102422  14810243  148102416  14810243
18      1106  148110610  14811066  148110620  14811063  148110614  14811063
19      1152   14811521  14811521  148115218  14811523  148115212  14811523
20      1270   14812701  14812701   14812701  14812709  148127014  14812703
21      1280   14812801  14812801   14812801  14812801  148128013  14812804
22      1408   14814081  14814081   14814081  14814081   14814081  14814081
23      1476   14814761  14814761   14814761  14814761   14814761  14814761
24      1536   14815361  14815361   14815361  14815361   14815361  14815361
25      1664   14816641  14816641   14816641  14816641   14816641  14816641
26      1740   14817401  14817401   14817401  14817401   14817401  14817401
27      1920   14819201  14819201   14819201  14819201   14819201  14819201
28      2048   14820481  14820481   14820481  14820481   14820481  14820481
29      2088   14820881  14820881   14820881  14820881   14820881  14820881
30      2112   14821121  14821121   14821121  14821121   14821121  14821121
31      2208   14822081  14822081   14822081  14822081   14822081  14822081
32      2304   14823041  14823041   14823041  14823041   14823041  14823041
33      2400   14824001  14824001   14824001  14824001   14824001  14824001
34      2496   14824961  14824961   14824961  14824961   14824961  14824961
35      2555   14825551  14825551   14825551  14825551   14825551  14825551
36      2592   14825921  14825921   14825921  14825921   14825921  14825921
37      2688   14826881  14826881   14826881  14826881   14826881  14826881
38      2784   14827841  14827841   14827841  14827841   14827841  14827841
39      2880   14828801  14828801   14828801  14828801   14828801  14828801
40      2976   14829761  14829761   14829761  14829761   14829761  14829761
41      3072   14830721  14830721   14830721  14830721   14830721  14830721
42      3168   14831681  14831681   14831681  14831681   14831681  14831681
43      3195   14831951  14831951   14831951  14831951   14831951  14831951
44      3264   14832641  14832641   14832641  14832641   14832641  14832641
45      3360   14833601  14833601   14833601  14833601   14833601  14833601
46      3456   14834561  14834561   14834561  14834561   14834561  14834561
47      3552   14835521  14835521   14835521  14835521   14835521  14835521
48      3606   14836061  14836061   14836061  14836061   14836061  14836061
49      3648   14836481  14836481   14836481  14836481   14836481  14836481
50      3671   14836711  14836711   14836711  14836711   14836711  14836711
51      3744   14837441  14837441   14837441  14837441   14837441  14837441
52      3760   14837601  14837601   14837601  14837601   14837601  14837601
53      3810   14838101  14838101   14838101  14838101   14838101  14838101
54      3840   14838401  14838401   14838401  14838401   14838401  14838401
55      3936   14839361  14839361   14839361  14839361   14839361  14839361
56      4032   14840321  14840321   14840321  14840321   14840321  14840321
57      4096   14840961  14840961   14840961  14840961   14840961  14840961

     14814089  148153610  14829762     ...       14840966  148409663  \
0           0          0         0     ...              0          0
1           0          0         0     ...              0          0
2           0          0         0     ...              0          0
3           0          0         0     ...              0          0
4           0          0         0     ...              0          0
5           0          0         0     ...              0          0
6           0          0         0     ...              0          0
7           0          0         0     ...              0          0
8           0          0         0     ...              0          0
9           0          0         0     ...              0          0
10          0          0         0     ...              0          0
11          0          0         0     ...              0          0
12          0          0         0     ...              0          0
13          0          0         0     ...              0          0
14          0          0         0     ...              0          0
15          0          0         0     ...              0          0
16          0          0         0     ...              0          0
17  148102414  148102415  14810242     ...      148102412  148102483
18  148110612  148110613  14811062     ...       14811069  148110677
19  148115210  148115211  14811522     ...       14811529  148115273
20  148127011  148127012  14812702     ...      148127010  148127071
21  148128010  148128011  14812802     ...       14812809  148128070
22   14814089  148140810  14814082     ...       14814088  148140862
23   14814761  148147616  14814762     ...       14814768  148147669
24   14815361  148153610  14815362     ...       14815368  148153669
25   14816641   14816641  14816642     ...       14816648  148166469
26   14817401   14817401  14817402     ...       14817408  148174064
27   14819201   14819201  14819202     ...       14819208  148192064
28   14820481   14820481  14820482     ...       14820488  148204862
29   14820881   14820881  14820882     ...       14820888  148208862
30   14821121   14821121  14821122     ...       14821128  148211261
31   14822081   14822081  14822082     ...       14822088  148220860
32   14823041   14823041  14823042     ...       14823048  148230461
33   14824001   14824001  14824002     ...       14824008  148240060
34   14824961   14824961  14824962     ...       14824968  148249665
35   14825551   14825551  14825552     ...       14825558  148255565
36   14825921   14825921  14825922     ...       14825928  148259265
37   14826881   14826881  14826882     ...       14826888  148268866
38   14827841   14827841  14827842     ...       14827848  148278465
39   14828801   14828801  14828802     ...       14828808  148288064
40   14829761   14829761  14829762     ...       14829768  148297666
41   14830721   14830721  14830721     ...       14830726  148307267
42   14831681   14831681  14831681     ...       14831688  148316866
43   14831951   14831951  14831951     ...       14831958  148319567
44   14832641   14832641  14832641     ...       14832648  148326468
45   14833601   14833601  14833601     ...       14833607  148336067
46   14834561   14834561  14834561     ...       14834567  148345667
47   14835521   14835521  14835521     ...       14835526  148355266
48   14836061   14836061  14836061     ...       14836066  148360668
49   14836481   14836481  14836481     ...       14836486  148364866
50   14836711   14836711  14836711     ...       14836716  148367167
51   14837441   14837441  14837441     ...       14837446  148374466
52   14837601   14837601  14837601     ...       14837606  148376066
53   14838101   14838101  14838101     ...       14838106  148381065
54   14838401   14838401  14838401     ...       14838406  148384064
55   14839361   14839361  14839361     ...       14839366  148393663
56   14840321   14840321  14840321     ...       14840326  148403262
57   14840961   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0
5             0           0
6             0           0
7             0           0
8             0           0
9             0           0
10            0           0
11            0           0
12            0           0
13            0           0
14            0           0
15            0           0
16            0           0
17            0           0
18            0           0
19            0           0
20            0           0
21            0           0
22            0           0
23            0           0
24            0           0
25            0  1481664583
26            0  1481740675
27            0  1481920723
28            0  1482048709
29  14820883070  1482088716
30  14821123108  1482112721
31  14822083288  1482208764
32  14823043356  1482304820
33  14824003391  1482400761
34  14824964889  1482496764
35  14825555134  1482555761
36  14825925307  1482592774
37  14826885446  1482688844
38  14827845472  1482784888
39  14828805569  1482880871
40  14829766423  1482976861
41  14830726494  1483072837
42  14831686490  1483168827
43  14831956438  1483195823
44  14832646491  1483264814
45  14833606420  1483360815
46  14834566949  1483456812
47  14835527642  1483552798
48  14836067699  1483606789
49  14836487660  1483648782
50  14836717573  1483671780
51  14837447690  1483744767

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481740105', '1481920110', '1482048122', '1482088125', '1482112124', '1482208128', '1482304128', '1482400127', '1482496129', '1482555127', '1482592127', '1482688148', '1482784300', '1482880302', '1482976337', '1483072371', '1483168414', '1483195413', '1483264429', '1483360437', '1483456439', '1483552441', '1483606436', '1483648434', '1483671433', '1483744440', '1483760440', '1483810445', '1483840450', '14839361095', '14840321186', '14840961467']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_105' | NDM=42217 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_110' | NDM=36958 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_122' | NDM=30443 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_125' | NDM=29496 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_124' | NDM=29446 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_128' | NDM=28462 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_128' | NDM=27546 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_127' | NDM=27105 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_129' | NDM=26905 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_127' | NDM=26581 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_127' | NDM=26004 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_148' | NDM=19532 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_300' | NDM=6846 Nstar=2889 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_302' | NDM=6588 Nstar=2830 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_337' | NDM=5467 Nstar=2749 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_371' | NDM=4518 Nstar=2649 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_414' | NDM=3902 Nstar=2555 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_413' | NDM=3766 Nstar=2526 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_429' | NDM=3525 Nstar=2487 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_437' | NDM=3311 Nstar=2455 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_439' | NDM=3184 Nstar=2438 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_441' | NDM=3091 Nstar=2427 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_436' | NDM=3033 Nstar=2427 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_434' | NDM=3022 Nstar=2420 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_433' | NDM=3008 Nstar=2420 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_440' | NDM=2931 Nstar=2413 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_440' | NDM=2919 Nstar=2410 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_445' | NDM=2820 Nstar=2407 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_450' | NDM=2736 Nstar=2396 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_1095' | NDM=681 Nstar=1246 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_1186' | NDM=653 Nstar=1085 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_1467' | NDM=500 Nstar=880 Ngas=0>]
Watch me go for the  10 th time...
Already Exists  14840961025
Completed Count -->  111
Already Exists  14832642
Completed Count -->  111
Already Exists  14840964127
Completed Count -->  111
Already Exists  32913443
Completed Count -->  111
Already Exists  14840961061
Completed Count -->  111
Already Exists  14812709
Completed Count -->  111
Already Exists  329022513
Completed Count -->  111
Already Exists  1484096567
Completed Count -->  111
Already Exists  3294096956
Completed Count -->  111
Already Exists  32940964414
Completed Count -->  111
Already Exists  329022530
Completed Count -->  111
Already Exists  329409616
Completed Count -->  111
Already Exists  329038417
Completed Count -->  111
Already Exists  329409620
Completed Count -->  111
Already Exists  329038430
Completed Count -->  111
Already Exists  329127010
Completed Count -->  111
Already Exists  329038438
Completed Count -->  111
Already Exists  32904809
Completed Count -->  111
Already Exists  329409643
Completed Count -->  111
Already Exists  148409620589
Completed Count -->  111
Already Exists  329022579
Completed Count -->  111
Already Exists  14840962
Completed Count -->  111
Already Exists  14840963
Completed Count -->  111
Already Exists  14840961156
Completed Count -->  111
Already Exists  14840964
Completed Count -->  111
Already Exists  14840965
Completed Count -->  111
Already Exists  14840966
Completed Count -->  111
Already Exists  14840967
Completed Count -->  111
Already Exists  14812804
Completed Count -->  111
Already Exists  1484096138
Completed Count -->  111
Already Exists  329409673
Completed Count -->  111
Already Exists  329409675
Completed Count -->  111
Already Exists  32906374
Completed Count -->  111
Already Exists  32940965015
Completed Count -->  111
Already Exists  14840961179
Completed Count -->  111
Already Exists  14840961693
Completed Count -->  111
Already Exists  329409696
Completed Count -->  111
Already Exists  3294096555
Completed Count -->  111
Already Exists  1484096179
Completed Count -->  111
Already Exists  1484096194
Completed Count -->  111
Already Exists  14829762
Completed Count -->  111
Already Exists  3294096585
Completed Count -->  111
Already Exists  329067210
Completed Count -->  111
Already Exists  1484096204
Completed Count -->  111
Already Exists  1484096210
Completed Count -->  111
Already Exists  32933603
Completed Count -->  111
Already Exists  3290192110
Completed Count -->  111
Already Exists  3290192111
Completed Count -->  111
Already Exists  148409613555
Completed Count -->  111
Already Exists  148409619718
Completed Count -->  111
Already Exists  148153610
Completed Count -->  111
Already Exists  148409610
Completed Count -->  111
Already Exists  148409611
Completed Count -->  111
Already Exists  148409612
Completed Count -->  111
Already Exists  148128013
Completed Count -->  111
Already Exists  1484096271
Completed Count -->  111
Already Exists  14840965903
Completed Count -->  111
Already Exists  148409617
Completed Count -->  111
Already Exists  148110610
Completed Count -->  111
Already Exists  148115218
Completed Count -->  111
Already Exists  148409621
Completed Count -->  111
Already Exists  1484096278
Completed Count -->  111
Already Exists  148409622
Completed Count -->  111
Already Exists  148409632
Completed Count -->  111
Already Exists  148409633
Completed Count -->  111
Already Exists  148409634
Completed Count -->  111
Already Exists  148409635
Completed Count -->  111
Already Exists  1484096803
Completed Count -->  111
Already Exists  32924962
Completed Count -->  111
Already Exists  148409639
Completed Count -->  111
Already Exists  148409641
Completed Count -->  111
Already Exists  148409651
Completed Count -->  111
Already Exists  148409653
Completed Count -->  111
Already Exists  148409655
Completed Count -->  111
Already Exists  14840964409
Completed Count -->  111
Already Exists  148409663
Completed Count -->  111
Already Exists  148409668
Completed Count -->  111
Already Exists  1484096266
Completed Count -->  111
Already Exists  1484096331
Completed Count -->  111
Already Exists  148409676
Completed Count -->  111
Already Exists  148409677
Completed Count -->  111
Already Exists  329096015
Completed Count -->  111
Already Exists  14840964944
Completed Count -->  111
Already Exists  32914768
Completed Count -->  111
Already Exists  1484096857
Completed Count -->  111
Already Exists  329019225
Completed Count -->  111
Already Exists  14840961883
Completed Count -->  111
Already Exists  32940961630
Completed Count -->  111
Already Exists  14840967007
Completed Count -->  111
Already Exists  329019230
Completed Count -->  111
Already Exists  14840961379
Completed Count -->  111
Already Exists  32908648
Completed Count -->  111
Already Exists  14840961900
Completed Count -->  111
Already Exists  14840962413
Completed Count -->  111
Already Exists  14840962927
Completed Count -->  111
Already Exists  32940961648
Completed Count -->  111
Already Exists  14840968565
Completed Count -->  111
Already Exists  1484096374
Completed Count -->  111
Already Exists  3290188153
Completed Count -->  111
Already Exists  3294096768
Completed Count -->  111
Already Exists  1484096387
Completed Count -->  111
Already Exists  14840961413
Completed Count -->  111
Already Exists  14814089
Completed Count -->  111
Already Exists  1484096412
Completed Count -->  111
Already Exists  32930722
Completed Count -->  111
Already Exists  1484096422
Completed Count -->  111
Already Exists  32940969
Completed Count -->  111
Already Exists  148409612211
Completed Count -->  111
Already Exists  32909747
Completed Count -->  111
Already Exists  14840964022
Completed Count -->  111
Already Exists  14811066
Completed Count -->  111
Started  14840961467
Started  14840961467
h148 Survivor 1467 4096

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481740105', '1481920110', '1482048122', '1482088125', '1482112124', '1482208128', '1482304128', '1482400127', '1482496129', '1482555127', '1482592127', '1482688148', '1482784300', '1482880302', '1482976337', '1483072371', '1483168414', '1483195413', '1483264429', '1483360437', '1483456439', '1483552441', '1483606436', '1483648434', '1483671433', '1483744440', '1483760440', '1483810445', '1483840450', '14839361095', '14840321186', '14840961467']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_105' | NDM=42217 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_110' | NDM=36958 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_122' | NDM=30443 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_125' | NDM=29496 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_124' | NDM=29446 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_128' | NDM=28462 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_128' | NDM=27546 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_127' | NDM=27105 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_129' | NDM=26905 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_127' | NDM=26581 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_127' | NDM=26004 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_148' | NDM=19532 Nstar=3082 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_300' | NDM=6846 Nstar=2889 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_302' | NDM=6588 Nstar=2830 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_337' | NDM=5467 Nstar=2749 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_371' | NDM=4518 Nstar=2649 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_414' | NDM=3902 Nstar=2555 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_413' | NDM=3766 Nstar=2526 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_429' | NDM=3525 Nstar=2487 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_437' | NDM=3311 Nstar=2455 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_439' | NDM=3184 Nstar=2438 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_441' | NDM=3091 Nstar=2427 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_436' | NDM=3033 Nstar=2427 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_434' | NDM=3022 Nstar=2420 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_433' | NDM=3008 Nstar=2420 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_440' | NDM=2931 Nstar=2413 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_440' | NDM=2919 Nstar=2410 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_445' | NDM=2820 Nstar=2407 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_450' | NDM=2736 Nstar=2396 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_1095' | NDM=681 Nstar=1246 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_1186' | NDM=653 Nstar=1085 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_1467' | NDM=500 Nstar=880 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481740105', '1481920110', '1482048122', '1482088125', '1482112124', '1482208128', '1482304128', '1482400127', '1482496129', '1482555127', '1482592127', '1482688148', '1482784300', '1482880302', '1482976337', '1483072371', '1483168414', '1483195413', '1483264429', '1483360437', '1483456439', '1483552441', '1483606436', '1483648434', '1483671433', '1483744440', '1483760440', '1483810445', '1483840450', '14839361095', '14840321186', '14840961467']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0         0          0         0          0         0
1        108          0         0          0         0          0         0
2        128          0         0          0         0          0         0
3        139          0         0          0         0          0         0
4        188          0         0          0         0          0         0
5        225          0         0          0         0          0         0
6        256          0         0          0         0          0         0
7        275          0         0          0         0          0         0
8        347          0         0          0         0          0         0
9        384          0         0          0         0          0         0
10       457          0         0          0         0          0         0
11       512          0         0          0         0          0         0
12       637          0         0          0         0          0         0
13       640          0         0          0         0          0         0
14       777          0         0          0         0          0         0
15       896          0         0          0         0          0         0
16       974          0         0          0         0          0         0
17      1024  148102411  14810245  148102422  14810243  148102416  14810243
18      1106  148110610  14811066  148110620  14811063  148110614  14811063
19      1152   14811521  14811521  148115218  14811523  148115212  14811523
20      1270   14812701  14812701   14812701  14812709  148127014  14812703
21      1280   14812801  14812801   14812801  14812801  148128013  14812804
22      1408   14814081  14814081   14814081  14814081   14814081  14814081
23      1476   14814761  14814761   14814761  14814761   14814761  14814761
24      1536   14815361  14815361   14815361  14815361   14815361  14815361
25      1664   14816641  14816641   14816641  14816641   14816641  14816641
26      1740   14817401  14817401   14817401  14817401   14817401  14817401
27      1920   14819201  14819201   14819201  14819201   14819201  14819201
28      2048   14820481  14820481   14820481  14820481   14820481  14820481
29      2088   14820881  14820881   14820881  14820881   14820881  14820881
30      2112   14821121  14821121   14821121  14821121   14821121  14821121
31      2208   14822081  14822081   14822081  14822081   14822081  14822081
32      2304   14823041  14823041   14823041  14823041   14823041  14823041
33      2400   14824001  14824001   14824001  14824001   14824001  14824001
34      2496   14824961  14824961   14824961  14824961   14824961  14824961
35      2555   14825551  14825551   14825551  14825551   14825551  14825551
36      2592   14825921  14825921   14825921  14825921   14825921  14825921
37      2688   14826881  14826881   14826881  14826881   14826881  14826881
38      2784   14827841  14827841   14827841  14827841   14827841  14827841
39      2880   14828801  14828801   14828801  14828801   14828801  14828801
40      2976   14829761  14829761   14829761  14829761   14829761  14829761
41      3072   14830721  14830721   14830721  14830721   14830721  14830721
42      3168   14831681  14831681   14831681  14831681   14831681  14831681
43      3195   14831951  14831951   14831951  14831951   14831951  14831951
44      3264   14832641  14832641   14832641  14832641   14832641  14832641
45      3360   14833601  14833601   14833601  14833601   14833601  14833601
46      3456   14834561  14834561   14834561  14834561   14834561  14834561
47      3552   14835521  14835521   14835521  14835521   14835521  14835521
48      3606   14836061  14836061   14836061  14836061   14836061  14836061
49      3648   14836481  14836481   14836481  14836481   14836481  14836481
50      3671   14836711  14836711   14836711  14836711   14836711  14836711
51      3744   14837441  14837441   14837441  14837441   14837441  14837441
52      3760   14837601  14837601   14837601  14837601   14837601  14837601
53      3810   14838101  14838101   14838101  14838101   14838101  14838101
54      3840   14838401  14838401   14838401  14838401   14838401  14838401
55      3936   14839361  14839361   14839361  14839361   14839361  14839361
56      4032   14840321  14840321   14840321  14840321   14840321  14840321
57      4096   14840961  14840961   14840961  14840961   14840961  14840961

     14814089  148153610  14829762     ...       14840966  148409663  \
0           0          0         0     ...              0          0
1           0          0         0     ...              0          0
2           0          0         0     ...              0          0
3           0          0         0     ...              0          0
4           0          0         0     ...              0          0
5           0          0         0     ...              0          0
6           0          0         0     ...              0          0
7           0          0         0     ...              0          0
8           0          0         0     ...              0          0
9           0          0         0     ...              0          0
10          0          0         0     ...              0          0
11          0          0         0     ...              0          0
12          0          0         0     ...              0          0
13          0          0         0     ...              0          0
14          0          0         0     ...              0          0
15          0          0         0     ...              0          0
16          0          0         0     ...              0          0
17  148102414  148102415  14810242     ...      148102412  148102483
18  148110612  148110613  14811062     ...       14811069  148110677
19  148115210  148115211  14811522     ...       14811529  148115273
20  148127011  148127012  14812702     ...      148127010  148127071
21  148128010  148128011  14812802     ...       14812809  148128070
22   14814089  148140810  14814082     ...       14814088  148140862
23   14814761  148147616  14814762     ...       14814768  148147669
24   14815361  148153610  14815362     ...       14815368  148153669
25   14816641   14816641  14816642     ...       14816648  148166469
26   14817401   14817401  14817402     ...       14817408  148174064
27   14819201   14819201  14819202     ...       14819208  148192064
28   14820481   14820481  14820482     ...       14820488  148204862
29   14820881   14820881  14820882     ...       14820888  148208862
30   14821121   14821121  14821122     ...       14821128  148211261
31   14822081   14822081  14822082     ...       14822088  148220860
32   14823041   14823041  14823042     ...       14823048  148230461
33   14824001   14824001  14824002     ...       14824008  148240060
34   14824961   14824961  14824962     ...       14824968  148249665
35   14825551   14825551  14825552     ...       14825558  148255565
36   14825921   14825921  14825922     ...       14825928  148259265
37   14826881   14826881  14826882     ...       14826888  148268866
38   14827841   14827841  14827842     ...       14827848  148278465
39   14828801   14828801  14828802     ...       14828808  148288064
40   14829761   14829761  14829762     ...       14829768  148297666
41   14830721   14830721  14830721     ...       14830726  148307267
42   14831681   14831681  14831681     ...       14831688  148316866
43   14831951   14831951  14831951     ...       14831958  148319567
44   14832641   14832641  14832641     ...       14832648  148326468
45   14833601   14833601  14833601     ...       14833607  148336067
46   14834561   14834561  14834561     ...       14834567  148345667
47   14835521   14835521  14835521     ...       14835526  148355266
48   14836061   14836061  14836061     ...       14836066  148360668
49   14836481   14836481  14836481     ...       14836486  148364866
50   14836711   14836711  14836711     ...       14836716  148367167
51   14837441   14837441  14837441     ...       14837446  148374466
52   14837601   14837601  14837601     ...       14837606  148376066
53   14838101   14838101  14838101     ...       14838106  148381065
54   14838401   14838401  14838401     ...       14838406  148384064
55   14839361   14839361  14839361     ...       14839366  148393663
56   14840321   14840321  14840321     ...       14840326  148403262
57   14840961   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0
5             0           0
6             0           0
7             0           0
8             0           0
9             0           0
10            0           0
11            0           0
12            0           0
13            0           0
14            0           0
15            0           0
16            0           0
17            0           0
18            0           0
19            0           0
20            0           0
21            0           0
22            0           0
23            0           0
24            0           0
25            0  1481664583
26            0  1481740675
27            0  1481920723
28            0  1482048709
29  14820883070  1482088716
30  14821123108  1482112721
31  14822083288  1482208764
32  14823043356  1482304820
33  14824003391  1482400761
34  14824964889  1482496764
35  14825555134  1482555761
36  14825925307  1482592774
37  14826885446  1482688844
38  14827845472  1482784888
39  14828805569  1482880871
40  14829766423  1482976861
41  14830726494  1483072837
42  14831686490  1483168827
43  14831956438  1483195823
44  14832646491  1483264814
45  14833606420  1483360815
46  14834566949  1483456812
47  14835527642  1483552798
48  14836067699  1483606789
49  14836487660  1483648782
50  14836717573  1483671780
51  14837447690  1483744767
52  14837607621  1483760767
53  14838107661  1483810759
54  14838407640  1483840752
55  14839367781  1483936756
56  14840328859  1484032786
57  14840968565  1484096857

[58 rows x 78 columns]
Finished  14840961467
Finished  14840961467
Completed Count -->  112
Started  1484096459
Started  1484096459
h148 Survivor 459 4096

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148102466', '148110679', '148115268', '148127049', '148128048', '148140855', '148147657', '148153659', '148166462', '148174058', '148192057', '148204858', '148208858', '148211256', '148220855', '148230457', '148240059', '148249661', '148255561', '148259261', '148268864', '148278475', '1482880133', '1482976121', '1483072175', '1483168363', '1483195386', '1483264349', '1483360374', '1483456382', '1483552391', '1483606397', '1483648405', '1483671403', '1483744411', '1483760419', '1483810431', '1483840442', '1483936443', '1484032450', '1484096459']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_66' | NDM=90340 Nstar=622 Ngas=10676>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_79' | NDM=64280 Nstar=622 Ngas=10984>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_68' | NDM=70355 Nstar=622 Ngas=14970>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_49' | NDM=110332 Nstar=622 Ngas=23799>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_48' | NDM=108907 Nstar=622 Ngas=22247>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_55' | NDM=91494 Nstar=622 Ngas=9900>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_57' | NDM=88227 Nstar=622 Ngas=9196>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_59' | NDM=86631 Nstar=622 Ngas=8884>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_62' | NDM=83791 Nstar=622 Ngas=6918>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_58' | NDM=85403 Nstar=622 Ngas=6376>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_57' | NDM=86852 Nstar=622 Ngas=6967>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_58' | NDM=85343 Nstar=622 Ngas=6328>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_58' | NDM=84929 Nstar=622 Ngas=6084>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_56' | NDM=84770 Nstar=622 Ngas=5898>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_55' | NDM=83926 Nstar=622 Ngas=4807>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_57' | NDM=81731 Nstar=622 Ngas=3432>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_59' | NDM=79545 Nstar=622 Ngas=2695>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_61' | NDM=78725 Nstar=622 Ngas=2680>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_61' | NDM=78259 Nstar=622 Ngas=2873>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_61' | NDM=77775 Nstar=622 Ngas=2943>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_64' | NDM=73397 Nstar=622 Ngas=2742>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_75' | NDM=53340 Nstar=622 Ngas=2603>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_133' | NDM=24016 Nstar=626 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_121' | NDM=27741 Nstar=627 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_175' | NDM=15968 Nstar=622 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_363' | NDM=6703 Nstar=607 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_386' | NDM=6258 Nstar=605 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_349' | NDM=6889 Nstar=605 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_374' | NDM=6377 Nstar=601 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_382' | NDM=6013 Nstar=600 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_391' | NDM=5812 Nstar=598 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_397' | NDM=5639 Nstar=597 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_405' | NDM=5490 Nstar=597 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_403' | NDM=5427 Nstar=597 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_411' | NDM=5188 Nstar=596 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_419' | NDM=5109 Nstar=596 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_431' | NDM=4761 Nstar=592 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_442' | NDM=4646 Nstar=591 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_443' | NDM=4502 Nstar=586 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_450' | NDM=4402 Nstar=587 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_459' | NDM=4298 Nstar=584 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148102466', '148110679', '148115268', '148127049', '148128048', '148140855', '148147657', '148153659', '148166462', '148174058', '148192057', '148204858', '148208858', '148211256', '148220855', '148230457', '148240059', '148249661', '148255561', '148259261', '148268864', '148278475', '1482880133', '1482976121', '1483072175', '1483168363', '1483195386', '1483264349', '1483360374', '1483456382', '1483552391', '1483606397', '1483648405', '1483671403', '1483744411', '1483760419', '1483810431', '1483840442', '1483936443', '1484032450', '1484096459']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0         0          0         0          0         0
1        108          0         0          0         0          0         0
2        128          0         0          0         0          0         0
3        139          0         0          0         0          0         0
4        188          0         0          0         0          0         0
5        225          0         0          0         0          0         0
6        256          0         0          0         0          0         0
7        275          0         0          0         0          0         0
8        347          0         0          0         0          0         0
9        384          0         0          0         0          0         0
10       457          0         0          0         0          0         0
11       512          0         0          0         0          0         0
12       637          0         0          0         0          0         0
13       640          0         0          0         0          0         0
14       777          0         0          0         0          0         0
15       896          0         0          0         0          0         0
16       974          0         0          0         0          0         0
17      1024  148102411  14810245  148102422  14810243  148102416  14810243
18      1106  148110610  14811066  148110620  14811063  148110614  14811063
19      1152   14811521  14811521  148115218  14811523  148115212  14811523
20      1270   14812701  14812701   14812701  14812709  148127014  14812703
21      1280   14812801  14812801   14812801  14812801  148128013  14812804
22      1408   14814081  14814081   14814081  14814081   14814081  14814081
23      1476   14814761  14814761   14814761  14814761   14814761  14814761
24      1536   14815361  14815361   14815361  14815361   14815361  14815361
25      1664   14816641  14816641   14816641  14816641   14816641  14816641
26      1740   14817401  14817401   14817401  14817401   14817401  14817401
27      1920   14819201  14819201   14819201  14819201   14819201  14819201
28      2048   14820481  14820481   14820481  14820481   14820481  14820481
29      2088   14820881  14820881   14820881  14820881   14820881  14820881
30      2112   14821121  14821121   14821121  14821121   14821121  14821121
31      2208   14822081  14822081   14822081  14822081   14822081  14822081
32      2304   14823041  14823041   14823041  14823041   14823041  14823041
33      2400   14824001  14824001   14824001  14824001   14824001  14824001
34      2496   14824961  14824961   14824961  14824961   14824961  14824961
35      2555   14825551  14825551   14825551  14825551   14825551  14825551
36      2592   14825921  14825921   14825921  14825921   14825921  14825921
37      2688   14826881  14826881   14826881  14826881   14826881  14826881
38      2784   14827841  14827841   14827841  14827841   14827841  14827841
39      2880   14828801  14828801   14828801  14828801   14828801  14828801
40      2976   14829761  14829761   14829761  14829761   14829761  14829761
41      3072   14830721  14830721   14830721  14830721   14830721  14830721
42      3168   14831681  14831681   14831681  14831681   14831681  14831681
43      3195   14831951  14831951   14831951  14831951   14831951  14831951
44      3264   14832641  14832641   14832641  14832641   14832641  14832641
45      3360   14833601  14833601   14833601  14833601   14833601  14833601
46      3456   14834561  14834561   14834561  14834561   14834561  14834561
47      3552   14835521  14835521   14835521  14835521   14835521  14835521
48      3606   14836061  14836061   14836061  14836061   14836061  14836061
49      3648   14836481  14836481   14836481  14836481   14836481  14836481
50      3671   14836711  14836711   14836711  14836711   14836711  14836711
51      3744   14837441  14837441   14837441  14837441   14837441  14837441
52      3760   14837601  14837601   14837601  14837601   14837601  14837601
53      3810   14838101  14838101   14838101  14838101   14838101  14838101
54      3840   14838401  14838401   14838401  14838401   14838401  14838401
55      3936   14839361  14839361   14839361  14839361   14839361  14839361
56      4032   14840321  14840321   14840321  14840321   14840321  14840321
57      4096   14840961  14840961   14840961  14840961   14840961  14840961

     14814089  148153610  14829762     ...       14840966  148409663  \
0           0          0         0     ...              0          0
1           0          0         0     ...              0          0
2           0          0         0     ...              0          0
3           0          0         0     ...              0          0
4           0          0         0     ...              0          0
5           0          0         0     ...              0          0
6           0          0         0     ...              0          0
7           0          0         0     ...              0          0
8           0          0         0     ...              0          0
9           0          0         0     ...              0          0
10          0          0         0     ...              0          0
11          0          0         0     ...              0          0
12          0          0         0     ...              0          0
13          0          0         0     ...              0          0
14          0          0         0     ...              0          0
15          0          0         0     ...              0          0
16          0          0         0     ...              0          0
17  148102414  148102415  14810242     ...      148102412  148102483
18  148110612  148110613  14811062     ...       14811069  148110677
19  148115210  148115211  14811522     ...       14811529  148115273
20  148127011  148127012  14812702     ...      148127010  148127071
21  148128010  148128011  14812802     ...       14812809  148128070
22   14814089  148140810  14814082     ...       14814088  148140862
23   14814761  148147616  14814762     ...       14814768  148147669
24   14815361  148153610  14815362     ...       14815368  148153669
25   14816641   14816641  14816642     ...       14816648  148166469
26   14817401   14817401  14817402     ...       14817408  148174064
27   14819201   14819201  14819202     ...       14819208  148192064
28   14820481   14820481  14820482     ...       14820488  148204862
29   14820881   14820881  14820882     ...       14820888  148208862
30   14821121   14821121  14821122     ...       14821128  148211261
31   14822081   14822081  14822082     ...       14822088  148220860
32   14823041   14823041  14823042     ...       14823048  148230461
33   14824001   14824001  14824002     ...       14824008  148240060
34   14824961   14824961  14824962     ...       14824968  148249665
35   14825551   14825551  14825552     ...       14825558  148255565
36   14825921   14825921  14825922     ...       14825928  148259265
37   14826881   14826881  14826882     ...       14826888  148268866
38   14827841   14827841  14827842     ...       14827848  148278465
39   14828801   14828801  14828802     ...       14828808  148288064
40   14829761   14829761  14829762     ...       14829768  148297666
41   14830721   14830721  14830721     ...       14830726  148307267
42   14831681   14831681  14831681     ...       14831688  148316866
43   14831951   14831951  14831951     ...       14831958  148319567
44   14832641   14832641  14832641     ...       14832648  148326468
45   14833601   14833601  14833601     ...       14833607  148336067
46   14834561   14834561  14834561     ...       14834567  148345667
47   14835521   14835521  14835521     ...       14835526  148355266
48   14836061   14836061  14836061     ...       14836066  148360668
49   14836481   14836481  14836481     ...       14836486  148364866
50   14836711   14836711  14836711     ...       14836716  148367167
51   14837441   14837441  14837441     ...       14837446  148374466
52   14837601   14837601  14837601     ...       14837606  148376066
53   14838101   14838101  14838101     ...       14838106  148381065
54   14838401   14838401  14838401     ...       14838406  148384064
55   14839361   14839361  14839361     ...       14839366  148393663
56   14840321   14840321  14840321     ...       14840326  148403262
57   14840961   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0
5             0           0
6             0           0
7             0           0
8             0           0
9             0           0
10            0           0
11            0           0
12            0           0
13            0           0
14            0           0
15            0           0
16            0           0
17            0           0
18            0           0
19            0           0
20            0           0
21            0           0
22            0           0
23            0           0
24            0           0
25            0  1481664583
26            0  1481740675
27            0  1481920723
28            0  1482048709
29  14820883070  1482088716
30  14821123108  1482112721
31  14822083288  1482208764
32  14823043356  1482304820
33  14824003391  1482400761
34  14824964889  1482496764
35  14825555134  1482555761
36  14825925307  1482592774
37  14826885446  1482688844
38  14827845472  1482784888
39  14828805569  1482880871
40  14829766423  1482976861
41  14830726494  1483072837
42  14831686490  1483168827
43  14831956438  1483195823
44  14832646491  1483264814
45  14833606420  1483360815
46  14834566949  1483456812
47  14835527642  1483552798
48  14836067699  1483606789
49  14836487660  1483648782
50  14836717573  1483671780
51  14837447690  1483744767
52  14837607621  1483760767
53  14838107661  1483810759
54  14838407640  1483840752
55  14839367781  1483936756
56  14840328859  1484032786
57  14840968565  1484096857

[58 rows x 78 columns]
Finished  1484096459
Finished  1484096459
Completed Count -->  113
Started  329048011
Started  329048011
h329 Zombie 11 0480

[0, '3290096346', '3290108453', '32901393', '32901885', '32901924', '32902257', '32902759', '329028810', '32903478', '329038410', '329045711', '329048011', '32905761', '32906371', '32906721', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[-1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096/halo_346' | NDM=406 Nstar=0 Ngas=8>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108/halo_453' | NDM=379 Nstar=0 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_3' | NDM=63083 Nstar=5425 Ngas=33914>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_5' | NDM=105475 Nstar=12356 Ngas=38781>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_4' | NDM=106319 Nstar=12767 Ngas=34127>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_7' | NDM=113710 Nstar=14289 Ngas=33256>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_9' | NDM=131081 Nstar=15488 Ngas=47540>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_10' | NDM=139512 Nstar=15855 Ngas=53907>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_8' | NDM=249151 Nstar=25936 Ngas=110114>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_10' | NDM=294452 Nstar=28705 Ngas=123645>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_11' | NDM=327851 Nstar=37276 Ngas=158625>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_11' | NDM=276241 Nstar=39355 Ngas=151352>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_1' | NDM=5065263 Nstar=1530172 Ngas=2738713>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_1' | NDM=7451554 Nstar=2236951 Ngas=4644431>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_1' | NDM=8496675 Nstar=2702944 Ngas=5442931>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_1' | NDM=10617049 Nstar=3856093 Ngas=7275738>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_1' | NDM=10872015 Nstar=3980353 Ngas=7482669>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_1' | NDM=12715287 Nstar=5722615 Ngas=9000800>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_1' | NDM=15028263 Nstar=7698307 Ngas=11059109>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_1' | NDM=15196786 Nstar=7990531 Ngas=11217754>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1' | NDM=15578696 Nstar=10217161 Ngas=11755160>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1' | NDM=15747259 Nstar=11784296 Ngas=11968198>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1' | NDM=15761360 Nstar=13147640 Ngas=12285340>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1' | NDM=15832293 Nstar=16238307 Ngas=12845015>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1' | NDM=15990494 Nstar=17157603 Ngas=12930029>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1' | NDM=17922263 Nstar=20611248 Ngas=14418911>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1' | NDM=20220937 Nstar=24755716 Ngas=15683385>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1' | NDM=20568424 Nstar=26701663 Ngas=15670524>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1' | NDM=21292522 Nstar=29070320 Ngas=16200299>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1' | NDM=22138471 Nstar=34143108 Ngas=16098369>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1' | NDM=22233114 Nstar=37948971 Ngas=16217261>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1' | NDM=22265580 Nstar=38395660 Ngas=16249600>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1' | NDM=22541017 Nstar=41934879 Ngas=16143723>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1' | NDM=23087646 Nstar=46137673 Ngas=15803476>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1' | NDM=23617232 Nstar=50351876 Ngas=15643527>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1' | NDM=24221915 Nstar=53530614 Ngas=15566115>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1' | NDM=24513553 Nstar=54733955 Ngas=15453339>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1' | NDM=26676353 Nstar=59100003 Ngas=16082599>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1' | NDM=29354421 Nstar=64311453 Ngas=16874211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1' | NDM=31464533 Nstar=68631869 Ngas=16998639>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1' | NDM=32730524 Nstar=72629063 Ngas=17093857>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1' | NDM=33576743 Nstar=76168219 Ngas=16582991>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1' | NDM=34007948 Nstar=77829519 Ngas=16271248>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1' | NDM=34817467 Nstar=82227069 Ngas=16133249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1' | NDM=35279749 Nstar=86891324 Ngas=15727574>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1' | NDM=34968677 Nstar=91010100 Ngas=14700620>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1' | NDM=34685343 Nstar=94725659 Ngas=13794122>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1' | NDM=34411771 Nstar=98430465 Ngas=12965040>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
[0, '3290096346', '3290108453', '32901393', '32901885', '32901924', '32902257', '32902759', '329028810', '32903478', '329038410', '329045711', '329048011', '32905761', '32906371', '32906721', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71           0           0           0          0          0
1         96   329009638   329009662    32900969          0          0
2        108   329010830   329010856   329010810          0  329010836
3        139   329013986  3290139151   329013963  329013935  329013959
4        188  3290188153  3290188114  3290188111  329018827  329018833
5        192    32901921  3290192110  3290192111  329019225  329019230
6        225    32902251    32902251    32902251   32902251   32902251
7        275    32902751    32902751    32902751   32902751   32902751
8        288    32902881    32902881    32902881   32902881   32902881
9        347    32903471    32903471    32903471   32903471   32903471
10       384    32903841    32903841    32903841   32903841   32903841
11       457    32904571    32904571    32904571   32904571   32904571
12       480    32904801    32904801    32904801   32904801   32904801
13       576    32905761    32905761    32905761   32905761   32905761
14       637    32906371    32906371    32906371   32906371   32906371
15       672    32906721    32906721    32906721   32906721   32906721
16       768    32907681    32907681    32907681   32907681   32907681
17       777    32907771    32907771    32907771   32907771   32907771
18       864    32908641    32908641    32908641   32908641   32908641
19       960    32909601    32909601    32909601   32909601   32909601
20       974    32909741    32909741    32909741   32909741   32909741
21      1056    32910561    32910561    32910561   32910561   32910561
22      1106    32911061    32911061    32911061   32911061   32911061
23      1152    32911521    32911521    32911521   32911521   32911521
24      1248    32912481    32912481    32912481   32912481   32912481
25      1270    32912701    32912701    32912701   32912701   32912701
26      1344    32913441    32913441    32913441   32913441   32913441
27      1440    32914401    32914401    32914401   32914401   32914401
28      1476    32914761    32914761    32914761   32914761   32914761
29      1536    32915361    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740    32917401    32917401    32917401   32917401   32917401
33      1824    32918241    32918241    32918241   32918241   32918241
34      1920    32919201    32919201    32919201   32919201   32919201
35      2016    32920161    32920161    32920161   32920161   32920161
36      2088    32920881    32920881    32920881   32920881   32920881
37      2112    32921121    32921121    32921121   32921121   32921121
38      2208    32922081    32922081    32922081   32922081   32922081
39      2304    32923041    32923041    32923041   32923041   32923041
40      2400    32924001    32924001    32924001   32924001   32924001
41      2496    32924961    32924961    32924961   32924961   32924961
42      2555    32925551    32925551    32925551   32925551   32925551
43      2592    32925921    32925921    32925921   32925921   32925921
44      2688    32926881    32926881    32926881   32926881   32926881
45      2784    32927841    32927841    32927841   32927841   32927841
46      2880    32928801    32928801    32928801   32928801   32928801
47      2976    32929761    32929761    32929761   32929761   32929761
48      3072    32930721    32930721    32930721   32930721   32930721
49      3168    32931681    32931681    32931681   32931681   32931681
50      3195    32931951    32931951    32931951   32931951   32931951
51      3264    32932641    32932641    32932641   32932641   32932641
52      3360    32933601    32933601    32933601   32933601   32933601
53      3456    32934561    32934561    32934561   32934561   32934561
54      3552    32935521    32935521    32935521   32935521   32935521
55      3606    32936061    32936061    32936061   32936061   32936061
56      3648    32936481    32936481    32936481   32936481   32936481
57      3744    32937441    32937441    32937441   32937441   32937441
58      3840    32938401    32938401    32938401   32938401   32938401
59      3936    32939361    32939361    32939361   32939361   32939361
60      4032    32940321    32940321    32940321   32940321   32940321
61      4096    32940961    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0           0
1    3290096221           0  32900961020   329009640           0  3290096124
2    3290108234           0  32901081471   329010844           0  3290108114
3    3290139545           0   3290139119  3290139138           0  3290139261
4    3290188538           0    329018879  3290188197           0  3290188285
5    3290192554           0    329019278  3290192195           0  3290192291
6    3290225544           0    329022582  3290225210  3290225189  3290225307
7    3290275579           0    329027574  3290275196  3290275121  3290275307
8    3290288619           0    329028872  3290288186  3290288109  3290288300
9    3290347581           0    329034758  3290347164   329034764  3290347281
10   3290384579           0    329038460  3290384127   329038446  3290384281
11   3290457588           0    329045751  3290457104   329045736  3290457298
12   3290480583           0    329048049  3290480102   329048032  3290480324
13   3290576536           0    329057638   329057696   329057626  3290576383
14   3290637554           0    329063738  3290637104   329063727  3290637432
15   3290672559           0    329067235  3290672100   329067221  3290672445
16   3290768567           0    329076836   329076886   329076824  3290768468
17   3290777570           0    329077736   329077786   329077723  3290777467
18   3290864555           0    329086434   329086477   329086420  3290864451
19   3290960543           0    329096033   329096073   329096021  3290960483
20   3290974534           0    329097431   329097473   329097420  3290974478
21   3291056562           0    329105639   329105668   329105622  3291056516
22   3291106741           0    329110652   329110666   329110622  3291106605
23   3291152887           0    329115265   329115271   329115223  3291152630
24  32912481314           0    329124869   329124868   329124825  3291248663
25   3291270963           0    329127068   329127066   329127026  3291270664
26   3291344954           0    329134471   329134461   329134424  3291344669
27   3291440948           0    329144073   329144058   329144021  3291440664
28   3291476953           0    329147674   329147661   329147621  3291476662
29   3291536954           0    329153675   329153662   329153634  3291536656
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043  3291740718
33  32918241363           0    329182478   329182462   329182445  3291824721
34  32919201657           0    329192075   329192057   329192047  3291920729
35  32920161763           0    329201673   329201653   329201648  3292016729
36  32920881809           0   3292088210   329208852   329208849  3292088728
37  32921121823           0   3292112188   329211251   329211250  3292112723
38  32922081833           0   3292208214   329220850   329220848  3292208722

[0, 0, 0, '329013996', '329018898', '329019294', '329022597', '3290275124', '3290288128', '3290347167', '3290384160', '3290457156', '3290480157', '3290576171', '3290637188', '3290672205', '3290768237', '3290777239', '3290864257', '3290960268', '3290974267', '3291056281', '3291106288', '3291152292', '3291248288', '3291270288', '3291344295', '3291440301', '3291476308', '3291536309', '3291632319', '3291728323', '3291740323', '3291824316', '3291920325', '3292016328', '3292088326', '3292112325', '3292208327', '3292304330', '3292400378', '3292496377', '3292555379', '3292592384', '3292688380', '3292784380', '3292880385', '3292976379', '3293072370', '3293168363', '3293195361', '3293264354', '3293360357', '3293456353', '3293552345', '3293606345', '3293648346', '3293744346', '3293840343', '3293936341', '3294032336', '3294096335']
[-1.0 -1.0 -1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_96' | NDM=3266 Nstar=0 Ngas=2092>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_98' | NDM=4818 Nstar=1 Ngas=3729>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_94' | NDM=4935 Nstar=2 Ngas=3811>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_97' | NDM=5758 Nstar=15 Ngas=4225>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_124' | NDM=6083 Nstar=15 Ngas=1421>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_128' | NDM=5932 Nstar=15 Ngas=1067>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_167' | NDM=5697 Nstar=15 Ngas=211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_160' | NDM=6061 Nstar=15 Ngas=146>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_156' | NDM=6773 Nstar=15 Ngas=78>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_157' | NDM=6920 Nstar=15 Ngas=37>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_171' | NDM=6524 Nstar=15 Ngas=10>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_188' | NDM=5925 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_205' | NDM=5483 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_237' | NDM=4794 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_239' | NDM=4766 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_257' | NDM=4568 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_268' | NDM=4419 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_267' | NDM=4375 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_281' | NDM=4205 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_288' | NDM=4105 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_292' | NDM=4056 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_288' | NDM=3955 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_288' | NDM=3943 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_295' | NDM=3905 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_301' | NDM=3838 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_308' | NDM=3825 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_309' | NDM=3767 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_319' | NDM=3674 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_323' | NDM=3607 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_323' | NDM=3595 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_316' | NDM=3548 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_325' | NDM=3493 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_328' | NDM=3478 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_326' | NDM=3452 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_325' | NDM=3447 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_327' | NDM=3411 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_330' | NDM=3279 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_378' | NDM=2796 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_377' | NDM=2749 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_379' | NDM=2731 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_384' | NDM=2709 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_380' | NDM=2679 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_380' | NDM=2663 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_385' | NDM=2646 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_379' | NDM=2639 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_370' | NDM=2633 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_363' | NDM=2633 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_361' | NDM=2633 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_354' | NDM=2631 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_357' | NDM=2624 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_353' | NDM=2619 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_345' | NDM=2616 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_345' | NDM=2615 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_346' | NDM=2613 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_346' | NDM=2601 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_343' | NDM=2599 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_341' | NDM=2598 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_336' | NDM=2599 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_335' | NDM=2595 Nstar=15 Ngas=0>]
Watch me go for the  11 th time...
Already Exists  14840961025
Completed Count -->  114
Already Exists  14832642
Completed Count -->  114
Already Exists  14840964127
Completed Count -->  114
Already Exists  32913443
Completed Count -->  114
Already Exists  14840961061
Completed Count -->  114
Already Exists  14812709
Completed Count -->  114
Already Exists  329022513
Completed Count -->  114
Already Exists  1484096567
Completed Count -->  114
Already Exists  3294096956
Completed Count -->  114
Already Exists  32940964414
Completed Count -->  114
Already Exists  329022530
Completed Count -->  114
Already Exists  329409616
Completed Count -->  114
Already Exists  329038417
Completed Count -->  114
Already Exists  329409620
Completed Count -->  114
Already Exists  329038430
Completed Count -->  114
Already Exists  329127010
Completed Count -->  114
Already Exists  329038438
Completed Count -->  114
Already Exists  32904809
Completed Count -->  114
Already Exists  329409643
Completed Count -->  114
Already Exists  148409620589
Completed Count -->  114
Already Exists  329022579
Completed Count -->  114
Already Exists  14840962
Completed Count -->  114
Already Exists  14840963
Completed Count -->  114
Already Exists  14840961156
Completed Count -->  114
Already Exists  14840964
Completed Count -->  114
Already Exists  14840965
Completed Count -->  114
Already Exists  14840966
Completed Count -->  114
Already Exists  14840967
Completed Count -->  114
Already Exists  14812804
Completed Count -->  114
Already Exists  1484096138
Completed Count -->  114
Already Exists  329409673
Completed Count -->  114
Already Exists  329409675
Completed Count -->  114
Already Exists  32906374
Completed Count -->  114
Already Exists  32940965015
Completed Count -->  114
Already Exists  14840961179
Completed Count -->  114
Already Exists  14840961693
Completed Count -->  114
Already Exists  329409696
Completed Count -->  114
Already Exists  3294096555
Completed Count -->  114
Already Exists  1484096179
Completed Count -->  114
Already Exists  1484096194
Completed Count -->  114
Already Exists  14829762
Completed Count -->  114
Already Exists  3294096585
Completed Count -->  114
Already Exists  329067210
Completed Count -->  114
Already Exists  1484096204
Completed Count -->  114
Already Exists  1484096210
Completed Count -->  114
Already Exists  32933603
Completed Count -->  114
Already Exists  3290192110
Completed Count -->  114
Already Exists  3290192111
Completed Count -->  114
Already Exists  148409613555
Completed Count -->  114
Already Exists  148409619718
Completed Count -->  114
Already Exists  148153610
Completed Count -->  114
Already Exists  148409610
Completed Count -->  114
Already Exists  148409611
Completed Count -->  114
Already Exists  148409612
Completed Count -->  114
Already Exists  148128013
Completed Count -->  114
Already Exists  1484096271
Completed Count -->  114
Already Exists  14840965903
Completed Count -->  114
Already Exists  148409617
Completed Count -->  114
Already Exists  148110610
Completed Count -->  114
Already Exists  148115218
Completed Count -->  114
Already Exists  148409621
Completed Count -->  114
Already Exists  1484096278
Completed Count -->  114
Already Exists  148409622
Completed Count -->  114
Already Exists  148409632
Completed Count -->  114
Already Exists  148409633
Completed Count -->  114
Already Exists  148409634
Completed Count -->  114
Already Exists  148409635
Completed Count -->  114
Already Exists  1484096803
Completed Count -->  114
Already Exists  32924962
Completed Count -->  114
Already Exists  148409639
Completed Count -->  114
Already Exists  148409641
Completed Count -->  114
Already Exists  148409651
Completed Count -->  114
Already Exists  148409653
Completed Count -->  114
Already Exists  148409655
Completed Count -->  114
Already Exists  14840964409
Completed Count -->  114
Already Exists  148409663
Completed Count -->  114
Already Exists  148409668
Completed Count -->  114
Already Exists  1484096266
Completed Count -->  114
Already Exists  1484096331
Completed Count -->  114
Already Exists  148409676
Completed Count -->  114
Already Exists  148409677
Completed Count -->  114
Already Exists  329096015
Completed Count -->  114
Already Exists  14840964944
Completed Count -->  114
Already Exists  32914768
Completed Count -->  114
Already Exists  1484096857
Completed Count -->  114
Already Exists  329019225
Completed Count -->  114
Already Exists  14840961883
Completed Count -->  114
Already Exists  32940961630
Completed Count -->  114
Already Exists  14840967007
Completed Count -->  114
Already Exists  329019230
Completed Count -->  114
Already Exists  14840961379
Completed Count -->  114
Already Exists  32908648
Completed Count -->  114
Already Exists  14840961900
Completed Count -->  114
Already Exists  14840962413
Completed Count -->  114
Already Exists  14840962927
Completed Count -->  114
Already Exists  32940961648
Completed Count -->  114
Already Exists  14840968565
Completed Count -->  114
Already Exists  1484096374
Completed Count -->  114
Already Exists  3290188153
Completed Count -->  114
Already Exists  3294096768
Completed Count -->  114
Already Exists  1484096387
Completed Count -->  114
Already Exists  14840961413
Completed Count -->  114
Already Exists  14814089
Completed Count -->  114
Already Exists  1484096412
Completed Count -->  114
Already Exists  32930722
Completed Count -->  114
Already Exists  1484096422
Completed Count -->  114
Already Exists  32940969
Completed Count -->  114
Already Exists  148409612211
Completed Count -->  114
Already Exists  32909747
Completed Count -->  114
Already Exists  14840964022
Completed Count -->  114
Already Exists  14811066
Completed Count -->  114
Already Exists  14840961467
Completed Count -->  114
Already Exists  1484096459
Completed Count -->  114
Already Exists  329048011
Completed Count -->  114
Started  3294096335
Started  3294096335
h329 Survivor 335 4096

[0, 0, 0, '329013996', '329018898', '329019294', '329022597', '3290275124', '3290288128', '3290347167', '3290384160', '3290457156', '3290480157', '3290576171', '3290637188', '3290672205', '3290768237', '3290777239', '3290864257', '3290960268', '3290974267', '3291056281', '3291106288', '3291152292', '3291248288', '3291270288', '3291344295', '3291440301', '3291476308', '3291536309', '3291632319', '3291728323', '3291740323', '3291824316', '3291920325', '3292016328', '3292088326', '3292112325', '3292208327', '3292304330', '3292400378', '3292496377', '3292555379', '3292592384', '3292688380', '3292784380', '3292880385', '3292976379', '3293072370', '3293168363', '3293195361', '3293264354', '3293360357', '3293456353', '3293552345', '3293606345', '3293648346', '3293744346', '3293840343', '3293936341', '3294032336', '3294096335']
[-1.0 -1.0 -1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_96' | NDM=3266 Nstar=0 Ngas=2092>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_98' | NDM=4818 Nstar=1 Ngas=3729>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_94' | NDM=4935 Nstar=2 Ngas=3811>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_97' | NDM=5758 Nstar=15 Ngas=4225>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_124' | NDM=6083 Nstar=15 Ngas=1421>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_128' | NDM=5932 Nstar=15 Ngas=1067>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_167' | NDM=5697 Nstar=15 Ngas=211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_160' | NDM=6061 Nstar=15 Ngas=146>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_156' | NDM=6773 Nstar=15 Ngas=78>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_157' | NDM=6920 Nstar=15 Ngas=37>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_171' | NDM=6524 Nstar=15 Ngas=10>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_188' | NDM=5925 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_205' | NDM=5483 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_237' | NDM=4794 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_239' | NDM=4766 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_257' | NDM=4568 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_268' | NDM=4419 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_267' | NDM=4375 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_281' | NDM=4205 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_288' | NDM=4105 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_292' | NDM=4056 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_288' | NDM=3955 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_288' | NDM=3943 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_295' | NDM=3905 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_301' | NDM=3838 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_308' | NDM=3825 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_309' | NDM=3767 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_319' | NDM=3674 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_323' | NDM=3607 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_323' | NDM=3595 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_316' | NDM=3548 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_325' | NDM=3493 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_328' | NDM=3478 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_326' | NDM=3452 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_325' | NDM=3447 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_327' | NDM=3411 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_330' | NDM=3279 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_378' | NDM=2796 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_377' | NDM=2749 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_379' | NDM=2731 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_384' | NDM=2709 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_380' | NDM=2679 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_380' | NDM=2663 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_385' | NDM=2646 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_379' | NDM=2639 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_370' | NDM=2633 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_363' | NDM=2633 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_361' | NDM=2633 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_354' | NDM=2631 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_357' | NDM=2624 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_353' | NDM=2619 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_345' | NDM=2616 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_345' | NDM=2615 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_346' | NDM=2613 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_346' | NDM=2601 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_343' | NDM=2599 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_341' | NDM=2598 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_336' | NDM=2599 Nstar=15 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_335' | NDM=2595 Nstar=15 Ngas=0>]
[0, 0, 0, '329013996', '329018898', '329019294', '329022597', '3290275124', '3290288128', '3290347167', '3290384160', '3290457156', '3290480157', '3290576171', '3290637188', '3290672205', '3290768237', '3290777239', '3290864257', '3290960268', '3290974267', '3291056281', '3291106288', '3291152292', '3291248288', '3291270288', '3291344295', '3291440301', '3291476308', '3291536309', '3291632319', '3291728323', '3291740323', '3291824316', '3291920325', '3292016328', '3292088326', '3292112325', '3292208327', '3292304330', '3292400378', '3292496377', '3292555379', '3292592384', '3292688380', '3292784380', '3292880385', '3292976379', '3293072370', '3293168363', '3293195361', '3293264354', '3293360357', '3293456353', '3293552345', '3293606345', '3293648346', '3293744346', '3293840343', '3293936341', '3294032336', '3294096335']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71           0           0           0          0          0
1         96   329009638   329009662    32900969          0          0
2        108   329010830   329010856   329010810          0  329010836
3        139   329013986  3290139151   329013963  329013935  329013959
4        188  3290188153  3290188114  3290188111  329018827  329018833
5        192    32901921  3290192110  3290192111  329019225  329019230
6        225    32902251    32902251    32902251   32902251   32902251
7        275    32902751    32902751    32902751   32902751   32902751
8        288    32902881    32902881    32902881   32902881   32902881
9        347    32903471    32903471    32903471   32903471   32903471
10       384    32903841    32903841    32903841   32903841   32903841
11       457    32904571    32904571    32904571   32904571   32904571
12       480    32904801    32904801    32904801   32904801   32904801
13       576    32905761    32905761    32905761   32905761   32905761
14       637    32906371    32906371    32906371   32906371   32906371
15       672    32906721    32906721    32906721   32906721   32906721
16       768    32907681    32907681    32907681   32907681   32907681
17       777    32907771    32907771    32907771   32907771   32907771
18       864    32908641    32908641    32908641   32908641   32908641
19       960    32909601    32909601    32909601   32909601   32909601
20       974    32909741    32909741    32909741   32909741   32909741
21      1056    32910561    32910561    32910561   32910561   32910561
22      1106    32911061    32911061    32911061   32911061   32911061
23      1152    32911521    32911521    32911521   32911521   32911521
24      1248    32912481    32912481    32912481   32912481   32912481
25      1270    32912701    32912701    32912701   32912701   32912701
26      1344    32913441    32913441    32913441   32913441   32913441
27      1440    32914401    32914401    32914401   32914401   32914401
28      1476    32914761    32914761    32914761   32914761   32914761
29      1536    32915361    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740    32917401    32917401    32917401   32917401   32917401
33      1824    32918241    32918241    32918241   32918241   32918241
34      1920    32919201    32919201    32919201   32919201   32919201
35      2016    32920161    32920161    32920161   32920161   32920161
36      2088    32920881    32920881    32920881   32920881   32920881
37      2112    32921121    32921121    32921121   32921121   32921121
38      2208    32922081    32922081    32922081   32922081   32922081
39      2304    32923041    32923041    32923041   32923041   32923041
40      2400    32924001    32924001    32924001   32924001   32924001
41      2496    32924961    32924961    32924961   32924961   32924961
42      2555    32925551    32925551    32925551   32925551   32925551
43      2592    32925921    32925921    32925921   32925921   32925921
44      2688    32926881    32926881    32926881   32926881   32926881
45      2784    32927841    32927841    32927841   32927841   32927841
46      2880    32928801    32928801    32928801   32928801   32928801
47      2976    32929761    32929761    32929761   32929761   32929761
48      3072    32930721    32930721    32930721   32930721   32930721
49      3168    32931681    32931681    32931681   32931681   32931681
50      3195    32931951    32931951    32931951   32931951   32931951
51      3264    32932641    32932641    32932641   32932641   32932641
52      3360    32933601    32933601    32933601   32933601   32933601
53      3456    32934561    32934561    32934561   32934561   32934561
54      3552    32935521    32935521    32935521   32935521   32935521
55      3606    32936061    32936061    32936061   32936061   32936061
56      3648    32936481    32936481    32936481   32936481   32936481
57      3744    32937441    32937441    32937441   32937441   32937441
58      3840    32938401    32938401    32938401   32938401   32938401
59      3936    32939361    32939361    32939361   32939361   32939361
60      4032    32940321    32940321    32940321   32940321   32940321
61      4096    32940961    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0           0
1    3290096221           0  32900961020   329009640           0  3290096124
2    3290108234           0  32901081471   329010844           0  3290108114
3    3290139545           0   3290139119  3290139138           0  3290139261
4    3290188538           0    329018879  3290188197           0  3290188285
5    3290192554           0    329019278  3290192195           0  3290192291
6    3290225544           0    329022582  3290225210  3290225189  3290225307
7    3290275579           0    329027574  3290275196  3290275121  3290275307
8    3290288619           0    329028872  3290288186  3290288109  3290288300
9    3290347581           0    329034758  3290347164   329034764  3290347281
10   3290384579           0    329038460  3290384127   329038446  3290384281
11   3290457588           0    329045751  3290457104   329045736  3290457298
12   3290480583           0    329048049  3290480102   329048032  3290480324
13   3290576536           0    329057638   329057696   329057626  3290576383
14   3290637554           0    329063738  3290637104   329063727  3290637432
15   3290672559           0    329067235  3290672100   329067221  3290672445
16   3290768567           0    329076836   329076886   329076824  3290768468
17   3290777570           0    329077736   329077786   329077723  3290777467
18   3290864555           0    329086434   329086477   329086420  3290864451
19   3290960543           0    329096033   329096073   329096021  3290960483
20   3290974534           0    329097431   329097473   329097420  3290974478
21   3291056562           0    329105639   329105668   329105622  3291056516
22   3291106741           0    329110652   329110666   329110622  3291106605
23   3291152887           0    329115265   329115271   329115223  3291152630
24  32912481314           0    329124869   329124868   329124825  3291248663
25   3291270963           0    329127068   329127066   329127026  3291270664
26   3291344954           0    329134471   329134461   329134424  3291344669
27   3291440948           0    329144073   329144058   329144021  3291440664
28   3291476953           0    329147674   329147661   329147621  3291476662
29   3291536954           0    329153675   329153662   329153634  3291536656
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043  3291740718
33  32918241363           0    329182478   329182462   329182445  3291824721
34  32919201657           0    329192075   329192057   329192047  3291920729
35  32920161763           0    329201673   329201653   329201648  3292016729
36  32920881809           0   3292088210   329208852   329208849  3292088728
37  32921121823           0   3292112188   329211251   329211250  3292112723
38  32922081833           0   3292208214   329220850   329220848  3292208722
39  32923041843           0   3292304234   329230450   329230449  3292304732
40  32924001879           0   3292400261   329240048   329240050  3292400787
41  32924962122           0   3292496271   329249648   329249650  3292496824
42  32925552182           0   3292555278   329255548   329255551  3292555828
43  32925922176           0   3292592282   329259249   329259252  3292592829
44  32926882164           0   3292688286   329268849   329268853  3292688812
45  32927842152           0   3292784291   329278449   329278454  3292784818
46  32928802121           0   3292880313   329288050   329288057  3292880812
47  32929762119           0   3292976362   329297650   329297662  3292976814
48  32930722348           0   3293072379   329307248   329307266  3293072822

['32900711', '32900963', '32901082', '32901398', '329018810', '32901928', '329022512', '329027514', '329028817', '329034721', '329038422', '329045720', '329048022', '32905761', '32906371', '32906721', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[ <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000071/halo_1' | NDM=9092 Nstar=639 Ngas=6655>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096/halo_3' | NDM=23134 Nstar=1259 Ngas=8534>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108/halo_2' | NDM=25866 Nstar=1451 Ngas=10885>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_8' | NDM=41087 Nstar=2368 Ngas=12210>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_10' | NDM=71042 Nstar=3500 Ngas=20735>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_8' | NDM=73735 Nstar=3570 Ngas=21319>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_12' | NDM=80388 Nstar=5088 Ngas=22391>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_14' | NDM=89384 Nstar=6193 Ngas=24074>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_17' | NDM=93587 Nstar=6531 Ngas=24606>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_21' | NDM=103892 Nstar=7820 Ngas=22972>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_22' | NDM=106235 Nstar=8227 Ngas=22081>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_20' | NDM=103847 Nstar=9168 Ngas=24335>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_22' | NDM=101791 Nstar=9368 Ngas=24419>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_1' | NDM=5065263 Nstar=1530172 Ngas=2738713>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_1' | NDM=7451554 Nstar=2236951 Ngas=4644431>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_1' | NDM=8496675 Nstar=2702944 Ngas=5442931>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_1' | NDM=10617049 Nstar=3856093 Ngas=7275738>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_1' | NDM=10872015 Nstar=3980353 Ngas=7482669>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_1' | NDM=12715287 Nstar=5722615 Ngas=9000800>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_1' | NDM=15028263 Nstar=7698307 Ngas=11059109>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_1' | NDM=15196786 Nstar=7990531 Ngas=11217754>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1' | NDM=15578696 Nstar=10217161 Ngas=11755160>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1' | NDM=15747259 Nstar=11784296 Ngas=11968198>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1' | NDM=15761360 Nstar=13147640 Ngas=12285340>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1' | NDM=15832293 Nstar=16238307 Ngas=12845015>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1' | NDM=15990494 Nstar=17157603 Ngas=12930029>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1' | NDM=17922263 Nstar=20611248 Ngas=14418911>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1' | NDM=20220937 Nstar=24755716 Ngas=15683385>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1' | NDM=20568424 Nstar=26701663 Ngas=15670524>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1' | NDM=21292522 Nstar=29070320 Ngas=16200299>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1' | NDM=22138471 Nstar=34143108 Ngas=16098369>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1' | NDM=22233114 Nstar=37948971 Ngas=16217261>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1' | NDM=22265580 Nstar=38395660 Ngas=16249600>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1' | NDM=22541017 Nstar=41934879 Ngas=16143723>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1' | NDM=23087646 Nstar=46137673 Ngas=15803476>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1' | NDM=23617232 Nstar=50351876 Ngas=15643527>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1' | NDM=24221915 Nstar=53530614 Ngas=15566115>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1' | NDM=24513553 Nstar=54733955 Ngas=15453339>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1' | NDM=26676353 Nstar=59100003 Ngas=16082599>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1' | NDM=29354421 Nstar=64311453 Ngas=16874211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1' | NDM=31464533 Nstar=68631869 Ngas=16998639>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1' | NDM=32730524 Nstar=72629063 Ngas=17093857>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1' | NDM=33576743 Nstar=76168219 Ngas=16582991>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1' | NDM=34007948 Nstar=77829519 Ngas=16271248>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1' | NDM=34817467 Nstar=82227069 Ngas=16133249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1' | NDM=35279749 Nstar=86891324 Ngas=15727574>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1' | NDM=34968677 Nstar=91010100 Ngas=14700620>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1' | NDM=34685343 Nstar=94725659 Ngas=13794122>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1' | NDM=34411771 Nstar=98430465 Ngas=12965040>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
[0, '32900963', '32901082', '32901398', '329018810', '32901928', '329022512', '329027514', '329028817', '329034721', '329038422', '329045720', '329048022', '32905761', '32906371', '32906721', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71           0           0           0          0          0
1         96   329009638   329009662    32900969          0          0
2        108   329010830   329010856   329010810          0  329010836
3        139   329013986  3290139151   329013963  329013935  329013959
4        188  3290188153  3290188114  3290188111  329018827  329018833
5        192    32901921  3290192110  3290192111  329019225  329019230
6        225    32902251    32902251    32902251   32902251   32902251
7        275    32902751    32902751    32902751   32902751   32902751
8        288    32902881    32902881    32902881   32902881   32902881
9        347    32903471    32903471    32903471   32903471   32903471
10       384    32903841    32903841    32903841   32903841   32903841
11       457    32904571    32904571    32904571   32904571   32904571
12       480    32904801    32904801    32904801   32904801   32904801
13       576    32905761    32905761    32905761   32905761   32905761
14       637    32906371    32906371    32906371   32906371   32906371
15       672    32906721    32906721    32906721   32906721   32906721
16       768    32907681    32907681    32907681   32907681   32907681
17       777    32907771    32907771    32907771   32907771   32907771
18       864    32908641    32908641    32908641   32908641   32908641
19       960    32909601    32909601    32909601   32909601   32909601
20       974    32909741    32909741    32909741   32909741   32909741
21      1056    32910561    32910561    32910561   32910561   32910561
22      1106    32911061    32911061    32911061   32911061   32911061
23      1152    32911521    32911521    32911521   32911521   32911521
24      1248    32912481    32912481    32912481   32912481   32912481
25      1270    32912701    32912701    32912701   32912701   32912701
26      1344    32913441    32913441    32913441   32913441   32913441
27      1440    32914401    32914401    32914401   32914401   32914401
28      1476    32914761    32914761    32914761   32914761   32914761
29      1536    32915361    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740    32917401    32917401    32917401   32917401   32917401
33      1824    32918241    32918241    32918241   32918241   32918241
34      1920    32919201    32919201    32919201   32919201   32919201
35      2016    32920161    32920161    32920161   32920161   32920161
36      2088    32920881    32920881    32920881   32920881   32920881
37      2112    32921121    32921121    32921121   32921121   32921121
38      2208    32922081    32922081    32922081   32922081   32922081
39      2304    32923041    32923041    32923041   32923041   32923041
40      2400    32924001    32924001    32924001   32924001   32924001
41      2496    32924961    32924961    32924961   32924961   32924961
42      2555    32925551    32925551    32925551   32925551   32925551
43      2592    32925921    32925921    32925921   32925921   32925921
44      2688    32926881    32926881    32926881   32926881   32926881
45      2784    32927841    32927841    32927841   32927841   32927841
46      2880    32928801    32928801    32928801   32928801   32928801
47      2976    32929761    32929761    32929761   32929761   32929761
48      3072    32930721    32930721    32930721   32930721   32930721
49      3168    32931681    32931681    32931681   32931681   32931681
50      3195    32931951    32931951    32931951   32931951   32931951
51      3264    32932641    32932641    32932641   32932641   32932641
52      3360    32933601    32933601    32933601   32933601   32933601
53      3456    32934561    32934561    32934561   32934561   32934561
54      3552    32935521    32935521    32935521   32935521   32935521
55      3606    32936061    32936061    32936061   32936061   32936061
56      3648    32936481    32936481    32936481   32936481   32936481
57      3744    32937441    32937441    32937441   32937441   32937441
58      3840    32938401    32938401    32938401   32938401   32938401
59      3936    32939361    32939361    32939361   32939361   32939361
60      4032    32940321    32940321    32940321   32940321   32940321
61      4096    32940961    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0           0
1    3290096221           0  32900961020   329009640           0  3290096124
2    3290108234           0  32901081471   329010844           0  3290108114
3    3290139545           0   3290139119  3290139138           0  3290139261
4    3290188538           0    329018879  3290188197           0  3290188285
5    3290192554           0    329019278  3290192195           0  3290192291
6    3290225544           0    329022582  3290225210  3290225189  3290225307
7    3290275579           0    329027574  3290275196  3290275121  3290275307
8    3290288619           0    329028872  3290288186  3290288109  3290288300
9    3290347581           0    329034758  3290347164   329034764  3290347281
10   3290384579           0    329038460  3290384127   329038446  3290384281
11   3290457588           0    329045751  3290457104   329045736  3290457298
12   3290480583           0    329048049  3290480102   329048032  3290480324
13   3290576536           0    329057638   329057696   329057626  3290576383
14   3290637554           0    329063738  3290637104   329063727  3290637432
15   3290672559           0    329067235  3290672100   329067221  3290672445
16   3290768567           0    329076836   329076886   329076824  3290768468
17   3290777570           0    329077736   329077786   329077723  3290777467
18   3290864555           0    329086434   329086477   329086420  3290864451
19   3290960543           0    329096033   329096073   329096021  3290960483
20   3290974534           0    329097431   329097473   329097420  3290974478
21   3291056562           0    329105639   329105668   329105622  3291056516
22   3291106741           0    329110652   329110666   329110622  3291106605
23   3291152887           0    329115265   329115271   329115223  3291152630
24  32912481314           0    329124869   329124868   329124825  3291248663
25   3291270963           0    329127068   329127066   329127026  3291270664
26   3291344954           0    329134471   329134461   329134424  3291344669
27   3291440948           0    329144073   329144058   329144021  3291440664
28   3291476953           0    329147674   329147661   329147621  3291476662
29   3291536954           0    329153675   329153662   329153634  3291536656
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043  3291740718
33  32918241363           0    329182478   329182462   329182445  3291824721
34  32919201657           0    329192075   329192057   329192047  3291920729
35  32920161763           0    329201673   329201653   329201648  3292016729
36  32920881809           0   3292088210   329208852   329208849  3292088728
37  32921121823           0   3292112188   329211251   329211250  3292112723

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481740126', '1481920137', '1482048142', '1482088142', '1482112141', '1482208141', '1482304136', '1482400138', '1482496140', '1482555136', '1482592136', '1482688135', '1482784158', '1482880185', '1482976190', '1483072188', '1483168192', '1483195195', '1483264194', '1483360195', '1483456199', '1483552201', '1483606211', '1483648224', '1483671272', '1483744375', '1483760382', '1483810397', '1483840405', '1483936441', '1484032466', '1484096478']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_126' | NDM=32740 Nstar=1913 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_137' | NDM=29028 Nstar=1913 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_142' | NDM=26562 Nstar=1913 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_142' | NDM=26096 Nstar=1913 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_141' | NDM=25900 Nstar=1913 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_141' | NDM=25253 Nstar=1913 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_136' | NDM=24958 Nstar=1913 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_138' | NDM=24806 Nstar=1913 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_140' | NDM=24717 Nstar=1913 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_136' | NDM=24275 Nstar=1913 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_136' | NDM=24518 Nstar=1913 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_135' | NDM=24032 Nstar=1913 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_158' | NDM=18004 Nstar=1913 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_185' | NDM=14256 Nstar=1911 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_190' | NDM=13274 Nstar=1910 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_188' | NDM=12909 Nstar=1910 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_192' | NDM=12090 Nstar=1909 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_195' | NDM=11928 Nstar=1910 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_194' | NDM=11624 Nstar=1909 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_195' | NDM=11311 Nstar=1909 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_199' | NDM=11012 Nstar=1909 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_201' | NDM=10350 Nstar=1909 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_211' | NDM=9700 Nstar=1909 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_224' | NDM=8743 Nstar=1906 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_272' | NDM=6935 Nstar=1899 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_375' | NDM=4743 Nstar=1751 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_382' | NDM=4616 Nstar=1730 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_397' | NDM=4303 Nstar=1677 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_405' | NDM=4143 Nstar=1639 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_441' | NDM=3572 Nstar=1567 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_466' | NDM=3290 Nstar=1530 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_478' | NDM=3145 Nstar=1512 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1481740126', '1481920137', '1482048142', '1482088142', '1482112141', '1482208141', '1482304136', '1482400138', '1482496140', '1482555136', '1482592136', '1482688135', '1482784158', '1482880185', '1482976190', '1483072188', '1483168192', '1483195195', '1483264194', '1483360195', '1483456199', '1483552201', '1483606211', '1483648224', '1483671272', '1483744375', '1483760382', '1483810397', '1483840405', '1483936441', '1484032466', '1484096478']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0         0          0         0          0         0
1        108          0         0          0         0          0         0
2        128          0         0          0         0          0         0
3        139          0         0          0         0          0         0
4        188          0         0          0         0          0         0
5        225          0         0          0         0          0         0
6        256          0         0          0         0          0         0
7        275          0         0          0         0          0         0
8        347          0         0          0         0          0         0
9        384          0         0          0         0          0         0
10       457          0         0          0         0          0         0
11       512          0         0          0         0          0         0
12       637          0         0          0         0          0         0
13       640          0         0          0         0          0         0
14       777          0         0          0         0          0         0
15       896          0         0          0         0          0         0
16       974          0         0          0         0          0         0
17      1024  148102411  14810245  148102422  14810243  148102416  14810243
18      1106  148110610  14811066  148110620  14811063  148110614  14811063
19      1152   14811521  14811521  148115218  14811523  148115212  14811523
20      1270   14812701  14812701   14812701  14812709  148127014  14812703
21      1280   14812801  14812801   14812801  14812801  148128013  14812804
22      1408   14814081  14814081   14814081  14814081   14814081  14814081
23      1476   14814761  14814761   14814761  14814761   14814761  14814761
24      1536   14815361  14815361   14815361  14815361   14815361  14815361
25      1664   14816641  14816641   14816641  14816641   14816641  14816641
26      1740   14817401  14817401   14817401  14817401   14817401  14817401
27      1920   14819201  14819201   14819201  14819201   14819201  14819201
28      2048   14820481  14820481   14820481  14820481   14820481  14820481
29      2088   14820881  14820881   14820881  14820881   14820881  14820881
30      2112   14821121  14821121   14821121  14821121   14821121  14821121
31      2208   14822081  14822081   14822081  14822081   14822081  14822081
32      2304   14823041  14823041   14823041  14823041   14823041  14823041
33      2400   14824001  14824001   14824001  14824001   14824001  14824001
34      2496   14824961  14824961   14824961  14824961   14824961  14824961
35      2555   14825551  14825551   14825551  14825551   14825551  14825551
36      2592   14825921  14825921   14825921  14825921   14825921  14825921
37      2688   14826881  14826881   14826881  14826881   14826881  14826881
38      2784   14827841  14827841   14827841  14827841   14827841  14827841
39      2880   14828801  14828801   14828801  14828801   14828801  14828801
40      2976   14829761  14829761   14829761  14829761   14829761  14829761
41      3072   14830721  14830721   14830721  14830721   14830721  14830721
42      3168   14831681  14831681   14831681  14831681   14831681  14831681
43      3195   14831951  14831951   14831951  14831951   14831951  14831951
44      3264   14832641  14832641   14832641  14832641   14832641  14832641
45      3360   14833601  14833601   14833601  14833601   14833601  14833601
46      3456   14834561  14834561   14834561  14834561   14834561  14834561
47      3552   14835521  14835521   14835521  14835521   14835521  14835521
48      3606   14836061  14836061   14836061  14836061   14836061  14836061
49      3648   14836481  14836481   14836481  14836481   14836481  14836481
50      3671   14836711  14836711   14836711  14836711   14836711  14836711
51      3744   14837441  14837441   14837441  14837441   14837441  14837441
52      3760   14837601  14837601   14837601  14837601   14837601  14837601
53      3810   14838101  14838101   14838101  14838101   14838101  14838101
54      3840   14838401  14838401   14838401  14838401   14838401  14838401
55      3936   14839361  14839361   14839361  14839361   14839361  14839361
56      4032   14840321  14840321   14840321  14840321   14840321  14840321
57      4096   14840961  14840961   14840961  14840961   14840961  14840961

     14814089  148153610  14829762     ...       14840966  148409663  \
0           0          0         0     ...              0          0
1           0          0         0     ...              0          0
2           0          0         0     ...              0          0
3           0          0         0     ...              0          0
4           0          0         0     ...              0          0
5           0          0         0     ...              0          0
6           0          0         0     ...              0          0
7           0          0         0     ...              0          0
8           0          0         0     ...              0          0
9           0          0         0     ...              0          0
10          0          0         0     ...              0          0
11          0          0         0     ...              0          0
12          0          0         0     ...              0          0
13          0          0         0     ...              0          0
14          0          0         0     ...              0          0
15          0          0         0     ...              0          0
16          0          0         0     ...              0          0
17  148102414  148102415  14810242     ...      148102412  148102483
18  148110612  148110613  14811062     ...       14811069  148110677
19  148115210  148115211  14811522     ...       14811529  148115273
20  148127011  148127012  14812702     ...      148127010  148127071
21  148128010  148128011  14812802     ...       14812809  148128070
22   14814089  148140810  14814082     ...       14814088  148140862
23   14814761  148147616  14814762     ...       14814768  148147669
24   14815361  148153610  14815362     ...       14815368  148153669
25   14816641   14816641  14816642     ...       14816648  148166469
26   14817401   14817401  14817402     ...       14817408  148174064
27   14819201   14819201  14819202     ...       14819208  148192064
28   14820481   14820481  14820482     ...       14820488  148204862
29   14820881   14820881  14820882     ...       14820888  148208862
30   14821121   14821121  14821122     ...       14821128  148211261
31   14822081   14822081  14822082     ...       14822088  148220860
32   14823041   14823041  14823042     ...       14823048  148230461
33   14824001   14824001  14824002     ...       14824008  148240060
34   14824961   14824961  14824962     ...       14824968  148249665
35   14825551   14825551  14825552     ...       14825558  148255565
36   14825921   14825921  14825922     ...       14825928  148259265
37   14826881   14826881  14826882     ...       14826888  148268866
38   14827841   14827841  14827842     ...       14827848  148278465
39   14828801   14828801  14828802     ...       14828808  148288064
40   14829761   14829761  14829762     ...       14829768  148297666
41   14830721   14830721  14830721     ...       14830726  148307267
42   14831681   14831681  14831681     ...       14831688  148316866
43   14831951   14831951  14831951     ...       14831958  148319567
44   14832641   14832641  14832641     ...       14832648  148326468
45   14833601   14833601  14833601     ...       14833607  148336067
46   14834561   14834561  14834561     ...       14834567  148345667
47   14835521   14835521  14835521     ...       14835526  148355266
48   14836061   14836061  14836061     ...       14836066  148360668
49   14836481   14836481  14836481     ...       14836486  148364866
50   14836711   14836711  14836711     ...       14836716  148367167
51   14837441   14837441  14837441     ...       14837446  148374466
52   14837601   14837601  14837601     ...       14837606  148376066
53   14838101   14838101  14838101     ...       14838106  148381065
54   14838401   14838401  14838401     ...       14838406  148384064
55   14839361   14839361  14839361     ...       14839366  148393663
56   14840321   14840321  14840321     ...       14840326  148403262
57   14840961   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0
5             0           0
6             0           0
7             0           0
8             0           0
9             0           0
10            0           0
11            0           0
12            0           0
13            0           0
14            0           0
15            0           0
16            0           0
17            0           0
18            0           0
19            0           0
20            0           0
21            0           0
22            0           0
23            0           0
24            0           0
25            0  1481664583
26            0  1481740675
27            0  1481920723
28            0  1482048709
29  14820883070  1482088716
30  14821123108  1482112721
31  14822083288  1482208764
32  14823043356  1482304820
33  14824003391  1482400761
34  14824964889  1482496764
35  14825555134  1482555761
36  14825925307  1482592774
37  14826885446  1482688844
38  14827845472  1482784888
39  14828805569  1482880871
40  14829766423  1482976861
41  14830726494  1483072837
42  14831686490  1483168827
43  14831956438  1483195823
44  14832646491  1483264814
45  14833606420  1483360815
46  14834566949  1483456812
47  14835527642  1483552798
48  14836067699  1483606789
49  14836487660  1483648782
50  14836717573  1483671780
51  14837447690  1483744767
52  14837607621  1483760767
53  14838107661  1483810759
54  14838407640  1483840752
55  14839367781  1483936756
56  14840328859  1484032786
57  14840968565  1484096857

[58 rows x 78 columns]
Finished  1484096478
Finished  1484096478
Completed Count -->  117
Started  3294096350
Started  3294096350
h329 Survivor 350 4096

[0, '329009654', '329010849', '3290139139', '3290188151', '3290192152', '3290225138', '3290275110', '3290288105', '329034793', '329038485', '329045777', '329048083', '329057671', '329063768', '329067260', '329076851', '329077751', '329086448', '329096054', '329097454', '329105649', '329110645', '329115248', '329124848', '329127048', '329134446', '329144044', '329147645', '329153647', '329163248', '329172850', '329174050', '329182450', '329192049', '329201660', '329208887', '329211289', '329220891', '329230497', '3292400104', '3292496110', '3292555113', '3292592117', '3292688113', '3292784116', '3292880120', '3292976123', '3293072189', '3293168200', '3293195202', '3293264202', '3293360214', '3293456218', '3293552219', '3293606224', '3293648226', '3293744231', '3293840230', '3293936241', '3294032344', '3294096350']
[-1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096/halo_54' | NDM=1517 Nstar=26 Ngas=167>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108/halo_49' | NDM=1794 Nstar=26 Ngas=303>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_139' | NDM=2632 Nstar=26 Ngas=425>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_151' | NDM=4245 Nstar=26 Ngas=281>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_152' | NDM=4380 Nstar=26 Ngas=267>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_138' | NDM=4857 Nstar=26 Ngas=240>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_110' | NDM=8503 Nstar=26 Ngas=450>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_105' | NDM=9383 Nstar=26 Ngas=484>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_93' | NDM=12962 Nstar=26 Ngas=523>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_85' | NDM=15464 Nstar=26 Ngas=672>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_77' | NDM=17477 Nstar=26 Ngas=583>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_83' | NDM=17553 Nstar=26 Ngas=459>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_71' | NDM=19337 Nstar=26 Ngas=170>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_68' | NDM=20373 Nstar=26 Ngas=88>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_60' | NDM=21619 Nstar=26 Ngas=72>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_51' | NDM=23649 Nstar=26 Ngas=46>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_51' | NDM=23851 Nstar=26 Ngas=40>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_48' | NDM=25822 Nstar=26 Ngas=34>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_54' | NDM=23683 Nstar=26 Ngas=21>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_54' | NDM=23247 Nstar=26 Ngas=21>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_49' | NDM=29386 Nstar=26 Ngas=42>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_45' | NDM=30536 Nstar=26 Ngas=75>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_48' | NDM=31126 Nstar=26 Ngas=79>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_48' | NDM=31434 Nstar=26 Ngas=79>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_48' | NDM=31395 Nstar=26 Ngas=80>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_46' | NDM=31113 Nstar=26 Ngas=60>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_44' | NDM=31210 Nstar=26 Ngas=25>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_45' | NDM=31415 Nstar=26 Ngas=21>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_47' | NDM=31484 Nstar=26 Ngas=21>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_48' | NDM=31423 Nstar=26 Ngas=21>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_50' | NDM=31369 Nstar=26 Ngas=21>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_50' | NDM=31384 Nstar=26 Ngas=21>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_50' | NDM=31298 Nstar=26 Ngas=20>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_49' | NDM=30480 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_60' | NDM=22412 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_87' | NDM=13774 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_89' | NDM=13742 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_91' | NDM=13011 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_97' | NDM=12043 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_104' | NDM=11121 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_110' | NDM=10540 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_113' | NDM=10350 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_117' | NDM=10265 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_113' | NDM=10054 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_116' | NDM=9846 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_120' | NDM=9639 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_123' | NDM=9192 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_189' | NDM=5412 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_200' | NDM=5081 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_202' | NDM=5019 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_202' | NDM=4821 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_214' | NDM=4626 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_218' | NDM=4475 Nstar=26 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_219' | NDM=4369 Nstar=25 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_224' | NDM=4317 Nstar=25 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_226' | NDM=4288 Nstar=25 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_231' | NDM=4228 Nstar=25 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_230' | NDM=4154 Nstar=25 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_241' | NDM=3985 Nstar=25 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_344' | NDM=2540 Nstar=21 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_350' | NDM=2437 Nstar=21 Ngas=0>]
[0, '329009654', '329010849', '3290139139', '3290188151', '3290192152', '3290225138', '3290275110', '3290288105', '329034793', '329038485', '329045777', '329048083', '329057671', '329063768', '329067260', '329076851', '329077751', '329086448', '329096054', '329097454', '329105649', '329110645', '329115248', '329124848', '329127048', '329134446', '329144044', '329147645', '329153647', '329163248', '329172850', '329174050', '329182450', '329192049', '329201660', '329208887', '329211289', '329220891', '329230497', '3292400104', '3292496110', '3292555113', '3292592117', '3292688113', '3292784116', '3292880120', '3292976123', '3293072189', '3293168200', '3293195202', '3293264202', '3293360214', '3293456218', '3293552219', '3293606224', '3293648226', '3293744231', '3293840230', '3293936241', '3294032344', '3294096350']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71           0           0           0          0          0
1         96   329009638   329009662    32900969          0          0
2        108   329010830   329010856   329010810          0  329010836
3        139   329013986  3290139151   329013963  329013935  329013959
4        188  3290188153  3290188114  3290188111  329018827  329018833
5        192    32901921  3290192110  3290192111  329019225  329019230
6        225    32902251    32902251    32902251   32902251   32902251
7        275    32902751    32902751    32902751   32902751   32902751
8        288    32902881    32902881    32902881   32902881   32902881
9        347    32903471    32903471    32903471   32903471   32903471
10       384    32903841    32903841    32903841   32903841   32903841
11       457    32904571    32904571    32904571   32904571   32904571
12       480    32904801    32904801    32904801   32904801   32904801
13       576    32905761    32905761    32905761   32905761   32905761
14       637    32906371    32906371    32906371   32906371   32906371
15       672    32906721    32906721    32906721   32906721   32906721
16       768    32907681    32907681    32907681   32907681   32907681
17       777    32907771    32907771    32907771   32907771   32907771
18       864    32908641    32908641    32908641   32908641   32908641
19       960    32909601    32909601    32909601   32909601   32909601
20       974    32909741    32909741    32909741   32909741   32909741
21      1056    32910561    32910561    32910561   32910561   32910561
22      1106    32911061    32911061    32911061   32911061   32911061
23      1152    32911521    32911521    32911521   32911521   32911521
24      1248    32912481    32912481    32912481   32912481   32912481
25      1270    32912701    32912701    32912701   32912701   32912701
26      1344    32913441    32913441    32913441   32913441   32913441
27      1440    32914401    32914401    32914401   32914401   32914401
28      1476    32914761    32914761    32914761   32914761   32914761
29      1536    32915361    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740    32917401    32917401    32917401   32917401   32917401
33      1824    32918241    32918241    32918241   32918241   32918241
34      1920    32919201    32919201    32919201   32919201   32919201
35      2016    32920161    32920161    32920161   32920161   32920161
36      2088    32920881    32920881    32920881   32920881   32920881
37      2112    32921121    32921121    32921121   32921121   32921121
38      2208    32922081    32922081    32922081   32922081   32922081
39      2304    32923041    32923041    32923041   32923041   32923041
40      2400    32924001    32924001    32924001   32924001   32924001
41      2496    32924961    32924961    32924961   32924961   32924961
42      2555    32925551    32925551    32925551   32925551   32925551
43      2592    32925921    32925921    32925921   32925921   32925921
44      2688    32926881    32926881    32926881   32926881   32926881
45      2784    32927841    32927841    32927841   32927841   32927841
46      2880    32928801    32928801    32928801   32928801   32928801
47      2976    32929761    32929761    32929761   32929761   32929761
48      3072    32930721    32930721    32930721   32930721   32930721
49      3168    32931681    32931681    32931681   32931681   32931681
50      3195    32931951    32931951    32931951   32931951   32931951
51      3264    32932641    32932641    32932641   32932641   32932641
52      3360    32933601    32933601    32933601   32933601   32933601
53      3456    32934561    32934561    32934561   32934561   32934561
54      3552    32935521    32935521    32935521   32935521   32935521
55      3606    32936061    32936061    32936061   32936061   32936061
56      3648    32936481    32936481    32936481   32936481   32936481
57      3744    32937441    32937441    32937441   32937441   32937441
58      3840    32938401    32938401    32938401   32938401   32938401
59      3936    32939361    32939361    32939361   32939361   32939361
60      4032    32940321    32940321    32940321   32940321   32940321
61      4096    32940961    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0           0
1    3290096221           0  32900961020   329009640           0  3290096124
2    3290108234           0  32901081471   329010844           0  3290108114
3    3290139545           0   3290139119  3290139138           0  3290139261
4    3290188538           0    329018879  3290188197           0  3290188285
5    3290192554           0    329019278  3290192195           0  3290192291
6    3290225544           0    329022582  3290225210  3290225189  3290225307
7    3290275579           0    329027574  3290275196  3290275121  3290275307
8    3290288619           0    329028872  3290288186  3290288109  3290288300
9    3290347581           0    329034758  3290347164   329034764  3290347281
10   3290384579           0    329038460  3290384127   329038446  3290384281
11   3290457588           0    329045751  3290457104   329045736  3290457298
12   3290480583           0    329048049  3290480102   329048032  3290480324
13   3290576536           0    329057638   329057696   329057626  3290576383
14   3290637554           0    329063738  3290637104   329063727  3290637432
15   3290672559           0    329067235  3290672100   329067221  3290672445
16   3290768567           0    329076836   329076886   329076824  3290768468
17   3290777570           0    329077736   329077786   329077723  3290777467
18   3290864555           0    329086434   329086477   329086420  3290864451
19   3290960543           0    329096033   329096073   329096021  3290960483
20   3290974534           0    329097431   329097473   329097420  3290974478
21   3291056562           0    329105639   329105668   329105622  3291056516
22   3291106741           0    329110652   329110666   329110622  3291106605
23   3291152887           0    329115265   329115271   329115223  3291152630
24  32912481314           0    329124869   329124868   329124825  3291248663
25   3291270963           0    329127068   329127066   329127026  3291270664
26   3291344954           0    329134471   329134461   329134424  3291344669
27   3291440948           0    329144073   329144058   329144021  3291440664
28   3291476953           0    329147674   329147661   329147621  3291476662
29   3291536954           0    329153675   329153662   329153634  3291536656
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043  3291740718
33  32918241363           0    329182478   329182462   329182445  3291824721
34  32919201657           0    329192075   329192057   329192047  3291920729
35  32920161763           0    329201673   329201653   329201648  3292016729
36  32920881809           0   3292088210   329208852   329208849  3292088728
37  32921121823           0   3292112188   329211251   329211250  3292112723
38  32922081833           0   3292208214   329220850   329220848  3292208722
39  32923041843           0   3292304234   329230450   329230449  3292304732
40  32924001879           0   3292400261   329240048   329240050  3292400787
41  32924962122           0   3292496271   329249648   329249650  3292496824
42  32925552182           0   3292555278   329255548   329255551  3292555828
43  32925922176           0   3292592282   329259249   329259252  3292592829
44  32926882164           0   3292688286   329268849   329268853  3292688812
45  32927842152           0   3292784291   329278449   329278454  3292784818
46  32928802121           0   3292880313   329288050   329288057  3292880812

[0, 0, 0, '329013937', '329018844', '329019241', '329022548', '329027524', '329028827', '329034731', '329038426', '329045728', '329048034', '32905761', '32906371', '32906721', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[-1.0 -1.0 -1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_37' | NDM=7433 Nstar=0 Ngas=6879>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_44' | NDM=11736 Nstar=87 Ngas=12360>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_41' | NDM=11857 Nstar=96 Ngas=12644>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_48' | NDM=12812 Nstar=237 Ngas=15109>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_24' | NDM=44270 Nstar=638 Ngas=38155>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_27' | NDM=49275 Nstar=2255 Ngas=34127>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_31' | NDM=41995 Nstar=2488 Ngas=38637>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_26' | NDM=45718 Nstar=3120 Ngas=53872>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_28' | NDM=46437 Nstar=3517 Ngas=35576>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_34' | NDM=42161 Nstar=3785 Ngas=32504>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_1' | NDM=5065263 Nstar=1530172 Ngas=2738713>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_1' | NDM=7451554 Nstar=2236951 Ngas=4644431>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_1' | NDM=8496675 Nstar=2702944 Ngas=5442931>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_1' | NDM=10617049 Nstar=3856093 Ngas=7275738>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_1' | NDM=10872015 Nstar=3980353 Ngas=7482669>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_1' | NDM=12715287 Nstar=5722615 Ngas=9000800>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_1' | NDM=15028263 Nstar=7698307 Ngas=11059109>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_1' | NDM=15196786 Nstar=7990531 Ngas=11217754>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1' | NDM=15578696 Nstar=10217161 Ngas=11755160>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1' | NDM=15747259 Nstar=11784296 Ngas=11968198>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1' | NDM=15761360 Nstar=13147640 Ngas=12285340>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1' | NDM=15832293 Nstar=16238307 Ngas=12845015>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1' | NDM=15990494 Nstar=17157603 Ngas=12930029>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1' | NDM=17922263 Nstar=20611248 Ngas=14418911>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1' | NDM=20220937 Nstar=24755716 Ngas=15683385>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1' | NDM=20568424 Nstar=26701663 Ngas=15670524>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1' | NDM=21292522 Nstar=29070320 Ngas=16200299>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1' | NDM=22138471 Nstar=34143108 Ngas=16098369>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1' | NDM=22233114 Nstar=37948971 Ngas=16217261>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1' | NDM=22265580 Nstar=38395660 Ngas=16249600>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1' | NDM=22541017 Nstar=41934879 Ngas=16143723>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1' | NDM=23087646 Nstar=46137673 Ngas=15803476>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1' | NDM=23617232 Nstar=50351876 Ngas=15643527>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1' | NDM=24221915 Nstar=53530614 Ngas=15566115>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1' | NDM=24513553 Nstar=54733955 Ngas=15453339>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1' | NDM=26676353 Nstar=59100003 Ngas=16082599>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1' | NDM=29354421 Nstar=64311453 Ngas=16874211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1' | NDM=31464533 Nstar=68631869 Ngas=16998639>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1' | NDM=32730524 Nstar=72629063 Ngas=17093857>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1' | NDM=33576743 Nstar=76168219 Ngas=16582991>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1' | NDM=34007948 Nstar=77829519 Ngas=16271248>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1' | NDM=34817467 Nstar=82227069 Ngas=16133249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1' | NDM=35279749 Nstar=86891324 Ngas=15727574>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1' | NDM=34968677 Nstar=91010100 Ngas=14700620>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1' | NDM=34685343 Nstar=94725659 Ngas=13794122>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1' | NDM=34411771 Nstar=98430465 Ngas=12965040>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
[0, 0, 0, '329013937', '329018844', '329019241', '329022548', '329027524', '329028827', '329034731', '329038426', '329045728', '329048034', '32905761', '32906371', '32906721', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71           0           0           0          0          0
1         96   329009638   329009662    32900969          0          0
2        108   329010830   329010856   329010810          0  329010836
3        139   329013986  3290139151   329013963  329013935  329013959
4        188  3290188153  3290188114  3290188111  329018827  329018833
5        192    32901921  3290192110  3290192111  329019225  329019230
6        225    32902251    32902251    32902251   32902251   32902251
7        275    32902751    32902751    32902751   32902751   32902751
8        288    32902881    32902881    32902881   32902881   32902881
9        347    32903471    32903471    32903471   32903471   32903471
10       384    32903841    32903841    32903841   32903841   32903841
11       457    32904571    32904571    32904571   32904571   32904571
12       480    32904801    32904801    32904801   32904801   32904801
13       576    32905761    32905761    32905761   32905761   32905761
14       637    32906371    32906371    32906371   32906371   32906371
15       672    32906721    32906721    32906721   32906721   32906721
16       768    32907681    32907681    32907681   32907681   32907681
17       777    32907771    32907771    32907771   32907771   32907771
18       864    32908641    32908641    32908641   32908641   32908641
19       960    32909601    32909601    32909601   32909601   32909601
20       974    32909741    32909741    32909741   32909741   32909741
21      1056    32910561    32910561    32910561   32910561   32910561
22      1106    32911061    32911061    32911061   32911061   32911061
23      1152    32911521    32911521    32911521   32911521   32911521
24      1248    32912481    32912481    32912481   32912481   32912481
25      1270    32912701    32912701    32912701   32912701   32912701
26      1344    32913441    32913441    32913441   32913441   32913441
27      1440    32914401    32914401    32914401   32914401   32914401
28      1476    32914761    32914761    32914761   32914761   32914761
29      1536    32915361    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740    32917401    32917401    32917401   32917401   32917401
33      1824    32918241    32918241    32918241   32918241   32918241
34      1920    32919201    32919201    32919201   32919201   32919201
35      2016    32920161    32920161    32920161   32920161   32920161
36      2088    32920881    32920881    32920881   32920881   32920881
37      2112    32921121    32921121    32921121   32921121   32921121
38      2208    32922081    32922081    32922081   32922081   32922081
39      2304    32923041    32923041    32923041   32923041   32923041
40      2400    32924001    32924001    32924001   32924001   32924001
41      2496    32924961    32924961    32924961   32924961   32924961
42      2555    32925551    32925551    32925551   32925551   32925551
43      2592    32925921    32925921    32925921   32925921   32925921
44      2688    32926881    32926881    32926881   32926881   32926881
45      2784    32927841    32927841    32927841   32927841   32927841
46      2880    32928801    32928801    32928801   32928801   32928801
47      2976    32929761    32929761    32929761   32929761   32929761
48      3072    32930721    32930721    32930721   32930721   32930721
49      3168    32931681    32931681    32931681   32931681   32931681
50      3195    32931951    32931951    32931951   32931951   32931951
51      3264    32932641    32932641    32932641   32932641   32932641
52      3360    32933601    32933601    32933601   32933601   32933601
53      3456    32934561    32934561    32934561   32934561   32934561
54      3552    32935521    32935521    32935521   32935521   32935521
55      3606    32936061    32936061    32936061   32936061   32936061
56      3648    32936481    32936481    32936481   32936481   32936481
57      3744    32937441    32937441    32937441   32937441   32937441
58      3840    32938401    32938401    32938401   32938401   32938401
59      3936    32939361    32939361    32939361   32939361   32939361
60      4032    32940321    32940321    32940321   32940321   32940321
61      4096    32940961    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0           0
1    3290096221           0  32900961020   329009640           0  3290096124
2    3290108234           0  32901081471   329010844           0  3290108114
3    3290139545           0   3290139119  3290139138           0  3290139261
4    3290188538           0    329018879  3290188197           0  3290188285
5    3290192554           0    329019278  3290192195           0  3290192291
6    3290225544           0    329022582  3290225210  3290225189  3290225307
7    3290275579           0    329027574  3290275196  3290275121  3290275307
8    3290288619           0    329028872  3290288186  3290288109  3290288300
9    3290347581           0    329034758  3290347164   329034764  3290347281
10   3290384579           0    329038460  3290384127   329038446  3290384281
11   3290457588           0    329045751  3290457104   329045736  3290457298
12   3290480583           0    329048049  3290480102   329048032  3290480324
13   3290576536           0    329057638   329057696   329057626  3290576383
14   3290637554           0    329063738  3290637104   329063727  3290637432
15   3290672559           0    329067235  3290672100   329067221  3290672445
16   3290768567           0    329076836   329076886   329076824  3290768468
17   3290777570           0    329077736   329077786   329077723  3290777467
18   3290864555           0    329086434   329086477   329086420  3290864451
19   3290960543           0    329096033   329096073   329096021  3290960483
20   3290974534           0    329097431   329097473   329097420  3290974478
21   3291056562           0    329105639   329105668   329105622  3291056516
22   3291106741           0    329110652   329110666   329110622  3291106605
23   3291152887           0    329115265   329115271   329115223  3291152630
24  32912481314           0    329124869   329124868   329124825  3291248663
25   3291270963           0    329127068   329127066   329127026  3291270664
26   3291344954           0    329134471   329134461   329134424  3291344669
27   3291440948           0    329144073   329144058   329144021  3291440664
28   3291476953           0    329147674   329147661   329147621  3291476662
29   3291536954           0    329153675   329153662   329153634  3291536656
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043  3291740718
33  32918241363           0    329182478   329182462   329182445  3291824721
34  32919201657           0    329192075   329192057   329192047  3291920729
35  32920161763           0    329201673   329201653   329201648  3292016729
36  32920881809           0   3292088210   329208852   329208849  3292088728
37  32921121823           0   3292112188   329211251   329211250  3292112723
38  32922081833           0   3292208214   329220850   329220848  3292208722
39  32923041843           0   3292304234   329230450   329230449  3292304732
40  32924001879           0   3292400261   329240048   329240050  3292400787
41  32924962122           0   3292496271   329249648   329249650  3292496824

['329007153', '3290096158', '3290108155', '3290139385', '3290188324', '3290192316', '3290225281', '3290275295', '3290288301', '3290347322', '3290384328', '3290457387', '3290480429', '3290576585', '3290637662', '3290672696', '3290768792', '3290777801', '3290864861', '3290960921', '3290974925', '32910561163', '32911061242', '32911521233', '32912481380', '32912701390', '32913441393', '32914401366', '32914761361', '32915361343', '32916321341', '32917281324', '32917401323', '32918241311', '32919201299', '32920161274', '32920881270', '32921121265', '32922081248', '32923041245', '32924001847', '32924961965', '32925551966', '32925921993', '32926881981', '32927842006', '32928801984', '32929761961', '32930721935', '32931682082', '32931952970', '32932643278', '32933603297', '32934563330', '32935523357', '32936063340', '32936483368', '32937443379', '32938403362', '32939363311', '32940323293', '32940963299']
[ <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000071/halo_53' | NDM=531 Nstar=0 Ngas=432>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096/halo_158' | NDM=696 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108/halo_155' | NDM=797 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_385' | NDM=956 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_324' | NDM=1692 Nstar=10 Ngas=6>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_316' | NDM=1756 Nstar=10 Ngas=8>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_281' | NDM=2343 Nstar=10 Ngas=8>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_295' | NDM=2718 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_301' | NDM=2721 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_322' | NDM=2820 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_328' | NDM=2891 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_387' | NDM=2668 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_429' | NDM=2511 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_585' | NDM=2004 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_662' | NDM=1877 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_696' | NDM=1806 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_792' | NDM=1651 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_801' | NDM=1629 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_861' | NDM=1522 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_921' | NDM=1429 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_925' | NDM=1417 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1163' | NDM=1111 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1242' | NDM=1034 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1233' | NDM=1049 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1380' | NDM=926 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1390' | NDM=916 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1393' | NDM=902 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1366' | NDM=890 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1361' | NDM=879 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1343' | NDM=872 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1341' | NDM=858 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1324' | NDM=857 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1323' | NDM=857 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1311' | NDM=857 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1299' | NDM=850 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1274' | NDM=853 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1270' | NDM=854 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1265' | NDM=854 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1248' | NDM=853 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1245' | NDM=842 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1847' | NDM=538 Nstar=9 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1965' | NDM=492 Nstar=9 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1966' | NDM=484 Nstar=9 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1993' | NDM=475 Nstar=8 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1981' | NDM=465 Nstar=8 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_2006' | NDM=452 Nstar=8 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1984' | NDM=448 Nstar=8 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1961' | NDM=446 Nstar=8 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1935' | NDM=444 Nstar=8 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_2082' | NDM=403 Nstar=8 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_2970' | NDM=272 Nstar=4 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_3278' | NDM=239 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_3297' | NDM=233 Nstar=4 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_3330' | NDM=227 Nstar=4 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_3357' | NDM=223 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_3340' | NDM=222 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_3368' | NDM=219 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_3379' | NDM=216 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_3362' | NDM=215 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_3311' | NDM=215 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_3293' | NDM=214 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_3299' | NDM=212 Nstar=3 Ngas=0>]
Watch me go for the  12 th time...
Already Exists  14840961025
Completed Count -->  119
Already Exists  14832642
Completed Count -->  119
Already Exists  14840964127
Completed Count -->  119
Already Exists  32913443
Completed Count -->  119
Already Exists  14840961061
Completed Count -->  119
Already Exists  14812709
Completed Count -->  119
Already Exists  329022513
Completed Count -->  119
Already Exists  1484096567
Completed Count -->  119
Already Exists  3294096956
Completed Count -->  119
Already Exists  32940964414
Completed Count -->  119
Already Exists  329022530
Completed Count -->  119
Already Exists  329409616
Completed Count -->  119
Already Exists  329038417
Completed Count -->  119
Already Exists  329409620
Completed Count -->  119
Already Exists  329038430
Completed Count -->  119
Already Exists  329127010
Completed Count -->  119
Already Exists  329038438
Completed Count -->  119
Already Exists  32904809
Completed Count -->  119
Already Exists  329409643
Completed Count -->  119
Already Exists  148409620589
Completed Count -->  119
Already Exists  329022579
Completed Count -->  119
Already Exists  14840962
Completed Count -->  119
Already Exists  14840963
Completed Count -->  119
Already Exists  14840961156
Completed Count -->  119
Already Exists  14840964
Completed Count -->  119
Already Exists  14840965
Completed Count -->  119
Already Exists  14840966
Completed Count -->  119
Already Exists  14840967
Completed Count -->  119
Already Exists  14812804
Completed Count -->  119
Already Exists  1484096138
Completed Count -->  119
Already Exists  329409673
Completed Count -->  119
Already Exists  329409675
Completed Count -->  119
Already Exists  32906374
Completed Count -->  119
Already Exists  32940965015
Completed Count -->  119
Already Exists  14840961179
Completed Count -->  119
Already Exists  14840961693
Completed Count -->  119
Already Exists  329409696
Completed Count -->  119
Already Exists  3294096555
Completed Count -->  119
Already Exists  1484096179
Completed Count -->  119
Already Exists  1484096194
Completed Count -->  119
Already Exists  14829762
Completed Count -->  119
Already Exists  3294096585
Completed Count -->  119
Already Exists  329067210
Completed Count -->  119
Already Exists  1484096204
Completed Count -->  119
Already Exists  1484096210
Completed Count -->  119
Already Exists  32933603
Completed Count -->  119
Already Exists  3290192110
Completed Count -->  119
Already Exists  3290192111
Completed Count -->  119
Already Exists  148409613555
Completed Count -->  119
Already Exists  148409619718
Completed Count -->  119
Already Exists  148153610
Completed Count -->  119
Already Exists  148409610
Completed Count -->  119
Already Exists  148409611
Completed Count -->  119
Already Exists  148409612
Completed Count -->  119
Already Exists  148128013
Completed Count -->  119
Already Exists  1484096271
Completed Count -->  119
Already Exists  14840965903
Completed Count -->  119
Already Exists  148409617
Completed Count -->  119
Already Exists  148110610
Completed Count -->  119
Already Exists  148115218
Completed Count -->  119
Already Exists  148409621
Completed Count -->  119
Already Exists  1484096278
Completed Count -->  119
Already Exists  148409622
Completed Count -->  119
Already Exists  148409632
Completed Count -->  119
Already Exists  148409633
Completed Count -->  119
Already Exists  148409634
Completed Count -->  119
Already Exists  148409635
Completed Count -->  119
Already Exists  1484096803
Completed Count -->  119
Already Exists  32924962
Completed Count -->  119
Already Exists  148409639
Completed Count -->  119
Already Exists  148409641
Completed Count -->  119
Already Exists  148409651
Completed Count -->  119
Already Exists  148409653
Completed Count -->  119
Already Exists  148409655
Completed Count -->  119
Already Exists  14840964409
Completed Count -->  119
Already Exists  148409663
Completed Count -->  119
Already Exists  148409668
Completed Count -->  119
Already Exists  1484096266
Completed Count -->  119
Already Exists  1484096331
Completed Count -->  119
Already Exists  148409676
Completed Count -->  119
Already Exists  148409677
Completed Count -->  119
Already Exists  329096015
Completed Count -->  119
Already Exists  14840964944
Completed Count -->  119
Already Exists  32914768
Completed Count -->  119
Already Exists  1484096857
Completed Count -->  119
Already Exists  329019225
Completed Count -->  119
Already Exists  14840961883
Completed Count -->  119
Already Exists  32940961630
Completed Count -->  119
Already Exists  14840967007
Completed Count -->  119
Already Exists  329019230
Completed Count -->  119
Already Exists  14840961379
Completed Count -->  119
Already Exists  32908648
Completed Count -->  119
Already Exists  14840961900
Completed Count -->  119
Already Exists  14840962413
Completed Count -->  119
Already Exists  14840962927
Completed Count -->  119
Already Exists  32940961648
Completed Count -->  119
Already Exists  14840968565
Completed Count -->  119
Already Exists  1484096374
Completed Count -->  119
Already Exists  3290188153
Completed Count -->  119
Already Exists  3294096768
Completed Count -->  119
Already Exists  1484096387
Completed Count -->  119
Already Exists  14840961413
Completed Count -->  119
Already Exists  14814089
Completed Count -->  119
Already Exists  1484096412
Completed Count -->  119
Already Exists  32930722
Completed Count -->  119
Already Exists  1484096422
Completed Count -->  119
Already Exists  32940969
Completed Count -->  119
Already Exists  148409612211
Completed Count -->  119
Already Exists  32909747
Completed Count -->  119
Already Exists  14840964022
Completed Count -->  119
Already Exists  14811066
Completed Count -->  119
Already Exists  14840961467
Completed Count -->  119
Already Exists  1484096459
Completed Count -->  119
Already Exists  329048011
Completed Count -->  119
Already Exists  3294096335
Completed Count -->  119
Already Exists  329048022
Completed Count -->  119
Already Exists  1484096478
Completed Count -->  119
Already Exists  3294096350
Completed Count -->  119
Already Exists  329048034
Completed Count -->  119
Started  32940963299
Started  32940963299
h329 Survivor 3299 4096

['329007153', '3290096158', '3290108155', '3290139385', '3290188324', '3290192316', '3290225281', '3290275295', '3290288301', '3290347322', '3290384328', '3290457387', '3290480429', '3290576585', '3290637662', '3290672696', '3290768792', '3290777801', '3290864861', '3290960921', '3290974925', '32910561163', '32911061242', '32911521233', '32912481380', '32912701390', '32913441393', '32914401366', '32914761361', '32915361343', '32916321341', '32917281324', '32917401323', '32918241311', '32919201299', '32920161274', '32920881270', '32921121265', '32922081248', '32923041245', '32924001847', '32924961965', '32925551966', '32925921993', '32926881981', '32927842006', '32928801984', '32929761961', '32930721935', '32931682082', '32931952970', '32932643278', '32933603297', '32934563330', '32935523357', '32936063340', '32936483368', '32937443379', '32938403362', '32939363311', '32940323293', '32940963299']
[ <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000071/halo_53' | NDM=531 Nstar=0 Ngas=432>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096/halo_158' | NDM=696 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108/halo_155' | NDM=797 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_385' | NDM=956 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_324' | NDM=1692 Nstar=10 Ngas=6>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_316' | NDM=1756 Nstar=10 Ngas=8>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_281' | NDM=2343 Nstar=10 Ngas=8>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_295' | NDM=2718 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_301' | NDM=2721 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_322' | NDM=2820 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_328' | NDM=2891 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_387' | NDM=2668 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_429' | NDM=2511 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_585' | NDM=2004 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_662' | NDM=1877 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_696' | NDM=1806 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_792' | NDM=1651 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_801' | NDM=1629 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_861' | NDM=1522 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_921' | NDM=1429 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_925' | NDM=1417 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1163' | NDM=1111 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1242' | NDM=1034 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1233' | NDM=1049 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1380' | NDM=926 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1390' | NDM=916 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1393' | NDM=902 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1366' | NDM=890 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1361' | NDM=879 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1343' | NDM=872 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1341' | NDM=858 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1324' | NDM=857 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1323' | NDM=857 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1311' | NDM=857 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1299' | NDM=850 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1274' | NDM=853 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1270' | NDM=854 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1265' | NDM=854 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1248' | NDM=853 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1245' | NDM=842 Nstar=10 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1847' | NDM=538 Nstar=9 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1965' | NDM=492 Nstar=9 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1966' | NDM=484 Nstar=9 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1993' | NDM=475 Nstar=8 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1981' | NDM=465 Nstar=8 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_2006' | NDM=452 Nstar=8 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1984' | NDM=448 Nstar=8 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1961' | NDM=446 Nstar=8 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1935' | NDM=444 Nstar=8 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_2082' | NDM=403 Nstar=8 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_2970' | NDM=272 Nstar=4 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_3278' | NDM=239 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_3297' | NDM=233 Nstar=4 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_3330' | NDM=227 Nstar=4 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_3357' | NDM=223 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_3340' | NDM=222 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_3368' | NDM=219 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_3379' | NDM=216 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_3362' | NDM=215 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_3311' | NDM=215 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_3293' | NDM=214 Nstar=3 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_3299' | NDM=212 Nstar=3 Ngas=0>]
[0, '3290096158', '3290108155', '3290139385', '3290188324', '3290192316', '3290225281', '3290275295', '3290288301', '3290347322', '3290384328', '3290457387', '3290480429', '3290576585', '3290637662', '3290672696', '3290768792', '3290777801', '3290864861', '3290960921', '3290974925', '32910561163', '32911061242', '32911521233', '32912481380', '32912701390', '32913441393', '32914401366', '32914761361', '32915361343', '32916321341', '32917281324', '32917401323', '32918241311', '32919201299', '32920161274', '32920881270', '32921121265', '32922081248', '32923041245', '32924001847', '32924961965', '32925551966', '32925921993', '32926881981', '32927842006', '32928801984', '32929761961', '32930721935', '32931682082', '32931952970', '32932643278', '32933603297', '32934563330', '32935523357', '32936063340', '32936483368', '32937443379', '32938403362', '32939363311', '32940323293', '32940963299']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71           0           0           0          0          0
1         96   329009638   329009662    32900969          0          0
2        108   329010830   329010856   329010810          0  329010836
3        139   329013986  3290139151   329013963  329013935  329013959
4        188  3290188153  3290188114  3290188111  329018827  329018833
5        192    32901921  3290192110  3290192111  329019225  329019230
6        225    32902251    32902251    32902251   32902251   32902251
7        275    32902751    32902751    32902751   32902751   32902751
8        288    32902881    32902881    32902881   32902881   32902881
9        347    32903471    32903471    32903471   32903471   32903471
10       384    32903841    32903841    32903841   32903841   32903841
11       457    32904571    32904571    32904571   32904571   32904571
12       480    32904801    32904801    32904801   32904801   32904801
13       576    32905761    32905761    32905761   32905761   32905761
14       637    32906371    32906371    32906371   32906371   32906371
15       672    32906721    32906721    32906721   32906721   32906721
16       768    32907681    32907681    32907681   32907681   32907681
17       777    32907771    32907771    32907771   32907771   32907771
18       864    32908641    32908641    32908641   32908641   32908641
19       960    32909601    32909601    32909601   32909601   32909601
20       974    32909741    32909741    32909741   32909741   32909741
21      1056    32910561    32910561    32910561   32910561   32910561
22      1106    32911061    32911061    32911061   32911061   32911061
23      1152    32911521    32911521    32911521   32911521   32911521
24      1248    32912481    32912481    32912481   32912481   32912481
25      1270    32912701    32912701    32912701   32912701   32912701
26      1344    32913441    32913441    32913441   32913441   32913441
27      1440    32914401    32914401    32914401   32914401   32914401
28      1476    32914761    32914761    32914761   32914761   32914761
29      1536    32915361    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740    32917401    32917401    32917401   32917401   32917401
33      1824    32918241    32918241    32918241   32918241   32918241
34      1920    32919201    32919201    32919201   32919201   32919201
35      2016    32920161    32920161    32920161   32920161   32920161
36      2088    32920881    32920881    32920881   32920881   32920881
37      2112    32921121    32921121    32921121   32921121   32921121
38      2208    32922081    32922081    32922081   32922081   32922081
39      2304    32923041    32923041    32923041   32923041   32923041
40      2400    32924001    32924001    32924001   32924001   32924001
41      2496    32924961    32924961    32924961   32924961   32924961
42      2555    32925551    32925551    32925551   32925551   32925551
43      2592    32925921    32925921    32925921   32925921   32925921
44      2688    32926881    32926881    32926881   32926881   32926881
45      2784    32927841    32927841    32927841   32927841   32927841
46      2880    32928801    32928801    32928801   32928801   32928801
47      2976    32929761    32929761    32929761   32929761   32929761
48      3072    32930721    32930721    32930721   32930721   32930721
49      3168    32931681    32931681    32931681   32931681   32931681
50      3195    32931951    32931951    32931951   32931951   32931951
51      3264    32932641    32932641    32932641   32932641   32932641
52      3360    32933601    32933601    32933601   32933601   32933601
53      3456    32934561    32934561    32934561   32934561   32934561
54      3552    32935521    32935521    32935521   32935521   32935521
55      3606    32936061    32936061    32936061   32936061   32936061
56      3648    32936481    32936481    32936481   32936481   32936481
57      3744    32937441    32937441    32937441   32937441   32937441
58      3840    32938401    32938401    32938401   32938401   32938401
59      3936    32939361    32939361    32939361   32939361   32939361
60      4032    32940321    32940321    32940321   32940321   32940321
61      4096    32940961    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0           0
1    3290096221           0  32900961020   329009640           0  3290096124
2    3290108234           0  32901081471   329010844           0  3290108114
3    3290139545           0   3290139119  3290139138           0  3290139261
4    3290188538           0    329018879  3290188197           0  3290188285
5    3290192554           0    329019278  3290192195           0  3290192291
6    3290225544           0    329022582  3290225210  3290225189  3290225307
7    3290275579           0    329027574  3290275196  3290275121  3290275307
8    3290288619           0    329028872  3290288186  3290288109  3290288300
9    3290347581           0    329034758  3290347164   329034764  3290347281
10   3290384579           0    329038460  3290384127   329038446  3290384281
11   3290457588           0    329045751  3290457104   329045736  3290457298
12   3290480583           0    329048049  3290480102   329048032  3290480324
13   3290576536           0    329057638   329057696   329057626  3290576383
14   3290637554           0    329063738  3290637104   329063727  3290637432
15   3290672559           0    329067235  3290672100   329067221  3290672445
16   3290768567           0    329076836   329076886   329076824  3290768468
17   3290777570           0    329077736   329077786   329077723  3290777467
18   3290864555           0    329086434   329086477   329086420  3290864451
19   3290960543           0    329096033   329096073   329096021  3290960483
20   3290974534           0    329097431   329097473   329097420  3290974478
21   3291056562           0    329105639   329105668   329105622  3291056516
22   3291106741           0    329110652   329110666   329110622  3291106605
23   3291152887           0    329115265   329115271   329115223  3291152630
24  32912481314           0    329124869   329124868   329124825  3291248663
25   3291270963           0    329127068   329127066   329127026  3291270664
26   3291344954           0    329134471   329134461   329134424  3291344669
27   3291440948           0    329144073   329144058   329144021  3291440664
28   3291476953           0    329147674   329147661   329147621  3291476662
29   3291536954           0    329153675   329153662   329153634  3291536656
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043  3291740718
33  32918241363           0    329182478   329182462   329182445  3291824721
34  32919201657           0    329192075   329192057   329192047  3291920729
35  32920161763           0    329201673   329201653   329201648  3292016729
36  32920881809           0   3292088210   329208852   329208849  3292088728
37  32921121823           0   3292112188   329211251   329211250  3292112723
38  32922081833           0   3292208214   329220850   329220848  3292208722
39  32923041843           0   3292304234   329230450   329230449  3292304732
40  32924001879           0   3292400261   329240048   329240050  3292400787
41  32924962122           0   3292496271   329249648   329249650  3292496824
42  32925552182           0   3292555278   329255548   329255551  3292555828
43  32925922176           0   3292592282   329259249   329259252  3292592829

[0, 0, 0, '32901394122', '329018834', '329019234', '329022535', '329027518', '329028819', '329034719', '329038418', '329045715', '329048015', '329057612', '329063710', '32906729', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[-1.0 -1.0 -1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_4122' | NDM=101 Nstar=0 Ngas=0>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_34' | NDM=20124 Nstar=1685 Ngas=9221>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_34' | NDM=20083 Nstar=1685 Ngas=9393>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_35' | NDM=27397 Nstar=1763 Ngas=12238>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_18' | NDM=58415 Nstar=2070 Ngas=31505>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_19' | NDM=65562 Nstar=2175 Ngas=38948>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_19' | NDM=90244 Nstar=2852 Ngas=68982>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_18' | NDM=105404 Nstar=3613 Ngas=90076>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_15' | NDM=126073 Nstar=7248 Ngas=143854>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_15' | NDM=134364 Nstar=8433 Ngas=164703>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_12' | NDM=135887 Nstar=11049 Ngas=208957>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_10' | NDM=144771 Nstar=15484 Ngas=228050>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_9' | NDM=155690 Nstar=17362 Ngas=238796>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_1' | NDM=10617049 Nstar=3856093 Ngas=7275738>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_1' | NDM=10872015 Nstar=3980353 Ngas=7482669>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_1' | NDM=12715287 Nstar=5722615 Ngas=9000800>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_1' | NDM=15028263 Nstar=7698307 Ngas=11059109>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_1' | NDM=15196786 Nstar=7990531 Ngas=11217754>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1' | NDM=15578696 Nstar=10217161 Ngas=11755160>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1' | NDM=15747259 Nstar=11784296 Ngas=11968198>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1' | NDM=15761360 Nstar=13147640 Ngas=12285340>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1' | NDM=15832293 Nstar=16238307 Ngas=12845015>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1' | NDM=15990494 Nstar=17157603 Ngas=12930029>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1' | NDM=17922263 Nstar=20611248 Ngas=14418911>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1' | NDM=20220937 Nstar=24755716 Ngas=15683385>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1' | NDM=20568424 Nstar=26701663 Ngas=15670524>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1' | NDM=21292522 Nstar=29070320 Ngas=16200299>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1' | NDM=22138471 Nstar=34143108 Ngas=16098369>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1' | NDM=22233114 Nstar=37948971 Ngas=16217261>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1' | NDM=22265580 Nstar=38395660 Ngas=16249600>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1' | NDM=22541017 Nstar=41934879 Ngas=16143723>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1' | NDM=23087646 Nstar=46137673 Ngas=15803476>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1' | NDM=23617232 Nstar=50351876 Ngas=15643527>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1' | NDM=24221915 Nstar=53530614 Ngas=15566115>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1' | NDM=24513553 Nstar=54733955 Ngas=15453339>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1' | NDM=26676353 Nstar=59100003 Ngas=16082599>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1' | NDM=29354421 Nstar=64311453 Ngas=16874211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1' | NDM=31464533 Nstar=68631869 Ngas=16998639>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1' | NDM=32730524 Nstar=72629063 Ngas=17093857>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1' | NDM=33576743 Nstar=76168219 Ngas=16582991>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1' | NDM=34007948 Nstar=77829519 Ngas=16271248>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1' | NDM=34817467 Nstar=82227069 Ngas=16133249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1' | NDM=35279749 Nstar=86891324 Ngas=15727574>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1' | NDM=34968677 Nstar=91010100 Ngas=14700620>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1' | NDM=34685343 Nstar=94725659 Ngas=13794122>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1' | NDM=34411771 Nstar=98430465 Ngas=12965040>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
[0, 0, 0, '32901394122', '329018834', '329019234', '329022535', '329027518', '329028819', '329034719', '329038418', '329045715', '329048015', '329057612', '329063710', '32906729', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71           0           0           0          0          0
1         96   329009638   329009662    32900969          0          0
2        108   329010830   329010856   329010810          0  329010836
3        139   329013986  3290139151   329013963  329013935  329013959
4        188  3290188153  3290188114  3290188111  329018827  329018833
5        192    32901921  3290192110  3290192111  329019225  329019230
6        225    32902251    32902251    32902251   32902251   32902251
7        275    32902751    32902751    32902751   32902751   32902751
8        288    32902881    32902881    32902881   32902881   32902881
9        347    32903471    32903471    32903471   32903471   32903471
10       384    32903841    32903841    32903841   32903841   32903841
11       457    32904571    32904571    32904571   32904571   32904571
12       480    32904801    32904801    32904801   32904801   32904801
13       576    32905761    32905761    32905761   32905761   32905761
14       637    32906371    32906371    32906371   32906371   32906371
15       672    32906721    32906721    32906721   32906721   32906721
16       768    32907681    32907681    32907681   32907681   32907681
17       777    32907771    32907771    32907771   32907771   32907771
18       864    32908641    32908641    32908641   32908641   32908641
19       960    32909601    32909601    32909601   32909601   32909601
20       974    32909741    32909741    32909741   32909741   32909741
21      1056    32910561    32910561    32910561   32910561   32910561
22      1106    32911061    32911061    32911061   32911061   32911061
23      1152    32911521    32911521    32911521   32911521   32911521
24      1248    32912481    32912481    32912481   32912481   32912481
25      1270    32912701    32912701    32912701   32912701   32912701
26      1344    32913441    32913441    32913441   32913441   32913441
27      1440    32914401    32914401    32914401   32914401   32914401
28      1476    32914761    32914761    32914761   32914761   32914761
29      1536    32915361    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740    32917401    32917401    32917401   32917401   32917401
33      1824    32918241    32918241    32918241   32918241   32918241
34      1920    32919201    32919201    32919201   32919201   32919201
35      2016    32920161    32920161    32920161   32920161   32920161
36      2088    32920881    32920881    32920881   32920881   32920881
37      2112    32921121    32921121    32921121   32921121   32921121
38      2208    32922081    32922081    32922081   32922081   32922081
39      2304    32923041    32923041    32923041   32923041   32923041
40      2400    32924001    32924001    32924001   32924001   32924001
41      2496    32924961    32924961    32924961   32924961   32924961
42      2555    32925551    32925551    32925551   32925551   32925551
43      2592    32925921    32925921    32925921   32925921   32925921
44      2688    32926881    32926881    32926881   32926881   32926881
45      2784    32927841    32927841    32927841   32927841   32927841
46      2880    32928801    32928801    32928801   32928801   32928801
47      2976    32929761    32929761    32929761   32929761   32929761
48      3072    32930721    32930721    32930721   32930721   32930721
49      3168    32931681    32931681    32931681   32931681   32931681
50      3195    32931951    32931951    32931951   32931951   32931951
51      3264    32932641    32932641    32932641   32932641   32932641
52      3360    32933601    32933601    32933601   32933601   32933601
53      3456    32934561    32934561    32934561   32934561   32934561
54      3552    32935521    32935521    32935521   32935521   32935521
55      3606    32936061    32936061    32936061   32936061   32936061
56      3648    32936481    32936481    32936481   32936481   32936481
57      3744    32937441    32937441    32937441   32937441   32937441
58      3840    32938401    32938401    32938401   32938401   32938401
59      3936    32939361    32939361    32939361   32939361   32939361
60      4032    32940321    32940321    32940321   32940321   32940321
61      4096    32940961    32940961    32940961   32940961   32940961

     329022513    329022530  329022579  329034745    ...      32940964414  \
0            0            0          0        NaN    ...                0
1   3290096431  32900961293          0        NaN    ...                0
2   3290108621  32901081787          0        NaN    ...                0
3    329013913    329013957  329013953        NaN    ...                0
4    329018813    329018845  329018866        NaN    ...                0
5    329019213    329019245  329019267        NaN    ...                0
6    329022513    329022530  329022579        NaN    ...                0
7     32902751     32902751   32902751        NaN    ...                0
8     32902881     32902881   32902881        NaN    ...                0
9     32903471     32903471   32903471        NaN    ...                0
10    32903841     32903841   32903841        NaN    ...                0
11    32904571     32904571   32904571        NaN    ...                0
12    32904801     32904801   32904801        NaN    ...                0
13    32905761     32905761   32905761        NaN    ...                0
14    32906371     32906371   32906371        NaN    ...                0
15    32906721     32906721   32906721        NaN    ...                0
16    32907681     32907681   32907681        NaN    ...                0
17    32907771     32907771   32907771        NaN    ...                0
18    32908641     32908641   32908641        NaN    ...                0
19    32909601     32909601   32909601        NaN    ...                0
20    32909741     32909741   32909741        NaN    ...                0
21    32910561     32910561   32910561        NaN    ...                0
22    32911061     32911061   32911061        NaN    ...                0
23    32911521     32911521   32911521        NaN    ...                0
24    32912481     32912481   32912481        NaN    ...                0
25    32912701     32912701   32912701        NaN    ...                0
26    32913441     32913441   32913441        NaN    ...                0
27    32914401     32914401   32914401        NaN    ...      32914404201
28    32914761     32914761   32914761        NaN    ...      32914764191
29    32915361     32915361   32915361        NaN    ...      32915364182
..         ...          ...        ...        ...    ...              ...
32    32917401     32917401   32917401        NaN    ...      32917404171
33    32918241     32918241   32918241        NaN    ...      32918244147
34    32919201     32919201   32919201        NaN    ...      32919204295
35    32920161     32920161   32920161        NaN    ...      32920164217
36    32920881     32920881   32920881        NaN    ...      32920884247
37    32921121     32921121   32921121        NaN    ...      32921124214
38    32922081     32922081   32922081        NaN    ...      32922084163
39    32923041     32923041   32923041        NaN    ...      32923044135
40    32924001     32924001   32924001        NaN    ...      32924004339
41    32924961     32924961   32924961        NaN    ...      32924964341
42    32925551     32925551   32925551        NaN    ...      32925554297
43    32925921     32925921   32925921        NaN    ...      32925924396
44    32926881     32926881   32926881        NaN    ...      32926884379
45    32927841     32927841   32927841        NaN    ...      32927844275
46    32928801     32928801   32928801        NaN    ...      32928804219
47    32929761     32929761   32929761        NaN    ...      32929764223
48    32930721     32930721   32930721        NaN    ...      32930724162
49    32931681     32931681   32931681        NaN    ...      32931684290
50    32931951     32931951   32931951        NaN    ...      32931954366
51    32932641     32932641   32932641        NaN    ...      32932644361
52    32933601     32933601   32933601        NaN    ...      32933604347
53    32934561     32934561   32934561        NaN    ...      32934564304
54    32935521     32935521   32935521        NaN    ...      32935524262
55    32936061     32936061   32936061        NaN    ...      32936064459
56    32936481     32936481   32936481        NaN    ...      32936484426
57    32937441     32937441   32937441        NaN    ...      32937444408
58    32938401     32938401   32938401        NaN    ...      32938404388
59    32939361     32939361   32939361        NaN    ...      32939364375
60    32940321     32940321   32940321        NaN    ...      32940324357
61    32940961     32940961   32940961        NaN    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0           0
1    3290096221           0  32900961020   329009640           0  3290096124
2    3290108234           0  32901081471   329010844           0  3290108114
3    3290139545           0   3290139119  3290139138           0  3290139261
4    3290188538           0    329018879  3290188197           0  3290188285
5    3290192554           0    329019278  3290192195           0  3290192291
6    3290225544           0    329022582  3290225210  3290225189  3290225307
7    3290275579           0    329027574  3290275196  3290275121  3290275307
8    3290288619           0    329028872  3290288186  3290288109  3290288300
9    3290347581           0    329034758  3290347164   329034764  3290347281
10   3290384579           0    329038460  3290384127   329038446  3290384281
11   3290457588           0    329045751  3290457104   329045736  3290457298
12   3290480583           0    329048049  3290480102   329048032  3290480324
13   3290576536           0    329057638   329057696   329057626  3290576383
14   3290637554           0    329063738  3290637104   329063727  3290637432
15   3290672559           0    329067235  3290672100   329067221  3290672445
16   3290768567           0    329076836   329076886   329076824  3290768468
17   3290777570           0    329077736   329077786   329077723  3290777467
18   3290864555           0    329086434   329086477   329086420  3290864451
19   3290960543           0    329096033   329096073   329096021  3290960483
20   3290974534           0    329097431   329097473   329097420  3290974478
21   3291056562           0    329105639   329105668   329105622  3291056516
22   3291106741           0    329110652   329110666   329110622  3291106605
23   3291152887           0    329115265   329115271   329115223  3291152630
24  32912481314           0    329124869   329124868   329124825  3291248663
25   3291270963           0    329127068   329127066   329127026  3291270664
26   3291344954           0    329134471   329134461   329134424  3291344669
27   3291440948           0    329144073   329144058   329144021  3291440664
28   3291476953           0    329147674   329147661   329147621  3291476662
29   3291536954           0    329153675   329153662   329153634  3291536656
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043  3291740718
33  32918241363           0    329182478   329182462   329182445  3291824721
34  32919201657           0    329192075   329192057   329192047  3291920729
35  32920161763           0    329201673   329201653   329201648  3292016729
36  32920881809           0   3292088210   329208852   329208849  3292088728
37  32921121823           0   3292112188   329211251   329211250  3292112723
38  32922081833           0   3292208214   329220850   329220848  3292208722
39  32923041843           0   3292304234   329230450   329230449  3292304732
40  32924001879           0   3292400261   329240048   329240050  3292400787
41  32924962122           0   3292496271   329249648   329249650  3292496824

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148102462', '148110668', '148115265', '148127096', '1481280102', '1481408130', '1481476145', '1481536155', '1481664159', '1481740173', '1481920230', '1482048273', '1482088283', '1482112288', '1482208307', '1482304341', '1482400419', '1482496523', '1482555576', '1482592614', '1482688671', '1482784721', '1482880771', '1482976805', '1483072820', '1483168861', '1483195882', '1483264896', '1483360938', '1483456967', '1483552989', '1483606997', '14836481000', '14836711000', '14837441023', '14837601028', '14838101043', '14838401046', '14839361194', '14840321568', '14840962026']
[-1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
 -1.0 -1.0
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001024/halo_62' | NDM=85698 Nstar=1373 Ngas=17880>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001106/halo_68' | NDM=80996 Nstar=1374 Ngas=16420>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001152/halo_65' | NDM=77724 Nstar=1387 Ngas=14737>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001270/halo_96' | NDM=51492 Nstar=1656 Ngas=3836>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001280/halo_102' | NDM=49792 Nstar=1656 Ngas=3540>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001408/halo_130' | NDM=34927 Nstar=1656 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001476/halo_145' | NDM=30638 Nstar=1656 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001536/halo_155' | NDM=26275 Nstar=1656 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001664/halo_159' | NDM=23903 Nstar=1656 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001740/halo_173' | NDM=21535 Nstar=1656 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.001920/halo_230' | NDM=13401 Nstar=1655 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002048/halo_273' | NDM=10790 Nstar=1652 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002088/halo_283' | NDM=10291 Nstar=1652 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002112/halo_288' | NDM=9993 Nstar=1652 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002208/halo_307' | NDM=9060 Nstar=1651 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002304/halo_341' | NDM=8024 Nstar=1650 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002400/halo_419' | NDM=5727 Nstar=1636 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002496/halo_523' | NDM=4171 Nstar=1575 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002555/halo_576' | NDM=3565 Nstar=1521 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002592/halo_614' | NDM=3296 Nstar=1506 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002688/halo_671' | NDM=2814 Nstar=1477 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_721' | NDM=2400 Nstar=1449 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002880/halo_771' | NDM=2128 Nstar=1418 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002976/halo_805' | NDM=1952 Nstar=1391 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003072/halo_820' | NDM=1773 Nstar=1373 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003168/halo_861' | NDM=1581 Nstar=1333 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003195/halo_882' | NDM=1530 Nstar=1327 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003264/halo_896' | NDM=1459 Nstar=1309 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003360/halo_938' | NDM=1342 Nstar=1276 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003456/halo_967' | NDM=1227 Nstar=1241 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003552/halo_989' | NDM=1146 Nstar=1205 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003606/halo_997' | NDM=1114 Nstar=1192 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003648/halo_1000' | NDM=1087 Nstar=1186 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003671/halo_1000' | NDM=1067 Nstar=1180 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003744/halo_1023' | NDM=1017 Nstar=1159 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003760/halo_1028' | NDM=1011 Nstar=1152 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003810/halo_1043' | NDM=963 Nstar=1131 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003840/halo_1046' | NDM=945 Nstar=1125 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.003936/halo_1194' | NDM=764 Nstar=978 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004032/halo_1568' | NDM=556 Nstar=730 Ngas=0>
 <Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.004096/halo_2026' | NDM=417 Nstar=567 Ngas=0>]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '148102462', '148110668', '148115265', '148127096', '1481280102', '1481408130', '1481476145', '1481536155', '1481664159', '1481740173', '1481920230', '1482048273', '1482088283', '1482112288', '1482208307', '1482304341', '1482400419', '1482496523', '1482555576', '1482592614', '1482688671', '1482784721', '1482880771', '1482976805', '1483072820', '1483168861', '1483195882', '1483264896', '1483360938', '1483456967', '1483552989', '1483606997', '14836481000', '14836711000', '14837441023', '14837601028', '14838101043', '14838401046', '14839361194', '14840321568', '14840962026']
    snapshot  148110610  14811066  148115218  14812709  148128013  14812804  \
0         71          0         0          0         0          0         0
1        108          0         0          0         0          0         0
2        128          0         0          0         0          0         0
3        139          0         0          0         0          0         0
4        188          0         0          0         0          0         0
5        225          0         0          0         0          0         0
6        256          0         0          0         0          0         0
7        275          0         0          0         0          0         0
8        347          0         0          0         0          0         0
9        384          0         0          0         0          0         0
10       457          0         0          0         0          0         0
11       512          0         0          0         0          0         0
12       637          0         0          0         0          0         0
13       640          0         0          0         0          0         0
14       777          0         0          0         0          0         0
15       896          0         0          0         0          0         0
16       974          0         0          0         0          0         0
17      1024  148102411  14810245  148102422  14810243  148102416  14810243
18      1106  148110610  14811066  148110620  14811063  148110614  14811063
19      1152   14811521  14811521  148115218  14811523  148115212  14811523
20      1270   14812701  14812701   14812701  14812709  148127014  14812703
21      1280   14812801  14812801   14812801  14812801  148128013  14812804
22      1408   14814081  14814081   14814081  14814081   14814081  14814081
23      1476   14814761  14814761   14814761  14814761   14814761  14814761
24      1536   14815361  14815361   14815361  14815361   14815361  14815361
25      1664   14816641  14816641   14816641  14816641   14816641  14816641
26      1740   14817401  14817401   14817401  14817401   14817401  14817401
27      1920   14819201  14819201   14819201  14819201   14819201  14819201
28      2048   14820481  14820481   14820481  14820481   14820481  14820481
29      2088   14820881  14820881   14820881  14820881   14820881  14820881
30      2112   14821121  14821121   14821121  14821121   14821121  14821121
31      2208   14822081  14822081   14822081  14822081   14822081  14822081
32      2304   14823041  14823041   14823041  14823041   14823041  14823041
33      2400   14824001  14824001   14824001  14824001   14824001  14824001
34      2496   14824961  14824961   14824961  14824961   14824961  14824961
35      2555   14825551  14825551   14825551  14825551   14825551  14825551
36      2592   14825921  14825921   14825921  14825921   14825921  14825921
37      2688   14826881  14826881   14826881  14826881   14826881  14826881
38      2784   14827841  14827841   14827841  14827841   14827841  14827841
39      2880   14828801  14828801   14828801  14828801   14828801  14828801
40      2976   14829761  14829761   14829761  14829761   14829761  14829761
41      3072   14830721  14830721   14830721  14830721   14830721  14830721
42      3168   14831681  14831681   14831681  14831681   14831681  14831681
43      3195   14831951  14831951   14831951  14831951   14831951  14831951
44      3264   14832641  14832641   14832641  14832641   14832641  14832641
45      3360   14833601  14833601   14833601  14833601   14833601  14833601
46      3456   14834561  14834561   14834561  14834561   14834561  14834561
47      3552   14835521  14835521   14835521  14835521   14835521  14835521
48      3606   14836061  14836061   14836061  14836061   14836061  14836061
49      3648   14836481  14836481   14836481  14836481   14836481  14836481
50      3671   14836711  14836711   14836711  14836711   14836711  14836711
51      3744   14837441  14837441   14837441  14837441   14837441  14837441
52      3760   14837601  14837601   14837601  14837601   14837601  14837601
53      3810   14838101  14838101   14838101  14838101   14838101  14838101
54      3840   14838401  14838401   14838401  14838401   14838401  14838401
55      3936   14839361  14839361   14839361  14839361   14839361  14839361
56      4032   14840321  14840321   14840321  14840321   14840321  14840321
57      4096   14840961  14840961   14840961  14840961   14840961  14840961

     14814089  148153610  14829762     ...       14840966  148409663  \
0           0          0         0     ...              0          0
1           0          0         0     ...              0          0
2           0          0         0     ...              0          0
3           0          0         0     ...              0          0
4           0          0         0     ...              0          0
5           0          0         0     ...              0          0
6           0          0         0     ...              0          0
7           0          0         0     ...              0          0
8           0          0         0     ...              0          0
9           0          0         0     ...              0          0
10          0          0         0     ...              0          0
11          0          0         0     ...              0          0
12          0          0         0     ...              0          0
13          0          0         0     ...              0          0
14          0          0         0     ...              0          0
15          0          0         0     ...              0          0
16          0          0         0     ...              0          0
17  148102414  148102415  14810242     ...      148102412  148102483
18  148110612  148110613  14811062     ...       14811069  148110677
19  148115210  148115211  14811522     ...       14811529  148115273
20  148127011  148127012  14812702     ...      148127010  148127071
21  148128010  148128011  14812802     ...       14812809  148128070
22   14814089  148140810  14814082     ...       14814088  148140862
23   14814761  148147616  14814762     ...       14814768  148147669
24   14815361  148153610  14815362     ...       14815368  148153669
25   14816641   14816641  14816642     ...       14816648  148166469
26   14817401   14817401  14817402     ...       14817408  148174064
27   14819201   14819201  14819202     ...       14819208  148192064
28   14820481   14820481  14820482     ...       14820488  148204862
29   14820881   14820881  14820882     ...       14820888  148208862
30   14821121   14821121  14821122     ...       14821128  148211261
31   14822081   14822081  14822082     ...       14822088  148220860
32   14823041   14823041  14823042     ...       14823048  148230461
33   14824001   14824001  14824002     ...       14824008  148240060
34   14824961   14824961  14824962     ...       14824968  148249665
35   14825551   14825551  14825552     ...       14825558  148255565
36   14825921   14825921  14825922     ...       14825928  148259265
37   14826881   14826881  14826882     ...       14826888  148268866
38   14827841   14827841  14827842     ...       14827848  148278465
39   14828801   14828801  14828802     ...       14828808  148288064
40   14829761   14829761  14829762     ...       14829768  148297666
41   14830721   14830721  14830721     ...       14830726  148307267
42   14831681   14831681  14831681     ...       14831688  148316866
43   14831951   14831951  14831951     ...       14831958  148319567
44   14832641   14832641  14832641     ...       14832648  148326468
45   14833601   14833601  14833601     ...       14833607  148336067
46   14834561   14834561  14834561     ...       14834567  148345667
47   14835521   14835521  14835521     ...       14835526  148355266
48   14836061   14836061  14836061     ...       14836066  148360668
49   14836481   14836481  14836481     ...       14836486  148364866
50   14836711   14836711  14836711     ...       14836716  148367167
51   14837441   14837441  14837441     ...       14837446  148374466
52   14837601   14837601  14837601     ...       14837606  148376066
53   14838101   14838101  14838101     ...       14838106  148381065
54   14838401   14838401  14838401     ...       14838406  148384064
55   14839361   14839361  14839361     ...       14839366  148393663
56   14840321   14840321  14840321     ...       14840326  148403262
57   14840961   14840961  14840961     ...       14840966  148409663

    148409668   14840967  14840967007   148409676  148409677  1484096803  \
0           0          0            0           0          0           0
1           0          0            0           0          0           0
2           0          0            0           0          0           0
3           0          0            0           0          0           0
4           0          0            0           0          0           0
5           0          0            0           0          0           0
6           0          0            0           0          0           0
7           0          0            0           0          0           0
8           0          0            0           0          0           0
9           0          0            0           0          0           0
10          0          0            0           0          0           0
11          0          0            0           0          0           0
12          0          0            0           0          0           0
13          0          0            0           0          0           0
14          0          0            0           0          0           0
15          0          0            0           0          0           0
16          0          0            0           0          0           0
17  148102429  148102420            0   148102478  148102443  1481024434
18  148110628  148110618            0   148110676  148110642  1481106226
19  148115225  148115217            0   148115274  148115236  1481152220
20  148127024  148127016            0   148127070  148127036  1481270209
21  148128023  148128015            0   148128069  148128035  1481280206
22  148140822  148140811            0  1481408101  148140832  1481408167
23  148147623  148147610            0   148147690  148147632  1481476159
24  148153624  148153611            0   148153683  148153633  1481536151
25  148166421   14816649            0   148166489  148166432  1481664184
26  148174023   14817409            0   148174092  148174032  1481740258
27  148192029   14819209            0   148192093  148192032  1481920159
28  148204838   14820489            0   148204891  148204830  1482048169
29  148208838   14820889            0   148208892  148208830  1482088290
30  148211238   14821129            0   148211292  148211229  1482112155
31  148220839   14822089  14822083497   148220894  148220829  1482208426
32  148230441   14823049  14823043442   148230496  148230430  1482304416
33  148240044   14824009  14824003365   148240096  148240028  1482400414
34  148249647   14824969  14824963293   148249696  148249632  1482496615
35  148255545   14825559  14825553257   148255597  148255535  1482555631
36  148259245   14825929  14825923218   148259296  148259235  1482592640
37  148268847   14826889  14826883158   148268897  148268838  1482688647
38  148278446   14827849  14827843254   148278496  148278450  1482784651
39  148288045   14828809  14828803215   148288095  148288056  1482880658
40  148297659   14829769  14829763183   148297694  148297656  1482976676
41  148307261   14830728  14830723119   148307291  148307260  1483072660
42  148316861   14831689  14831683080   148316888  148316860  1483168670
43  148319561   14831959  14831953057   148319588  148319562  1483195670
44  148326460   14832649  14832643021   148326484  148326463  1483264670
45  148336059   14833608  14833604234   148336080  148336063  1483360684
46  148345660   14834568  14834564423   148345680  148345663  1483456722
47  148355259   14835527  14835524415   148355277  148355262  1483552797
48  148360662   14836067  14836064442   148360680  148360665  1483606800
49  148364861   14836487  14836484417   148364880  148364865  1483648798
50  148367160   14836717  14836714436   148367180  148367165  1483671802
51  148374460   14837447  14837444450   148374477  148374464  1483744794
52  148376059   14837607  14837604580   148376077  148376065  1483760800
53  148381059   14838107  14838106247   148381077  148381066  1483810802
54  148384058   14838407  14838406616   148384077  148384066  1483840796
55  148393659   14839367  14839366912   148393676  148393670  1483936801
56  148403266   14840327  14840326946   148403276  148403275  1484032798
57  148409668   14840967  14840967007   148409676  148409677  1484096803

    14840968565  1484096857
0             0           0
1             0           0
2             0           0
3             0           0
4             0           0
5             0           0
6             0           0
7             0           0
8             0           0
9             0           0
10            0           0
11            0           0
12            0           0
13            0           0
14            0           0
15            0           0
16            0           0
17            0           0
18            0           0
19            0           0
20            0           0
21            0           0
22            0           0
23            0           0
24            0           0
25            0  1481664583
26            0  1481740675
27            0  1481920723
28            0  1482048709
29  14820883070  1482088716
30  14821123108  1482112721
31  14822083288  1482208764
32  14823043356  1482304820
33  14824003391  1482400761
34  14824964889  1482496764
35  14825555134  1482555761
36  14825925307  1482592774
37  14826885446  1482688844
38  14827845472  1482784888
39  14828805569  1482880871
40  14829766423  1482976861
41  14830726494  1483072837
42  14831686490  1483168827
43  14831956438  1483195823
44  14832646491  1483264814
45  14833606420  1483360815
46  14834566949  1483456812
47  14835527642  1483552798
48  14836067699  1483606789
49  14836487660  1483648782
50  14836717573  1483671780
51  14837447690  1483744767
52  14837607621  1483760767
53  14838107661  1483810759
54  14838407640  1483840752
55  14839367781  1483936756
56  14840328859  1484032786
57  14840968565  1484096857

[58 rows x 78 columns]
Finished  14840962026
Finished  14840962026
Completed Count -->  122
Started  329034745
Started  329034745
h329 Zombie 45 0347

['329007113', '329009617', '329010817', '3290139109', '329018881', '329019272', '329022549', '329027538', '329028840', '329034745', '32903841', '32904571', '32904801', '32905761', '32906371', '32906721', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[ <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000071/halo_13' | NDM=846 Nstar=0 Ngas=672>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096/halo_17' | NDM=2069 Nstar=0 Ngas=1638>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108/halo_17' | NDM=2663 Nstar=0 Ngas=2140>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_109' | NDM=3882 Nstar=80 Ngas=683>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_81' | NDM=9460 Nstar=80 Ngas=1272>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_72' | NDM=10973 Nstar=80 Ngas=1573>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_49' | NDM=21358 Nstar=80 Ngas=6323>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_38' | NDM=34031 Nstar=124 Ngas=16408>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_40' | NDM=36074 Nstar=132 Ngas=17871>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_45' | NDM=34461 Nstar=441 Ngas=13743>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_1' | NDM=1884862 Nstar=573154 Ngas=945541>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_1' | NDM=2788363 Nstar=842283 Ngas=1392793>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_1' | NDM=3225374 Nstar=976143 Ngas=1595943>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_1' | NDM=5065263 Nstar=1530172 Ngas=2738713>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_1' | NDM=7451554 Nstar=2236951 Ngas=4644431>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_1' | NDM=8496675 Nstar=2702944 Ngas=5442931>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_1' | NDM=10617049 Nstar=3856093 Ngas=7275738>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_1' | NDM=10872015 Nstar=3980353 Ngas=7482669>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_1' | NDM=12715287 Nstar=5722615 Ngas=9000800>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_1' | NDM=15028263 Nstar=7698307 Ngas=11059109>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_1' | NDM=15196786 Nstar=7990531 Ngas=11217754>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1' | NDM=15578696 Nstar=10217161 Ngas=11755160>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1' | NDM=15747259 Nstar=11784296 Ngas=11968198>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1' | NDM=15761360 Nstar=13147640 Ngas=12285340>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1' | NDM=15832293 Nstar=16238307 Ngas=12845015>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1' | NDM=15990494 Nstar=17157603 Ngas=12930029>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1' | NDM=17922263 Nstar=20611248 Ngas=14418911>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1' | NDM=20220937 Nstar=24755716 Ngas=15683385>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1' | NDM=20568424 Nstar=26701663 Ngas=15670524>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1' | NDM=21292522 Nstar=29070320 Ngas=16200299>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1' | NDM=22138471 Nstar=34143108 Ngas=16098369>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1' | NDM=22233114 Nstar=37948971 Ngas=16217261>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1' | NDM=22265580 Nstar=38395660 Ngas=16249600>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1' | NDM=22541017 Nstar=41934879 Ngas=16143723>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1' | NDM=23087646 Nstar=46137673 Ngas=15803476>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1' | NDM=23617232 Nstar=50351876 Ngas=15643527>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1' | NDM=24221915 Nstar=53530614 Ngas=15566115>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1' | NDM=24513553 Nstar=54733955 Ngas=15453339>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1' | NDM=26676353 Nstar=59100003 Ngas=16082599>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1' | NDM=29354421 Nstar=64311453 Ngas=16874211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1' | NDM=31464533 Nstar=68631869 Ngas=16998639>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1' | NDM=32730524 Nstar=72629063 Ngas=17093857>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1' | NDM=33576743 Nstar=76168219 Ngas=16582991>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1' | NDM=34007948 Nstar=77829519 Ngas=16271248>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1' | NDM=34817467 Nstar=82227069 Ngas=16133249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1' | NDM=35279749 Nstar=86891324 Ngas=15727574>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1' | NDM=34968677 Nstar=91010100 Ngas=14700620>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1' | NDM=34685343 Nstar=94725659 Ngas=13794122>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1' | NDM=34411771 Nstar=98430465 Ngas=12965040>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
[0, '329009617', '329010817', '3290139109', '329018881', '329019272', '329022549', '329027538', '329028840', '329034745', '32903841', '32904571', '32904801', '32905761', '32906371', '32906721', '32907681', '32907771', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71           0           0           0          0          0
1         96   329009638   329009662    32900969          0          0
2        108   329010830   329010856   329010810          0  329010836
3        139   329013986  3290139151   329013963  329013935  329013959
4        188  3290188153  3290188114  3290188111  329018827  329018833
5        192    32901921  3290192110  3290192111  329019225  329019230
6        225    32902251    32902251    32902251   32902251   32902251
7        275    32902751    32902751    32902751   32902751   32902751
8        288    32902881    32902881    32902881   32902881   32902881
9        347    32903471    32903471    32903471   32903471   32903471
10       384    32903841    32903841    32903841   32903841   32903841
11       457    32904571    32904571    32904571   32904571   32904571
12       480    32904801    32904801    32904801   32904801   32904801
13       576    32905761    32905761    32905761   32905761   32905761
14       637    32906371    32906371    32906371   32906371   32906371
15       672    32906721    32906721    32906721   32906721   32906721
16       768    32907681    32907681    32907681   32907681   32907681
17       777    32907771    32907771    32907771   32907771   32907771
18       864    32908641    32908641    32908641   32908641   32908641
19       960    32909601    32909601    32909601   32909601   32909601
20       974    32909741    32909741    32909741   32909741   32909741
21      1056    32910561    32910561    32910561   32910561   32910561
22      1106    32911061    32911061    32911061   32911061   32911061
23      1152    32911521    32911521    32911521   32911521   32911521
24      1248    32912481    32912481    32912481   32912481   32912481
25      1270    32912701    32912701    32912701   32912701   32912701
26      1344    32913441    32913441    32913441   32913441   32913441
27      1440    32914401    32914401    32914401   32914401   32914401
28      1476    32914761    32914761    32914761   32914761   32914761
29      1536    32915361    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740    32917401    32917401    32917401   32917401   32917401
33      1824    32918241    32918241    32918241   32918241   32918241
34      1920    32919201    32919201    32919201   32919201   32919201
35      2016    32920161    32920161    32920161   32920161   32920161
36      2088    32920881    32920881    32920881   32920881   32920881
37      2112    32921121    32921121    32921121   32921121   32921121
38      2208    32922081    32922081    32922081   32922081   32922081
39      2304    32923041    32923041    32923041   32923041   32923041
40      2400    32924001    32924001    32924001   32924001   32924001
41      2496    32924961    32924961    32924961   32924961   32924961
42      2555    32925551    32925551    32925551   32925551   32925551
43      2592    32925921    32925921    32925921   32925921   32925921
44      2688    32926881    32926881    32926881   32926881   32926881
45      2784    32927841    32927841    32927841   32927841   32927841
46      2880    32928801    32928801    32928801   32928801   32928801
47      2976    32929761    32929761    32929761   32929761   32929761
48      3072    32930721    32930721    32930721   32930721   32930721
49      3168    32931681    32931681    32931681   32931681   32931681
50      3195    32931951    32931951    32931951   32931951   32931951
51      3264    32932641    32932641    32932641   32932641   32932641
52      3360    32933601    32933601    32933601   32933601   32933601
53      3456    32934561    32934561    32934561   32934561   32934561
54      3552    32935521    32935521    32935521   32935521   32935521
55      3606    32936061    32936061    32936061   32936061   32936061
56      3648    32936481    32936481    32936481   32936481   32936481
57      3744    32937441    32937441    32937441   32937441   32937441
58      3840    32938401    32938401    32938401   32938401   32938401
59      3936    32939361    32939361    32939361   32939361   32939361
60      4032    32940321    32940321    32940321   32940321   32940321
61      4096    32940961    32940961    32940961   32940961   32940961

     329022513    329022530  329022579   329034745    ...      32940964414  \
0            0            0          0           0    ...                0
1   3290096431  32900961293          0   329009617    ...                0
2   3290108621  32901081787          0   329010817    ...                0
3    329013913    329013957  329013953  3290139109    ...                0
4    329018813    329018845  329018866   329018881    ...                0
5    329019213    329019245  329019267   329019272    ...                0
6    329022513    329022530  329022579   329022549    ...                0
7     32902751     32902751   32902751   329027538    ...                0
8     32902881     32902881   32902881   329028840    ...                0
9     32903471     32903471   32903471   329034745    ...                0
10    32903841     32903841   32903841    32903841    ...                0
11    32904571     32904571   32904571    32904571    ...                0
12    32904801     32904801   32904801    32904801    ...                0
13    32905761     32905761   32905761    32905761    ...                0
14    32906371     32906371   32906371    32906371    ...                0
15    32906721     32906721   32906721    32906721    ...                0
16    32907681     32907681   32907681    32907681    ...                0
17    32907771     32907771   32907771    32907771    ...                0
18    32908641     32908641   32908641    32908641    ...                0
19    32909601     32909601   32909601    32909601    ...                0
20    32909741     32909741   32909741    32909741    ...                0
21    32910561     32910561   32910561    32910561    ...                0
22    32911061     32911061   32911061    32911061    ...                0
23    32911521     32911521   32911521    32911521    ...                0
24    32912481     32912481   32912481    32912481    ...                0
25    32912701     32912701   32912701    32912701    ...                0
26    32913441     32913441   32913441    32913441    ...                0
27    32914401     32914401   32914401    32914401    ...      32914404201
28    32914761     32914761   32914761    32914761    ...      32914764191
29    32915361     32915361   32915361    32915361    ...      32915364182
..         ...          ...        ...         ...    ...              ...
32    32917401     32917401   32917401    32917401    ...      32917404171
33    32918241     32918241   32918241    32918241    ...      32918244147
34    32919201     32919201   32919201    32919201    ...      32919204295
35    32920161     32920161   32920161    32920161    ...      32920164217
36    32920881     32920881   32920881    32920881    ...      32920884247
37    32921121     32921121   32921121    32921121    ...      32921124214
38    32922081     32922081   32922081    32922081    ...      32922084163
39    32923041     32923041   32923041    32923041    ...      32923044135
40    32924001     32924001   32924001    32924001    ...      32924004339
41    32924961     32924961   32924961    32924961    ...      32924964341
42    32925551     32925551   32925551    32925551    ...      32925554297
43    32925921     32925921   32925921    32925921    ...      32925924396
44    32926881     32926881   32926881    32926881    ...      32926884379
45    32927841     32927841   32927841    32927841    ...      32927844275
46    32928801     32928801   32928801    32928801    ...      32928804219
47    32929761     32929761   32929761    32929761    ...      32929764223
48    32930721     32930721   32930721    32930721    ...      32930724162
49    32931681     32931681   32931681    32931681    ...      32931684290
50    32931951     32931951   32931951    32931951    ...      32931954366
51    32932641     32932641   32932641    32932641    ...      32932644361
52    32933601     32933601   32933601    32933601    ...      32933604347
53    32934561     32934561   32934561    32934561    ...      32934564304
54    32935521     32935521   32935521    32935521    ...      32935524262
55    32936061     32936061   32936061    32936061    ...      32936064459
56    32936481     32936481   32936481    32936481    ...      32936484426
57    32937441     32937441   32937441    32937441    ...      32937444408
58    32938401     32938401   32938401    32938401    ...      32938404388
59    32939361     32939361   32939361    32939361    ...      32939364375
60    32940321     32940321   32940321    32940321    ...      32940324357
61    32940961     32940961   32940961    32940961    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0           0
1    3290096221           0  32900961020   329009640           0  3290096124
2    3290108234           0  32901081471   329010844           0  3290108114
3    3290139545           0   3290139119  3290139138           0  3290139261
4    3290188538           0    329018879  3290188197           0  3290188285
5    3290192554           0    329019278  3290192195           0  3290192291
6    3290225544           0    329022582  3290225210  3290225189  3290225307
7    3290275579           0    329027574  3290275196  3290275121  3290275307
8    3290288619           0    329028872  3290288186  3290288109  3290288300
9    3290347581           0    329034758  3290347164   329034764  3290347281
10   3290384579           0    329038460  3290384127   329038446  3290384281
11   3290457588           0    329045751  3290457104   329045736  3290457298
12   3290480583           0    329048049  3290480102   329048032  3290480324
13   3290576536           0    329057638   329057696   329057626  3290576383
14   3290637554           0    329063738  3290637104   329063727  3290637432
15   3290672559           0    329067235  3290672100   329067221  3290672445
16   3290768567           0    329076836   329076886   329076824  3290768468
17   3290777570           0    329077736   329077786   329077723  3290777467
18   3290864555           0    329086434   329086477   329086420  3290864451
19   3290960543           0    329096033   329096073   329096021  3290960483
20   3290974534           0    329097431   329097473   329097420  3290974478
21   3291056562           0    329105639   329105668   329105622  3291056516
22   3291106741           0    329110652   329110666   329110622  3291106605
23   3291152887           0    329115265   329115271   329115223  3291152630
24  32912481314           0    329124869   329124868   329124825  3291248663
25   3291270963           0    329127068   329127066   329127026  3291270664
26   3291344954           0    329134471   329134461   329134424  3291344669
27   3291440948           0    329144073   329144058   329144021  3291440664
28   3291476953           0    329147674   329147661   329147621  3291476662
29   3291536954           0    329153675   329153662   329153634  3291536656
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043  3291740718
33  32918241363           0    329182478   329182462   329182445  3291824721
34  32919201657           0    329192075   329192057   329192047  3291920729
35  32920161763           0    329201673   329201653   329201648  3292016729
36  32920881809           0   3292088210   329208852   329208849  3292088728

[0, 0, 0, '329013943', '329018815', '329019210', '32902255', '32902754', '32902884', '32903474', '32903844', '32904576', '32904807', '32905766', '32906376', '32906724', '32907684', '32907774', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
[-1.0 -1.0 -1.0
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139/halo_43' | NDM=7077 Nstar=202 Ngas=4119>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188/halo_15' | NDM=39515 Nstar=432 Ngas=24358>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192/halo_10' | NDM=53982 Nstar=1122 Ngas=35140>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225/halo_5' | NDM=108045 Nstar=6518 Ngas=85881>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275/halo_4' | NDM=271882 Nstar=17895 Ngas=159879>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288/halo_4' | NDM=308702 Nstar=20541 Ngas=175592>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000347/halo_4' | NDM=412288 Nstar=35177 Ngas=240263>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000384/halo_4' | NDM=456062 Nstar=51237 Ngas=266061>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000457/halo_6' | NDM=507522 Nstar=77493 Ngas=284474>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000480/halo_7' | NDM=508172 Nstar=83047 Ngas=284278>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000576/halo_6' | NDM=613302 Nstar=107072 Ngas=346673>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000637/halo_6' | NDM=768503 Nstar=131964 Ngas=401513>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000672/halo_4' | NDM=884967 Nstar=138161 Ngas=468968>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000768/halo_4' | NDM=989343 Nstar=161657 Ngas=499008>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000777/halo_4' | NDM=989243 Nstar=162799 Ngas=497950>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000864/halo_1' | NDM=12715287 Nstar=5722615 Ngas=9000800>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000960/halo_1' | NDM=15028263 Nstar=7698307 Ngas=11059109>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000974/halo_1' | NDM=15196786 Nstar=7990531 Ngas=11217754>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001056/halo_1' | NDM=15578696 Nstar=10217161 Ngas=11755160>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001106/halo_1' | NDM=15747259 Nstar=11784296 Ngas=11968198>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001152/halo_1' | NDM=15761360 Nstar=13147640 Ngas=12285340>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001248/halo_1' | NDM=15832293 Nstar=16238307 Ngas=12845015>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001270/halo_1' | NDM=15990494 Nstar=17157603 Ngas=12930029>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001344/halo_1' | NDM=17922263 Nstar=20611248 Ngas=14418911>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001440/halo_1' | NDM=20220937 Nstar=24755716 Ngas=15683385>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001476/halo_1' | NDM=20568424 Nstar=26701663 Ngas=15670524>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001536/halo_1' | NDM=21292522 Nstar=29070320 Ngas=16200299>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001632/halo_1' | NDM=22138471 Nstar=34143108 Ngas=16098369>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001728/halo_1' | NDM=22233114 Nstar=37948971 Ngas=16217261>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001740/halo_1' | NDM=22265580 Nstar=38395660 Ngas=16249600>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001824/halo_1' | NDM=22541017 Nstar=41934879 Ngas=16143723>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.001920/halo_1' | NDM=23087646 Nstar=46137673 Ngas=15803476>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002016/halo_1' | NDM=23617232 Nstar=50351876 Ngas=15643527>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002088/halo_1' | NDM=24221915 Nstar=53530614 Ngas=15566115>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002112/halo_1' | NDM=24513553 Nstar=54733955 Ngas=15453339>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002208/halo_1' | NDM=26676353 Nstar=59100003 Ngas=16082599>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002304/halo_1' | NDM=29354421 Nstar=64311453 Ngas=16874211>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002400/halo_1' | NDM=31464533 Nstar=68631869 Ngas=16998639>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002496/halo_1' | NDM=32730524 Nstar=72629063 Ngas=17093857>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002555/halo_1' | NDM=33576743 Nstar=76168219 Ngas=16582991>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002592/halo_1' | NDM=34007948 Nstar=77829519 Ngas=16271248>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002688/halo_1' | NDM=34817467 Nstar=82227069 Ngas=16133249>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002784/halo_1' | NDM=35279749 Nstar=86891324 Ngas=15727574>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002880/halo_1' | NDM=34968677 Nstar=91010100 Ngas=14700620>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.002976/halo_1' | NDM=34685343 Nstar=94725659 Ngas=13794122>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003072/halo_1' | NDM=34411771 Nstar=98430465 Ngas=12965040>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003168/halo_1' | NDM=34273995 Nstar=101907116 Ngas=12143213>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003195/halo_1' | NDM=34281538 Nstar=102986035 Ngas=11930801>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003264/halo_1' | NDM=34403326 Nstar=105881046 Ngas=11346491>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003360/halo_1' | NDM=34711017 Nstar=109882160 Ngas=10650697>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003456/halo_1' | NDM=35012302 Nstar=113417585 Ngas=10102143>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003552/halo_1' | NDM=35074237 Nstar=116672811 Ngas=9642768>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003606/halo_1' | NDM=35078318 Nstar=118433355 Ngas=9387439>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003648/halo_1' | NDM=35055860 Nstar=119720222 Ngas=9225094>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003744/halo_1' | NDM=35467949 Nstar=122257598 Ngas=9112884>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003840/halo_1' | NDM=35682098 Nstar=124356800 Ngas=9033732>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.003936/halo_1' | NDM=35862661 Nstar=126368290 Ngas=8945709>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004032/halo_1' | NDM=36011917 Nstar=128577496 Ngas=8759078>
 <Halo 'snapshots/h329.cosmo50PLK.6144g5HbwK1BH.004096/halo_1' | NDM=36055356 Nstar=129857780 Ngas=8655975>]
[0, 0, 0, '329013943', '329018815', '329019210', '32902255', '32902754', '32902884', '32903474', '32903844', '32904576', '32904807', '32905766', '32906376', '32906724', '32907684', '32907774', '32908641', '32909601', '32909741', '32910561', '32911061', '32911521', '32912481', '32912701', '32913441', '32914401', '32914761', '32915361', '32916321', '32917281', '32917401', '32918241', '32919201', '32920161', '32920881', '32921121', '32922081', '32923041', '32924001', '32924961', '32925551', '32925921', '32926881', '32927841', '32928801', '32929761', '32930721', '32931681', '32931951', '32932641', '32933601', '32934561', '32935521', '32936061', '32936481', '32937441', '32938401', '32939361', '32940321', '32940961']
    snapshot  3290188153  3290192110  3290192111  329019225  329019230  \
0         71           0           0           0          0          0
1         96   329009638   329009662    32900969          0          0
2        108   329010830   329010856   329010810          0  329010836
3        139   329013986  3290139151   329013963  329013935  329013959
4        188  3290188153  3290188114  3290188111  329018827  329018833
5        192    32901921  3290192110  3290192111  329019225  329019230
6        225    32902251    32902251    32902251   32902251   32902251
7        275    32902751    32902751    32902751   32902751   32902751
8        288    32902881    32902881    32902881   32902881   32902881
9        347    32903471    32903471    32903471   32903471   32903471
10       384    32903841    32903841    32903841   32903841   32903841
11       457    32904571    32904571    32904571   32904571   32904571
12       480    32904801    32904801    32904801   32904801   32904801
13       576    32905761    32905761    32905761   32905761   32905761
14       637    32906371    32906371    32906371   32906371   32906371
15       672    32906721    32906721    32906721   32906721   32906721
16       768    32907681    32907681    32907681   32907681   32907681
17       777    32907771    32907771    32907771   32907771   32907771
18       864    32908641    32908641    32908641   32908641   32908641
19       960    32909601    32909601    32909601   32909601   32909601
20       974    32909741    32909741    32909741   32909741   32909741
21      1056    32910561    32910561    32910561   32910561   32910561
22      1106    32911061    32911061    32911061   32911061   32911061
23      1152    32911521    32911521    32911521   32911521   32911521
24      1248    32912481    32912481    32912481   32912481   32912481
25      1270    32912701    32912701    32912701   32912701   32912701
26      1344    32913441    32913441    32913441   32913441   32913441
27      1440    32914401    32914401    32914401   32914401   32914401
28      1476    32914761    32914761    32914761   32914761   32914761
29      1536    32915361    32915361    32915361   32915361   32915361
..       ...         ...         ...         ...        ...        ...
32      1740    32917401    32917401    32917401   32917401   32917401
33      1824    32918241    32918241    32918241   32918241   32918241
34      1920    32919201    32919201    32919201   32919201   32919201
35      2016    32920161    32920161    32920161   32920161   32920161
36      2088    32920881    32920881    32920881   32920881   32920881
37      2112    32921121    32921121    32921121   32921121   32921121
38      2208    32922081    32922081    32922081   32922081   32922081
39      2304    32923041    32923041    32923041   32923041   32923041
40      2400    32924001    32924001    32924001   32924001   32924001
41      2496    32924961    32924961    32924961   32924961   32924961
42      2555    32925551    32925551    32925551   32925551   32925551
43      2592    32925921    32925921    32925921   32925921   32925921
44      2688    32926881    32926881    32926881   32926881   32926881
45      2784    32927841    32927841    32927841   32927841   32927841
46      2880    32928801    32928801    32928801   32928801   32928801
47      2976    32929761    32929761    32929761   32929761   32929761
48      3072    32930721    32930721    32930721   32930721   32930721
49      3168    32931681    32931681    32931681   32931681   32931681
50      3195    32931951    32931951    32931951   32931951   32931951
51      3264    32932641    32932641    32932641   32932641   32932641
52      3360    32933601    32933601    32933601   32933601   32933601
53      3456    32934561    32934561    32934561   32934561   32934561
54      3552    32935521    32935521    32935521   32935521   32935521
55      3606    32936061    32936061    32936061   32936061   32936061
56      3648    32936481    32936481    32936481   32936481   32936481
57      3744    32937441    32937441    32937441   32937441   32937441
58      3840    32938401    32938401    32938401   32938401   32938401
59      3936    32939361    32939361    32939361   32939361   32939361
60      4032    32940321    32940321    32940321   32940321   32940321
61      4096    32940961    32940961    32940961   32940961   32940961

     329022513    329022530  329022579   329034745    ...      32940964414  \
0            0            0          0           0    ...                0
1   3290096431  32900961293          0   329009617    ...                0
2   3290108621  32901081787          0   329010817    ...                0
3    329013913    329013957  329013953  3290139109    ...                0
4    329018813    329018845  329018866   329018881    ...                0
5    329019213    329019245  329019267   329019272    ...                0
6    329022513    329022530  329022579   329022549    ...                0
7     32902751     32902751   32902751   329027538    ...                0
8     32902881     32902881   32902881   329028840    ...                0
9     32903471     32903471   32903471   329034745    ...                0
10    32903841     32903841   32903841    32903841    ...                0
11    32904571     32904571   32904571    32904571    ...                0
12    32904801     32904801   32904801    32904801    ...                0
13    32905761     32905761   32905761    32905761    ...                0
14    32906371     32906371   32906371    32906371    ...                0
15    32906721     32906721   32906721    32906721    ...                0
16    32907681     32907681   32907681    32907681    ...                0
17    32907771     32907771   32907771    32907771    ...                0
18    32908641     32908641   32908641    32908641    ...                0
19    32909601     32909601   32909601    32909601    ...                0
20    32909741     32909741   32909741    32909741    ...                0
21    32910561     32910561   32910561    32910561    ...                0
22    32911061     32911061   32911061    32911061    ...                0
23    32911521     32911521   32911521    32911521    ...                0
24    32912481     32912481   32912481    32912481    ...                0
25    32912701     32912701   32912701    32912701    ...                0
26    32913441     32913441   32913441    32913441    ...                0
27    32914401     32914401   32914401    32914401    ...      32914404201
28    32914761     32914761   32914761    32914761    ...      32914764191
29    32915361     32915361   32915361    32915361    ...      32915364182
..         ...          ...        ...         ...    ...              ...
32    32917401     32917401   32917401    32917401    ...      32917404171
33    32918241     32918241   32918241    32918241    ...      32918244147
34    32919201     32919201   32919201    32919201    ...      32919204295
35    32920161     32920161   32920161    32920161    ...      32920164217
36    32920881     32920881   32920881    32920881    ...      32920884247
37    32921121     32921121   32921121    32921121    ...      32921124214
38    32922081     32922081   32922081    32922081    ...      32922084163
39    32923041     32923041   32923041    32923041    ...      32923044135
40    32924001     32924001   32924001    32924001    ...      32924004339
41    32924961     32924961   32924961    32924961    ...      32924964341
42    32925551     32925551   32925551    32925551    ...      32925554297
43    32925921     32925921   32925921    32925921    ...      32925924396
44    32926881     32926881   32926881    32926881    ...      32926884379
45    32927841     32927841   32927841    32927841    ...      32927844275
46    32928801     32928801   32928801    32928801    ...      32928804219
47    32929761     32929761   32929761    32929761    ...      32929764223
48    32930721     32930721   32930721    32930721    ...      32930724162
49    32931681     32931681   32931681    32931681    ...      32931684290
50    32931951     32931951   32931951    32931951    ...      32931954366
51    32932641     32932641   32932641    32932641    ...      32932644361
52    32933601     32933601   32933601    32933601    ...      32933604347
53    32934561     32934561   32934561    32934561    ...      32934564304
54    32935521     32935521   32935521    32935521    ...      32935524262
55    32936061     32936061   32936061    32936061    ...      32936064459
56    32936481     32936481   32936481    32936481    ...      32936484426
57    32937441     32937441   32937441    32937441    ...      32937444408
58    32938401     32938401   32938401    32938401    ...      32938404388
59    32939361     32939361   32939361    32939361    ...      32939364375
60    32940321     32940321   32940321    32940321    ...      32940324357
61    32940961     32940961   32940961    32940961    ...      32940964414

    32940965015  3294096555   3294096585   329409673   329409675  3294096768  \
0             0           0            0           0           0           0
1    3290096221           0  32900961020   329009640           0  3290096124
2    3290108234           0  32901081471   329010844           0  3290108114
3    3290139545           0   3290139119  3290139138           0  3290139261
4    3290188538           0    329018879  3290188197           0  3290188285
5    3290192554           0    329019278  3290192195           0  3290192291
6    3290225544           0    329022582  3290225210  3290225189  3290225307
7    3290275579           0    329027574  3290275196  3290275121  3290275307
8    3290288619           0    329028872  3290288186  3290288109  3290288300
9    3290347581           0    329034758  3290347164   329034764  3290347281
10   3290384579           0    329038460  3290384127   329038446  3290384281
11   3290457588           0    329045751  3290457104   329045736  3290457298
12   3290480583           0    329048049  3290480102   329048032  3290480324
13   3290576536           0    329057638   329057696   329057626  3290576383
14   3290637554           0    329063738  3290637104   329063727  3290637432
15   3290672559           0    329067235  3290672100   329067221  3290672445
16   3290768567           0    329076836   329076886   329076824  3290768468
17   3290777570           0    329077736   329077786   329077723  3290777467
18   3290864555           0    329086434   329086477   329086420  3290864451
19   3290960543           0    329096033   329096073   329096021  3290960483
20   3290974534           0    329097431   329097473   329097420  3290974478
21   3291056562           0    329105639   329105668   329105622  3291056516
22   3291106741           0    329110652   329110666   329110622  3291106605
23   3291152887           0    329115265   329115271   329115223  3291152630
24  32912481314           0    329124869   329124868   329124825  3291248663
25   3291270963           0    329127068   329127066   329127026  3291270664
26   3291344954           0    329134471   329134461   329134424  3291344669
27   3291440948           0    329144073   329144058   329144021  3291440664
28   3291476953           0    329147674   329147661   329147621  3291476662
29   3291536954           0    329153675   329153662   329153634  3291536656
..          ...         ...          ...         ...         ...         ...
32   3291740964           0    329174076   329174063   329174043  3291740718
33  32918241363           0    329182478   329182462   329182445  3291824721
34  32919201657           0    329192075   329192057   329192047  3291920729
35  32920161763           0    329201673   329201653   329201648  3292016729
36  32920881809           0   3292088210   329208852   329208849  3292088728
37  32921121823           0   3292112188   329211251   329211250  3292112723
38  32922081833           0   3292208214   329220850   329220848  3292208722
39  32923041843           0   3292304234   329230450   329230449  3292304732
40  32924001879           0   3292400261   329240048   329240050  3292400787

In [4]:
# simulation='h148'
# resolution=100
# host = get_host(simulation=simulation, resolution=resolution)
# host_MPB, host_ids = get_main_progenitor_branch(tangos_halo=host, simulation=simulation, 
#                                                 resolution=resolution)
# host_ids=[int(i) for i in host_ids]
# df=df.replace(host_ids, 0)
# df

pd.set_option("display.max_rows", None, "display.max_columns", None)
df = pd.read_csv('h148MPB_ids.csv')
# df.to_csv('h148MPB_ids.csv', index=False)
df

,snapshot,148110610,14811066,148115218,14812709,148128013,14812804,14814089,148153610,14829762,14832642,148409610,14840961025,14840961061,148409611,14840961156,14840961179,148409612,148409612211,148409613555,14840961379,1484096138,14840961413,14840961467,14840961693,148409617,1484096179,14840961883,14840961900,1484096194,148409619718,14840962,14840962026,1484096204,148409620589,148409621,1484096210,148409622,14840962413,1484096266,1484096271,1484096278,14840962927,14840963,148409632,148409633,1484096331,148409634,148409635,1484096374,1484096387,148409639,14840964,14840964022,148409641,1484096412,14840964127,1484096422,14840964409,1484096459,1484096478,14840964944,14840965,148409651,148409653,148409655,1484096567,14840965903,14840966,148409663,148409668,14840967,14840967007,148409676,148409677,1484096803,14840968565,1484096857
0,71,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,108,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,128,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,139,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,188,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,225,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,256,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,275,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,347,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,384,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,457,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,512,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,637,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,640,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,777,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,896,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,974,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,1024,148102411,14810245,148102422,14810243,148102416,14810243,148102414,148102415,14810242,0,148102421,1481024220,0,148102418,14810241276,148102425,148102444,0,0,1481024284,148102484,14810241127,0,0,148102419,148102446,0,0,148102485,0,14810246,148102462,1481024118,0,148102426,148102497,148102447,0,0,1481024166,1481024102,0,14810244,0,148102424,1481024107,148102461,148102428,1481024292,1481024232,148102457,14810247,0,1481024238,148102491,148102474,1481024237,14810241090,148102466,0,0,148102410,148102460,1481024160,1481024183,0,1481024681,148102412,148102483,148102429,148102420,0,148102478,148102443,1481024434,0,0
18,1106,148110610,14811066,148110620,14811063,148110614,14811063,148110612,148110613,14811062,0,148110619,1481106217,0,148110615,1481106898,148110622,148110644,0,0,1481106275,148110675,14811061194,0,0,148110617,148110648,0,0,148110682,0,14811065,148110668,1481106118,0,148110623,148110694,148110649,0,0,1481106159,148110695,0,14811064,0,148110621,1481106108,148110656,148110626,1481106283,1481106241,148110658,14811067,0,1481106115,148110689,148110674,1481106228,14811061246,148110679,0,0,14811068,148110627,1481106146,1481106167,0,1481106929,14811069,148110677,148110628,148110618,0,148110676,148110642,1481106226,0,0
19,1152,0,0,148115218,14811523,148115212,14811523,148115210,148115211,14811522,0,148115216,1481152211,0,148115213,1481152800,148115221,148115238,0,0,1481152279,148115266,14811521200,0,0,148115215,148115244,0,0,148115280,0,14811525,148115265,1481152112,0,148115220,148115288,148115242,0,0,1481152165,148115287,0,14811524,0,148115219,1481152105,148115251,148115223,1481152277,1481152237,148115252,14811526,0,148115293,148115283,148115279,1481152219,14811521182,148115268,0,0,14811527,148115224,1481152139,1481152141,0,1481152646,14811529,148115273,148115225,148115217,0,148115274,148115236,1481152220,0,0
20,1270,0,0,0,14812709,148127014,14812703,148127011,148127012,14812702,0,148127017,1481270202,0,148127013,1481270849,148127039,148127034,0,0,1481270275,148127054,14812701291,0,0,148127019,148127044,0,0,148127077,0,14812705,148127096,1481270122,0,148127018,148127094,148127042,148127067,0,1481270155,148127084,0,14812704,0,148127020,1481270108,148127051,148127022,1481270260,1481270247,148127046,14812706,0,148127080,148127083,148127090,1481270213,14812701348,148127049,0,0,14812708,148127023,1481270140,148127095,0,1481270668,148127010,148127071,148127024,148127016,0,148127070,148127036,1481270209,0,0
21,1280,0,0,0,0,148128013,14812804,148128010,148128011,14812802,0,148128018,1481280203,0,148128012,1481280855,148128038,148128033,0,0,1481280278,148128053,14812801298,0,0,148128017,148128044,0,0,148128077,0,14812805,1481280102,1481280120,0,148128016,148128091,148128041,148128067,0,1481280154,148128087,0,14812803,0,148128019,1481280108,148128050,148128021,1481280283,1481280250,148128045,14812806,0,148128080,148128086,148128094,1481280213,14812801346,148128048,0,0,14812808,148128022,1481280138,148128082,0,1481280668,14812809,148128070,148128023,148128015,0,148128069,148128035,1481280206,0,0
22,1408,0,0,0,0,0,0,14814089,148140810,14814082,0,148140816,1481408183,0,148140812,1481408856,148140842,148140837,0,0,1481408248,148140847,14814081405,0,0,148140813,148140839,0,0,148140873,0,14814084,1481408130,1481408112,0,148140815,148140887,148140833,148140886,0,1481408141,148140878,0,14814083,0,148140817,148140894,148140848,148140820,1481408222,1481408245,148140838,14814085,14814085871,148140865,148140881,1481408135,1481408189,14814081879,148140855,0,0,14814086,148140823,1481408107,148140857,0,1481408694,14814088,148140862,148140822,148140811,0,1481408101,148140832,1481408167,0,0
23,1476,0,0,0,0,0,0,0,148147616,14814762,0,148147615,1481476179,1481476765,148147611,1481476877,148147643,148147617,0,0,1481476233,148147645,14814761479,0,0,148147612,148147635,0,0,148147672,0,14814764,1481476145,1481476124,0,148147614,148147689,148147629,1481476104,0,1481476138,148147677,0,14814763,0,148147618,148147696,148147646,148147622,1481476222,1481476246,148147636,14814765,14814765742,148147671,148147695,1481476147,1481476183,14814762037,148147657,0,0,14814766,148147624,1481476106,148147658,0,1481476768,14814768,148147669,148147623,148147610,0,148147690,148147632,1481476159,0,0
24,1536,0,0,0,0,0,0,0,148153610,14815362,0,148153616,1481536171,1481536801,148153612,1481536863,148153650,148153617,0,0,1481536224,148153644,14815361480,0,0,148153613,148153635,0,1481536677,148153674,0,14815364,1481536155,1481536137,0,148153615,148153686,148153628,148153697,1481536271,1481536134,148153668,0,14815363,148153621,148153619,148153693,148153647,148153622,1481536229,1481536252,148153636,14815365,14815365725,148153670,1481536101,1481536148,1481536175,14815361725,148153659,0,0,14815366,148153623,148153699,148153657,0,1481536783,14815368,148153669,148153624,148153611,0,148153683,148153633,1481536151,0,0
25,1664,0,0,0,0,0,0,0,0,14816642,0,148166412,1481664164,1481664903,148166410,1481664828,148166458,148166416,0,0,1481664212,148166444,14816641509,0,0,148166411,148166437,0,1481664684,148166473,0,14816644,1481664159,1481664153,0,148166414,148166490,148166426,1481664104,1481664296,1481664130,148166460,0,14816643,148166422,148166419,148166492,148166446,148166420,1481664249,1481664215,148166435,14816645,14816645601,148166454,1481664120,1481664174,1481664163,14816641935,148166462,0,0,14816646,148166423,148166493,148166456,0,1481664866,14816648,148166469,148166421,14816649,0,148166489,148166432,1481664184,0,1481664583
26,1740,0,0,0,0,0,0,0,0,14817402,0,148174013,1481740174,14817401016,148174010,1481740870,148174071,148174017,0,0,1481740209,1481740116,14817401539,1481740105,0,148174011,148174038,0,1481740763,148174073,0,14817404,1481740173,1481740162,0,148174014,1481740156,148174028,1481740114,1481740313,1481740134,148174056,14817403459,14817403,148174026,148174021,148174096,148174049,148174022,1481740254,1481740214,148174036,14817405,14817405586,148174048,1481740179,1481740261,1481740164,14817401997,148174058,1481740126,14817401283,14817406,148174024,148174093,148174055,0,1481740935,14817408,148174064,148174023,14817409,0,148174092,148174032,1481740258,0,1481740675
27,1920,0,0,0,0,0,0,0,0,14819202,0,148192013,1481920391,14819201254,148192010,14819201114,1481920145,148192014,0,0,1481920206,148192086,14819201652,1481920110,0,148192011,148192035,0,1481920773,1481920102,0,14819204,1481920230,1481920172,0,148192012,1481920127,148192026,1481920339,1481920312,1481920134,148192054,14819203385,14819203,148192025,148192019,1481920117,148192048,148192021,1481920261,1481920216,148192039,14819205,14819205381,148192045,1481920183,1481920450,1481920158,14819202693,148192057,1481920137,14819201352,14819206,148192023,148192072,148192053,0,1481920979,14819208,148192064,148192029,14819209,0,148192093,148192032,1481920159,0,1481920723
28,2048,0,0,0,0,0,0,0,0,14820482,0,148204812,1482048443,14820481273,148204810,14820481146,1482048213,148204814,0,0,1482048195,148204886,14820481687,1482048122,0,148204811,148204833,0,1482048789,1482048128,0,14820484,1482048273,1482048175,0,148204819,1482048143,148204827,14820481782,1482048314,1482048132,148204854,14820483333,14820483,148204826,148204818,1482048113,148204849,148204823,1482048256,1482048210,148204837,14820485,14820485260,148204847,1482048182,14820483529,1482048151,14820482713,148204858,1482048142,14820481355,14820486,148204820,148204873,148204853,0,14820481038,14820488,148204862,148204838,14820489,0,148204891,148204830,1482048169,0,1482048709
29,2088,0,0,0,0,0,0,0,0,14820882,0,148208812,1482088462,14820881301,148208810,14820881160,14820881647,148208814,0,0,1482088193,148208888,14820881685,1482088125,0,148208811,148208833,0,1482088787,1482088110,0,14820884,1482088283,1482088173,0,148208819,1482088146,148208827,14820881798,1482088310,1482088133,148208853,14820883314,14820883,148208826,148208817,1482088120,148208847,148208818,1482088259,1482088208,148208836,14820885,14820885245,148208845,1482088185,14820883931,1482088150,14820882736,148208858,1482088142,14820881352,14820886,148208820,148208872,148208852,0,14820881028,14820888,148208862,148208838,14820889,0,148208892,148208830,1482088290,14820883070,1482088716
30,2112,0,0,0,0,0,0,0,0,14821122,0,148211212,1482112462,14821121285,148211210,14821121167,14821121660,148211214,0,0,1482112193,148211285,14821121686,1482112124,14821121586,148211211,148211232,0,1482112784,1482112109,0,14821124,1482112288,1482112172,0,148211217,1482112146,148211226,14821121845,1482112305,1482112132,148211253,14821123286,14821123,148211224,148211218,1482112120,148211245,148211219,1482112258,1482112205,148211235,14821125,14821125232,148211244,1482112188,14821123734,1482112148,14821122767,148211256,1482112141,14821121339,14821126,148211220,148211270,148211251,0,14821121023,14821128,148211261,148211238,14821129,0,148211292,148211229,1482112155,14821123108,1482112721
31,2208,0,0,0,0,0,0,0,0,14822082,0,148220811,1482208459,14822081275,148220810,14822081192,14822081624,148220814,0,0,1482208345,148220884,14822081680,1482208128,14822081598,148220812,148220868,0,1482208774,1482208131,0,14822084,1482208307,1482208168,0,148220816,1482208150,148220823,14822082023,1482208294,1482208133,148220851,14822083244,14822083,148220822,148220821,1482208126,148220842,148220818,1482208245,1482208204,148220833,14822086,14822085214,148220840,1482208190,14822083583,1482208146,14822082831,148220855,1482208141,14822081323,14822085,148220819,148220866,148220846,0,14822081022,14822088,148220860,148220839,14822089,14822083497,148220894,148220829,1482208426,14822083288,1482208764
32,2304,0,0,0,0,0,0,0,0,14823042,0,148230411,1482304471,14823041288,148230410,14823041212,14823041632,148230415,0,0,1482304344,148230486,14823041682,1482304128,14823041644,148230414,148230469,0,1482304768,1482304129,0,14823044,1482304341,1482304168,0,148230416,1482304147,148230426,14823042638,1482304279,1482304126,148230453,14823043379,14823043,148230424,148230420,1482304130,148230442,148230418,1482304241,1482304202,148230434,14823046,14823045122,148230440,1482304189,14823043650,1482304144,14823043170,148230457,1482304136,14823041325,14823045,148230419,148230470,148230448,0,14823041025,14823048,148230461,148230441,14823049,14823043442,148230496,148230430,1482304416,14823043356,1482304820
33,2400,0,0,0,0,0,0,0,0,14824002,0,148240012,1482400473,14824001272,148240010,14824001204,14824001637,148240014,0,0,1482400327,148240087,14824001677,1482400127,14824001668,148240015,148240074,0,1482400752,1482400119,0,14824004,1482400419,1482400166,0,148240016,1482400146,148240024,14824002623,1482400282,1482400126,148240050,14824003401,14824003,148240025,148240018,1482400130,148240043,148240020,1482400236,1482400196,148240032,14824007,14824005038,148240042,1482400188,14824004438,1482400141,14824003389,148240059,1482400138,14824001415,14824005,148240019,148240066,148240045,0,14824001079,14824008,148240060,148240044,14824009,14824003365,148240096,148240028,1482400414,14824003391,1482400761
34,2496,0,0,0,0,0,0,0,0,14824962,0,148249613,1482496512,14824961231,148249610,14824961235,14824961593,148249614,0,0,1482496356,148249691,14824961740,1482496129,14824961697,148249615,148249672,0,1482496743,1482496126,0,14824963,1482496523,1482496171,0,148249617,1482496146,148249622,14824962571,1482496276,1482496128,148249652,14824963375,14824964,148249624,148249618,1482496131,148249642,148249621,1482496235,1482496253,148249628,14824967,14824964957,148249641,1482496191,14824964366,1482496142,14824963430,148249661,1482496140,14824962156,14824966,148249619,148249664,148249646,0,14824962054,14824968,148249665,148249647,14824969,14824963293,148249696,148249632,1482496615,14824964889,1482496764
35,2555,0,0,0,0,0,0,0,0,14825552,0,148255513,1482555625,14825551226,148255510,14825551349,14825551560,148255514,0,0,1482555402,148255596,14825551728,1482555127,14825551706,148255515,148255576,0,1482555731,1482555129,0,14825553,1482555576,1482555177,0,148255517,1482555144,148255522,14825552546,1482555268,1482555128,148255549,14825553340,14825554,148255526,148255519,1482555130,148255542,148255524,1482555229,1482555225,148255528,14825557,14825554891,148255540,1482555190,14825554329,1482555142,14825553413,148255561,1482555136,14825552227,14825556,148255520,148255564,148255543,0,14825552171,14825558,148255565,148255545,14825559,14825553257,148255597,148255535,1482555631,14825555134,1482555761
36,2592,0,0,0,0,0,0,0,0,14825922,0,148259213,1482592648,14825921214,148259211,14825921342,14825921553,148259214,0,0,1482592483,1482592101,14825921733,1482592127,14825921739,148259215,148259277,0,1482592722,1482592129,0,14825923,1482592614,1482592179,0,148259217,1482592143,148259222,14825922586,1482592264,1482592128,148259249,14825923363,14825924,148259227,148259219,1482592130,148259242,148259226,1482592230,1482592368,148259229,14825927,14825924827,148259240,1482592190,14825924302,1482592141,14825923397,148259261,1482592136,14825922252,14825926,148259220,148259263,148259241,0,14825922266,14825928,148259265,148259245,14825929,14825923218,148259296,148259235,1482592640,14825925307,1482592774
37,2688,0,0,0,0,0,0,0,0,14826882,0,148268812,1482688655,14826881210,148268814,14826881359,14826881518,148268813,148268811976,148268814078,1482688743,1482688117,14826881727,1482688148,14826881900,148268815,148268882,0,1482688716,1482688130,148268817841,14826883,1482688671,1482688191,0,148268817,1482688140,148268823,14826882675,1482688262,1482688149,148268851,14826883226,14826884,148268827,148268819,1482688128,148268842,148268825,1482688226,1482688375,148268831,14826887,14826884736,148268840,1482688202,14826884385,1482688146,14826883539,148268864,1482688135,14826882262,14826885,148268826,148268855,148268841,0,14826882371,14826888,148268866,148268847,14826889,14826883158,148268897,148268838,1482688647,14826885446,1482688844
38,2784,0,0,0,0,0,0,0,0,14827842,0,148278412,1482784661,14827841202,148278413,14827841338,14827841494,148278414,148278412202,148278414058,1482784743,1482784119,14827841696,1482784300,14827841838,148278415,148278482,0,1482784695,1482784131,148278419543,14827843,1482784721,1482784189,0,148278417,1482784138,148278420,14827842660,1482784255,1482784164,148278452,14827843174,14827844,148278427,148278418,1482784124,148278442,148278424,1482784227,1482784380,148278429,14827846,14827844612,148278438,1482784238,14827844407,1482784186,14827843751,148278475,1482784158,14827842302,14827845,148278431,148278455,148278441,0,14827842406,14827848,148278465,148278446,14827849,14827843254,148278496,148278450,1482784651,14827845472,1482784888
39,2880,0,0,0,0,0,0,0,0,14828802,0,148288013,1482880676,14828801183,148288012,14828801368,14828801468,148288014,148288012871,148288013895,1482880744,1482880122,14828801689,1482880302,14828801832,148288015,148288082,0,1482880683,1482880130,148288020026,14828803,1482880771,1482880191,0,148288018,1482880138,148288021,14828802623,1482880270,1482880163,148288051,14828803272,14828804,148288029,148288019,1482880125,148288043,148288030,1482880296,1482880391,148288028,14828806,14828804530,148288039,1482880247,14828804347,1482880188,14828803727,1482880133,1482880185,14828802820,14828805,148288031,148288046,148288042,0,14828802438,14828808,148288064,148288045,14828809,14828803215,148288095,148288056,1482880658,14828805569,1482880871
40,2976,0,0,0,0,0,0,0,0,14829762,0,148297613,1482976688,14829761179,148297612,14829761374,14829761440,148297614,148297612628,148297613744,1482976754,1482976123,14829761707,1482976337,14829761812,148297615,148297682,0,1482976679,1482976128,148297619963,14829763,1482976805,1482976192,0,148297618,1482976138,148297620,14829762581,1482976288,1482976165,148297649,14829763249,14829764,148297628,148297623,1482976122,148297643,148297629,1482976362,1482976405,148297627,14829766,14829764453,148297640,1482976249,14829764303,1482976187,14829763702,1482976121,1482976190,14829763088,14829765,148297631,148297645,148297642,0,14829762489,14829768,148297666,148297659,14829769,14829763183,148297694,148297656,1482976676,14829766423,1482976861

### Get & Store sSFR

In [5]:
# for sim in ['h329', 'h148']:
#     if sim=='h329':
#         idx = h329_ids
#     else:
#         idx = h148_ids
#     for what in ['SFR', 'sSFR', 'mass', 'new_mass']:
#         column_names = ['snapshot']+idx
#         df = pd.DataFrame(columns = column_names)
#         df.to_csv(str(sim)+'MPB_'+ str(what) +'.csv', index=False)
#         ts = get_timesteps(simulation=sim, resolution=100)[3]
#         df['snapshot'] = ts
#         df.to_csv(str(sim)+'MPB_'+ str(what) +'.csv', index=False)
#         print(what, ' initialized ', sim)

SFR  initialized  h329
sSFR  initialized  h329
mass  initialized  h329
new_mass  initialized  h329
SFR  initialized  h148
sSFR  initialized  h148
mass  initialized  h148
new_mass  initialized  h148

In [ ]:
for sim in ['h329', 'h148']:
    print('started simulation ', sim)
    
    df = pd.read_csv(str(sim)+'MPB_ids.csv')
    IDs = np.asarray(df.columns)[1:]
    print('my IDs are ', IDs)
    ts = get_timesteps(simulation=sim, resolution=100)[3]
    print('the timesteps are ', ts)
    
    
    
    #Read in new dfs
    df_SFR = pd.read_csv(str(sim)+'MPB_SFR.csv')
    df_sSFR = pd.read_csv(str(sim)+'MPB_sSFR.csv')
    df_mass = pd.read_csv(str(sim)+'MPB_mass.csv')
    df_new_mass = pd.read_csv(str(sim)+'MPB_new_mass.csv')
    
    #Iterate through each timestep
    for index in range(0, len(ts)):
        #index is #row
        snapnum = ts[index]
        print('starting with timestep ', snapnum)
        
        halo_ids = np.asarray(df.loc[index][1:])
        print('for timestep ', snapnum, ' my halo IDs are ', halo_ids)
    
        if sim=='h329':
            snapshot = pynbody.load('/home/dp1144/tangos_simulations/'+ str(sim) +'/snapshots/'+ str(sim) +'.cosmo50PLK.6144g5HbwK1BH.00'+ str(snapnum))
        else:
            snapshot = pynbody.load('/home/dp1144/tangos_simulations/'+ str(sim) +'/snapshots/'+ str(sim) +'.cosmo50PLK.6144g3HbwK1BH.00'+ str(snapnum))
        snapshot.physical_units()
        all_halos = snapshot.halos()
        print(snapshot)
        print(all_halos)
        
        count=0 #This is #column-1
        
        #Iterate through each halo
        for idx in halo_ids:
            print('started [', index, ', ', count, ']')
            ID = IDs[count]
            print('my ID is ', ID)
            print('')
            if idx==0:
                #set everything to -1 and move on
                df_SFR.iat[index, count+1] = -1
                df_sSFR.iat[index, count+1] = -1
                df_mass.iat[index, count+1] = -1
                df_new_mass.iat[index, count+1] = -1
            else:
                idx=int(idx)
                simulation, status, halo_id, snap_num = ID_to_sim_halo_snap(ID=idx)
                halo=all_halos[int(halo_id)]
                print(halo)
                #Do the calculation
                mass = np.asarray(halo.s['mass'].in_units('Msol'))
                age = halo.properties['time'].in_units('Gyr') - halo.s['tform'].in_units('Gyr') #SimArray in Gyr
                new_mass = np.sum(mass[age <= 0.1]) # Formed within last 100 Myr
                total_mass = np.sum(mass)
                SFR = new_mass/1e8
                if SFR==0:
                    sSFR=0
                else:
                    sSFR = SFR/total_mass
                
                print('SFR: ', SFR)
                print('sSFR: ', sSFR)
                print('mass: ', total_mass)
                print('new mass: ', new_mass)
                
                #add data in dfs
                df_SFR.iat[index, count+1] = SFR
                df_sSFR.iat[index, count+1] = sSFR
                df_mass.iat[index, count+1] = total_mass
                df_new_mass.iat[index, count+1] = new_mass
            print('finished [', index, ', ', count+1, ']')     

            df_SFR.to_csv(str(sim)+'MPB_SFR.csv', index=False)
            df_sSFR.to_csv(str(sim)+'MPB_sSFR.csv', index=False)
            df_mass.to_csv(str(sim)+'MPB_mass.csv', index=False)
            df_new_mass.to_csv(str(sim)+'MPB_new_mass.csv', index=False)
            
            print('saved [', index, ', ', count, ']')
            
            #Move on to next id == next column
            count+=1
        
        print('finished timestep ', snapnum)
    print('finished simulation ', sim)
print('FINALLY WE ARE DONE!!!')

started simulation  h329
my IDs are  ['3290188153' '3290192110' '3290192111' '329019225' '329019230' '329022513'
 '329022530' '329022579' '329034745' '329038417' '329038430' '329038438'
 '329048011' '329048022' '329048034' '32904809' '32906374' '329067210'
 '32906729' '32907774' '32908648' '329096015' '32909747' '329127010'
 '32913443' '32914768' '32924962' '32930722' '32933603' '329409616'
 '32940961630' '32940961648' '329409620' '32940963299' '3294096335'
 '3294096350' '329409643' '32940964414' '32940965015' '3294096555'
 '3294096585' '329409673' '329409675' '3294096768' '32940969' '3294096956'
 '329409696']
the timesteps are  ['0071', '0096', '0108', '0139', '0188', '0192', '0225', '0275', '0288', '0347', '0384', '0457', '0480', '0576', '0637', '0672', '0768', '0777', '0864', '0960', '0974', '1056', '1106', '1152', '1248', '1270', '1344', '1440', '1476', '1536', '1632', '1728', '1740', '1824', '1920', '2016', '2088', '2112', '2208', '2304', '2400', '2496', '2555', '2592', '2688', '2784', '2880', '2976', '3072', '3168', '3195', '3264', '3360', '3456', '3552', '3606', '3648', '3744', '3840', '3936', '4032', '4096']
starting with timestep  0071
for timestep  0071  my halo IDs are  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0]
<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000071" len=109184070>
<pynbody.halo.ahf.AHFCatalogue object at 0x7f9c54d50d30>
started [ 0 ,  0 ]
my ID is  3290188153

finished [ 0 ,  1 ]
saved [ 0 ,  0 ]
started [ 0 ,  1 ]
my ID is  3290192110

finished [ 0 ,  2 ]
saved [ 0 ,  1 ]
started [ 0 ,  2 ]
my ID is  3290192111

finished [ 0 ,  3 ]
saved [ 0 ,  2 ]
started [ 0 ,  3 ]
my ID is  329019225

finished [ 0 ,  4 ]
saved [ 0 ,  3 ]
started [ 0 ,  4 ]
my ID is  329019230

finished [ 0 ,  5 ]
saved [ 0 ,  4 ]
started [ 0 ,  5 ]
my ID is  329022513

finished [ 0 ,  6 ]
saved [ 0 ,  5 ]
started [ 0 ,  6 ]
my ID is  329022530

finished [ 0 ,  7 ]
saved [ 0 ,  6 ]
started [ 0 ,  7 ]
my ID is  329022579

finished [ 0 ,  8 ]
saved [ 0 ,  7 ]
started [ 0 ,  8 ]
my ID is  329034745

finished [ 0 ,  9 ]
saved [ 0 ,  8 ]
started [ 0 ,  9 ]
my ID is  329038417

finished [ 0 ,  10 ]
saved [ 0 ,  9 ]
started [ 0 ,  10 ]
my ID is  329038430

finished [ 0 ,  11 ]
saved [ 0 ,  10 ]
started [ 0 ,  11 ]
my ID is  329038438

finished [ 0 ,  12 ]
saved [ 0 ,  11 ]
started [ 0 ,  12 ]
my ID is  329048011

finished [ 0 ,  13 ]
saved [ 0 ,  12 ]
started [ 0 ,  13 ]
my ID is  329048022

finished [ 0 ,  14 ]
saved [ 0 ,  13 ]
started [ 0 ,  14 ]
my ID is  329048034

finished [ 0 ,  15 ]
saved [ 0 ,  14 ]
started [ 0 ,  15 ]
my ID is  32904809

finished [ 0 ,  16 ]
saved [ 0 ,  15 ]
started [ 0 ,  16 ]
my ID is  32906374

finished [ 0 ,  17 ]
saved [ 0 ,  16 ]
started [ 0 ,  17 ]
my ID is  329067210

finished [ 0 ,  18 ]
saved [ 0 ,  17 ]
started [ 0 ,  18 ]
my ID is  32906729

finished [ 0 ,  19 ]
saved [ 0 ,  18 ]
started [ 0 ,  19 ]
my ID is  32907774

finished [ 0 ,  20 ]
saved [ 0 ,  19 ]
started [ 0 ,  20 ]
my ID is  32908648

finished [ 0 ,  21 ]
saved [ 0 ,  20 ]
started [ 0 ,  21 ]
my ID is  329096015

finished [ 0 ,  22 ]
saved [ 0 ,  21 ]
started [ 0 ,  22 ]
my ID is  32909747

finished [ 0 ,  23 ]
saved [ 0 ,  22 ]
started [ 0 ,  23 ]
my ID is  329127010

finished [ 0 ,  24 ]
saved [ 0 ,  23 ]
started [ 0 ,  24 ]
my ID is  32913443

finished [ 0 ,  25 ]
saved [ 0 ,  24 ]
started [ 0 ,  25 ]
my ID is  32914768

finished [ 0 ,  26 ]
saved [ 0 ,  25 ]
started [ 0 ,  26 ]
my ID is  32924962

finished [ 0 ,  27 ]
saved [ 0 ,  26 ]
started [ 0 ,  27 ]
my ID is  32930722

finished [ 0 ,  28 ]
saved [ 0 ,  27 ]
started [ 0 ,  28 ]
my ID is  32933603

finished [ 0 ,  29 ]
saved [ 0 ,  28 ]
started [ 0 ,  29 ]
my ID is  329409616

finished [ 0 ,  30 ]
saved [ 0 ,  29 ]
started [ 0 ,  30 ]
my ID is  32940961630

finished [ 0 ,  31 ]
saved [ 0 ,  30 ]
started [ 0 ,  31 ]
my ID is  32940961648

finished [ 0 ,  32 ]
saved [ 0 ,  31 ]
started [ 0 ,  32 ]
my ID is  329409620

finished [ 0 ,  33 ]
saved [ 0 ,  32 ]
started [ 0 ,  33 ]
my ID is  32940963299

finished [ 0 ,  34 ]
saved [ 0 ,  33 ]
started [ 0 ,  34 ]
my ID is  3294096335

finished [ 0 ,  35 ]
saved [ 0 ,  34 ]
started [ 0 ,  35 ]
my ID is  3294096350

finished [ 0 ,  36 ]
saved [ 0 ,  35 ]
started [ 0 ,  36 ]
my ID is  329409643

finished [ 0 ,  37 ]
saved [ 0 ,  36 ]
started [ 0 ,  37 ]
my ID is  32940964414

finished [ 0 ,  38 ]
saved [ 0 ,  37 ]
started [ 0 ,  38 ]
my ID is  32940965015

finished [ 0 ,  39 ]
saved [ 0 ,  38 ]
started [ 0 ,  39 ]
my ID is  3294096555

finished [ 0 ,  40 ]
saved [ 0 ,  39 ]
started [ 0 ,  40 ]
my ID is  3294096585

finished [ 0 ,  41 ]
saved [ 0 ,  40 ]
started [ 0 ,  41 ]
my ID is  329409673

finished [ 0 ,  42 ]
saved [ 0 ,  41 ]
started [ 0 ,  42 ]
my ID is  329409675

finished [ 0 ,  43 ]
saved [ 0 ,  42 ]
started [ 0 ,  43 ]
my ID is  3294096768

finished [ 0 ,  44 ]
saved [ 0 ,  43 ]
started [ 0 ,  44 ]
my ID is  32940969

finished [ 0 ,  45 ]
saved [ 0 ,  44 ]
started [ 0 ,  45 ]
my ID is  3294096956

finished [ 0 ,  46 ]
saved [ 0 ,  45 ]
started [ 0 ,  46 ]
my ID is  329409696

finished [ 0 ,  47 ]
saved [ 0 ,  46 ]
finished timestep  0071
starting with timestep  0096
for timestep  0096  my halo IDs are  [  329009638   329009662    32900969           0           0  3290096431
 32900961293           0   329009617           0  3290096554   329009611
  3290096346    32900963           0           0           0           0
           0           0           0           0   329009659   329009659
  3290096532           0           0           0           0           0
           0  3290096321   329009634  3290096158           0   329009654
           0           0  3290096221           0 32900961020   329009640
           0  3290096124           0           0   329009612]
<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096" len=109195063>
<pynbody.halo.ahf.AHFCatalogue object at 0x7f9c54553f98>
started [ 1 ,  0 ]
my ID is  3290188153

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_38" len=2141>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 1 ,  1 ]
saved [ 1 ,  0 ]
started [ 1 ,  1 ]
my ID is  3290192110

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_62" len=1520>
SFR:  0.0
sSFR:  0
mass:  191646.68433
new mass:  0.0
finished [ 1 ,  2 ]
saved [ 1 ,  1 ]
started [ 1 ,  2 ]
my ID is  3290192111

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_9" len=5810>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 1 ,  3 ]
saved [ 1 ,  2 ]
started [ 1 ,  3 ]
my ID is  329019225

finished [ 1 ,  4 ]
saved [ 1 ,  3 ]
started [ 1 ,  4 ]
my ID is  329019230

finished [ 1 ,  5 ]
saved [ 1 ,  4 ]
started [ 1 ,  5 ]
my ID is  329022513

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_431" len=344>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 1 ,  6 ]
saved [ 1 ,  5 ]
started [ 1 ,  6 ]
my ID is  329022530

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_1293" len=138>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 1 ,  7 ]
saved [ 1 ,  6 ]
started [ 1 ,  7 ]
my ID is  329022579

finished [ 1 ,  8 ]
saved [ 1 ,  7 ]
started [ 1 ,  8 ]
my ID is  329034745

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_17" len=3707>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 1 ,  9 ]
saved [ 1 ,  8 ]
started [ 1 ,  9 ]
my ID is  329038417

finished [ 1 ,  10 ]
saved [ 1 ,  9 ]
started [ 1 ,  10 ]
my ID is  329038430

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_554" len=282>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 1 ,  11 ]
saved [ 1 ,  10 ]
started [ 1 ,  11 ]
my ID is  329038438

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_11" len=5382>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 1 ,  12 ]
saved [ 1 ,  11 ]
started [ 1 ,  12 ]
my ID is  329048011

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_346" len=414>

SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 1 ,  13 ]
saved [ 1 ,  12 ]
started [ 1 ,  13 ]
my ID is  329048022

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_3" len=32927>
SFR:  0.00835871609749
sSFR:  8.34634876523e-09
mass:  1001481.76557
new mass:  835871.609749
finished [ 1 ,  14 ]
saved [ 1 ,  13 ]
started [ 1 ,  14 ]
my ID is  329048034

finished [ 1 ,  15 ]
saved [ 1 ,  14 ]
started [ 1 ,  15 ]
my ID is  32904809

finished [ 1 ,  16 ]
saved [ 1 ,  15 ]
started [ 1 ,  16 ]
my ID is  32906374

finished [ 1 ,  17 ]
saved [ 1 ,  16 ]
started [ 1 ,  17 ]
my ID is  329067210

finished [ 1 ,  18 ]
saved [ 1 ,  17 ]
started [ 1 ,  18 ]
my ID is  32906729

finished [ 1 ,  19 ]
saved [ 1 ,  18 ]
started [ 1 ,  19 ]
my ID is  32907774

finished [ 1 ,  20 ]
saved [ 1 ,  19 ]
started [ 1 ,  20 ]
my ID is  32908648

finished [ 1 ,  21 ]
saved [ 1 ,  20 ]
started [ 1 ,  21 ]
my ID is  329096015

finished [ 1 ,  22 ]
saved [ 1 ,  21 ]
started [ 1 ,  22 ]
my ID is  32909747

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_59" len=1609>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 1 ,  23 ]
saved [ 1 ,  22 ]
started [ 1 ,  23 ]
my ID is  329127010

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_59" len=1609>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 1 ,  24 ]
saved [ 1 ,  23 ]
started [ 1 ,  24 ]
my ID is  32913443

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_532" len=292>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 1 ,  25 ]
saved [ 1 ,  24 ]
started [ 1 ,  25 ]
my ID is  32914768

finished [ 1 ,  26 ]
saved [ 1 ,  25 ]
started [ 1 ,  26 ]
my ID is  32924962

finished [ 1 ,  27 ]
saved [ 1 ,  26 ]
started [ 1 ,  27 ]
my ID is  32930722

finished [ 1 ,  28 ]
saved [ 1 ,  27 ]
started [ 1 ,  28 ]
my ID is  32933603

finished [ 1 ,  29 ]
saved [ 1 ,  28 ]
started [ 1 ,  29 ]
my ID is  329409616

finished [ 1 ,  30 ]
saved [ 1 ,  29 ]
started [ 1 ,  30 ]
my ID is  32940961630

finished [ 1 ,  31 ]
saved [ 1 ,  30 ]
started [ 1 ,  31 ]
my ID is  32940961648

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_321" len=437>
SFR:  0.0
sSFR:  0
mass:  12182.8534512
new mass:  0.0
finished [ 1 ,  32 ]
saved [ 1 ,  31 ]
started [ 1 ,  32 ]
my ID is  329409620

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_34" len=2256>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 1 ,  33 ]
saved [ 1 ,  32 ]
started [ 1 ,  33 ]
my ID is  32940963299

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_158" len=706>
SFR:  8.10274461816e-05
sSFR:  1e-08
mass:  8102.74461816
new mass:  8102.74461816
finished [ 1 ,  34 ]
saved [ 1 ,  33 ]
started [ 1 ,  34 ]
my ID is  3294096335

finished [ 1 ,  35 ]
saved [ 1 ,  34 ]
started [ 1 ,  35 ]
my ID is  3294096350

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_54" len=1710>
SFR:  8.05596650953e-06
sSFR:  3.94930672878e-10
mass:  20398.4320864
new mass:  805.596650953
finished [ 1 ,  36 ]
saved [ 1 ,  35 ]
started [ 1 ,  36 ]
my ID is  329409643

finished [ 1 ,  37 ]
saved [ 1 ,  36 ]
started [ 1 ,  37 ]
my ID is  32940964414

finished [ 1 ,  38 ]
saved [ 1 ,  37 ]
started [ 1 ,  38 ]
my ID is  32940965015

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_221" len=564>
SFR:  0.0
sSFR:  0
mass:  3844.73921407
new mass:  0.0
finished [ 1 ,  39 ]
saved [ 1 ,  38 ]
started [ 1 ,  39 ]
my ID is  3294096555

finished [ 1 ,  40 ]
saved [ 1 ,  39 ]
started [ 1 ,  40 ]
my ID is  3294096585

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_1020" len=170>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 1 ,  41 ]
saved [ 1 ,  40 ]
started [ 1 ,  41 ]
my ID is  329409673

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_40" len=2108>
SFR:  8.07964381256e-06
sSFR:  1e-08
mass:  807.964381256
new mass:  807.964381256
finished [ 1 ,  42 ]
saved [ 1 ,  41 ]
started [ 1 ,  42 ]
my ID is  329409675

finished [ 1 ,  43 ]
saved [ 1 ,  42 ]
started [ 1 ,  43 ]
my ID is  3294096768

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_124" len=828>
SFR:  0.0
sSFR:  0
mass:  38141.2584071
new mass:  0.0
finished [ 1 ,  44 ]
saved [ 1 ,  43 ]
started [ 1 ,  44 ]
my ID is  32940969

finished [ 1 ,  45 ]
saved [ 1 ,  44 ]
started [ 1 ,  45 ]
my ID is  3294096956

finished [ 1 ,  46 ]
saved [ 1 ,  45 ]
started [ 1 ,  46 ]
my ID is  329409696

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000096:halo_12" len=4490>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 1 ,  47 ]
saved [ 1 ,  46 ]
finished timestep  0096
starting with timestep  0108
for timestep  0108  my halo IDs are  [  329010830   329010856   329010810           0   329010836  3290108621
 32901081787           0   329010817           0 32901081324   329010813
  3290108453    32901082           0 32901081510           0           0
           0           0           0           0   329010835   329010835
 32901081189           0           0           0 32901082025           0
           0  3290108319   329010828  3290108155           0   329010849
           0           0  3290108234           0 32901081471   329010844
           0  3290108114           0           0   329010814]
<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108" len=109199514>
<pynbody.halo.ahf.AHFCatalogue object at 0x7f9c54ee4710>
started [ 2 ,  0 ]
my ID is  3290188153

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_30" len=3001>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  1 ]
saved [ 2 ,  0 ]
started [ 2 ,  1 ]
my ID is  3290192110

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_56" len=1878>
SFR:  0.0
sSFR:  0
mass:  191527.148868
new mass:  0.0
finished [ 2 ,  2 ]
saved [ 2 ,  1 ]
started [ 2 ,  2 ]
my ID is  3290192111

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_10" len=7685>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  3 ]
saved [ 2 ,  2 ]
started [ 2 ,  3 ]
my ID is  329019225

finished [ 2 ,  4 ]
saved [ 2 ,  3 ]
started [ 2 ,  4 ]
my ID is  329019230

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_36" len=2662>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  5 ]
saved [ 2 ,  4 ]
started [ 2 ,  5 ]
my ID is  329022513

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_621" len=302>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  6 ]
saved [ 2 ,  5 ]
started [ 2 ,  6 ]
my ID is  329022530

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_1787" len=119>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  7 ]
saved [ 2 ,  6 ]
started [ 2 ,  7 ]
my ID is  329022579

finished [ 2 ,  8 ]
saved [ 2 ,  7 ]
started [ 2 ,  8 ]
my ID is  329034745

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_17" len=4803>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  9 ]
saved [ 2 ,  8 ]
started [ 2 ,  9 ]
my ID is  329038417

finished [ 2 ,  10 ]
saved [ 2 ,  9 ]
started [ 2 ,  10 ]
my ID is  329038430

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_1324" len=157>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  11 ]
saved [ 2 ,  10 ]
started [ 2 ,  11 ]
my ID is  329038438

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_13" len=7150>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  12 ]
saved [ 2 ,  11 ]
started [ 2 ,  12 ]
my ID is  329048011

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_453" len=379>

SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  13 ]
saved [ 2 ,  12 ]
started [ 2 ,  13 ]
my ID is  329048022

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_2" len=38202>
SFR:  0.0016599709931
sSFR:  1.45330598842e-09
mass:  1142203.36689
new mass:  165997.09931
finished [ 2 ,  14 ]
saved [ 2 ,  13 ]
started [ 2 ,  14 ]
my ID is  329048034

finished [ 2 ,  15 ]
saved [ 2 ,  14 ]
started [ 2 ,  15 ]
my ID is  32904809

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_1510" len=138>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  16 ]
saved [ 2 ,  15 ]
started [ 2 ,  16 ]
my ID is  32906374

finished [ 2 ,  17 ]
saved [ 2 ,  16 ]
started [ 2 ,  17 ]
my ID is  329067210

finished [ 2 ,  18 ]
saved [ 2 ,  17 ]
started [ 2 ,  18 ]
my ID is  32906729

finished [ 2 ,  19 ]
saved [ 2 ,  18 ]
started [ 2 ,  19 ]
my ID is  32907774

finished [ 2 ,  20 ]
saved [ 2 ,  19 ]
started [ 2 ,  20 ]
my ID is  32908648

finished [ 2 ,  21 ]
saved [ 2 ,  20 ]
started [ 2 ,  21 ]
my ID is  329096015

finished [ 2 ,  22 ]
saved [ 2 ,  21 ]
started [ 2 ,  22 ]
my ID is  32909747

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_35" len=2676>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  23 ]
saved [ 2 ,  22 ]
started [ 2 ,  23 ]
my ID is  329127010

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_35" len=2676>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  24 ]
saved [ 2 ,  23 ]
started [ 2 ,  24 ]
my ID is  32913443

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_1189" len=172>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  25 ]
saved [ 2 ,  24 ]
started [ 2 ,  25 ]
my ID is  32914768

finished [ 2 ,  26 ]
saved [ 2 ,  25 ]
started [ 2 ,  26 ]
my ID is  32924962

finished [ 2 ,  27 ]
saved [ 2 ,  26 ]
started [ 2 ,  27 ]
my ID is  32930722

finished [ 2 ,  28 ]
saved [ 2 ,  27 ]
started [ 2 ,  28 ]
my ID is  32933603

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_2025" len=107>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  29 ]
saved [ 2 ,  28 ]
started [ 2 ,  29 ]
my ID is  329409616

finished [ 2 ,  30 ]
saved [ 2 ,  29 ]
started [ 2 ,  30 ]
my ID is  32940961630

finished [ 2 ,  31 ]
saved [ 2 ,  30 ]
started [ 2 ,  31 ]
my ID is  32940961648

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_319" len=496>
SFR:  0.0
sSFR:  0
mass:  11991.4387117
new mass:  0.0
finished [ 2 ,  32 ]
saved [ 2 ,  31 ]
started [ 2 ,  32 ]
my ID is  329409620

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_28" len=3030>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  33 ]
saved [ 2 ,  32 ]
started [ 2 ,  33 ]
my ID is  32940963299

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_155" len=807>
SFR:  0.0
sSFR:  0
mass:  7859.07682548
new mass:  0.0
finished [ 2 ,  34 ]
saved [ 2 ,  33 ]
started [ 2 ,  34 ]
my ID is  3294096335

finished [ 2 ,  35 ]
saved [ 2 ,  34 ]
started [ 2 ,  35 ]
my ID is  3294096350

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_49" len=2123>
SFR:  0.0
sSFR:  0
mass:  19951.2530386
new mass:  0.0
finished [ 2 ,  36 ]
saved [ 2 ,  35 ]
started [ 2 ,  36 ]
my ID is  329409643

finished [ 2 ,  37 ]
saved [ 2 ,  36 ]
started [ 2 ,  37 ]
my ID is  32940964414

finished [ 2 ,  38 ]
saved [ 2 ,  37 ]
started [ 2 ,  38 ]
my ID is  32940965015

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_234" len=619>
SFR:  0.0
sSFR:  0
mass:  3776.32000083
new mass:  0.0
finished [ 2 ,  39 ]
saved [ 2 ,  38 ]
started [ 2 ,  39 ]
my ID is  3294096555

finished [ 2 ,  40 ]
saved [ 2 ,  39 ]
started [ 2 ,  40 ]
my ID is  3294096585

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_1471" len=141>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  41 ]
saved [ 2 ,  40 ]
started [ 2 ,  41 ]
my ID is  329409673

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_44" len=2336>
SFR:  0.0
sSFR:  0
mass:  782.118871518
new mass:  0.0
finished [ 2 ,  42 ]
saved [ 2 ,  41 ]
started [ 2 ,  42 ]
my ID is  329409675

finished [ 2 ,  43 ]
saved [ 2 ,  42 ]
started [ 2 ,  43 ]
my ID is  3294096768

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_114" len=1027>
SFR:  0.0
sSFR:  0
mass:  37671.8452427
new mass:  0.0
finished [ 2 ,  44 ]
saved [ 2 ,  43 ]
started [ 2 ,  44 ]
my ID is  32940969

finished [ 2 ,  45 ]
saved [ 2 ,  44 ]
started [ 2 ,  45 ]
my ID is  3294096956

finished [ 2 ,  46 ]
saved [ 2 ,  45 ]
started [ 2 ,  46 ]
my ID is  329409696

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000108:halo_14" len=6449>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 2 ,  47 ]
saved [ 2 ,  46 ]
finished timestep  0108
starting with timestep  0139
for timestep  0139  my halo IDs are  [  329013986  3290139151   329013963   329013935   329013959   329013913
   329013957   329013953  3290139109  3290139264  3290139931   329013949
    32901393    32901398   329013937 32901392449    32901391   329013915
 32901394122   329013943   329013931   329013931   329013981   329013981
    32901392  3290139195   329013928           0   329013919           0
           0  3290139540   329013984  3290139385   329013996  3290139139
   329013910           0  3290139545           0  3290139119  3290139138
           0  3290139261   329013924   329013940   329013960]
<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139" len=109228889>
<pynbody.halo.ahf.AHFCatalogue object at 0x7f98055d72b0>
started [ 3 ,  0 ]
my ID is  3290188153

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_86" len=5991>
SFR:  7.31590064809e-05
sSFR:  1e-08
mass:  7315.90064809
new mass:  7315.90064809
finished [ 3 ,  1 ]
saved [ 3 ,  0 ]
started [ 3 ,  1 ]
my ID is  3290192110

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_151" len=2827>
SFR:  0.0
sSFR:  0
mass:  191304.413512
new mass:  0.0
finished [ 3 ,  2 ]
saved [ 3 ,  1 ]
started [ 3 ,  2 ]
my ID is  3290192111

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_63" len=8421>
SFR:  0.00156476092012
sSFR:  1e-08
mass:  156476.092012
new mass:  156476.092012
finished [ 3 ,  3 ]
saved [ 3 ,  2 ]
started [ 3 ,  3 ]
my ID is  329019225

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_35" len=15187>
SFR:  9.94145147986e-06
sSFR:  3.30187349594e-10
mass:  30108.5171558
new mass:  994.145147986
finished [ 3 ,  4 ]
saved [ 3 ,  3 ]
started [ 3 ,  4 ]
my ID is  329019230

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_59" len=9220>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 3 ,  5 ]
saved [ 3 ,  4 ]
started [ 3 ,  5 ]
my ID is  329022513

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_13" len=33121>
SFR:  0.0051286375522
sSFR:  1.36153349668e-09
mass:  3766809.678
new mass:  512863.75522
finished [ 3 ,  6 ]
saved [ 3 ,  5 ]
started [ 3 ,  6 ]
my ID is  329022530

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_57" len=9317>
SFR:  0.0040516024763
sSFR:  1e-08
mass:  405160.24763
new mass:  405160.24763
finished [ 3 ,  7 ]
saved [ 3 ,  6 ]
started [ 3 ,  7 ]
my ID is  329022579

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_53" len=9957>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 3 ,  8 ]
saved [ 3 ,  7 ]
started [ 3 ,  8 ]
my ID is  329034745

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_109" len=4645>

SFR:  0.00067489423274
sSFR:  1e-08
mass:  67489.423274
new mass:  67489.423274
finished [ 3 ,  9 ]
saved [ 3 ,  8 ]
started [ 3 ,  9 ]
my ID is  329038417

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_264" len=1343>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 3 ,  10 ]
saved [ 3 ,  9 ]
started [ 3 ,  10 ]
my ID is  329038430

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_931" len=458>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 3 ,  11 ]
saved [ 3 ,  10 ]
started [ 3 ,  11 ]
my ID is  329038438

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_49" len=10314>
SFR:  0.00106684478338
sSFR:  1e-08
mass:  106684.478338
new mass:  106684.478338
finished [ 3 ,  12 ]
saved [ 3 ,  11 ]
started [ 3 ,  12 ]
my ID is  329048011

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_3" len=102422>
SFR:  0.00840785598093
sSFR:  2.00069731709e-09
mass:  4202462.76591
new mass:  840785.598093
finished [ 3 ,  13 ]
saved [ 3 ,  12 ]
started [ 3 ,  13 ]
my ID is  329048022

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_8" len=55665>
SFR:  0.00750606387599
sSFR:  4.08675152216e-09
mass:  1836682.22432
new mass:  750606.387599
finished [ 3 ,  14 ]
saved [ 3 ,  13 ]
started [ 3 ,  14 ]
my ID is  329048034

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_37" len=14312>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 3 ,  15 ]
saved [ 3 ,  14 ]
started [ 3 ,  15 ]
my ID is  32904809

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_2449" len=180>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 3 ,  16 ]
saved [ 3 ,  15 ]
started [ 3 ,  16 ]
my ID is  32906374

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_1" len=219663>
SFR:  0.0974568634859
sSFR:  4.79715058888e-09
mass:  20315573.1054
new mass:  9745686.34859
finished [ 3 ,  17 ]
saved [ 3 ,  16 ]
started [ 3 ,  17 ]
my ID is  329067210

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_15" len=29781>
SFR:  0.00176041558391
sSFR:  1e-08
mass:  176041.558391
new mass:  176041.558391
finished [ 3 ,  18 ]
saved [ 3 ,  17 ]
started [ 3 ,  18 ]
my ID is  32906729

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_4122" len=101>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 3 ,  19 ]
saved [ 3 ,  18 ]
started [ 3 ,  19 ]
my ID is  32907774

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_43" len=11398>
SFR:  0.00167197496315
sSFR:  1e-08
mass:  167197.496315
new mass:  167197.496315
finished [ 3 ,  20 ]
saved [ 3 ,  19 ]
started [ 3 ,  20 ]
my ID is  32908648

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_31" len=16430>
SFR:  0.000169444110618
sSFR:  1e-08
mass:  16944.4110618
new mass:  16944.4110618
finished [ 3 ,  21 ]
saved [ 3 ,  20 ]
started [ 3 ,  21 ]
my ID is  329096015

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_31" len=16430>
SFR:  0.000169444110618
sSFR:  1e-08
mass:  16944.4110618
new mass:  16944.4110618
finished [ 3 ,  22 ]
saved [ 3 ,  21 ]
started [ 3 ,  22 ]
my ID is  32909747

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_81" len=6578>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 3 ,  23 ]
saved [ 3 ,  22 ]
started [ 3 ,  23 ]
my ID is  329127010

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_81" len=6578>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 3 ,  24 ]
saved [ 3 ,  23 ]
started [ 3 ,  24 ]
my ID is  32913443

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_2" len=156897>
SFR:  0.0359347529691
sSFR:  8.05044692979e-09
mass:  4463696.64721
new mass:  3593475.29691
finished [ 3 ,  25 ]
saved [ 3 ,  24 ]
started [ 3 ,  25 ]
my ID is  32914768

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_195" len=2062>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 3 ,  26 ]
saved [ 3 ,  25 ]
started [ 3 ,  26 ]
my ID is  32924962

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_28" len=17175>
SFR:  5.9128698702e-05
sSFR:  1e-08
mass:  5912.8698702
new mass:  5912.8698702
finished [ 3 ,  27 ]
saved [ 3 ,  26 ]
started [ 3 ,  27 ]
my ID is  32930722

finished [ 3 ,  28 ]
saved [ 3 ,  27 ]
started [ 3 ,  28 ]
my ID is  32933603

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_19" len=22840>
SFR:  0.000256250145297
sSFR:  1e-08
mass:  25625.0145297
new mass:  25625.0145297
finished [ 3 ,  29 ]
saved [ 3 ,  28 ]
started [ 3 ,  29 ]
my ID is  329409616

finished [ 3 ,  30 ]
saved [ 3 ,  29 ]
started [ 3 ,  30 ]
my ID is  32940961630

finished [ 3 ,  31 ]
saved [ 3 ,  30 ]
started [ 3 ,  31 ]
my ID is  32940961648

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_540" len=717>
SFR:  0.0
sSFR:  0
mass:  11645.5182905
new mass:  0.0
finished [ 3 ,  32 ]
saved [ 3 ,  31 ]
started [ 3 ,  32 ]
my ID is  329409620

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_84" len=6221>
SFR:  9.94145147986e-06
sSFR:  1e-08
mass:  994.145147986
new mass:  994.145147986
finished [ 3 ,  33 ]
saved [ 3 ,  32 ]
started [ 3 ,  33 ]
my ID is  32940963299

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_385" len=966>
SFR:  0.0
sSFR:  0
mass:  7508.46368712
new mass:  0.0
finished [ 3 ,  34 ]
saved [ 3 ,  33 ]
started [ 3 ,  34 ]
my ID is  3294096335

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_96" len=5358>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 3 ,  35 ]
saved [ 3 ,  34 ]
started [ 3 ,  35 ]
my ID is  3294096350

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_139" len=3083>
SFR:  0.0
sSFR:  0
mass:  19223.7545188
new mass:  0.0
finished [ 3 ,  36 ]
saved [ 3 ,  35 ]
started [ 3 ,  36 ]
my ID is  329409643

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_10" len=43871>
SFR:  0.00239666550816
sSFR:  1.81795915278e-09
mass:  1318327.47975
new mass:  239666.550816
finished [ 3 ,  37 ]
saved [ 3 ,  36 ]
started [ 3 ,  37 ]
my ID is  32940964414

finished [ 3 ,  38 ]
saved [ 3 ,  37 ]
started [ 3 ,  38 ]
my ID is  32940965015

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_545" len=715>
SFR:  0.0
sSFR:  0
mass:  3657.14451211
new mass:  0.0
finished [ 3 ,  39 ]
saved [ 3 ,  38 ]
started [ 3 ,  39 ]
my ID is  3294096555

finished [ 3 ,  40 ]
saved [ 3 ,  39 ]
started [ 3 ,  40 ]
my ID is  3294096585

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_119" len=3964>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 3 ,  41 ]
saved [ 3 ,  40 ]
started [ 3 ,  41 ]
my ID is  329409673

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_138" len=3103>
SFR:  0.0
sSFR:  0
mass:  746.076394897
new mass:  0.0
finished [ 3 ,  42 ]
saved [ 3 ,  41 ]
started [ 3 ,  42 ]
my ID is  329409675

finished [ 3 ,  43 ]
saved [ 3 ,  42 ]
started [ 3 ,  43 ]
my ID is  3294096768

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_261" len=1352>
SFR:  0.0
sSFR:  0
mass:  36767.8896145
new mass:  0.0
finished [ 3 ,  44 ]
saved [ 3 ,  43 ]
started [ 3 ,  44 ]
my ID is  32940969

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_24" len=20689>

SFR:  1.9560095703e-05
sSFR:  1e-08
mass:  1956.0095703
new mass:  1956.0095703
finished [ 3 ,  45 ]
saved [ 3 ,  44 ]
started [ 3 ,  45 ]
my ID is  3294096956

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_40" len=12713>
SFR:  0.00020984292388
sSFR:  1e-08
mass:  20984.292388
new mass:  20984.292388
finished [ 3 ,  46 ]
saved [ 3 ,  45 ]
started [ 3 ,  46 ]
my ID is  329409696

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000139:halo_60" len=8789>
SFR:  0.00145184087804
sSFR:  1e-08
mass:  145184.087804
new mass:  145184.087804
finished [ 3 ,  47 ]
saved [ 3 ,  46 ]
finished timestep  0139
starting with timestep  0188
for timestep  0188  my halo IDs are  [ 3290188153  3290188114  3290188111   329018827   329018833   329018813
   329018845   329018866   329018881   329018840  3290188477   329018830
    32901885   329018810   329018844 32901882712    32901881   329018811
   329018834   329018815   329018825   329018825   329018857   329018857
    32901883   329018878    32901888           0    32901889   329018877
           0  3290188655   329018855  3290188324   329018898  3290188151
   329018814           0  3290188538           0   329018879  3290188197
           0  3290188285   329018822   329018862   329018880]
<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188" len=109278141>
<pynbody.halo.ahf.AHFCatalogue object at 0x7f9c54eecb70>
started [ 4 ,  0 ]
my ID is  3290188153

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_153" len=4545>
SFR:  8.16763333784e-06
sSFR:  6.2472916409e-10
mass:  13073.8787419
new mass:  816.763333784
finished [ 4 ,  1 ]
saved [ 4 ,  0 ]
started [ 4 ,  1 ]
my ID is  3290192110

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_114" len=6915>
SFR:  0.0
sSFR:  0
mass:  191356.922163
new mass:  0.0
finished [ 4 ,  2 ]
saved [ 4 ,  1 ]
started [ 4 ,  2 ]
my ID is  3290192111

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_111" len=7155>
SFR:  8.85522606029e-06
sSFR:  6.13408824319e-11
mass:  144360.917372
new mass:  885.522606029
finished [ 4 ,  3 ]
saved [ 4 ,  2 ]
started [ 4 ,  3 ]
my ID is  329019225

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_27" len=39331>
SFR:  0.00231629392576
sSFR:  8.05753526431e-09
mass:  287469.288037
new mass:  231629.392576
finished [ 4 ,  4 ]
saved [ 4 ,  3 ]
started [ 4 ,  4 ]
my ID is  329019230

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_33" len=31854>
SFR:  0.000586851005008
sSFR:  4.58531750523e-09
mass:  127984.813339
new mass:  58685.1005008
finished [ 4 ,  5 ]
saved [ 4 ,  4 ]
started [ 4 ,  5 ]
my ID is  329022513

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_13" len=75060>
SFR:  0.0
sSFR:  0
mass:  3818687.76085
new mass:  0.0
finished [ 4 ,  6 ]
saved [ 4 ,  5 ]
started [ 4 ,  6 ]
my ID is  329022530

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_45" len=24081>
SFR:  0.0
sSFR:  0
mass:  370859.647135
new mass:  0.0
finished [ 4 ,  7 ]
saved [ 4 ,  6 ]
started [ 4 ,  7 ]
my ID is  329022579

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_66" len=14862>
SFR:  0.000697489795713
sSFR:  9.78116707806e-09
mass:  71309.4654397
new mass:  69748.9795713
finished [ 4 ,  8 ]
saved [ 4 ,  7 ]
started [ 4 ,  8 ]
my ID is  329034745

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_81" len=10812>
SFR:  0.0
sSFR:  0
mass:  60322.7509977
new mass:  0.0
finished [ 4 ,  9 ]
saved [ 4 ,  8 ]
started [ 4 ,  9 ]
my ID is  329038417

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_40" len=27818>
SFR:  5.53908582043e-05
sSFR:  1e-08
mass:  5539.08582043
new mass:  5539.08582043
finished [ 4 ,  10 ]
saved [ 4 ,  9 ]
started [ 4 ,  10 ]
my ID is  329038430

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_477" len=1189>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 4 ,  11 ]
saved [ 4 ,  10 ]
started [ 4 ,  11 ]
my ID is  329038438

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_30" len=37156>
SFR:  0.000381878957104
sSFR:  2.90245962809e-09
mass:  131570.807534
new mass:  38187.8957104
finished [ 4 ,  12 ]
saved [ 4 ,  11 ]
started [ 4 ,  12 ]
my ID is  329048011

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_5" len=156612>
SFR:  0.0484833996442
sSFR:  4.88518490867e-09
mass:  9924578.1993
new mass:  4848339.96442
finished [ 4 ,  13 ]
saved [ 4 ,  12 ]
started [ 4 ,  13 ]
my ID is  329048022

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_10" len=95277>
SFR:  0.00378259333173
sSFR:  1.42503415013e-09
mass:  2654387.84844
new mass:  378259.333173
finished [ 4 ,  14 ]
saved [ 4 ,  13 ]
started [ 4 ,  14 ]
my ID is  329048034

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_44" len=24183>
SFR:  0.000418206308293
sSFR:  5.8482252164e-09
mass:  71509.9526469
new mass:  41820.6308293
finished [ 4 ,  15 ]
saved [ 4 ,  14 ]
started [ 4 ,  15 ]
my ID is  32904809

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_2712" len=250>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 4 ,  16 ]
saved [ 4 ,  15 ]
started [ 4 ,  16 ]
my ID is  32906374

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_1" len=320246>
SFR:  0.0463980595479
sSFR:  1.73278202333e-09
mass:  26776627.9447
new mass:  4639805.95479
finished [ 4 ,  17 ]
saved [ 4 ,  16 ]
started [ 4 ,  17 ]
my ID is  329067210

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_11" len=78425>
SFR:  0.0146654887997
sSFR:  8.6013403416e-09
mass:  1705023.66111
new mass:  1466548.87997
finished [ 4 ,  18 ]
saved [ 4 ,  17 ]
started [ 4 ,  18 ]
my ID is  32906729

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_34" len=31030>
SFR:  0.00144406900517
sSFR:  1.1286079369e-09
mass:  1279513.42353
new mass:  144406.900517
finished [ 4 ,  19 ]
saved [ 4 ,  18 ]
started [ 4 ,  19 ]
my ID is  32907774

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_15" len=64305>
SFR:  0.000486107386241
sSFR:  1.47342220525e-09
mass:  329917.239273
new mass:  48610.7386241
finished [ 4 ,  20 ]
saved [ 4 ,  19 ]
started [ 4 ,  20 ]
my ID is  32908648

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_25" len=41195>
SFR:  0.0013583392656
sSFR:  7.30497750342e-09
mass:  185947.084021
new mass:  135833.92656
finished [ 4 ,  21 ]
saved [ 4 ,  20 ]
started [ 4 ,  21 ]
my ID is  329096015

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_25" len=41195>
SFR:  0.0013583392656
sSFR:  7.30497750342e-09
mass:  185947.084021
new mass:  135833.92656
finished [ 4 ,  22 ]
saved [ 4 ,  21 ]
started [ 4 ,  22 ]
my ID is  32909747

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_57" len=17020>
SFR:  0.000179968044692
sSFR:  7.93022313761e-09
mass:  22693.9446178
new mass:  17996.8044692
finished [ 4 ,  23 ]
saved [ 4 ,  22 ]
started [ 4 ,  23 ]
my ID is  329127010

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_57" len=17020>
SFR:  0.000179968044692
sSFR:  7.93022313761e-09
mass:  22693.9446178
new mass:  17996.8044692
finished [ 4 ,  24 ]
saved [ 4 ,  23 ]
started [ 4 ,  24 ]
my ID is  32913443

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_3" len=194042>

SFR:  0.0228651766293
sSFR:  2.79449763796e-09
mass:  8182213.61818
new mass:  2286517.66293
finished [ 4 ,  25 ]
saved [ 4 ,  24 ]
started [ 4 ,  25 ]
my ID is  32914768

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_78" len=11020>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 4 ,  26 ]
saved [ 4 ,  25 ]
started [ 4 ,  26 ]
my ID is  32924962

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_8" len=100680>
SFR:  0.00213982151709
sSFR:  2.85717701778e-09
mass:  748928.576625
new mass:  213982.151709
finished [ 4 ,  27 ]
saved [ 4 ,  26 ]
started [ 4 ,  27 ]
my ID is  32930722

finished [ 4 ,  28 ]
saved [ 4 ,  27 ]
started [ 4 ,  28 ]
my ID is  32933603

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_9" len=96013>
SFR:  0.0236689328486
sSFR:  8.53015700184e-09
mass:  2774735.898
new mass:  2366893.28486
finished [ 4 ,  29 ]
saved [ 4 ,  28 ]
started [ 4 ,  29 ]
my ID is  329409616

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_77" len=11299>
SFR:  0.000162341941344
sSFR:  9.54415979392e-09
mass:  17009.5581853
new mass:  16234.1941344
finished [ 4 ,  30 ]
saved [ 4 ,  29 ]
started [ 4 ,  30 ]
my ID is  32940961630

finished [ 4 ,  31 ]
saved [ 4 ,  30 ]
started [ 4 ,  31 ]
my ID is  32940961648

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_655" len=908>
SFR:  0.0
sSFR:  0
mass:  11304.7616822
new mass:  0.0
finished [ 4 ,  32 ]
saved [ 4 ,  31 ]
started [ 4 ,  32 ]
my ID is  329409620

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_55" len=18152>
SFR:  0.000266294720304
sSFR:  7.57564231436e-09
mass:  35151.4378918
new mass:  26629.4720304
finished [ 4 ,  33 ]
saved [ 4 ,  32 ]
started [ 4 ,  33 ]
my ID is  32940963299

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_324" len=1708>
SFR:  0.0
sSFR:  0
mass:  7219.33970381
new mass:  0.0
finished [ 4 ,  34 ]
saved [ 4 ,  33 ]
started [ 4 ,  34 ]
my ID is  3294096335

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_98" len=8548>
SFR:  8.64898926004e-06
sSFR:  1e-08
mass:  864.898926004
new mass:  864.898926004
finished [ 4 ,  35 ]
saved [ 4 ,  34 ]
started [ 4 ,  35 ]
my ID is  3294096350

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_151" len=4552>
SFR:  0.0
sSFR:  0
mass:  18568.9788125
new mass:  0.0
finished [ 4 ,  36 ]
saved [ 4 ,  35 ]
started [ 4 ,  36 ]
my ID is  329409643

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_14" len=66114>
SFR:  0.00102123459745
sSFR:  7.28650754458e-10
mass:  1401541.9475
new mass:  102123.459745
finished [ 4 ,  37 ]
saved [ 4 ,  36 ]
started [ 4 ,  37 ]
my ID is  32940964414

finished [ 4 ,  38 ]
saved [ 4 ,  37 ]
started [ 4 ,  38 ]
my ID is  32940965015

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_538" len=1067>
SFR:  0.0
sSFR:  0
mass:  3543.63178028
new mass:  0.0
finished [ 4 ,  39 ]
saved [ 4 ,  38 ]
started [ 4 ,  39 ]
my ID is  3294096555

finished [ 4 ,  40 ]
saved [ 4 ,  39 ]
started [ 4 ,  40 ]
my ID is  3294096585

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_79" len=10913>
SFR:  6.80652156486e-05
sSFR:  1e-08
mass:  6806.52156486
new mass:  6806.52156486
finished [ 4 ,  41 ]
saved [ 4 ,  40 ]
started [ 4 ,  41 ]
my ID is  329409673

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_197" len=3102>
SFR:  0.0
sSFR:  0
mass:  717.010929537
new mass:  0.0
finished [ 4 ,  42 ]
saved [ 4 ,  41 ]
started [ 4 ,  42 ]
my ID is  329409675

finished [ 4 ,  43 ]
saved [ 4 ,  42 ]
started [ 4 ,  43 ]
my ID is  3294096768

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_285" len=1940>
SFR:  0.0
sSFR:  0
mass:  35819.3794026
new mass:  0.0
finished [ 4 ,  44 ]
saved [ 4 ,  43 ]
started [ 4 ,  44 ]
my ID is  32940969

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_22" len=45175>
SFR:  0.000514089635496
sSFR:  1.75052382542e-09
mass:  293677.599831
new mass:  51408.9635496
finished [ 4 ,  45 ]
saved [ 4 ,  44 ]
started [ 4 ,  45 ]
my ID is  3294096956

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_62" len=15733>
SFR:  9.38706954604e-05
sSFR:  1.1898376412e-09
mass:  78893.7012998
new mass:  9387.06954604
finished [ 4 ,  46 ]
saved [ 4 ,  45 ]
started [ 4 ,  46 ]
my ID is  329409696

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000188:halo_80" len=10819>
SFR:  0.0
sSFR:  0
mass:  132687.796825
new mass:  0.0
finished [ 4 ,  47 ]
saved [ 4 ,  46 ]
finished timestep  0188
starting with timestep  0192
for timestep  0192  my halo IDs are  [          0  3290192110  3290192111   329019225   329019230   329019213
   329019245   329019267   329019272   329019237  3290192418   329019228
    32901924    32901928   329019241 32901922794    32901922   329019212
   329019234   329019210   329019224   329019224   329019256   329019256
    32901923   329019276    32901927           0    32901929   329019279
           0  3290192670   329019253  3290192316   329019294  3290192152
   329019215           0  3290192554           0   329019278  3290192195
           0  3290192291   329019220   329019261   329019281]
<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192" len=109283765>
<pynbody.halo.ahf.AHFCatalogue object at 0x7f9c54c84ef0>
started [ 5 ,  0 ]
my ID is  3290188153

finished [ 5 ,  1 ]
saved [ 5 ,  0 ]
started [ 5 ,  1 ]
my ID is  3290192110

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_110" len=7131>
SFR:  0.0
sSFR:  0
mass:  191430.012397
new mass:  0.0
finished [ 5 ,  2 ]
saved [ 5 ,  1 ]
started [ 5 ,  2 ]
my ID is  3290192111

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_111" len=7104>
SFR:  8.56703455428e-06
sSFR:  5.95896787562e-11
mass:  143767.087407
new mass:  856.703455428
finished [ 5 ,  3 ]
saved [ 5 ,  2 ]
started [ 5 ,  3 ]
my ID is  329019225

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_25" len=41866>
SFR:  0.00222955498972
sSFR:  7.87133271678e-09
mass:  283249.999707
new mass:  222955.498972
finished [ 5 ,  4 ]
saved [ 5 ,  3 ]
started [ 5 ,  4 ]
my ID is  329019230

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_30" len=36475>
SFR:  0.000455306697089
sSFR:  3.55422302844e-09
mass:  128103.018141
new mass:  45530.6697089
finished [ 5 ,  5 ]
saved [ 5 ,  4 ]
started [ 5 ,  5 ]
my ID is  329022513

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_13" len=75626>
SFR:  0.0
sSFR:  0
mass:  3817590.25822
new mass:  0.0
finished [ 5 ,  6 ]
saved [ 5 ,  5 ]
started [ 5 ,  6 ]
my ID is  329022530

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_45" len=23463>
SFR:  0.0
sSFR:  0
mass:  369384.838272
new mass:  0.0
finished [ 5 ,  7 ]
saved [ 5 ,  6 ]
started [ 5 ,  7 ]
my ID is  329022579

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_67" len=14002>
SFR:  0.000622133577391
sSFR:  8.87699163135e-09
mass:  70083.830562
new mass:  62213.3577391
finished [ 5 ,  8 ]
saved [ 5 ,  7 ]
started [ 5 ,  8 ]
my ID is  329034745

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_72" len=12626>
SFR:  0.0
sSFR:  0
mass:  60056.0184508
new mass:  0.0
finished [ 5 ,  9 ]
saved [ 5 ,  8 ]
started [ 5 ,  9 ]
my ID is  329038417

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_37" len=29881>

SFR:  8.10489523096e-05
sSFR:  1e-08
mass:  8104.89523096
new mass:  8104.89523096
finished [ 5 ,  10 ]
saved [ 5 ,  9 ]
started [ 5 ,  10 ]
my ID is  329038430

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_418" len=1357>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 5 ,  11 ]
saved [ 5 ,  10 ]
started [ 5 ,  11 ]
my ID is  329038438

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_28" len=39758>
SFR:  0.000748164238452
sSFR:  4.45969897509e-09
mass:  167761.152183
new mass:  74816.4238452
finished [ 5 ,  12 ]
saved [ 5 ,  11 ]
started [ 5 ,  12 ]
my ID is  329048011

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_4" len=153213>
SFR:  0.0450382474685
sSFR:  4.45042746396e-09
mass:  10119982.3687
new mass:  4503824.74685
finished [ 5 ,  13 ]
saved [ 5 ,  12 ]
started [ 5 ,  13 ]
my ID is  329048022

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_8" len=98624>
SFR:  0.00285506979576
sSFR:  1.05614946893e-09
mass:  2703281.94991
new mass:  285506.979576
finished [ 5 ,  14 ]
saved [ 5 ,  13 ]
started [ 5 ,  14 ]
my ID is  329048034

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_41" len=24597>
SFR:  0.000476463720885
sSFR:  6.0546632123e-09
mass:  78693.6786042
new mass:  47646.3720885
finished [ 5 ,  15 ]
saved [ 5 ,  14 ]
started [ 5 ,  15 ]
my ID is  32904809

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_2794" len=247>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 5 ,  16 ]
saved [ 5 ,  15 ]
started [ 5 ,  16 ]
my ID is  32906374

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_2" len=329266>
SFR:  0.0495648717577
sSFR:  1.77440271082e-09
mass:  27933270.9849
new mass:  4956487.17577
finished [ 5 ,  17 ]
saved [ 5 ,  16 ]
started [ 5 ,  17 ]
my ID is  329067210

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_12" len=79857>
SFR:  0.0145266856002
sSFR:  8.38912225659e-09
mass:  1731609.71504
new mass:  1452668.56002
finished [ 5 ,  18 ]
saved [ 5 ,  17 ]
started [ 5 ,  18 ]
my ID is  32906729

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_34" len=31161>
SFR:  0.00141808484623
sSFR:  1.11475481111e-09
mass:  1272104.71047
new mass:  141808.484623
finished [ 5 ,  19 ]
saved [ 5 ,  18 ]
started [ 5 ,  19 ]
my ID is  32907774

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_10" len=90244>
SFR:  0.00155960368758
sSFR:  1.8006480082e-09
mass:  866134.680673
new mass:  155960.368758
finished [ 5 ,  20 ]
saved [ 5 ,  19 ]
started [ 5 ,  20 ]
my ID is  32908648

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_24" len=42397>
SFR:  0.0014184523226
sSFR:  6.97169194907e-09
mass:  203458.835095
new mass:  141845.23226
finished [ 5 ,  21 ]
saved [ 5 ,  20 ]
started [ 5 ,  21 ]
my ID is  329096015

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_24" len=42397>
SFR:  0.0014184523226
sSFR:  6.97169194907e-09
mass:  203458.835095
new mass:  141845.23226
finished [ 5 ,  22 ]
saved [ 5 ,  21 ]
started [ 5 ,  22 ]
my ID is  32909747

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_56" len=18250>
SFR:  0.000147518738585
sSFR:  5.9149275657e-09
mass:  24940.0752497
new mass:  14751.8738585
finished [ 5 ,  23 ]
saved [ 5 ,  22 ]
started [ 5 ,  23 ]
my ID is  329127010

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_56" len=18250>
SFR:  0.000147518738585
sSFR:  5.9149275657e-09
mass:  24940.0752497
new mass:  14751.8738585
finished [ 5 ,  24 ]
saved [ 5 ,  23 ]
started [ 5 ,  24 ]
my ID is  32913443

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_3" len=196350>
SFR:  0.0227883202936
sSFR:  2.77830637048e-09
mass:  8202234.47483
new mass:  2278832.02936
finished [ 5 ,  25 ]
saved [ 5 ,  24 ]
started [ 5 ,  25 ]
my ID is  32914768

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_76" len=11654>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 5 ,  26 ]
saved [ 5 ,  25 ]
started [ 5 ,  26 ]
my ID is  32924962

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_7" len=109882>
SFR:  0.00662011514219
sSFR:  5.4429581108e-09
mass:  1216271.55812
new mass:  662011.514219
finished [ 5 ,  27 ]
saved [ 5 ,  26 ]
started [ 5 ,  27 ]
my ID is  32930722

finished [ 5 ,  28 ]
saved [ 5 ,  27 ]
started [ 5 ,  28 ]
my ID is  32933603

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_9" len=98023>
SFR:  0.0218954265425
sSFR:  8.02488352606e-09
mass:  2728441.66166
new mass:  2189542.65425
finished [ 5 ,  29 ]
saved [ 5 ,  28 ]
started [ 5 ,  29 ]
my ID is  329409616

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_79" len=11169>
SFR:  0.000160188275514
sSFR:  9.1172320485e-09
mass:  17569.8364001
new mass:  16018.8275514
finished [ 5 ,  30 ]
saved [ 5 ,  29 ]
started [ 5 ,  30 ]
my ID is  32940961630

finished [ 5 ,  31 ]
saved [ 5 ,  30 ]
started [ 5 ,  31 ]
my ID is  32940961648

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_670" len=904>
SFR:  0.0
sSFR:  0
mass:  11283.1231681
new mass:  0.0
finished [ 5 ,  32 ]
saved [ 5 ,  31 ]
started [ 5 ,  32 ]
my ID is  329409620

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_53" len=18592>
SFR:  0.000237949918823
sSFR:  7.03189918349e-09
mass:  33838.6419677
new mass:  23794.9918823
finished [ 5 ,  33 ]
saved [ 5 ,  32 ]
started [ 5 ,  33 ]
my ID is  32940963299

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_316" len=1774>
SFR:  0.0
sSFR:  0
mass:  7202.12724573
new mass:  0.0
finished [ 5 ,  34 ]
saved [ 5 ,  33 ]
started [ 5 ,  34 ]
my ID is  3294096335

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_94" len=8748>
SFR:  1.74173127318e-05
sSFR:  1e-08
mass:  1741.73127318
new mass:  1741.73127318
finished [ 5 ,  35 ]
saved [ 5 ,  34 ]
started [ 5 ,  35 ]
my ID is  3294096350

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_152" len=4673>
SFR:  0.0
sSFR:  0
mass:  18528.8163924
new mass:  0.0
finished [ 5 ,  36 ]
saved [ 5 ,  35 ]
started [ 5 ,  36 ]
my ID is  329409643

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_15" len=67467>
SFR:  0.0011422120891
sSFR:  7.99746707945e-10
mass:  1428217.3065
new mass:  114221.20891
finished [ 5 ,  37 ]
saved [ 5 ,  36 ]
started [ 5 ,  37 ]
my ID is  32940964414

finished [ 5 ,  38 ]
saved [ 5 ,  37 ]
started [ 5 ,  38 ]
my ID is  32940965015

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_554" len=1075>
SFR:  0.0
sSFR:  0
mass:  3536.51984638
new mass:  0.0
finished [ 5 ,  39 ]
saved [ 5 ,  38 ]
started [ 5 ,  39 ]
my ID is  3294096555

finished [ 5 ,  40 ]
saved [ 5 ,  39 ]
started [ 5 ,  40 ]
my ID is  3294096585

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_78" len=11203>
SFR:  5.85584222883e-05
sSFR:  8.81768152142e-09
mass:  6641.02260283
new mass:  5855.84222883
finished [ 5 ,  41 ]
saved [ 5 ,  40 ]
started [ 5 ,  41 ]
my ID is  329409673

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_195" len=3103>
SFR:  0.0
sSFR:  0
mass:  715.294281893
new mass:  0.0
finished [ 5 ,  42 ]
saved [ 5 ,  41 ]
started [ 5 ,  42 ]
my ID is  329409675

finished [ 5 ,  43 ]
saved [ 5 ,  42 ]
started [ 5 ,  43 ]
my ID is  3294096768

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_291" len=1958>

SFR:  0.0
sSFR:  0
mass:  35757.5142991
new mass:  0.0
finished [ 5 ,  44 ]
saved [ 5 ,  43 ]
started [ 5 ,  44 ]
my ID is  32940969

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_20" len=46748>
SFR:  0.000545537278673
sSFR:  1.83360658744e-09
mass:  297521.443483
new mass:  54553.7278673
finished [ 5 ,  45 ]
saved [ 5 ,  44 ]
started [ 5 ,  45 ]
my ID is  3294096956

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_61" len=16259>
SFR:  9.31761051105e-05
sSFR:  1.1766676319e-09
mass:  79186.426638
new mass:  9317.61051105
finished [ 5 ,  46 ]
saved [ 5 ,  45 ]
started [ 5 ,  46 ]
my ID is  329409696

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000192:halo_81" len=10848>
SFR:  0.0
sSFR:  0
mass:  132155.132147
new mass:  0.0
finished [ 5 ,  47 ]
saved [ 5 ,  46 ]
finished timestep  0192
starting with timestep  0225
for timestep  0225  my halo IDs are  [          0           0           0           0           0   329022513
   329022530   329022579   329022549   329022532  3290225421   329022529
    32902257   329022512   329022548 32902252633    32902252   329022510
   329022535    32902255   329022527   329022527   329022538   329022538
    32902253   329022572    32902256           0   329022514   329022578
           0  3290225644   329022560  3290225281   329022597  3290225138
   329022517           0  3290225544           0   329022582  3290225210
  3290225189  3290225307   329022523   329022554   329022577]
<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225" len=109356197>
<pynbody.halo.ahf.AHFCatalogue object at 0x7f9c54c80160>
started [ 6 ,  0 ]
my ID is  3290188153

finished [ 6 ,  1 ]
saved [ 6 ,  0 ]
started [ 6 ,  1 ]
my ID is  3290192110

finished [ 6 ,  2 ]
saved [ 6 ,  1 ]
started [ 6 ,  2 ]
my ID is  3290192111

finished [ 6 ,  3 ]
saved [ 6 ,  2 ]
started [ 6 ,  3 ]
my ID is  329019225

finished [ 6 ,  4 ]
saved [ 6 ,  3 ]
started [ 6 ,  4 ]
my ID is  329019230

finished [ 6 ,  5 ]
saved [ 6 ,  4 ]
started [ 6 ,  5 ]
my ID is  329022513

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_13" len=106503>
SFR:  8.24049263906e-06
sSFR:  2.15662566072e-12
mass:  3821012.05098
new mass:  824.049263906
finished [ 6 ,  6 ]
saved [ 6 ,  5 ]
started [ 6 ,  6 ]
my ID is  329022530

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_30" len=48296>
SFR:  8.891707845e-05
sSFR:  2.41149260574e-10
mass:  368722.16916
new mass:  8891.707845
finished [ 6 ,  7 ]
saved [ 6 ,  6 ]
started [ 6 ,  7 ]
my ID is  329022579

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_79" len=13083>
SFR:  4.93182695117e-05
sSFR:  6.97283026519e-10
mass:  70729.1983829
new mass:  4931.82695117
finished [ 6 ,  8 ]
saved [ 6 ,  7 ]
started [ 6 ,  8 ]
my ID is  329034745

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_49" len=27761>
SFR:  0.0
sSFR:  0
mass:  58365.0337926
new mass:  0.0
finished [ 6 ,  9 ]
saved [ 6 ,  8 ]
started [ 6 ,  9 ]
my ID is  329038417

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_32" len=45601>
SFR:  0.00289369330619
sSFR:  9.63680773387e-09
mass:  300275.089647
new mass:  289369.330619
finished [ 6 ,  10 ]
saved [ 6 ,  9 ]
started [ 6 ,  10 ]
my ID is  329038430

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_421" len=1627>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 6 ,  11 ]
saved [ 6 ,  10 ]
started [ 6 ,  11 ]
my ID is  329038438

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_29" len=48863>
SFR:  0.0027671747827
sSFR:  6.34672766308e-09
mass:  436000.239745
new mass:  276717.47827
finished [ 6 ,  12 ]
saved [ 6 ,  11 ]
started [ 6 ,  12 ]
my ID is  329048011

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_7" len=161255>
SFR:  0.0129938367992
sSFR:  1.19753132532e-09
mass:  10850519.3347
new mass:  1299383.67992
finished [ 6 ,  13 ]
saved [ 6 ,  12 ]
started [ 6 ,  13 ]
my ID is  329048022

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_12" len=107867>
SFR:  0.0124534119232
sSFR:  3.20991438299e-09
mass:  3879671.05577
new mass:  1245341.19232
finished [ 6 ,  14 ]
saved [ 6 ,  13 ]
started [ 6 ,  14 ]
my ID is  329048034

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_48" len=28158>
SFR:  0.00113673059431
sSFR:  5.92629269398e-09
mass:  191811.416176
new mass:  113673.059431
finished [ 6 ,  15 ]
saved [ 6 ,  14 ]
started [ 6 ,  15 ]
my ID is  32904809

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_2633" len=310>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 6 ,  16 ]
saved [ 6 ,  15 ]
started [ 6 ,  16 ]
my ID is  32906374

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_2" len=393193>
SFR:  0.0459803537438
sSFR:  1.44552996913e-09
mass:  31808647.8494
new mass:  4598035.37438
finished [ 6 ,  17 ]
saved [ 6 ,  16 ]
started [ 6 ,  17 ]
my ID is  329067210

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_10" len=113515>
SFR:  0.00949033467669
sSFR:  3.69942708411e-09
mass:  2565352.54268
new mass:  949033.467669
finished [ 6 ,  18 ]
saved [ 6 ,  17 ]
started [ 6 ,  18 ]
my ID is  32906729

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_35" len=41398>
SFR:  0.00064428986951
sSFR:  4.97148583026e-10
mass:  1295970.44326
new mass:  64428.986951
finished [ 6 ,  19 ]
saved [ 6 ,  18 ]
started [ 6 ,  19 ]
my ID is  32907774

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_5" len=200444>
SFR:  0.0497173039549
sSFR:  8.39683160199e-09
mass:  5920959.98962
new mass:  4971730.39549
finished [ 6 ,  20 ]
saved [ 6 ,  19 ]
started [ 6 ,  20 ]
my ID is  32908648

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_27" len=50589>
SFR:  0.00193651083903
sSFR:  4.92119509526e-09
mass:  393504.179685
new mass:  193651.083903
finished [ 6 ,  21 ]
saved [ 6 ,  20 ]
started [ 6 ,  21 ]
my ID is  329096015

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_27" len=50589>
SFR:  0.00193651083903
sSFR:  4.92119509526e-09
mass:  393504.179685
new mass:  193651.083903
finished [ 6 ,  22 ]
saved [ 6 ,  21 ]
started [ 6 ,  22 ]
my ID is  32909747

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_38" len=36956>
SFR:  0.000200991993756
sSFR:  4.6821286618e-09
mass:  42927.4819797
new mass:  20099.1993756
finished [ 6 ,  23 ]
saved [ 6 ,  22 ]
started [ 6 ,  23 ]
my ID is  329127010

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_38" len=36956>
SFR:  0.000200991993756
sSFR:  4.6821286618e-09
mass:  42927.4819797
new mass:  20099.1993756
finished [ 6 ,  24 ]
saved [ 6 ,  23 ]
started [ 6 ,  24 ]
my ID is  32913443

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_3" len=300245>
SFR:  0.0369984740895
sSFR:  2.95883714198e-09
mass:  12504396.935
new mass:  3699847.40895
finished [ 6 ,  25 ]
saved [ 6 ,  24 ]
started [ 6 ,  25 ]
my ID is  32914768

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_72" len=15394>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 6 ,  26 ]
saved [ 6 ,  25 ]
started [ 6 ,  26 ]
my ID is  32924962

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_6" len=188906>
SFR:  0.011852715313
sSFR:  4.07577731042e-09
mass:  2908087.07401
new mass:  1185271.5313
finished [ 6 ,  27 ]
saved [ 6 ,  26 ]
started [ 6 ,  27 ]
my ID is  32930722

finished [ 6 ,  28 ]
saved [ 6 ,  27 ]
started [ 6 ,  28 ]
my ID is  32933603

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_14" len=105945>

SFR:  0.0108644934947
sSFR:  2.99000507115e-09
mass:  3633603.70173
new mass:  1086449.34947
finished [ 6 ,  29 ]
saved [ 6 ,  28 ]
started [ 6 ,  29 ]
my ID is  329409616

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_78" len=13351>
SFR:  8.82966793576e-06
sSFR:  4.76608762532e-10
mass:  18526.0293765
new mass:  882.966793576
finished [ 6 ,  30 ]
saved [ 6 ,  29 ]
started [ 6 ,  30 ]
my ID is  32940961630

finished [ 6 ,  31 ]
saved [ 6 ,  30 ]
started [ 6 ,  31 ]
my ID is  32940961648

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_644" len=1095>
SFR:  0.0
sSFR:  0
mass:  11127.1589187
new mass:  0.0
finished [ 6 ,  32 ]
saved [ 6 ,  31 ]
started [ 6 ,  32 ]
my ID is  329409620

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_60" len=20426>
SFR:  0.000256080430434
sSFR:  4.21836913477e-09
mass:  60706.0269627
new mass:  25608.0430434
finished [ 6 ,  33 ]
saved [ 6 ,  32 ]
started [ 6 ,  33 ]
my ID is  32940963299

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_281" len=2361>
SFR:  0.0
sSFR:  0
mass:  7081.04362717
new mass:  0.0
finished [ 6 ,  34 ]
saved [ 6 ,  33 ]
started [ 6 ,  34 ]
my ID is  3294096335

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_97" len=9998>
SFR:  0.000102707004288
sSFR:  8.15461197995e-09
mass:  12594.9590907
new mass:  10270.7004288
finished [ 6 ,  35 ]
saved [ 6 ,  34 ]
started [ 6 ,  35 ]
my ID is  3294096350

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_138" len=5123>
SFR:  0.0
sSFR:  0
mass:  18243.2205819
new mass:  0.0
finished [ 6 ,  36 ]
saved [ 6 ,  35 ]
started [ 6 ,  36 ]
my ID is  329409643

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_17" len=81029>
SFR:  0.00488733365317
sSFR:  2.57094823897e-09
mass:  1900984.85029
new mass:  488733.365317
finished [ 6 ,  37 ]
saved [ 6 ,  36 ]
started [ 6 ,  37 ]
my ID is  32940964414

finished [ 6 ,  38 ]
saved [ 6 ,  37 ]
started [ 6 ,  38 ]
my ID is  32940965015

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_544" len=1267>
SFR:  0.0
sSFR:  0
mass:  3485.53431037
new mass:  0.0
finished [ 6 ,  39 ]
saved [ 6 ,  38 ]
started [ 6 ,  39 ]
my ID is  3294096555

finished [ 6 ,  40 ]
saved [ 6 ,  39 ]
started [ 6 ,  40 ]
my ID is  3294096585

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_82" len=12373>
SFR:  3.30161965021e-05
sSFR:  3.23619625233e-09
mass:  10202.1614043
new mass:  3301.61965021
finished [ 6 ,  41 ]
saved [ 6 ,  40 ]
started [ 6 ,  41 ]
my ID is  329409673

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_210" len=3196>
SFR:  0.0
sSFR:  0
mass:  703.254109936
new mass:  0.0
finished [ 6 ,  42 ]
saved [ 6 ,  41 ]
started [ 6 ,  42 ]
my ID is  329409675

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_189" len=3650>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 6 ,  43 ]
saved [ 6 ,  42 ]
started [ 6 ,  43 ]
my ID is  3294096768

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_307" len=2237>
SFR:  0.0
sSFR:  0
mass:  35306.6005928
new mass:  0.0
finished [ 6 ,  44 ]
saved [ 6 ,  43 ]
started [ 6 ,  44 ]
my ID is  32940969

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_23" len=60775>
SFR:  0.00143552305039
sSFR:  3.35240428505e-09
mass:  428207.020492
new mass:  143552.305039
finished [ 6 ,  45 ]
saved [ 6 ,  44 ]
started [ 6 ,  45 ]
my ID is  3294096956

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_54" len=23799>
SFR:  0.000231737552981
sSFR:  2.30585420879e-09
mass:  100499.655224
new mass:  23173.7552981
finished [ 6 ,  46 ]
saved [ 6 ,  45 ]
started [ 6 ,  46 ]
my ID is  329409696

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000225:halo_77" len=13633>
SFR:  0.0
sSFR:  0
mass:  128710.173228
new mass:  0.0
finished [ 6 ,  47 ]
saved [ 6 ,  46 ]
finished timestep  0225
starting with timestep  0275
for timestep  0275  my halo IDs are  [          0           0           0           0           0           0
           0           0   329027538   329027533   329027536   329027535
    32902759   329027514   329027524 32902752502    32902753   329027510
   329027518    32902754   329027511   329027511   329027532   329027532
    32902755   329027571    32902752           0   329027513   329027564
           0  3290275731   329027557  3290275295  3290275124  3290275110
   329027520           0  3290275579           0   329027574  3290275196
  3290275121  3290275307   329027522   329027554   329027566]
<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275" len=109570742>
<pynbody.halo.ahf.AHFCatalogue object at 0x7f9c4fdf2eb8>
started [ 7 ,  0 ]
my ID is  3290188153

finished [ 7 ,  1 ]
saved [ 7 ,  0 ]
started [ 7 ,  1 ]
my ID is  3290192110

finished [ 7 ,  2 ]
saved [ 7 ,  1 ]
started [ 7 ,  2 ]
my ID is  3290192111

finished [ 7 ,  3 ]
saved [ 7 ,  2 ]
started [ 7 ,  3 ]
my ID is  329019225

finished [ 7 ,  4 ]
saved [ 7 ,  3 ]
started [ 7 ,  4 ]
my ID is  329019230

finished [ 7 ,  5 ]
saved [ 7 ,  4 ]
started [ 7 ,  5 ]
my ID is  329022513

finished [ 7 ,  6 ]
saved [ 7 ,  5 ]
started [ 7 ,  6 ]
my ID is  329022530

finished [ 7 ,  7 ]
saved [ 7 ,  6 ]
started [ 7 ,  7 ]
my ID is  329022579

finished [ 7 ,  8 ]
saved [ 7 ,  7 ]
started [ 7 ,  8 ]
my ID is  329034745

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_38" len=50563>
SFR:  8.1081826479e-06
sSFR:  9.30607940321e-11
mass:  87127.8042728
new mass:  810.81826479
finished [ 7 ,  9 ]
saved [ 7 ,  8 ]
started [ 7 ,  9 ]
my ID is  329038417

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_33" len=61598>
SFR:  0.00131419843788
sSFR:  2.83750222191e-09
mass:  463153.271821
new mass:  131419.843788
finished [ 7 ,  10 ]
saved [ 7 ,  9 ]
started [ 7 ,  10 ]
my ID is  329038430

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_36" len=58222>
SFR:  0.000836185145662
sSFR:  7.83289958715e-09
mass:  106752.95098
new mass:  83618.5145662
finished [ 7 ,  11 ]
saved [ 7 ,  10 ]
started [ 7 ,  11 ]
my ID is  329038438

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_35" len=59642>
SFR:  0.00480984916848
sSFR:  5.33452518899e-09
mass:  901645.225784
new mass:  480984.916848
finished [ 7 ,  12 ]
saved [ 7 ,  11 ]
started [ 7 ,  12 ]
my ID is  329048011

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_9" len=194109>
SFR:  0.00391222935329
sSFR:  3.44703214035e-10
mass:  11349558.6754
new mass:  391222.935329
finished [ 7 ,  13 ]
saved [ 7 ,  12 ]
started [ 7 ,  13 ]
my ID is  329048022

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_14" len=119651>
SFR:  0.00319843473593
sSFR:  6.98486543065e-10
mass:  4579092.85108
new mass:  319843.473593
finished [ 7 ,  14 ]
saved [ 7 ,  13 ]
started [ 7 ,  14 ]
my ID is  329048034

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_24" len=83063>
SFR:  0.00193318755803
sSFR:  3.77804314219e-09
mass:  511690.175383
new mass:  193318.755803
finished [ 7 ,  15 ]
saved [ 7 ,  14 ]
started [ 7 ,  15 ]
my ID is  32904809

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_2502" len=388>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 7 ,  16 ]
saved [ 7 ,  15 ]
started [ 7 ,  16 ]
my ID is  32906374

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_3" len=477290>

SFR:  0.0477886759481
sSFR:  1.29518859938e-09
mass:  36897078.905
new mass:  4778867.59481
finished [ 7 ,  17 ]
saved [ 7 ,  16 ]
started [ 7 ,  17 ]
my ID is  329067210

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_10" len=188385>
SFR:  0.00948186234217
sSFR:  2.48389449478e-09
mass:  3817336.99322
new mass:  948186.234217
finished [ 7 ,  18 ]
saved [ 7 ,  17 ]
started [ 7 ,  18 ]
my ID is  32906729

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_18" len=91990>
SFR:  0.00233096723325
sSFR:  1.54562819766e-09
mass:  1508103.46031
new mass:  233096.723325
finished [ 7 ,  19 ]
saved [ 7 ,  18 ]
started [ 7 ,  19 ]
my ID is  32907774

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_4" len=449656>
SFR:  0.0371103266652
sSFR:  2.60883240377e-09
mass:  14224879.5329
new mass:  3711032.66652
finished [ 7 ,  20 ]
saved [ 7 ,  19 ]
started [ 7 ,  20 ]
my ID is  32908648

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_11" len=156664>
SFR:  0.00976578698953
sSFR:  5.7705675037e-09
mass:  1692344.29426
new mass:  976578.698953
finished [ 7 ,  21 ]
saved [ 7 ,  20 ]
started [ 7 ,  21 ]
my ID is  329096015

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_11" len=156664>
SFR:  0.00976578698953
sSFR:  5.7705675037e-09
mass:  1692344.29426
new mass:  976578.698953
finished [ 7 ,  22 ]
saved [ 7 ,  21 ]
started [ 7 ,  22 ]
my ID is  32909747

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_32" len=62907>
SFR:  0.00280185971636
sSFR:  7.0566507074e-09
mass:  397052.345729
new mass:  280185.971636
finished [ 7 ,  23 ]
saved [ 7 ,  22 ]
started [ 7 ,  23 ]
my ID is  329127010

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_32" len=62907>
SFR:  0.00280185971636
sSFR:  7.0566507074e-09
mass:  397052.345729
new mass:  280185.971636
finished [ 7 ,  24 ]
saved [ 7 ,  23 ]
started [ 7 ,  24 ]
my ID is  32913443

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_5" len=386839>
SFR:  0.0665419472355
sSFR:  3.41069808476e-09
mass:  19509773.5366
new mass:  6654194.72355
finished [ 7 ,  25 ]
saved [ 7 ,  24 ]
started [ 7 ,  25 ]
my ID is  32914768

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_71" len=19108>
SFR:  4.35215889685e-05
sSFR:  1e-08
mass:  4352.15889685
new mass:  4352.15889685
finished [ 7 ,  26 ]
saved [ 7 ,  25 ]
started [ 7 ,  26 ]
my ID is  32924962

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_2" len=546398>
SFR:  0.0743332835199
sSFR:  5.65794333631e-09
mass:  13137862.8419
new mass:  7433328.35199
finished [ 7 ,  27 ]
saved [ 7 ,  26 ]
started [ 7 ,  27 ]
my ID is  32930722

finished [ 7 ,  28 ]
saved [ 7 ,  27 ]
started [ 7 ,  28 ]
my ID is  32933603

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_13" len=133271>
SFR:  0.00209888834436
sSFR:  4.9988089523e-10
mass:  4198776.87743
new mass:  209888.834436
finished [ 7 ,  29 ]
saved [ 7 ,  28 ]
started [ 7 ,  29 ]
my ID is  329409616

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_64" len=21042>
SFR:  0.0
sSFR:  0
mass:  17523.0240211
new mass:  0.0
finished [ 7 ,  30 ]
saved [ 7 ,  29 ]
started [ 7 ,  30 ]
my ID is  32940961630

finished [ 7 ,  31 ]
saved [ 7 ,  30 ]
started [ 7 ,  31 ]
my ID is  32940961648

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_731" len=1231>
SFR:  0.0
sSFR:  0
mass:  10945.1764046
new mass:  0.0
finished [ 7 ,  32 ]
saved [ 7 ,  31 ]
started [ 7 ,  32 ]
my ID is  329409620

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_57" len=24056>
SFR:  0.00037372375068
sSFR:  3.45415989332e-09
mass:  108195.266642
new mass:  37372.375068
finished [ 7 ,  33 ]
saved [ 7 ,  32 ]
started [ 7 ,  33 ]
my ID is  32940963299

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_295" len=2728>
SFR:  0.0
sSFR:  0
mass:  6945.23708899
new mass:  0.0
finished [ 7 ,  34 ]
saved [ 7 ,  33 ]
started [ 7 ,  34 ]
my ID is  3294096335

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_124" len=7519>
SFR:  0.0
sSFR:  0
mass:  11228.8762282
new mass:  0.0
finished [ 7 ,  35 ]
saved [ 7 ,  34 ]
started [ 7 ,  35 ]
my ID is  3294096350

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_110" len=8979>
SFR:  0.0
sSFR:  0
mass:  17917.3089713
new mass:  0.0
finished [ 7 ,  36 ]
saved [ 7 ,  35 ]
started [ 7 ,  36 ]
my ID is  329409643

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_20" len=89812>
SFR:  0.00404360936646
sSFR:  1.60809757419e-09
mass:  2514529.85899
new mass:  404360.936646
finished [ 7 ,  37 ]
saved [ 7 ,  36 ]
started [ 7 ,  37 ]
my ID is  32940964414

finished [ 7 ,  38 ]
saved [ 7 ,  37 ]
started [ 7 ,  38 ]
my ID is  32940965015

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_579" len=1455>
SFR:  0.0
sSFR:  0
mass:  3426.5738753
new mass:  0.0
finished [ 7 ,  39 ]
saved [ 7 ,  38 ]
started [ 7 ,  39 ]
my ID is  3294096555

finished [ 7 ,  40 ]
saved [ 7 ,  39 ]
started [ 7 ,  40 ]
my ID is  3294096585

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_74" len=18099>
SFR:  0.0
sSFR:  0
mass:  9530.9395465
new mass:  0.0
finished [ 7 ,  41 ]
saved [ 7 ,  40 ]
started [ 7 ,  41 ]
my ID is  329409673

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_196" len=4071>
SFR:  0.0
sSFR:  0
mass:  689.816625222
new mass:  0.0
finished [ 7 ,  42 ]
saved [ 7 ,  41 ]
started [ 7 ,  42 ]
my ID is  329409675

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_121" len=7669>
SFR:  0.0
sSFR:  0
mass:  0.0
new mass:  0.0
finished [ 7 ,  43 ]
saved [ 7 ,  42 ]
started [ 7 ,  43 ]
my ID is  3294096768

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_307" len=2669>
SFR:  0.0
sSFR:  0
mass:  34770.4182651
new mass:  0.0
finished [ 7 ,  44 ]
saved [ 7 ,  43 ]
started [ 7 ,  44 ]
my ID is  32940969

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_22" len=87596>
SFR:  0.00291849171268
sSFR:  3.8243682601e-09
mass:  763130.408525
new mass:  291849.171268
finished [ 7 ,  45 ]
saved [ 7 ,  44 ]
started [ 7 ,  45 ]
my ID is  3294096956

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_54" len=25163>
SFR:  1.59189153987e-05
sSFR:  8.62775258517e-11
mass:  184508.251037
new mass:  1591.89153987
finished [ 7 ,  46 ]
saved [ 7 ,  45 ]
started [ 7 ,  46 ]
my ID is  329409696

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000275:halo_66" len=20163>
SFR:  0.0
sSFR:  0
mass:  125297.4259
new mass:  0.0
finished [ 7 ,  47 ]
saved [ 7 ,  46 ]
finished timestep  0275
starting with timestep  0288
for timestep  0288  my halo IDs are  [         0          0          0          0          0          0
          0          0  329028840  329028834  329028838  329028836
  329028810  329028817  329028827   32902885   32902883  329028811
  329028819   32902884  329028812  329028812  329028828  329028828
   32902886  329028873   32902882          0  329028815  329028867
          0 3290288741  329028859 3290288301 3290288128 3290288105
  329028823          0 3290288619          0  329028872 3290288186
 3290288109 3290288300  329028820  329028857  329028868]
<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288" len=109662325>
<pynbody.halo.ahf.AHFCatalogue object at 0x7f9c54f8ee10>
started [ 8 ,  0 ]
my ID is  3290188153

finished [ 8 ,  1 ]
saved [ 8 ,  0 ]
started [ 8 ,  1 ]
my ID is  3290192110

finished [ 8 ,  2 ]
saved [ 8 ,  1 ]
started [ 8 ,  2 ]
my ID is  3290192111

finished [ 8 ,  3 ]
saved [ 8 ,  2 ]
started [ 8 ,  3 ]
my ID is  329019225

finished [ 8 ,  4 ]
saved [ 8 ,  3 ]
started [ 8 ,  4 ]
my ID is  329019230

finished [ 8 ,  5 ]
saved [ 8 ,  4 ]
started [ 8 ,  5 ]
my ID is  329022513

finished [ 8 ,  6 ]
saved [ 8 ,  5 ]
started [ 8 ,  6 ]
my ID is  329022530

finished [ 8 ,  7 ]
saved [ 8 ,  6 ]
started [ 8 ,  7 ]
my ID is  329022579

finished [ 8 ,  8 ]
saved [ 8 ,  7 ]
started [ 8 ,  8 ]
my ID is  329034745

<SimSnap "/home/dp1144/tangos_simulations/h329/snapshots/h329.cosmo50PLK.6144g5HbwK1BH.000288:halo_40" len=54077>

In [4]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

df = pd.read_csv('h329MPB_SFR.csv')
# df.to_csv('h148MPB_ids.csv', index=False)
df

,snapshot,3290188153,3290192110,3290192111,329019225,329019230,329022513,329022530,329022579,329034745,329038417,329038430,329038438,329048011,329048022,329048034,32904809,32906374,329067210,32906729,32907774,32908648,329096015,32909747,329127010,32913443,32914768,32924962,32930722,32933603,329409616,32940961630,32940961648,329409620,32940963299,3294096335,3294096350,329409643,32940964414,32940965015,3294096555,3294096585,329409673,329409675,3294096768,32940969,3294096956,329409696
0,71,-1.000000,-1.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.000000,-1.000000,-1.0,-1.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.000000,-1.000000,-1.0,-1.0,-1.000000,-1.000000,-1.000000
1,96,0.000000,0.0,0.000000,-1.000000,-1.000000,0.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.008359,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-1.0,-1.000000,-1.000000,-1.0,0.0,0.000000,0.000081,-1.000000,0.000008,-1.000000,-1.0,0.0,-1.0,0.000000,0.000008,-1.0,0.0,-1.000000,-1.000000,0.000000
2,108,0.000000,0.0,0.000000,-1.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.001660,-1.000000,0.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-1.0,0.000000,-1.000000,-1.0,0.0,0.000000,0.000000,-1.000000,0.000000,-1.000000,-1.0,0.0,-1.0,0.000000,0.000000,-1.0,0.0,-1.000000,-1.000000,0.000000
3,139,0.000073,0.0,0.001565,0.000010,0.000000,0.005129,0.004052,0.000000,0.000675,0.000000,0.000000,0.001067,0.008408,0.007506,0.000000,0.000000,0.097457,0.001760,0.000000,0.001672,0.000169,0.000169,0.000000,0.000000,0.035935,0.000000,0.000059,-1.0,0.000256,-1.000000,-1.0,0.0,0.000010,0.000000,0.000000,0.000000,0.002397,-1.0,0.0,-1.0,0.000000,0.000000,-1.0,0.0,0.000020,0.000210,0.001452
4,188,0.000008,0.0,0.000009,0.002316,0.000587,0.000000,0.000000,0.000697,0.000000,0.000055,0.000000,0.000382,0.048483,0.003783,0.000418,0.000000,0.046398,0.014665,0.001444,0.000486,0.001358,0.001358,0.000180,0.000180,0.022865,0.000000,0.002140,-1.0,0.023669,0.000162,-1.0,0.0,0.000266,0.000000,0.000009,0.000000,0.001021,-1.0,0.0,-1.0,0.000068,0.000000,-1.0,0.0,0.000514,0.000094,0.000000
5,192,-1.000000,0.0,0.000009,0.002230,0.000455,0.000000,0.000000,0.000622,0.000000,0.000081,0.000000,0.000748,0.045038,0.002855,0.000476,0.000000,0.049565,0.014527,0.001418,0.001560,0.001418,0.001418,0.000148,0.000148,0.022788,0.000000,0.006620,-1.0,0.021895,0.000160,-1.0,0.0,0.000238,0.000000,0.000017,0.000000,0.001142,-1.0,0.0,-1.0,0.000059,0.000000,-1.0,0.0,0.000546,0.000093,0.000000
6,225,-1.000000,-1.0,-1.000000,-1.000000,-1.000000,0.000008,0.000089,0.000049,0.000000,0.002894,0.000000,0.002767,0.012994,0.012453,0.001137,0.000000,0.045980,0.009490,0.000644,0.049717,0.001937,0.001937,0.000201,0.000201,0.036998,0.000000,0.011853,-1.0,0.010864,0.000009,-1.0,0.0,0.000256,0.000000,0.000103,0.000000,0.004887,-1.0,0.0,-1.0,0.000033,0.000000,0.0,0.0,0.001436,0.000232,0.000000
7,275,-1.000000,-1.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000008,0.001314,0.000836,0.004810,0.003912,0.003198,0.001933,0.000000,0.047789,0.009482,0.002331,0.037110,0.009766,0.009766,0.002802,0.002802,0.066542,0.000044,0.074333,-1.0,0.002099,0.000000,-1.0,0.0,0.000374,0.000000,0.000000,0.000000,0.004044,-1.0,0.0,-1.0,0.000000,0.000000,0.0,0.0,0.002918,0.000016,0.000000
8,288,-1.000000,-1.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000072,0.002238,0.006232,0.004318,0.005901,0.004579,0.015637,0.024818,0.043750,0.011949,0.001415,0.047256,0.020659,0.020659,0.001585,0.001585,0.063264,0.000058,0.115384,-1.0,0.003801,0.000000,-1.0,0.0,0.000335,0.000000,0.000000,0.000000,0.002976,-1.0,0.0,-1.0,0.000000,0.000000,0.0,0.0,0.003664,0.000000,0.000000
9,347,-1.000000,-1.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,480,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,576,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,637,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1344,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,1632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,1728,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,1740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,1824,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,1920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2088,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,2208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,2555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,2592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,2784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,2880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,2976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,3072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,3168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,3195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,3264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,3360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,3456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,3552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,3606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,3648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,3744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,3840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,3936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,4032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,4096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Initialize dataframe
column_names = ['ID', 'IDs', 'SFR', 'sSFR', 'stellar_mass', 'new_stellar_mass']
df = pd.DataFrame(columns = column_names)
# df.to_csv('sSFR_data100.csv', index=False)

In [3]:
# Load routine for getting tracks
def sSFR_track(ID=0, simulation=0, status=0, tangos_halo=0, halo_id=0, snap_num=0, resolution=1000):
    
#     from tangos_halo_module.halos import tangos_to_pynbody_halo, get_main_progenitor_branch

    if ID != 0:
        print('Started ', ID)
        simulation, status, halo_id, snap_num = ID_to_sim_halo_snap(ID=ID)
        print(simulation, status, halo_id, snap_num)
        tangos_halo = ID_to_tangos_halo(ID=ID, resolution=resolution)
    
    # Satellite MPB ids
    MPB, MPB_ids = get_main_progenitor_branch(tangos_halo=tangos_halo, simulation=simulation, resolution=resolution)
    print(MPB_ids)
    print(MPB)
    # Store and recall
    # Host MPB and ids
    host = get_host(simulation=simulation, resolution=resolution)
    host_MPB, host_ids = get_main_progenitor_branch(tangos_halo=host, simulation=simulation, 
                                                    resolution=resolution)

    # Only consider halo while separate from host
    MPB_ids[MPB_ids==host_ids] = 0
    print(MPB_ids)

    for i in range(len(MPB_ids)):
        if MPB_ids[i]!=0:
            if len(str(MPB[i]))>6:
                MPB_ids[i]=get_halo_snap_num(tangos_halo=MPB[i])[2]
            else: 
                MPB_ids[i]=0
    print('MPB new IDs: ', MPB_ids)
    IDs_track = np.zeros(0)
    SFR_track = np.zeros(0)
    sSFR_track = np.zeros(0)
    mass_track = np.zeros(0)
    new_mass_track = np.zeros(0)

    for index, idx in enumerate(MPB_ids):
        print(idx)
        if idx==0:
            IDs_track = np.concatenate((IDs_track, [-1]), axis=None)
            SFR_track = np.concatenate((SFR_track, [-1]), axis=None)
            sSFR_track = np.concatenate((sSFR_track, [-1]), axis=None)
            mass_track = np.concatenate((mass_track, [-1]), axis=None)
            new_mass_track = np.concatenate((new_mass_track, [-1]), axis=None)
        elif len(str(MPB[index]))<6:
            IDs_track = np.concatenate((IDs_track, [idx]), axis=None)
            SFR_track = np.concatenate((SFR_track, [-1]), axis=None)
            sSFR_track = np.concatenate((sSFR_track, [-1]), axis=None)
            mass_track = np.concatenate((mass_track, [-1]), axis=None)
            new_mass_track = np.concatenate((new_mass_track, [-1]), axis=None)
        else:
            tang_halo = ID_to_tangos_halo(ID=idx, resolution=resolution)
            print(tang_halo)
            pyn_halo = tangos_to_pynbody_halo(tangos_halo=tang_halo, simulation=simulation, resolution=resolution)
            mass = np.asarray(pyn_halo.s['mass'].in_units('Msol'))
            age = pyn_halo.properties['time'].in_units('Gyr') - pyn_halo.s['tform'].in_units('Gyr') #SimArray in Gyr
            new_mass = np.sum(mass[age <= 0.1]) # Formed within last 100 Myr
            total_mass = np.sum(mass)
            SFR = new_mass/1e8
            sSFR = SFR/total_mass
            IDs_track = np.concatenate((IDs_track, [idx]), axis=None)
            SFR_track = np.concatenate((SFR_track, [SFR]), axis=None)
            sSFR_track = np.concatenate((sSFR_track, [sSFR]), axis=None)
            mass_track = np.concatenate((mass_track, [total_mass]), axis=None)
            new_mass_track = np.concatenate((new_mass_track, [new_mass]), axis=None)
    print(SFR_track, sSFR_track, mass_track, new_mass_track)
    dat = {'ID': ID,
           'IDs': [IDs_track],
           'SFR': [SFR_track], 
           'sSFR': [sSFR_track], 
           'stellar_mass': [mass_track], 
           'new_stellar_mass': [new_mass_track],}
    df = pd.DataFrame(data=dat)
    return df
    
df = pd.read_csv('sSFR_data100.csv')
completed_ids = np.asarray(df['ID'])
len(completed_ids)

0

In [4]:
# Timing the slowest part of my code
# Test ID
# Well this works, so why does my loop keep breaking here??? (check pipe2.out for what I mean)

%timeit tang_halo = ID_to_tangos_halo(ID='1482784661', resolution=100)
tang_halo = ID_to_tangos_halo(ID='1482784661', resolution=100)
print(tang_halo)

%timeit pyn_halo = tangos_to_pynbody_halo(tangos_halo=tang_halo, simulation='h148', resolution=100)
pyn_halo = tangos_to_pynbody_halo(tangos_halo=tang_halo, simulation='h148', resolution=100)
print(pyn_halo)

%timeit mass = np.asarray(pyn_halo.s['mass'].in_units('Msol')) #This takes incredibly long
mass = np.asarray(pyn_halo.s['mass'].in_units('Msol')) #This takes incredibly long
print(mass)

%timeit age = pyn_halo.properties['time'].in_units('Gyr') - pyn_halo.s['tform'].in_units('Gyr') #SimArray in Gyr #This also takes forever
age = pyn_halo.properties['time'].in_units('Gyr') - pyn_halo.s['tform'].in_units('Gyr') #SimArray in Gyr #This also takes forever
print(age)

%timeit new_mass = np.sum(mass[age <= 0.1]) # Formed within last 100 Myr
new_mass = np.sum(mass[age <= 0.1]) # Formed within last 100 Myr
print(new_mass)

%timeit total_mass = np.sum(mass)
total_mass = np.sum(mass)
print(total_mass)

%timeit SFR = new_mass/1e8
SFR = new_mass/1e8
print(SFR)
sSFR = SFR/total_mass
print(sSFR)

# h2data = h.load_copy(2) @ https://pynbody.github.io/pynbody/tutorials/halos.html
# Reproduce quirm plots only for h148 and h329

100 loops, best of 3: 14.4 ms per loop
<Halo 'snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784/halo_661' | NDM=4191 Nstar=4 Ngas=0>
1 loop, best of 3: 2.52 s per loop
<SimSnap "/home/dp1144/tangos_simulations/h148/snapshots/h148.cosmo50PLK.6144g3HbwK1BH.002784:halo_661" len=4195>
The slowest run took 80.99 times longer than the fastest. This could mean that an intermediate result is being cached.
1 loop, best of 3: 2.08 s per loop
[    614.0498492      614.04995714  407982.27862832     614.04995714]
1 loop, best of 3: 1.53 s per loop
[ 9.16143659  9.15554392  9.61123794  9.15386031]
10000 loops, best of 3: 51.1 µs per loop
0.0
100000 loops, best of 3: 5.98 µs per loop
409824.428392
The slowest run took 18.00 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 93.5 ns per loop
0.0
0.0

In [ ]:
count=0
done=0
while done<124:
    try:
        print('Watch me go for the ', count, 'th time...')
        for idx in ids:
            if idx in completed_ids:
                print('Already Exists ', idx)
                done=len(completed_ids)
                print('Completed Count --> ', done)
                pass
            else:
                print('Started ', idx)
                sat_df = sSFR_track(ID=idx, resolution=100)
                df = pd.concat([df, sat_df])
                df.to_csv('sSFR_data100.csv', index=False)
                completed_ids = np.concatenate((completed_ids, [idx]), axis=None)
                print('Finished ', idx)
                done=len(completed_ids)
                print('Completed Count --> ', done)
    except: 
        count+=1
        continue